import { build } from './build.mjs';

export default build("canadas-economy", "Discover Canada — Canada's Economy", [
  {
    id: 'eco-001',
    p: 'Canada is a member of which group of advanced economies?',
    pf: 'Le Canada fait partie de quel groupe d’économies avancées?',
    o: ['The G7', 'OPEC', 'The African Union', 'The Warsaw Pact'],
    of: ['Le G7', 'L’OPEP', 'L’Union africaine', 'Le pacte de Varsovie'],
    a: 'a',
    e: 'Canada is one of the G7 countries. Trade, natural resources, services, and manufacturing are all important parts of the economy.',
    ef: 'Le Canada compte parmi les pays du G7. Le commerce, les ressources naturelles, les services et la fabrication occupent tous une place importante dans l’économie.',
  },
  {
    id: 'eco-002',
    p: 'Which of these is a major Canadian export sector highlighted in the study guide?',
    pf: 'Lequel de ces secteurs d’exportation canadiens est mis en évidence dans le guide d’étude?',
    o: [
      'Natural resources such as energy, minerals, and forest products',
      'Domestic postage stamps',
      'Municipal parking tickets',
      'Provincial court transcripts',
    ],
    of: [
      'Les ressources naturelles comme l’énergie, les minéraux et les produits forestiers',
      'Les timbres-poste vendus au pays',
      'Les contraventions de stationnement municipales',
      'Les transcriptions des tribunaux provinciaux',
    ],
    a: 'a',
    e: 'Canada has a resource-rich economy and also strong manufacturing and service industries. The United States is Canada’s largest trading partner.',
    ef: 'Le Canada possède une économie riche en ressources, ainsi que de solides industries manufacturières et de services. Les États-Unis sont son principal partenaire commercial.',
  },
  {
    id: 'eco-003',
    p: 'Canada’s largest trading partner is:',
    pf: 'Le principal partenaire commercial du Canada est :',
    o: ['The United States', 'New Zealand', 'Chad', 'Iceland only'],
    of: ['Les États-Unis', 'La Nouvelle-Zélande', 'Le Tchad', 'L’Islande seulement'],
    a: 'a',
    e: 'Geography and supply chains make the U.S. market dominant. Mexico also matters under North American trade rules.',
    ef: 'La géographie et les chaînes d’approvisionnement rendent le marché américain dominant. Le Mexique compte aussi en vertu des règles commerciales nord-américaines.',
  },
  {
    id: 'eco-004',
    p: 'A mixed economy means that:',
    pf: 'Une économie mixte signifie que :',
    o: [
      'Markets and private firms produce most goods, while governments tax, regulate, and provide public services',
      'The army owns every shop',
      'There is no private property',
      'Only barter is legal',
    ],
    of: [
      'Les marchés et les entreprises privées produisent la plupart des biens, tandis que les gouvernements imposent, réglementent et offrent des services publics',
      'L’armée possède tous les commerces',
      'La propriété privée n’existe pas',
      'Seul le troc est légal',
    ],
    a: 'a',
    e: 'Canada is capitalist with a substantial public sector—not a command economy, not a night-watchman state with no hospitals.',
    ef: 'Le Canada est capitaliste, mais doté d’un secteur public important : ce n’est ni une économie planifiée, ni un État minimal sans hôpitaux.',
  },
  {
    id: 'eco-005',
    t: 'tf',
    p: 'Most Canadians work in the service sector rather than in farming.',
    pf: 'La majorité des Canadiens travaillent dans le secteur des services plutôt qu’en agriculture.',
    a: 'true',
    e: 'Services (health, education, retail, finance, government, technology) employ the majority. Resources still punch above their job count in exports.',
    ef: 'Les services (santé, éducation, commerce de détail, finance, fonction publique, technologie) emploient la majorité des travailleurs. Les ressources pèsent toutefois plus lourd dans les exportations que dans l’emploi.',
  },
  {
    id: 'eco-006',
    p: 'Manufacturing, including vehicles and machinery, is especially concentrated in:',
    pf: 'La fabrication, notamment des véhicules et de la machinerie, est surtout concentrée :',
    o: ['Ontario and Quebec', 'Nunavut hamlets only', 'Prince Edward Island’s fishing villages only', 'Yukon gold creeks only'],
    of: ['En Ontario et au Québec', 'Dans les hameaux du Nunavut seulement', 'Dans les villages de pêche de l’Île-du-Prince-Édouard seulement', 'Dans les ruisseaux aurifères du Yukon seulement'],
    a: 'a',
    e: 'Central Canada’s industrial belt is a standard regional-economy fact. Other provinces manufacture too, but the share is largest here.',
    ef: 'La ceinture industrielle du Canada central est un fait classique d’économie régionale. D’autres provinces fabriquent aussi des biens, mais la part la plus forte se trouve ici.',
  },
  {
    id: 'eco-007',
    p: 'Prairie agriculture is famous for:',
    pf: 'L’agriculture des Prairies est reconnue pour :',
    o: ['Grain (including wheat) and other farm exports', 'Tropical fruit plantations', 'Coffee estates', 'Banana republics'],
    of: ['Les céréales (dont le blé) et d’autres exportations agricoles', 'Les plantations de fruits tropicaux', 'Les domaines caféiers', 'Les républiques bananières'],
    a: 'a',
    e: 'The Prairies feed export markets. Potash and energy sit beside the grain story, especially in Saskatchewan and Alberta.',
    ef: 'Les Prairies alimentent les marchés d’exportation. La potasse et l’énergie accompagnent les céréales, surtout en Saskatchewan et en Alberta.',
  },
  {
    id: 'eco-008',
    p: 'Alberta’s economy is closely associated with:',
    pf: 'L’économie de l’Alberta est étroitement associée :',
    o: ['Oil and gas', 'Cod stocks alone', 'Maple syrup alone', 'Automobile assembly in Windsor only'],
    of: ['Au pétrole et au gaz', 'Aux stocks de morue seulement', 'Au sirop d’érable seulement', 'À l’assemblage automobile à Windsor seulement'],
    a: 'a',
    e: 'Energy wealth shapes Alberta’s politics and Canada’s export mix. Agriculture remains important as well.',
    ef: 'La richesse énergétique façonne la politique albertaine et la composition des exportations canadiennes. L’agriculture demeure aussi importante.',
  },
  {
    id: 'eco-009',
    p: 'British Columbia’s historic staple export sector includes:',
    pf: 'Le secteur d’exportation traditionnel de la Colombie-Britannique comprend :',
    o: ['Forestry', 'Prairie wheat only', 'Nunavut diamonds only', 'PEI potatoes only'],
    of: ['La foresterie', 'Le blé des Prairies seulement', 'Les diamants du Nunavut seulement', 'Les pommes de terre de l’Île-du-Prince-Édouard seulement'],
    a: 'a',
    e: 'Wood, pulp, and paper—plus mining, ports, film, and Pacific trade—define much of B.C.’s economy.',
    ef: 'Le bois, la pâte et le papier — ainsi que les mines, les ports, le cinéma et le commerce avec le Pacifique — définissent une grande part de l’économie de la Colombie-Britannique.',
  },
  {
    id: 'eco-010',
    p: 'Atlantic Canada’s traditional resource economy includes:',
    pf: 'L’économie traditionnelle des ressources du Canada atlantique comprend :',
    o: ['Fisheries', 'Desert oil only', 'Alpine watches', 'Prairie potash only'],
    of: ['Les pêches', 'Le pétrole du désert seulement', 'Les montres alpines', 'La potasse des Prairies seulement'],
    a: 'a',
    e: 'Cod, lobster, and other fisheries sit beside energy, tourism, and public-sector jobs. The groundfish collapse is part of modern history.',
    ef: 'La morue, le homard et les autres pêches côtoient l’énergie, le tourisme et les emplois du secteur public. L’effondrement des stocks de poisson de fond fait partie de l’histoire récente.',
  },
  {
    id: 'eco-011',
    t: 'tf',
    p: 'Quebec is a major producer of hydroelectric power.',
    pf: 'Le Québec est un grand producteur d’électricité d’origine hydraulique.',
    a: 'true',
    e: 'Hydro-Québec and northern rivers made electricity a provincial economic pillar and an export.',
    ef: 'Hydro-Québec et les rivières du Nord ont fait de l’électricité un pilier de l’économie provinciale et un produit d’exportation.',
  },
  {
    id: 'eco-012',
    p: 'The Bank of Canada is:',
    pf: 'La Banque du Canada est :',
    o: [
      'The central bank that issues notes and conducts monetary policy',
      'A private supermarket',
      'A municipal credit union in Ottawa only',
      'The Senate’s cashier',
    ],
    of: [
      'La banque centrale qui émet les billets et mène la politique monétaire',
      'Un supermarché privé',
      'Une caisse populaire municipale d’Ottawa seulement',
      'Le caissier du Sénat',
    ],
    a: 'a',
    e: 'It is public and independent in its day-to-day policy. Commercial banks are separate, regulated companies.',
    ef: 'Elle est publique et indépendante dans sa conduite quotidienne de la politique monétaire. Les banques commerciales sont des sociétés distinctes et réglementées.',
  },
  {
    id: 'eco-013',
    p: 'Crown corporations are:',
    pf: 'Les sociétés d’État sont :',
    o: [
      'Companies owned by government to provide a public service or strategic role',
      'Always illegal',
      'The same as Cabinet',
      'Foreign embassies',
    ],
    of: [
      'Des entreprises appartenant à l’État pour offrir un service public ou jouer un rôle stratégique',
      'Toujours illégales',
      'La même chose que le Cabinet',
      'Des ambassades étrangères',
    ],
    a: 'a',
    e: 'Examples in the national story include railways, broadcasters, and energy utilities at various times.',
    ef: 'Dans l’histoire du pays, on en trouve des exemples parmi les chemins de fer, les radiodiffuseurs et les services publics d’énergie, selon les époques.',
  },
  {
    id: 'eco-014',
    p: 'Employment Insurance and public pensions exist because:',
    pf: 'L’assurance-emploi et les régimes de retraite publics existent parce que :',
    o: [
      'Modern Canada built social programs to share risk',
      'The Quebec Act required them in 1774',
      'NATO dues include EI',
      'Municipalities print money',
    ],
    of: [
      'Le Canada moderne a bâti des programmes sociaux pour partager les risques',
      'L’Acte de Québec les exigeait en 1774',
      'Les cotisations à l’OTAN comprennent l’assurance-emploi',
      'Les municipalités impriment la monnaie',
    ],
    a: 'a',
    e: 'They are economic-citizenship facts as well as “modern Canada” facts: the market is not the only institution.',
    ef: 'Ce sont des faits de citoyenneté économique autant que des faits du « Canada moderne » : le marché n’est pas la seule institution.',
  },
  {
    id: 'eco-015',
    t: 'tf',
    p: 'Income taxes help pay for public services such as health care, defence, and infrastructure.',
    pf: 'L’impôt sur le revenu contribue à financer des services publics comme les soins de santé, la défense et les infrastructures.',
    a: 'true',
    e: 'Paying taxes lawfully is part of the civic bargain in a mixed economy.',
    ef: 'Payer ses impôts conformément à la loi fait partie du contrat civique dans une économie mixte.',
  },
  {
    id: 'eco-016',
    p: 'Unions and collective bargaining in Canada are:',
    pf: 'Les syndicats et la négociation collective au Canada sont :',
    o: [
      'Legal features of labour relations',
      'Banned by the Charter',
      'Available only to senators',
      'A U.S. import with no Canadian history',
    ],
    of: [
      'Des éléments légaux des relations de travail',
      'Interdits par la Charte',
      'Réservés aux sénateurs',
      'Une importation américaine sans histoire au Canada',
    ],
    a: 'a',
    e: 'Minimum standards are mainly provincial. Unions are part of how wages and conditions are set in many workplaces.',
    ef: 'Les normes minimales du travail relèvent surtout des provinces. Dans de nombreux milieux de travail, les syndicats participent à la fixation des salaires et des conditions.',
  },
  {
    id: 'eco-017',
    p: 'Toronto is especially important to the Canadian economy as:',
    pf: 'Toronto occupe une place particulièrement importante dans l’économie canadienne à titre :',
    o: ['A financial and business-services centre', 'The only port', 'The Arctic’s diamond capital', 'A territorial capital'],
    of: ['De centre financier et de services aux entreprises', 'De seul port du pays', 'De capitale du diamant dans l’Arctique', 'De capitale territoriale'],
    a: 'a',
    e: 'Banks, markets, and corporate head offices cluster there. Other cities have other specialties.',
    ef: 'Les banques, les marchés et les sièges sociaux y sont concentrés. D’autres villes ont leurs propres spécialités.',
  },
  {
    id: 'eco-018',
    p: 'Ports such as Vancouver and Halifax matter because Canada:',
    pf: 'Des ports comme Vancouver et Halifax sont importants parce que le Canada :',
    o: [
      'Trades heavily by sea as well as across the U.S. land border',
      'Is landlocked',
      'Bans exports',
      'Only ships by dogsled',
    ],
    of: [
      'Commerce beaucoup par voie maritime autant que par la frontière terrestre américaine',
      'Est enclavé',
      'Interdit les exportations',
      'N’expédie ses marchandises qu’en traîneau à chiens',
    ],
    a: 'a',
    e: 'Pacific, Atlantic, and Great Lakes–St. Lawrence routes are geography as economic destiny.',
    ef: 'Les routes du Pacifique, de l’Atlantique et du réseau Grands Lacs–Saint-Laurent illustrent la géographie comme destin économique.',
  },
  {
    id: 'eco-019',
    p: 'Information technology and other advanced services are:',
    pf: 'Les technologies de l’information et les autres services de pointe sont :',
    o: [
      'Growing parts of a modern mixed economy, not a replacement for resources overnight',
      'Illegal in Canada',
      'The only sector in 1867',
      'Run exclusively by the RCMP',
    ],
    of: [
      'Des composantes en croissance d’une économie mixte moderne, sans remplacer les ressources du jour au lendemain',
      'Illégaux au Canada',
      'Le seul secteur existant en 1867',
      'Gérés exclusivement par la GRC',
    ],
    a: 'a',
    e: 'The guide still stresses resources and manufacturing. A serious citizen also sees the service and tech shift.',
    ef: 'Le guide insiste toujours sur les ressources et la fabrication. Un citoyen attentif remarque aussi le virage vers les services et la technologie.',
  },
  {
    id: 'eco-020',
    t: 'tf',
    p: 'Prosperity is even across every region of Canada.',
    pf: 'La prospérité est répartie de façon égale dans toutes les régions du Canada.',
    a: 'false',
    e: 'The study guide itself describes different regional economies and different challenges. That unevenness is a testable idea.',
    ef: 'Le guide d’étude décrit lui-même des économies régionales différentes et des défis différents. Cette inégalité peut faire l’objet d’une question à l’examen.',
  },
  {
    id: 'eco-021',
    p: 'Potash is a mineral export especially associated with:',
    pf: 'La potasse est un minéral d’exportation surtout associé :',
    o: ['Saskatchewan', 'Prince Edward Island beaches', 'Downtown Montreal fashion only', 'Yukon tourism only'],
    of: ['À la Saskatchewan', 'Aux plages de l’Île-du-Prince-Édouard', 'À la mode du centre-ville de Montréal seulement', 'Au tourisme au Yukon seulement'],
    a: 'a',
    e: 'Fertilizer minerals are a Prairie specialty. Energy and grain complete the picture.',
    ef: 'Les minéraux servant aux engrais sont une spécialité des Prairies. L’énergie et les céréales complètent le tableau.',
  },
  {
    id: 'eco-022',
    p: 'The Canadian dollar:',
    pf: 'Le dollar canadien :',
    o: [
      'Floats on foreign-exchange markets',
      'Is printed by each province separately as legal tender',
      'Is pegged to the yen by the Charter',
      'Was replaced by the euro in 2002',
    ],
    of: [
      'Flotte sur les marchés des changes',
      'Est imprimé séparément par chaque province comme monnaie légale',
      'Est arrimé au yen par la Charte',
      'A été remplacé par l’euro en 2002',
    ],
    a: 'a',
    e: 'A floating currency is part of how a trading economy adjusts. The Bank of Canada influences conditions, not a fixed peg.',
    ef: 'Une monnaie flottante aide une économie commerçante à s’ajuster. La Banque du Canada influence les conditions financières; elle ne maintient pas de taux fixe.',
  },
  {
    id: 'eco-023',
    p: 'Why does the citizenship test care about the economy at all?',
    pf: 'Pourquoi l’examen de citoyenneté s’intéresse-t-il à l’économie?',
    o: [
      'Because geography, trade, and jobs shape the country you are joining',
      'Because you must work in oil to become a citizen',
      'Because the Charter lists stock tips',
      'Because senators run factories',
    ],
    of: [
      'Parce que la géographie, le commerce et l’emploi façonnent le pays que vous rejoignez',
      'Parce qu’il faut travailler dans le pétrole pour devenir citoyen',
      'Parce que la Charte contient des conseils boursiers',
      'Parce que les sénateurs dirigent les usines',
    ],
    a: 'a',
    e: 'You are not asked to forecast GDP. You are asked to place Canada among trading democracies with regional specialties.',
    ef: 'On ne vous demande pas de prévoir le PIB, mais de situer le Canada parmi les démocraties commerçantes dotées de spécialités régionales.',
  },
  {
    id: 'eco-024',
    t: 'tf',
    p: 'The federal government is the only government that spends money in the economy.',
    pf: 'Le gouvernement fédéral est le seul gouvernement à dépenser de l’argent dans l’économie.',
    a: 'false',
    e: 'Provinces spend heavily on health and education. Municipalities spend on local services. All three tax in overlapping ways.',
    ef: 'Les provinces dépensent beaucoup en santé et en éducation. Les municipalités financent les services locaux. Les trois ordres de gouvernement perçoivent des taxes et impôts qui se chevauchent.',
  },
  {
    id: 'eco-025',
    p: 'Mining is important in:',
    pf: 'L’exploitation minière est importante :',
    o: [
      'The Shield, the Cordillera, and the North, among other regions',
      'Only downtown Toronto condominiums',
      'Only the Senate',
      'Only PEI potato fields',
    ],
    of: [
      'Dans le Bouclier, la Cordillère et le Nord, entre autres régions',
      'Dans les condominiums du centre-ville de Toronto seulement',
      'Au Sénat seulement',
      'Dans les champs de pommes de terre de l’Île-du-Prince-Édouard seulement',
    ],
    a: 'a',
    e: 'Gold, iron, nickel, diamonds, and more are regional staples. Indigenous land rights often intersect with mines.',
    ef: 'L’or, le fer, le nickel et le diamant, entre autres, sont des produits de base régionaux. Les droits territoriaux autochtones recoupent souvent les projets miniers.',
  },
  {
    id: 'eco-026',
    p: 'Tourism is an export in the economic sense when:',
    pf: 'Au sens économique, le tourisme constitue une exportation lorsque :',
    o: [
      'Visitors from abroad spend money in Canada',
      'Canadians buy groceries',
      'A city reprints a parking ticket',
      'A court charges a filing fee to a resident',
    ],
    of: [
      'Des visiteurs de l’étranger dépensent de l’argent au Canada',
      'Des Canadiens font leur épicerie',
      'Une ville réimprime une contravention de stationnement',
      'Un tribunal facture des frais de dépôt à un résident',
    ],
    a: 'a',
    e: 'Landscapes, cities, and cultural attractions are part of the service economy the guide groups with other industries.',
    ef: 'Les paysages, les villes et les attractions culturelles font partie de l’économie de services que le guide regroupe avec les autres industries.',
  },
  {
    id: 'eco-027',
    p: 'NAFTA-era (and successor) free-trade rules matter most for:',
    pf: 'Les règles de libre-échange de l’époque de l’ALENA (et de ses successeurs) comptent surtout pour :',
    o: [
      'Cross-border manufacturing and agriculture',
      'Whether the Monarch can visit',
      'How juries are selected',
      'The lyrics of O Canada',
    ],
    of: [
      'La fabrication et l’agriculture transfrontalières',
      'La possibilité pour le monarque de venir en visite',
      'La façon de choisir les jurys',
      'Les paroles de l’Ô Canada',
    ],
    a: 'a',
    e: 'The legal title of the agreement has changed. The citizenship-test idea is close economic integration in North America.',
    ef: 'Le titre officiel de l’accord a changé. Ce qu’il faut retenir pour l’examen, c’est l’étroite intégration économique en Amérique du Nord.',
  },
  {
    id: 'eco-028',
    t: 'tf',
    p: 'Canada has both large private banks and a public central bank.',
    pf: 'Le Canada compte à la fois de grandes banques privées et une banque centrale publique.',
    a: 'true',
    e: 'Do not mix the Bank of Canada with the Royal Bank or other commercial banks. They play different roles.',
    ef: 'Ne confondez pas la Banque du Canada avec la Banque Royale ou les autres banques commerciales : leurs rôles diffèrent.',
  },
  {
    id: 'eco-029',
    p: 'Softwood lumber is a recurring Canada–U.S. trade issue because:',
    pf: 'Le bois d’œuvre revient constamment dans les différends commerciaux entre le Canada et les États-Unis parce que :',
    o: [
      'Canadian timber is a major export and the two countries dispute subsidies and duties',
      'Canada has no forests',
      'The Senate owns all trees',
      'Lumber is banned by the Charter',
    ],
    of: [
      'Le bois canadien est une exportation majeure et les deux pays s’opposent sur les subventions et les droits de douane',
      'Le Canada n’a pas de forêts',
      'Le Sénat est propriétaire de tous les arbres',
      'Le bois d’œuvre est interdit par la Charte',
    ],
    a: 'a',
    e: 'It is a classic resource-and-trade file. Forestry jobs are regional; the dispute is bilateral.',
    ef: 'C’est un dossier classique de ressources et de commerce. Les emplois forestiers sont régionaux, alors que le différend est bilatéral.',
  },
  {
    id: 'eco-030',
    p: 'Personal income tax in Canada is:',
    pf: 'Au Canada, l’impôt sur le revenu des particuliers est :',
    o: [
      'Collected by the federal government, with provinces levying income tax as well in most cases',
      'Paid only by senators',
      'Illegal under the Charter',
      'A municipal dog-licence fee only',
    ],
    of: [
      'Perçu par le gouvernement fédéral, les provinces prélevant elles aussi un impôt sur le revenu dans la plupart des cas',
      'Payé uniquement par les sénateurs',
      'Illégal en vertu de la Charte',
      'Un simple droit municipal de licence pour chien',
    ],
    a: 'a',
    e: 'Most people file one federal return that also handles provincial tax (Quebec is the exception with its own form).',
    ef: 'La plupart des gens produisent une seule déclaration fédérale qui règle aussi l’impôt provincial (le Québec fait exception avec sa propre déclaration).',
  },
  {
    id: 'eco-031',
    t: 'tf',
    p: 'Hydroelectric power is a major Canadian energy source, especially in Quebec, British Columbia, Manitoba, and Newfoundland and Labrador.',
    pf: 'L’hydroélectricité est une grande source d’énergie au Canada, surtout au Québec, en Colombie-Britannique, au Manitoba et à Terre-Neuve-et-Labrador.',
    a: 'true',
    e: 'Dams are a classic “geography plus economy” fact. Oil and gas are another energy story, concentrated elsewhere.',
    ef: 'Les barrages illustrent bien le lien entre géographie et économie. Le pétrole et le gaz forment une autre filière énergétique, concentrée ailleurs.',
  },
  {
    id: 'eco-032',
    p: 'The Canadian Wheat Board’s historic role (now ended in its old form) was to:',
    pf: 'Le rôle historique de la Commission canadienne du blé (qui n’existe plus sous sa forme d’origine) était de :',
    o: [
      'Market Prairie grain in a pooled system',
      'Appoint the Governor General',
      'Run the Senate',
      'Print banknotes',
    ],
    of: [
      'Commercialiser les céréales des Prairies dans un système de mise en commun',
      'Nommer le gouverneur général',
      'Diriger le Sénat',
      'Imprimer les billets de banque',
    ],
    a: 'a',
    e: 'Even if the institution changed, the testable idea is that Prairie grain was a staple export with special marketing rules.',
    ef: 'Même si l’institution a changé, l’idée à retenir est que les céréales des Prairies constituaient une exportation de base assortie de règles de commercialisation particulières.',
  },
  {
    id: 'eco-033',
    p: 'Auto manufacturing in Canada has long depended on:',
    pf: 'Au Canada, la construction automobile dépend depuis longtemps :',
    o: [
      'Integrated North American supply chains, especially in Ontario',
      'Only Arctic ice roads',
      'Senate carpooling',
      'A ban on trade with the United States',
    ],
    of: [
      'De chaînes d’approvisionnement nord-américaines intégrées, surtout en Ontario',
      'Des routes de glace de l’Arctique seulement',
      'Du covoiturage au Sénat',
      'D’une interdiction de commercer avec les États-Unis',
    ],
    a: 'a',
    e: 'The Auto Pact story and later free-trade rules are why plants sit near the border, not why Ottawa writes parking tickets.',
    ef: 'Le Pacte de l’automobile et les règles de libre-échange qui ont suivi expliquent pourquoi les usines se trouvent près de la frontière.',
  },
  {
    id: 'eco-034',
    p: 'Diamond mining became an important northern industry especially in:',
    pf: 'L’extraction du diamant est devenue une industrie nordique importante surtout :',
    o: ['The Northwest Territories (and later other northern sites)', 'PEI potato farms', 'Downtown Toronto only', 'The Senate chamber'],
    of: ['Aux Territoires du Nord-Ouest (puis dans d’autres sites nordiques)', 'Dans les fermes de pommes de terre de l’Île-du-Prince-Édouard', 'Au centre-ville de Toronto seulement', 'Dans la chambre du Sénat'],
    a: 'a',
    e: 'Northern resources are not only gold rushes. Diamonds are a late-20th-century chapter.',
    ef: 'Les ressources du Nord ne se limitent pas aux ruées vers l’or. Le diamant est un chapitre de la fin du XXe siècle.',
  },
  {
    id: 'eco-035',
    t: 'tf',
    p: 'Most working Canadians are employees or self-employed in services such as retail, health, education, and professional work.',
    pf: 'La plupart des Canadiens en emploi sont salariés ou travailleurs autonomes dans les services, comme le commerce de détail, la santé, l’éducation et les professions libérales.',
    a: 'true',
    e: 'Primary industries still matter for exports. They no longer employ most people.',
    ef: 'Les industries primaires comptent encore pour les exportations, mais elles n’emploient plus la majorité de la population.',
  },
  {
    id: 'eco-036',
    p: 'A tariff is:',
    pf: 'Un tarif douanier est :',
    o: [
      'A tax on imports',
      'A type of provincial flower',
      'The Speaker’s gavel',
      'A municipal snow-clearing route',
    ],
    of: [
      'Une taxe sur les importations',
      'Une sorte de fleur provinciale',
      'Le marteau du président de la Chambre',
      'Un circuit municipal de déneigement',
    ],
    a: 'a',
    e: 'Free-trade agreements lower many tariffs. The citizenship idea is that trade policy shapes jobs.',
    ef: 'Les accords de libre-échange réduisent de nombreux tarifs. L’idée à retenir est que la politique commerciale influe sur l’emploi.',
  },
  {
    id: 'eco-037',
    p: 'Why do governments regulate banks and securities in Canada?',
    pf: 'Pourquoi les gouvernements réglementent-ils les banques et les valeurs mobilières au Canada?',
    o: [
      'To protect depositors and markets while private firms still compete',
      'Because there is no private banking',
      'To elect the Prime Minister',
      'To set hockey salaries',
    ],
    of: [
      'Pour protéger les déposants et les marchés, tout en laissant les entreprises privées se faire concurrence',
      'Parce qu’il n’existe pas de banques privées',
      'Pour élire le premier ministre',
      'Pour fixer les salaires au hockey',
    ],
    a: 'a',
    e: 'A mixed economy is not an unregulated one. The Bank of Canada is the central bank; OSFI and provincial regulators watch firms.',
    ef: 'Une économie mixte n’est pas une économie sans règles. La Banque du Canada est la banque centrale; le BSIF et les organismes provinciaux surveillent les entreprises.',
  },
  {
    id: 'eco-038',
    p: 'Seasonal industries such as fishing, farming, and tourism help explain why:',
    pf: 'Les industries saisonnières comme la pêche, l’agriculture et le tourisme expliquent en partie pourquoi :',
    o: [
      'Employment Insurance and other supports matter in some regions',
      'The Senate sits only in August',
      'There is no service sector',
      'Canada has no exports',
    ],
    of: [
      'L’assurance-emploi et d’autres mesures de soutien comptent beaucoup dans certaines régions',
      'Le Sénat ne siège qu’en août',
      'Il n’existe pas de secteur des services',
      'Le Canada n’a aucune exportation',
    ],
    a: 'a',
    e: 'Regional economies are not identical. Social programs sit beside resource cycles.',
    ef: 'Les économies régionales ne sont pas identiques. Les programmes sociaux accompagnent les cycles des ressources.',
  },
  {
    id: 'eco-039',
    t: 'tf',
    p: 'Crown land and resource royalties are a major source of wealth for some provincial governments.',
    pf: 'Les terres de la Couronne et les redevances sur les ressources constituent une source importante de richesse pour certains gouvernements provinciaux.',
    a: 'true',
    e: 'Oil, hydro, timber, and minerals sit on public land in much of the country. That is why resource policy is political.',
    ef: 'Dans une grande partie du pays, le pétrole, l’hydroélectricité, le bois et les minéraux se trouvent sur des terres publiques. C’est pourquoi la politique des ressources est un enjeu politique.',
  },
  {
    id: 'eco-040',
    p: 'The “staples” idea in Canadian economic history refers to:',
    pf: 'Dans l’histoire économique du Canada, la thèse des « produits de base » désigne :',
    o: [
      'Exporting raw or lightly processed goods such as fur, timber, wheat, and minerals',
      'Stapling bills in the Senate',
      'A type of maple-leaf pin only',
      'Municipal stapler by-laws',
    ],
    of: [
      'L’exportation de biens bruts ou peu transformés comme la fourrure, le bois, le blé et les minéraux',
      'L’agrafage des projets de loi au Sénat',
      'Un type d’épinglette à feuille d’érable seulement',
      'Des règlements municipaux sur les agrafeuses',
    ],
    a: 'a',
    e: 'The citizenship guide still walks through those classic exports before services took over employment.',
    ef: 'Le guide de citoyenneté passe encore en revue ces exportations classiques, antérieures à la domination des services dans l’emploi.',
  },
  {
    id: 'eco-041',
    p: 'Interprovincial trade barriers are a live issue because:',
    pf: 'Les obstacles au commerce interprovincial demeurent un enjeu actuel parce que :',
    o: [
      'Provinces can still regulate some goods and professions differently',
      'The Charter bans all trucking',
      'There is no Trans-Canada Highway',
      'Only territories may sell food',
    ],
    of: [
      'Les provinces peuvent encore réglementer différemment certains biens et certaines professions',
      'La Charte interdit tout camionnage',
      'La route Transcanadienne n’existe pas',
      'Seuls les territoires peuvent vendre des aliments',
    ],
    a: 'a',
    e: 'Canada is one country with internal frictions. That is an economy-and-federalism fact.',
    ef: 'Le Canada est un seul pays, mais avec des frictions internes. C’est un fait qui relève à la fois de l’économie et du fédéralisme.',
  },
  {
    id: 'eco-042',
    p: 'A balanced view of Canada’s economy for the test includes:',
    pf: 'Pour l’examen, une vision équilibrée de l’économie canadienne comprend :',
    o: [
      'Resources, manufacturing, and a large service sector, with big regional differences',
      'Only gold mining',
      'Only Hollywood film lots',
      'No trade with anyone',
    ],
    of: [
      'Les ressources, la fabrication et un vaste secteur des services, avec de grandes différences régionales',
      'L’extraction de l’or seulement',
      'Les studios de cinéma hollywoodiens seulement',
      'Aucun commerce avec qui que ce soit',
    ],
    a: 'a',
    e: 'If you remember only oil, or only banks, you will miss questions about fish, cars, or tourism.',
    ef: 'Si vous ne retenez que le pétrole ou que les banques, vous raterez les questions sur le poisson, l’automobile ou le tourisme.',
  },
  {
    id: 'eco-043',
    p: 'What are the three main types of industry in Canada?',
    pf: 'Quels sont les trois principaux types d’industrie au Canada?',
    o: [
      'Natural resources, manufacturing, and services',
      'Tourism, filmmaking, and banking only',
      'Fishing, hockey, and logging only',
      'Mining, railways, and the Senate',
    ],
    of: [
      'Les ressources naturelles, la fabrication et les services',
      'Le tourisme, le cinéma et les banques seulement',
      'La pêche, le hockey et l’exploitation forestière seulement',
      'Les mines, les chemins de fer et le Sénat',
    ],
    a: 'a',
    e: 'Most Canadians work in services, but resources and manufacturing remain central to the guide’s economic picture.',
    ef: 'La plupart des Canadiens travaillent dans les services, mais les ressources et la fabrication restent centrales dans le portrait économique du guide.',
  },
  {
    id: 'eco-044',
    p: 'Which three countries were the original partners in the NAFTA free-trade agreement (later updated as CUSMA/USMCA)?',
    pf: 'Quels trois pays étaient les partenaires initiaux de l’Accord de libre-échange nord-américain (ALENA), plus tard mis à jour (ACEUM/USMCA)?',
    o: [
      'Canada, the United States, and Mexico',
      'Canada, the United Kingdom, and France',
      'Canada, Japan, and China',
      'Canada, Australia, and New Zealand',
    ],
    of: [
      'Le Canada, les États-Unis et le Mexique',
      'Le Canada, le Royaume-Uni et la France',
      'Le Canada, le Japon et la Chine',
      'Le Canada, l’Australie et la Nouvelle-Zélande',
    ],
    a: 'a',
    e: 'North American free trade links Canada with its two continental neighbours. The agreement’s name has changed; the three-country idea has not.',
    ef: 'Le libre-échange nord-américain lie le Canada à ses deux voisins continentaux. Le nom de l’accord a changé; l’idée des trois pays, non.',
  },
  {
    id: 'eco-045',
    p: 'Why is trade with other countries important to Canada?',
    pf: 'Pourquoi le commerce avec d’autres pays est-il important pour le Canada?',
    o: [
      'It strengthens the economy and raises our standard of living',
      'It replaces the need for any domestic industry',
      'It lets provinces leave Confederation',
      'It is required before you can vote',
    ],
    of: [
      'Il renforce l’économie et élève notre niveau de vie',
      'Il remplace tout besoin d’industrie intérieure',
      'Il permet aux provinces de quitter la Confédération',
      'Il est obligatoire avant de pouvoir voter',
    ],
    a: 'a',
    e: 'Canada exports resources and manufactured goods and imports many products. Trade is taught as a path to prosperity, not as optional trivia.',
    ef: 'Le Canada exporte des ressources et des biens manufacturés et importe de nombreux produits. Le commerce est présenté comme un levier de prospérité, et non comme une anecdote facultative.',
  },
]);
