import { build } from './build.mjs';

export default build("canadas-economy", "Discover Canada — Canada's Economy", [
  {
    id: 'eco-001',
    p: 'Canada is a member of which group of advanced economies?',
    o: ['The G7', 'OPEC', 'The African Union', 'The Warsaw Pact'],
    a: 'a',
    e: 'Canada is one of the G7 countries. Trade, natural resources, services, and manufacturing are all important parts of the economy.',
  },
  {
    id: 'eco-002',
    p: 'Which of these is a major Canadian export sector highlighted in the study guide?',
    o: [
      'Natural resources such as energy, minerals, and forest products',
      'Domestic postage stamps',
      'Municipal parking tickets',
      'Provincial court transcripts',
    ],
    a: 'a',
    e: 'Canada has a resource-rich economy and also strong manufacturing and service industries. The United States is Canada’s largest trading partner.',
  },
  {
    id: 'eco-003',
    p: 'Canada’s largest trading partner is:',
    o: ['The United States', 'New Zealand', 'Chad', 'Iceland only'],
    a: 'a',
    e: 'Geography and supply chains make the U.S. market dominant. Mexico also matters under North American trade rules.',
  },
  {
    id: 'eco-004',
    p: 'A mixed economy means that:',
    o: [
      'Markets and private firms produce most goods, while governments tax, regulate, and provide public services',
      'The army owns every shop',
      'There is no private property',
      'Only barter is legal',
    ],
    a: 'a',
    e: 'Canada is capitalist with a substantial public sector—not a command economy, not a night-watchman state with no hospitals.',
  },
  {
    id: 'eco-005',
    t: 'tf',
    p: 'Most Canadians work in the service sector rather than in farming.',
    a: 'true',
    e: 'Services (health, education, retail, finance, government, technology) employ the majority. Resources still punch above their job count in exports.',
  },
  {
    id: 'eco-006',
    p: 'Manufacturing, including vehicles and machinery, is especially concentrated in:',
    o: ['Ontario and Quebec', 'Nunavut hamlets only', 'Prince Edward Island’s fishing villages only', 'Yukon gold creeks only'],
    a: 'a',
    e: 'Central Canada’s industrial belt is a standard regional-economy fact. Other provinces manufacture too, but the share is largest here.',
  },
  {
    id: 'eco-007',
    p: 'Prairie agriculture is famous for:',
    o: ['Grain (including wheat) and other farm exports', 'Tropical fruit plantations', 'Coffee estates', 'Banana republics'],
    a: 'a',
    e: 'The Prairies feed export markets. Potash and energy sit beside the grain story, especially in Saskatchewan and Alberta.',
  },
  {
    id: 'eco-008',
    p: 'Alberta’s economy is closely associated with:',
    o: ['Oil and gas', 'Cod stocks alone', 'Maple syrup alone', 'Automobile assembly in Windsor only'],
    a: 'a',
    e: 'Energy wealth shapes Alberta’s politics and Canada’s export mix. Agriculture remains important as well.',
  },
  {
    id: 'eco-009',
    p: 'British Columbia’s historic staple export sector includes:',
    o: ['Forestry', 'Prairie wheat only', 'Nunavut diamonds only', 'PEI potatoes only'],
    a: 'a',
    e: 'Wood, pulp, and paper—plus mining, ports, film, and Pacific trade—define much of B.C.’s economy.',
  },
  {
    id: 'eco-010',
    p: 'Atlantic Canada’s traditional resource economy includes:',
    o: ['Fisheries', 'Desert oil only', 'Alpine watches', 'Prairie potash only'],
    a: 'a',
    e: 'Cod, lobster, and other fisheries sit beside energy, tourism, and public-sector jobs. The groundfish collapse is part of modern history.',
  },
  {
    id: 'eco-011',
    t: 'tf',
    p: 'Quebec is a major producer of hydroelectric power.',
    a: 'true',
    e: 'Hydro-Québec and northern rivers made electricity a provincial economic pillar and an export.',
  },
  {
    id: 'eco-012',
    p: 'The Bank of Canada is:',
    o: [
      'The central bank that issues notes and conducts monetary policy',
      'A private supermarket',
      'A municipal credit union in Ottawa only',
      'The Senate’s cashier',
    ],
    a: 'a',
    e: 'It is public and independent in its day-to-day policy. Commercial banks are separate, regulated companies.',
  },
  {
    id: 'eco-013',
    p: 'Crown corporations are:',
    o: [
      'Companies owned by government to provide a public service or strategic role',
      'Always illegal',
      'The same as Cabinet',
      'Foreign embassies',
    ],
    a: 'a',
    e: 'Examples in the national story include railways, broadcasters, and energy utilities at various times.',
  },
  {
    id: 'eco-014',
    p: 'Employment Insurance and public pensions exist because:',
    o: [
      'Modern Canada built social programs to share risk',
      'The Quebec Act required them in 1774',
      'NATO dues include EI',
      'Municipalities print money',
    ],
    a: 'a',
    e: 'They are economic-citizenship facts as well as “modern Canada” facts: the market is not the only institution.',
  },
  {
    id: 'eco-015',
    t: 'tf',
    p: 'Income taxes help pay for public services such as health care, defence, and infrastructure.',
    a: 'true',
    e: 'Paying taxes lawfully is part of the civic bargain in a mixed economy.',
  },
  {
    id: 'eco-016',
    p: 'Unions and collective bargaining in Canada are:',
    o: [
      'Legal features of labour relations',
      'Banned by the Charter',
      'Available only to senators',
      'A U.S. import with no Canadian history',
    ],
    a: 'a',
    e: 'Minimum standards are mainly provincial. Unions are part of how wages and conditions are set in many workplaces.',
  },
  {
    id: 'eco-017',
    p: 'Toronto is especially important to the Canadian economy as:',
    o: ['A financial and business-services centre', 'The only port', 'The Arctic’s diamond capital', 'A territorial capital'],
    a: 'a',
    e: 'Banks, markets, and corporate head offices cluster there. Other cities have other specialties.',
  },
  {
    id: 'eco-018',
    p: 'Ports such as Vancouver and Halifax matter because Canada:',
    o: [
      'Trades heavily by sea as well as across the U.S. land border',
      'Is landlocked',
      'Bans exports',
      'Only ships by dogsled',
    ],
    a: 'a',
    e: 'Pacific, Atlantic, and Great Lakes–St. Lawrence routes are geography as economic destiny.',
  },
  {
    id: 'eco-019',
    p: 'Information technology and other advanced services are:',
    o: [
      'Growing parts of a modern mixed economy, not a replacement for resources overnight',
      'Illegal in Canada',
      'The only sector in 1867',
      'Run exclusively by the RCMP',
    ],
    a: 'a',
    e: 'The guide still stresses resources and manufacturing. A serious citizen also sees the service and tech shift.',
  },
  {
    id: 'eco-020',
    t: 'tf',
    p: 'Prosperity is even across every region of Canada.',
    a: 'false',
    e: 'The study guide itself describes different regional economies and different challenges. That unevenness is a testable idea.',
  },
  {
    id: 'eco-021',
    p: 'Potash is a mineral export especially associated with:',
    o: ['Saskatchewan', 'Prince Edward Island beaches', 'Downtown Montreal fashion only', 'Yukon tourism only'],
    a: 'a',
    e: 'Fertilizer minerals are a Prairie specialty. Energy and grain complete the picture.',
  },
  {
    id: 'eco-022',
    p: 'The Canadian dollar:',
    o: [
      'Floats on foreign-exchange markets',
      'Is printed by each province separately as legal tender',
      'Is pegged to the yen by the Charter',
      'Was replaced by the euro in 2002',
    ],
    a: 'a',
    e: 'A floating currency is part of how a trading economy adjusts. The Bank of Canada influences conditions, not a fixed peg.',
  },
  {
    id: 'eco-023',
    p: 'Why does the citizenship test care about the economy at all?',
    o: [
      'Because geography, trade, and jobs shape the country you are joining',
      'Because you must work in oil to become a citizen',
      'Because the Charter lists stock tips',
      'Because senators run factories',
    ],
    a: 'a',
    e: 'You are not asked to forecast GDP. You are asked to place Canada among trading democracies with regional specialties.',
  },
  {
    id: 'eco-024',
    t: 'tf',
    p: 'The federal government is the only government that spends money in the economy.',
    a: 'false',
    e: 'Provinces spend heavily on health and education. Municipalities spend on local services. All three tax in overlapping ways.',
  },
  {
    id: 'eco-025',
    p: 'Mining is important in:',
    o: [
      'The Shield, the Cordillera, and the North, among other regions',
      'Only downtown Toronto condominiums',
      'Only the Senate',
      'Only PEI potato fields',
    ],
    a: 'a',
    e: 'Gold, iron, nickel, diamonds, and more are regional staples. Indigenous land rights often intersect with mines.',
  },
  {
    id: 'eco-026',
    p: 'Tourism is an export in the economic sense when:',
    o: [
      'Visitors from abroad spend money in Canada',
      'Canadians buy groceries',
      'A city reprints a parking ticket',
      'A court charges a filing fee to a resident',
    ],
    a: 'a',
    e: 'Landscapes, cities, and cultural attractions are part of the service economy the guide groups with other industries.',
  },
  {
    id: 'eco-027',
    p: 'NAFTA-era (and successor) free-trade rules matter most for:',
    o: [
      'Cross-border manufacturing and agriculture',
      'Whether the Monarch can visit',
      'How juries are selected',
      'The lyrics of O Canada',
    ],
    a: 'a',
    e: 'The legal title of the agreement has changed. The citizenship-test idea is close economic integration in North America.',
  },
  {
    id: 'eco-028',
    t: 'tf',
    p: 'Canada has both large private banks and a public central bank.',
    a: 'true',
    e: 'Do not mix the Bank of Canada with the Royal Bank or other commercial banks. They play different roles.',
  },
]);
