import { build } from './build.mjs';

export default build('federal-elections', 'Discover Canada — Federal Elections', [
  {
    id: 'ele-001',
    p: 'What is the minimum age to vote in a Canadian federal election?',
    o: ['16', '18', '19', '21'],
    a: 'b',
    e: 'Canadian citizens who are at least 18 years old on election day may vote in federal elections.',
  },
  {
    id: 'ele-002',
    p: 'What is an electoral district also called?',
    o: ['A riding', 'A Cabinet', 'A caucus', 'A constituency court'],
    a: 'a',
    e: 'Voters in each electoral district, or riding, elect one Member of Parliament to the House of Commons.',
  },
  {
    id: 'ele-003',
    t: 'tf',
    p: 'Federal ballots in Canada are secret.',
    a: 'true',
    e: 'The secret ballot is a safeguard of democracy: no one should know how you voted, and you should not feel pressured to reveal it.',
  },
  {
    id: 'ele-004',
    p: 'To vote in a federal election you must be:',
    o: [
      'A Canadian citizen',
      'A permanent resident who has lived here one year',
      'A visitor with a tourist visa',
      'A municipal taxpayer even if you are not a citizen',
    ],
    a: 'a',
    e: 'Citizenship and age 18 are the basic federal voting rules. Residency rules affect where you vote, not the citizenship requirement.',
  },
  {
    id: 'ele-005',
    p: 'Federal elections are run by:',
    o: ['Elections Canada, an independent agency', 'The Prime Minister’s campaign office', 'The RCMP commissioner personally', 'City clerks in Ottawa only'],
    a: 'a',
    e: 'The Chief Electoral Officer and Elections Canada are independent of the government of the day.',
  },
  {
    id: 'ele-006',
    p: 'Canada’s federal voting system is:',
    o: [
      'Single-member plurality (first past the post)',
      'A nationwide presidential college',
      'Sortition of all adults',
      'Appointment by the Senate',
    ],
    a: 'a',
    e: 'The candidate with the most votes in a riding wins, even without 50%. Seat totals can differ from the popular vote.',
  },
  {
    id: 'ele-007',
    p: 'A by-election is held when:',
    o: [
      'A seat becomes vacant between general elections',
      'The Supreme Court rewrites a statute',
      'A municipality wants a new flag',
      'NATO meets',
    ],
    a: 'a',
    e: 'Death, resignation, or other vacancy in a riding triggers a by-election, not a full national vote.',
  },
  {
    id: 'ele-008',
    t: 'tf',
    p: 'You must belong to a political party to run for the House of Commons.',
    a: 'false',
    e: 'Independents may run. Most successful candidates still have a party, but it is not a legal requirement.',
  },
  {
    id: 'ele-009',
    p: 'Intimidation, vote buying, and impersonation at the polls are:',
    o: ['Crimes', 'Ordinary campaign tactics', 'Senate privileges', 'Municipal zoning tools'],
    a: 'a',
    e: 'Electoral fraud is a criminal matter. The secret ballot exists to reduce pressure and bribery.',
  },
  {
    id: 'ele-010',
    p: 'There is a legal maximum life of a House of Commons. In practice this means:',
    o: [
      'A general election must be held within that limit (governments often go sooner)',
      'MPs keep their seats for life',
      'There are never elections',
      'Only the Senate is dissolved',
    ],
    a: 'a',
    e: 'Parliament cannot sit forever. The government usually chooses an earlier date while it still has confidence.',
  },
  {
    id: 'ele-011',
    p: 'After the votes are counted, a government is formed when:',
    o: [
      'A leader can command the confidence of the House and is invited by the Governor General',
      'The candidate with the most personal votes nationwide becomes president',
      'The Chief Justice appoints Cabinet',
      'Mayors of provincial capitals vote',
    ],
    a: 'a',
    e: 'Election night seat counts matter because they predict confidence—not because they are a direct vote for Prime Minister.',
  },
  {
    id: 'ele-012',
    p: 'Advance polls exist so that:',
    o: [
      'People who cannot vote easily on election day can vote earlier',
      'Parties can see your ballot',
      'Only senators vote',
      'Tourists can elect MPs',
    ],
    a: 'a',
    e: 'Special ballots and advance voting are accessibility features of a modern election, still under Elections Canada rules.',
  },
  {
    id: 'ele-013',
    t: 'tf',
    p: 'Permanent residents may vote in federal elections.',
    a: 'false',
    e: 'Federal voting is for citizens. Permanent residents may later become citizens and then vote.',
  },
  {
    id: 'ele-014',
    p: 'A riding elects how many MPs to the House of Commons?',
    o: ['One', 'Two, always', 'Ten', 'None; ridings elect senators'],
    a: 'a',
    e: 'One MP per district is the first-past-the-post design.',
  },
  {
    id: 'ele-015',
    p: 'Party platforms are:',
    o: [
      'The promises and policies a party offers voters',
      'The floor of the Senate',
      'Police search warrants',
      'Municipal bus routes',
    ],
    a: 'a',
    e: 'You vote for a local candidate, but platforms tell you what a party would try to do in government.',
  },
  {
    id: 'ele-016',
    p: 'Election advertising and spending are:',
    o: ['Regulated by law', 'Unlimited and untraceable by design', 'Run by the U.S. Federal Election Commission', 'Secret even from Elections Canada'],
    a: 'a',
    e: 'Limits and disclosure rules aim to keep money from buying the outcome outright.',
  },
  {
    id: 'ele-017',
    p: 'You should not tell a stranger how you voted if you do not want to, because:',
    o: [
      'The ballot is secret and pressure is improper',
      'It is a Criminal Code offence to discuss politics at home',
      'Only lawyers may know',
      'The Governor General must be informed first',
    ],
    a: 'a',
    e: 'Secrecy protects you. You may discuss politics freely; you must not be forced to show a marked ballot.',
  },
  {
    id: 'ele-018',
    t: 'tf',
    p: 'The Prime Minister can legally cancel an election result because the party dislikes it.',
    a: 'false',
    e: 'Elections Canada counts ballots. Courts can hear legal challenges. The government does not get a veto on the people’s choice.',
  },
  {
    id: 'ele-019',
    p: 'Voters lists exist to:',
    o: [
      'Identify eligible electors, with ways to register if you are missing',
      'Publish how you voted last time',
      'Replace citizenship',
      'Appoint senators',
    ],
    a: 'a',
    e: 'If you are not on the list, you can usually register with proof of identity and address, including at the polling station in many cases.',
  },
  {
    id: 'ele-020',
    p: 'Scrutineers at a polling place are typically:',
    o: [
      'Party or candidate representatives watching the count for fairness',
      'Supreme Court judges',
      'Foreign diplomats with votes',
      'Municipal animal-control officers',
    ],
    a: 'a',
    e: 'They observe; they do not mark ballots. Transparency is part of trust in the count.',
  },
  {
    id: 'ele-021',
    p: 'A minority government can still govern if it:',
    o: [
      'Wins confidence votes with support from other parties or independents',
      'Ignores the House entirely',
      'Dissolves the Supreme Court',
      'Declares ridings abolished',
    ],
    a: 'a',
    e: 'Minority parliaments are common. They require negotiation. They are still legitimate governments.',
  },
  {
    id: 'ele-022',
    t: 'tf',
    p: 'Winning the nationwide popular vote automatically makes a party the government.',
    a: 'false',
    e: 'Seats matter, not the popular-vote total alone. A party can win the most votes and still lose the seat race.',
  },
  {
    id: 'ele-023',
    p: 'Who may be a candidate for MP, in general terms?',
    o: [
      'A citizen who meets legal eligibility rules and is properly nominated',
      'Any tourist',
      'Only people born in Ottawa',
      'Only sitting senators',
    ],
    a: 'a',
    e: 'There are rules on age, citizenship, deposits, and signatures. Criminal disqualifications exist. Birthplace in Ottawa is not one of them.',
  },
  {
    id: 'ele-024',
    p: 'The writ of election is:',
    o: [
      'The formal order that starts an election in a riding',
      'A Supreme Court novel',
      'A municipal parking ticket',
      'The Speech from the Throne',
    ],
    a: 'a',
    e: 'When writs are issued, the campaign clock runs. Returning officers then administer the vote locally.',
  },
  {
    id: 'ele-025',
    p: 'If you are away from home, you may still vote by:',
    o: [
      'Special ballot or other Elections Canada procedures',
      'Emailing the Prime Minister your choice',
      'Asking a neighbour to mark your ballot for you as they wish',
      'Voting in a U.S. presidential primary',
    ],
    a: 'a',
    e: 'There are lawful absentee methods. Giving someone else your vote to use as they please is not one of them.',
  },
  {
    id: 'ele-026',
    t: 'tf',
    p: 'It is illegal to take a photo of your marked federal ballot to show others as a general practice; ballot secrecy rules apply.',
    a: 'true',
    e: 'The point of the secret ballot is that nobody can demand proof of your vote. Follow Elections Canada rules at the polling place.',
  },
  {
    id: 'ele-027',
    p: 'Ridings are designed, in principle, to:',
    o: [
      'Give each MP a roughly comparable number of people to represent, with northern and rural exceptions',
      'Match NHL team markets',
      'Equal the number of senators from each city',
      'Follow subway lines only',
    ],
    a: 'a',
    e: 'Independent commissions redraw maps. Geography and communities of interest also matter, especially in the North.',
  },
  {
    id: 'ele-028',
    p: 'A campaign “transfer of power” after a change of government includes:',
    o: [
      'Swearing in a new Prime Minister and Cabinet',
      'Repealing the Constitution automatically',
      'Firing all judges',
      'Closing Elections Canada forever',
    ],
    a: 'a',
    e: 'The public service stays. Ministers change. That is how a parliamentary system rotates power without a revolution.',
  },
  {
    id: 'ele-029',
    p: 'Why do some people say “vote splitting” matters in first past the post?',
    o: [
      'Similar parties can divide votes and let another candidate win the riding with less than half',
      'Every vote is transferred until someone has 50%',
      'Senators break ties in each poll',
      'The Governor General picks the local winner',
    ],
    a: 'a',
    e: 'Plurality means the top vote-getter wins. That is a feature of the system, not a glitch in the counting machines.',
  },
  {
    id: 'ele-030',
    t: 'tf',
    p: 'Federal election day voting is open to anyone who shows a hydro bill, even if they are not a citizen.',
    a: 'false',
    e: 'ID proves who you are and where you live. It does not replace citizenship.',
  },
]);
