import { build } from './build.mjs';

export default build('federal-elections', 'Discover Canada — Federal Elections', [
  {
    id: 'ele-001',
    p: 'What is the minimum age to vote in a Canadian federal election?',
    pf: 'Quel est l’âge minimal pour voter à une élection fédérale canadienne?',
    o: ['16', '18', '19', '21'],
    of: ['16 ans', '18 ans', '19 ans', '21 ans'],
    a: 'b',
    e: 'Canadian citizens who are at least 18 years old on election day may vote in federal elections.',
    ef: 'Les citoyens canadiens âgés d’au moins 18 ans le jour du scrutin peuvent voter aux élections fédérales.',
  },
  {
    id: 'ele-002',
    p: 'What is an electoral district also called?',
    pf: 'Comment appelle-t-on aussi une circonscription électorale?',
    o: ['A riding', 'A Cabinet', 'A caucus', 'A constituency court'],
    of: ['Un comté', 'Un cabinet', 'Un caucus', 'Un tribunal de circonscription'],
    a: 'a',
    e: 'Voters in each electoral district, or riding, elect one Member of Parliament to the House of Commons.',
    ef: 'Les électeurs de chaque circonscription électorale, ou comté, élisent un député à la Chambre des communes.',
  },
  {
    id: 'ele-003',
    t: 'tf',
    p: 'Federal ballots in Canada are secret.',
    pf: 'Au Canada, le vote aux élections fédérales est secret.',
    a: 'true',
    e: 'The secret ballot is a safeguard of democracy: no one should know how you voted, and you should not feel pressured to reveal it.',
    ef: 'Le scrutin secret protège la démocratie : personne ne doit savoir pour qui vous avez voté et vous ne devez subir aucune pression pour le révéler.',
  },
  {
    id: 'ele-004',
    p: 'To vote in a federal election you must be:',
    pf: 'Pour voter à une élection fédérale, vous devez être :',
    o: [
      'A Canadian citizen',
      'A permanent resident who has lived here one year',
      'A visitor with a tourist visa',
      'A municipal taxpayer even if you are not a citizen',
    ],
    of: [
      'Citoyen canadien',
      'Résident permanent qui vit ici depuis un an',
      'Visiteur muni d’un visa de touriste',
      'Contribuable municipal, même sans être citoyen',
    ],
    a: 'a',
    e: 'Citizenship and age 18 are the basic federal voting rules. Residency rules affect where you vote, not the citizenship requirement.',
    ef: 'La citoyenneté et l’âge de 18 ans sont les règles de base du vote fédéral. Les règles de résidence déterminent où vous votez, et non l’exigence de citoyenneté.',
  },
  {
    id: 'ele-005',
    p: 'Federal elections are run by:',
    pf: 'Les élections fédérales sont administrées par :',
    o: ['Elections Canada, an independent agency', 'The Prime Minister’s campaign office', 'The RCMP commissioner personally', 'City clerks in Ottawa only'],
    of: ['Élections Canada, un organisme indépendant', 'Le bureau de campagne du premier ministre', 'Le commissaire de la GRC en personne', 'Les greffiers municipaux d’Ottawa seulement'],
    a: 'a',
    e: 'The Chief Electoral Officer and Elections Canada are independent of the government of the day.',
    ef: 'Le directeur général des élections et Élections Canada sont indépendants du gouvernement en place.',
  },
  {
    id: 'ele-006',
    p: 'Canada’s federal voting system is:',
    pf: 'Le système électoral fédéral du Canada est :',
    o: [
      'Single-member plurality (first past the post)',
      'A nationwide presidential college',
      'Sortition of all adults',
      'Appointment by the Senate',
    ],
    of: [
      'Le scrutin uninominal majoritaire à un tour',
      'Un collège présidentiel national',
      'Le tirage au sort parmi tous les adultes',
      'La nomination par le Sénat',
    ],
    a: 'a',
    e: 'The candidate with the most votes in a riding wins, even without 50%. Seat totals can differ from the popular vote.',
    ef: 'Le candidat qui obtient le plus de voix dans une circonscription gagne, même sans atteindre 50 %. Le nombre de sièges peut différer du vote populaire.',
  },
  {
    id: 'ele-007',
    p: 'A by-election is held when:',
    pf: 'Une élection partielle a lieu lorsque :',
    o: [
      'A seat becomes vacant between general elections',
      'The Supreme Court rewrites a statute',
      'A municipality wants a new flag',
      'NATO meets',
    ],
    of: [
      'Un siège devient vacant entre deux élections générales',
      'La Cour suprême réécrit une loi',
      'Une municipalité veut un nouveau drapeau',
      'L’OTAN se réunit',
    ],
    a: 'a',
    e: 'Death, resignation, or other vacancy in a riding triggers a by-election, not a full national vote.',
    ef: 'Un décès, une démission ou une autre vacance dans une circonscription déclenche une élection partielle, et non un scrutin national complet.',
  },
  {
    id: 'ele-008',
    t: 'tf',
    p: 'You must belong to a political party to run for the House of Commons.',
    pf: 'Il faut appartenir à un parti politique pour se présenter à la Chambre des communes.',
    a: 'false',
    e: 'Independents may run. Most successful candidates still have a party, but it is not a legal requirement.',
    ef: 'Des candidats indépendants peuvent se présenter. La plupart des candidats élus ont un parti, mais ce n’est pas une exigence légale.',
  },
  {
    id: 'ele-009',
    p: 'Intimidation, vote buying, and impersonation at the polls are:',
    pf: 'L’intimidation, l’achat de votes et l’usurpation d’identité au bureau de scrutin sont :',
    o: ['Crimes', 'Ordinary campaign tactics', 'Senate privileges', 'Municipal zoning tools'],
    of: ['Des crimes', 'Des tactiques de campagne ordinaires', 'Des privilèges du Sénat', 'Des outils de zonage municipal'],
    a: 'a',
    e: 'Electoral fraud is a criminal matter. The secret ballot exists to reduce pressure and bribery.',
    ef: 'La fraude électorale est une affaire criminelle. Le scrutin secret existe pour réduire la pression et la corruption.',
  },
  {
    id: 'ele-010',
    p: 'There is a legal maximum life of a House of Commons. In practice this means:',
    pf: 'La loi fixe une durée maximale à une législature. En pratique, cela veut dire que :',
    o: [
      'A general election must be held within that limit (governments often go sooner)',
      'MPs keep their seats for life',
      'There are never elections',
      'Only the Senate is dissolved',
    ],
    of: [
      'Une élection générale doit avoir lieu dans ce délai (les gouvernements y vont souvent plus tôt)',
      'Les députés gardent leur siège à vie',
      'Il n’y a jamais d’élections',
      'Seul le Sénat est dissous',
    ],
    a: 'a',
    e: 'Parliament cannot sit forever. The government usually chooses an earlier date while it still has confidence.',
    ef: 'Le Parlement ne peut pas siéger indéfiniment. Le gouvernement choisit habituellement une date plus rapprochée pendant qu’il a encore la confiance de la Chambre.',
  },
  {
    id: 'ele-011',
    p: 'After the votes are counted, a government is formed when:',
    pf: 'Après le dépouillement des votes, un gouvernement se forme lorsque :',
    o: [
      'A leader can command the confidence of the House and is invited by the Governor General',
      'The candidate with the most personal votes nationwide becomes president',
      'The Chief Justice appoints Cabinet',
      'Mayors of provincial capitals vote',
    ],
    of: [
      'Un chef peut obtenir la confiance de la Chambre des communes et est invité par le gouverneur général',
      'Le candidat ayant le plus de voix personnelles au pays devient président',
      'Le juge en chef nomme le Cabinet',
      'Les maires des capitales provinciales votent',
    ],
    a: 'a',
    e: 'Election night seat counts matter because they predict confidence—not because they are a direct vote for Prime Minister.',
    ef: 'Le nombre de sièges compte le soir du scrutin parce qu’il annonce la confiance de la Chambre, et non parce qu’il s’agit d’un vote direct pour le premier ministre.',
  },
  {
    id: 'ele-012',
    p: 'Advance polls exist so that:',
    pf: 'Les bureaux de vote par anticipation existent pour que :',
    o: [
      'People who cannot vote easily on election day can vote earlier',
      'Parties can see your ballot',
      'Only senators vote',
      'Tourists can elect MPs',
    ],
    of: [
      'Les personnes qui ne peuvent pas voter facilement le jour du scrutin puissent voter plus tôt',
      'Les partis puissent voir votre bulletin',
      'Seuls les sénateurs votent',
      'Les touristes puissent élire des députés',
    ],
    a: 'a',
    e: 'Special ballots and advance voting are accessibility features of a modern election, still under Elections Canada rules.',
    ef: 'Le bulletin spécial et le vote par anticipation sont des mesures d’accessibilité d’une élection moderne, toujours régies par les règles d’Élections Canada.',
  },
  {
    id: 'ele-013',
    t: 'tf',
    p: 'Permanent residents may vote in federal elections.',
    pf: 'Les résidents permanents peuvent voter aux élections fédérales.',
    a: 'false',
    e: 'Federal voting is for citizens. Permanent residents may later become citizens and then vote.',
    ef: 'Le vote fédéral est réservé aux citoyens. Les résidents permanents pourront voter une fois devenus citoyens.',
  },
  {
    id: 'ele-014',
    p: 'A riding elects how many MPs to the House of Commons?',
    pf: 'Combien de députés une circonscription élit-elle à la Chambre des communes?',
    o: ['One', 'Two, always', 'Ten', 'None; ridings elect senators'],
    of: ['Un', 'Deux, toujours', 'Dix', 'Aucun; les circonscriptions élisent des sénateurs'],
    a: 'a',
    e: 'One MP per district is the first-past-the-post design.',
    ef: 'Un député par circonscription : c’est la logique du scrutin uninominal majoritaire à un tour.',
  },
  {
    id: 'ele-015',
    p: 'Party platforms are:',
    pf: 'Les plateformes de parti sont :',
    o: [
      'The promises and policies a party offers voters',
      'The floor of the Senate',
      'Police search warrants',
      'Municipal bus routes',
    ],
    of: [
      'Les promesses et les politiques qu’un parti propose aux électeurs',
      'Le parquet du Sénat',
      'Des mandats de perquisition policiers',
      'Des circuits d’autobus municipaux',
    ],
    a: 'a',
    e: 'You vote for a local candidate, but platforms tell you what a party would try to do in government.',
    ef: 'Vous votez pour un candidat local, mais les plateformes indiquent ce qu’un parti tenterait de faire au gouvernement.',
  },
  {
    id: 'ele-016',
    p: 'Election advertising and spending are:',
    pf: 'La publicité et les dépenses électorales sont :',
    o: ['Regulated by law', 'Unlimited and untraceable by design', 'Run by the U.S. Federal Election Commission', 'Secret even from Elections Canada'],
    of: ['Encadrées par la loi', 'Illimitées et intraçables par conception', 'Gérées par la commission électorale fédérale des États-Unis', 'Secrètes, même pour Élections Canada'],
    a: 'a',
    e: 'Limits and disclosure rules aim to keep money from buying the outcome outright.',
    ef: 'Les plafonds et les règles de divulgation visent à empêcher que l’argent achète carrément le résultat.',
  },
  {
    id: 'ele-017',
    p: 'You should not tell a stranger how you voted if you do not want to, because:',
    pf: 'Vous n’avez pas à dire à un inconnu pour qui vous avez voté, parce que :',
    o: [
      'The ballot is secret and pressure is improper',
      'It is a Criminal Code offence to discuss politics at home',
      'Only lawyers may know',
      'The Governor General must be informed first',
    ],
    of: [
      'Le bulletin est secret et toute pression est inacceptable',
      'Discuter de politique à la maison est une infraction au Code criminel',
      'Seuls les avocats peuvent le savoir',
      'Le gouverneur général doit en être informé d’abord',
    ],
    a: 'a',
    e: 'Secrecy protects you. You may discuss politics freely; you must not be forced to show a marked ballot.',
    ef: 'Le secret vous protège. Vous pouvez discuter librement de politique; on ne peut pas vous forcer à montrer un bulletin marqué.',
  },
  {
    id: 'ele-018',
    t: 'tf',
    p: 'The Prime Minister can legally cancel an election result because the party dislikes it.',
    pf: 'Le premier ministre peut légalement annuler un résultat électoral parce que son parti ne l’aime pas.',
    a: 'false',
    e: 'Elections Canada counts ballots. Courts can hear legal challenges. The government does not get a veto on the people’s choice.',
    ef: 'Élections Canada compte les bulletins. Les tribunaux peuvent entendre les contestations. Le gouvernement n’a aucun droit de veto sur le choix de la population.',
  },
  {
    id: 'ele-019',
    p: 'Voters lists exist to:',
    pf: 'Les listes électorales servent :',
    o: [
      'Identify eligible electors, with ways to register if you are missing',
      'Publish how you voted last time',
      'Replace citizenship',
      'Appoint senators',
    ],
    of: [
      'À recenser les électeurs admissibles, avec des moyens de s’inscrire si vous n’y figurez pas',
      'À publier pour qui vous avez voté la dernière fois',
      'À remplacer la citoyenneté',
      'À nommer les sénateurs',
    ],
    a: 'a',
    e: 'If you are not on the list, you can usually register with proof of identity and address, including at the polling station in many cases.',
    ef: 'Si vous ne figurez pas sur la liste, vous pouvez habituellement vous inscrire avec une preuve d’identité et d’adresse, souvent même au bureau de scrutin.',
  },
  {
    id: 'ele-020',
    p: 'Scrutineers at a polling place are typically:',
    pf: 'Les représentants présents à un bureau de scrutin sont généralement :',
    o: [
      'Party or candidate representatives watching the count for fairness',
      'Supreme Court judges',
      'Foreign diplomats with votes',
      'Municipal animal-control officers',
    ],
    of: [
      'Des représentants d’un parti ou d’un candidat qui surveillent le dépouillement pour en assurer l’équité',
      'Des juges de la Cour suprême',
      'Des diplomates étrangers ayant droit de vote',
      'Des agents municipaux du contrôle animalier',
    ],
    a: 'a',
    e: 'They observe; they do not mark ballots. Transparency is part of trust in the count.',
    ef: 'Ils observent; ils ne marquent pas les bulletins. La transparence fait partie de la confiance envers le dépouillement.',
  },
  {
    id: 'ele-021',
    p: 'A minority government can still govern if it:',
    pf: 'Un gouvernement minoritaire peut quand même gouverner s’il :',
    o: [
      'Wins confidence votes with support from other parties or independents',
      'Ignores the House entirely',
      'Dissolves the Supreme Court',
      'Declares ridings abolished',
    ],
    of: [
      'Remporte les votes de confiance grâce à l’appui d’autres partis ou de députés indépendants',
      'Ignore complètement la Chambre des communes',
      'Dissout la Cour suprême',
      'Déclare les circonscriptions abolies',
    ],
    a: 'a',
    e: 'Minority parliaments are common. They require negotiation. They are still legitimate governments.',
    ef: 'Les parlements minoritaires sont fréquents. Ils exigent de la négociation. Ils forment néanmoins des gouvernements légitimes.',
  },
  {
    id: 'ele-022',
    t: 'tf',
    p: 'Winning the nationwide popular vote automatically makes a party the government.',
    pf: 'Remporter le vote populaire à l’échelle du pays fait automatiquement d’un parti le gouvernement.',
    a: 'false',
    e: 'Seats matter, not the popular-vote total alone. A party can win the most votes and still lose the seat race.',
    ef: 'Ce sont les sièges qui comptent, et non le total du vote populaire à lui seul. Un parti peut obtenir le plus de voix et perdre quand même la course aux sièges.',
  },
  {
    id: 'ele-023',
    p: 'Who may be a candidate for MP, in general terms?',
    pf: 'De façon générale, qui peut être candidat à la députation fédérale?',
    o: [
      'A citizen who meets legal eligibility rules and is properly nominated',
      'Any tourist',
      'Only people born in Ottawa',
      'Only sitting senators',
    ],
    of: [
      'Un citoyen qui satisfait aux règles légales d’admissibilité et dont la candidature est dûment présentée',
      'N’importe quel touriste',
      'Seulement les personnes nées à Ottawa',
      'Seulement les sénateurs en poste',
    ],
    a: 'a',
    e: 'There are rules on age, citizenship, deposits, and signatures. Criminal disqualifications exist. Birthplace in Ottawa is not one of them.',
    ef: 'Des règles portent sur l’âge, la citoyenneté, le cautionnement et les signatures. Des inadmissibilités liées à des infractions existent. Être né à Ottawa n’en fait pas partie.',
  },
  {
    id: 'ele-024',
    p: 'The writ of election is:',
    pf: 'Le bref d’élection est :',
    o: [
      'The formal order that starts an election in a riding',
      'A Supreme Court novel',
      'A municipal parking ticket',
      'The Speech from the Throne',
    ],
    of: [
      'L’ordre officiel qui déclenche l’élection dans une circonscription',
      'Un roman de la Cour suprême',
      'Un constat d’infraction de stationnement municipal',
      'Le discours du Trône',
    ],
    a: 'a',
    e: 'When writs are issued, the campaign clock runs. Returning officers then administer the vote locally.',
    ef: 'Dès l’émission des brefs, le compte à rebours de la campagne commence. Les directeurs du scrutin administrent ensuite le vote sur place.',
  },
  {
    id: 'ele-025',
    p: 'If you are away from home, you may still vote by:',
    pf: 'Si vous êtes loin de chez vous, vous pouvez quand même voter :',
    o: [
      'Special ballot or other Elections Canada procedures',
      'Emailing the Prime Minister your choice',
      'Asking a neighbour to mark your ballot for you as they wish',
      'Voting in a U.S. presidential primary',
    ],
    of: [
      'Par bulletin spécial ou par d’autres procédures d’Élections Canada',
      'En envoyant votre choix par courriel au premier ministre',
      'En demandant à un voisin de marquer votre bulletin à sa guise',
      'En votant à une primaire présidentielle américaine',
    ],
    a: 'a',
    e: 'There are lawful absentee methods. Giving someone else your vote to use as they please is not one of them.',
    ef: 'Des méthodes légales existent pour voter à distance. Confier votre vote à quelqu’un qui en fera ce qu’il veut n’en est pas une.',
  },
  {
    id: 'ele-026',
    t: 'tf',
    p: 'It is illegal to take a photo of your marked federal ballot to show others as a general practice; ballot secrecy rules apply.',
    pf: 'En règle générale, il est interdit de photographier votre bulletin fédéral marqué pour le montrer à d’autres; les règles sur le secret du vote s’appliquent.',
    a: 'true',
    e: 'The point of the secret ballot is that nobody can demand proof of your vote. Follow Elections Canada rules at the polling place.',
    ef: 'Le scrutin secret fait que personne ne peut exiger une preuve de votre vote. Respectez les règles d’Élections Canada au bureau de scrutin.',
  },
  {
    id: 'ele-027',
    p: 'Ridings are designed, in principle, to:',
    pf: 'Les circonscriptions sont conçues, en principe, pour :',
    o: [
      'Give each MP a roughly comparable number of people to represent, with northern and rural exceptions',
      'Match NHL team markets',
      'Equal the number of senators from each city',
      'Follow subway lines only',
    ],
    of: [
      'Donner à chaque député un nombre de personnes à représenter à peu près comparable, avec des exceptions dans le Nord et en milieu rural',
      'Correspondre aux marchés des équipes de la LNH',
      'Égaler le nombre de sénateurs de chaque ville',
      'Suivre uniquement les lignes de métro',
    ],
    a: 'a',
    e: 'Independent commissions redraw maps. Geography and communities of interest also matter, especially in the North.',
    ef: 'Des commissions indépendantes redessinent la carte électorale. La géographie et les communautés d’intérêts comptent aussi, surtout dans le Nord.',
  },
  {
    id: 'ele-028',
    p: 'A campaign “transfer of power” after a change of government includes:',
    pf: 'Le « transfert du pouvoir » après un changement de gouvernement comprend :',
    o: [
      'Swearing in a new Prime Minister and Cabinet',
      'Repealing the Constitution automatically',
      'Firing all judges',
      'Closing Elections Canada forever',
    ],
    of: [
      'L’assermentation d’un nouveau premier ministre et d’un nouveau Cabinet',
      'L’abrogation automatique de la Constitution',
      'Le congédiement de tous les juges',
      'La fermeture définitive d’Élections Canada',
    ],
    a: 'a',
    e: 'The public service stays. Ministers change. That is how a parliamentary system rotates power without a revolution.',
    ef: 'La fonction publique demeure en place. Les ministres changent. C’est ainsi qu’un régime parlementaire fait alterner le pouvoir sans révolution.',
  },
  {
    id: 'ele-029',
    p: 'Why do some people say “vote splitting” matters in first past the post?',
    pf: 'Pourquoi dit-on que la « division du vote » compte dans un scrutin majoritaire à un tour?',
    o: [
      'Similar parties can divide votes and let another candidate win the riding with less than half',
      'Every vote is transferred until someone has 50%',
      'Senators break ties in each poll',
      'The Governor General picks the local winner',
    ],
    of: [
      'Des partis semblables peuvent se partager les voix et laisser un autre candidat remporter la circonscription avec moins de la moitié des voix',
      'Chaque vote est transféré jusqu’à ce que quelqu’un atteigne 50 %',
      'Les sénateurs brisent les égalités dans chaque bureau de scrutin',
      'Le gouverneur général choisit le gagnant local',
    ],
    a: 'a',
    e: 'Plurality means the top vote-getter wins. That is a feature of the system, not a glitch in the counting machines.',
    ef: 'La pluralité veut dire que celui qui récolte le plus de voix gagne. C’est une caractéristique du système, non un défaut du dépouillement.',
  },
  {
    id: 'ele-030',
    t: 'tf',
    p: 'Federal election day voting is open to anyone who shows a hydro bill, even if they are not a citizen.',
    pf: 'Le jour du scrutin fédéral, quiconque présente une facture d’électricité peut voter, même sans être citoyen.',
    a: 'false',
    e: 'ID proves who you are and where you live. It does not replace citizenship.',
    ef: 'Les pièces d’identité prouvent qui vous êtes et où vous habitez. Elles ne remplacent pas la citoyenneté.',
  },
  {
    id: 'ele-031',
    p: 'To vote on election day you generally need to:',
    pf: 'Pour voter le jour du scrutin, vous devez généralement :',
    o: [
      'Prove your identity and address according to Elections Canada rules',
      'Bring a letter from your MP',
      'Speak both official languages fluently',
      'Pay a poll tax',
    ],
    of: [
      'Prouver votre identité et votre adresse selon les règles d’Élections Canada',
      'Apporter une lettre de votre député',
      'Parler couramment les deux langues officielles',
      'Payer une taxe électorale',
    ],
    a: 'a',
    e: 'Several ID combinations are accepted. Citizenship is still required; a hydro bill alone does not make a non-citizen a voter.',
    ef: 'Plusieurs combinaisons de pièces d’identité sont acceptées. La citoyenneté demeure obligatoire; une facture d’électricité ne fait pas d’un non-citoyen un électeur.',
  },
  {
    id: 'ele-032',
    p: 'Enumeration historically meant:',
    pf: 'Historiquement, le recensement électoral consistait :',
    o: [
      'Going door to door to build the voters list',
      'Appointing senators',
      'Counting Supreme Court votes',
      'A type of municipal compost program',
    ],
    of: [
      'À faire du porte-à-porte pour dresser la liste électorale',
      'À nommer des sénateurs',
      'À compter les votes de la Cour suprême',
      'En un type de programme municipal de compostage',
    ],
    a: 'a',
    e: 'Canada now relies more on a National Register of Electors. You should still check that you are on the list.',
    ef: 'Le Canada s’appuie maintenant davantage sur le Registre national des électeurs. Vérifiez quand même que vous figurez sur la liste.',
  },
  {
    id: 'ele-033',
    t: 'tf',
    p: 'Third-party advertising in federal campaigns is regulated so that groups besides parties cannot spend without limits or disclosure.',
    pf: 'La publicité des tiers pendant les campagnes fédérales est encadrée, de sorte que des groupes autres que les partis ne peuvent pas dépenser sans plafond ni divulgation.',
    a: 'true',
    e: 'The idea is a fairer fight, not a ban on all speech. Parties, candidates, and third parties all face rules.',
    ef: 'L’idée est une lutte plus équitable, non une interdiction de toute expression. Les partis, les candidats et les tiers sont tous assujettis à des règles.',
  },
  {
    id: 'ele-034',
    p: 'A returning officer is:',
    pf: 'Un directeur du scrutin est :',
    o: [
      'The local Elections Canada official who runs the vote in a riding',
      'A Cabinet minister who counts ballots in secret',
      'A senator who vetoes results',
      'The Prime Minister’s campaign manager',
    ],
    of: [
      'Le fonctionnaire local d’Élections Canada qui administre le vote dans une circonscription',
      'Un ministre du Cabinet qui compte les bulletins en secret',
      'Un sénateur qui bloque les résultats',
      'Le directeur de campagne du premier ministre',
    ],
    a: 'a',
    e: 'Each electoral district has one. They are not the candidate.',
    ef: 'Chaque circonscription électorale en compte un. Ce n’est pas le candidat.',
  },
  {
    id: 'ele-035',
    p: 'Special (write-in or mail) ballots exist mainly so that:',
    pf: 'Les bulletins spéciaux (par la poste ou à inscription manuscrite) existent surtout pour que :',
    o: [
      'People who cannot get to an ordinary poll can still vote',
      'Non-citizens can elect the Speaker',
      'The Senate can vote in House races',
      'Tourists can pick the Prime Minister',
    ],
    of: [
      'Les personnes qui ne peuvent pas se rendre à un bureau de scrutin ordinaire puissent quand même voter',
      'Les non-citoyens puissent élire le président de la Chambre des communes',
      'Le Sénat puisse voter dans les courses aux Communes',
      'Les touristes puissent choisir le premier ministre',
    ],
    a: 'a',
    e: 'Students, travellers, some workers, and Canadians abroad may have special-ballot options. Rules are specific; guesswork is not.',
    ef: 'Les étudiants, les voyageurs, certains travailleurs et les Canadiens à l’étranger peuvent avoir accès au bulletin spécial. Les règles sont précises; il ne faut pas improviser.',
  },
  {
    id: 'ele-036',
    p: 'If you move to a new riding you should:',
    pf: 'Si vous déménagez dans une nouvelle circonscription, vous devriez :',
    o: [
      'Update your voter registration so you are on the correct list',
      'Keep voting in your old riding forever',
      'Ask the Governor General to move the riding with you',
      'Give up the right to vote',
    ],
    of: [
      'Mettre à jour votre inscription pour figurer sur la bonne liste électorale',
      'Continuer de voter dans votre ancienne circonscription pour toujours',
      'Demander au gouverneur général de déplacer la circonscription avec vous',
      'Renoncer à votre droit de vote',
    ],
    a: 'a',
    e: 'You vote where you reside (with some special rules). Lists go stale if you do not update.',
    ef: 'Vous votez là où vous résidez (sous réserve de quelques règles particulières). Les listes se périment si vous ne les mettez pas à jour.',
  },
  {
    id: 'ele-037',
    t: 'tf',
    p: 'Federal election campaigns have a minimum length set by law once the writs are issued.',
    pf: 'Les campagnes électorales fédérales ont une durée minimale fixée par la loi dès l’émission des brefs.',
    a: 'true',
    e: 'There is also a maximum life of a House. Combined, that is why election timing is not a complete free-for-all.',
    ef: 'Il existe aussi une durée maximale pour une législature. Ensemble, ces règles font que le choix de la date n’est pas entièrement libre.',
  },
  {
    id: 'ele-038',
    p: 'An independent candidate is someone who:',
    pf: 'Un candidat indépendant est une personne qui :',
    o: [
      'Runs without a party label',
      'Is appointed by the Senate',
      'Must be a judge',
      'Is chosen by the Governor General as local MP without a vote',
    ],
    of: [
      'Se présente sans étiquette de parti',
      'Est nommée par le Sénat',
      'Doit être juge',
      'Est choisie comme députée locale par le gouverneur général, sans vote',
    ],
    a: 'a',
    e: 'Independents can win. Most MPs still sit as party members.',
    ef: 'Des indépendants peuvent gagner. La plupart des députés siègent tout de même sous une bannière de parti.',
  },
  {
    id: 'ele-039',
    p: 'Why does the citizenship guide care that you know how to vote?',
    pf: 'Pourquoi le guide de citoyenneté tient-il à ce que vous sachiez comment voter?',
    o: [
      'Voting is both a right and a listed responsibility of citizenship',
      'Only public servants may vote',
      'Ballots elect senators in every province',
      'The test replaces the election',
    ],
    of: [
      'Voter est à la fois un droit et une responsabilité énumérée de la citoyenneté',
      'Seuls les fonctionnaires peuvent voter',
      'Les bulletins servent à élire des sénateurs dans chaque province',
      'L’examen remplace l’élection',
    ],
    a: 'a',
    e: 'Knowing the mechanics is how you use the right. Staying home is legal; it is not the civic ideal the guide teaches.',
    ef: 'Connaître la mécanique du vote, c’est ce qui permet d’exercer le droit. Rester à la maison est légal, mais ce n’est pas l’idéal civique enseigné par le guide.',
  },
  {
    id: 'ele-040',
    p: 'A coalition government, if one formed, would mean:',
    pf: 'Un gouvernement de coalition, s’il s’en formait un, voudrait dire que :',
    o: [
      'Two or more parties agree to govern together',
      'The Supreme Court sits in Cabinet',
      'Municipalities run foreign policy',
      'The Monarch picks every deputy minister',
    ],
    of: [
      'Deux partis ou plus s’entendent pour gouverner ensemble',
      'La Cour suprême siège au Cabinet',
      'Les municipalités dirigent la politique étrangère',
      'Le souverain choisit chaque sous-ministre',
    ],
    a: 'a',
    e: 'Canada more often uses minority governments with case-by-case support. Coalition is still a parliamentary possibility.',
    ef: 'Le Canada recourt plus souvent à des gouvernements minoritaires appuyés au cas par cas. La coalition demeure une possibilité parlementaire.',
  },
  {
    id: 'ele-041',
    t: 'tf',
    p: 'You may volunteer on a campaign even if you are not a candidate.',
    pf: 'Vous pouvez faire du bénévolat dans une campagne même si vous n’êtes pas candidat.',
    a: 'true',
    e: 'Parties and candidates depend on volunteers. Foreign interference rules still apply; the civic activity itself is normal.',
    ef: 'Les partis et les candidats dépendent des bénévoles. Les règles sur l’ingérence étrangère s’appliquent toujours; l’activité civique elle-même est tout à fait normale.',
  },
  {
    id: 'ele-042',
    p: 'Poll clerks and deputy returning officers at a polling place are there to:',
    pf: 'Les greffiers du scrutin et les scrutateurs présents à un bureau de vote sont là pour :',
    o: [
      'Administer the vote fairly, not to campaign',
      'Tell you which party to support',
      'Open your marked ballot to the room',
      'Swear in the Prime Minister',
    ],
    of: [
      'Administrer le vote équitablement, et non pour faire campagne',
      'Vous dire quel parti appuyer',
      'Ouvrir votre bulletin marqué devant la salle',
      'Assermenter le premier ministre',
    ],
    a: 'a',
    e: 'They are election workers. Scrutineers watch for parties; they do not run the poll.',
    ef: 'Ce sont des membres du personnel électoral. Les représentants des candidats surveillent pour les partis; ils n’administrent pas le bureau de scrutin.',
  },
  {
    id: 'ele-043',
    p: 'Reapportionment of seats among provinces happens because:',
    pf: 'La redistribution des sièges entre les provinces a lieu parce que :',
    o: [
      'Population changes, and the Constitution plus statute adjust Commons seat counts',
      'The Senate demands more MPs in Ottawa’s suburbs only',
      'The Governor General picks a lucky province each decade',
      'Ridings are banned in the West',
    ],
    of: [
      'La population change, et la Constitution ainsi que la loi ajustent le nombre de sièges aux Communes',
      'Le Sénat exige plus de députés uniquement dans la banlieue d’Ottawa',
      'Le gouverneur général choisit une province chanceuse chaque décennie',
      'Les circonscriptions sont interdites dans l’Ouest',
    ],
    a: 'a',
    e: 'Representation by population is the principle. Senate regional seats are a different design.',
    ef: 'La représentation proportionnelle à la population est le principe directeur. Les sièges régionaux du Sénat suivent une autre logique.',
  },
  {
    id: 'ele-044',
    p: 'A recount may be requested or required when:',
    pf: 'Un nouveau dépouillement peut être demandé ou obligatoire lorsque :',
    o: [
      'The margin is very close or there are serious counting concerns',
      'A party simply dislikes the winner',
      'The weather is poor',
      'The Speaker wants a different seating plan',
    ],
    of: [
      'L’écart est très serré ou de sérieuses préoccupations entourent le dépouillement',
      'Un parti n’aime tout simplement pas le gagnant',
      'Le temps est mauvais',
      'Le président de la Chambre veut un autre plan de salle',
    ],
    a: 'a',
    e: 'Close races have legal recount rules. Losing on a clear count is not grounds to rerun the election for fun.',
    ef: 'Des règles légales encadrent le nouveau dépouillement dans les courses serrées. Perdre selon un décompte clair n’est pas un motif pour refaire l’élection.',
  },
]);
