import { build } from './build.mjs';

export default build(
  'how-canadians-govern-themselves',
  'Discover Canada — How Canadians Govern Themselves',
  [
    {
      id: 'gov-001',
      p: 'Who is the Head of State in Canada?',
      pf: 'Qui est le chef de l’État au Canada?',
      o: ['The Prime Minister', 'The Governor General', 'The Monarch', 'The Chief Justice of Canada'],
      of: ['Le premier ministre', 'Le gouverneur général', 'Le souverain', 'Le juge en chef du Canada'],
      a: 'c',
      e: 'Canada is a constitutional monarchy. The Monarch is Head of State and is represented in Canada by the Governor General.',
      ef: 'Le Canada est une monarchie constitutionnelle. Le souverain est chef de l’État et le gouverneur général le représente au Canada.',
    },
    {
      id: 'gov-002',
      p: 'Who is the Head of Government in Canada?',
      pf: 'Qui est le chef du gouvernement au Canada?',
      o: [
        'The Governor General',
        'The Prime Minister',
        'The Speaker of the Senate',
        'The Lieutenant Governor of Ontario',
      ],
      of: [
        'Le gouverneur général',
        'Le premier ministre',
        'Le président du Sénat',
        'Le lieutenant-gouverneur de l’Ontario',
      ],
      a: 'b',
      e: 'The Prime Minister is Head of Government, leads the party that can command the House of Commons, and chooses Cabinet.',
      ef: 'Le premier ministre est chef du gouvernement, dirige le parti qui obtient l’appui de la Chambre des communes et choisit le Cabinet.',
    },
    {
      id: 'gov-003',
      p: 'Which three levels of government operate in Canada?',
      pf: 'Quels sont les trois ordres de gouvernement au Canada?',
      o: [
        'Federal, provincial or territorial, and municipal',
        'Royal, colonial, and county',
        'Senate, Cabinet, and Supreme Court',
        'Federal, NATO, and United Nations',
      ],
      of: [
        'Fédéral, provincial ou territorial, et municipal',
        'Royal, colonial et comtal',
        'Le Sénat, le Cabinet et la Cour suprême',
        'Fédéral, l’OTAN et les Nations Unies',
      ],
      a: 'a',
      e: 'Federal, provincial/territorial, and municipal governments share responsibilities such as defence, education, and local services.',
      ef: 'Les gouvernements fédéral, provinciaux ou territoriaux et municipaux se partagent des responsabilités comme la défense, l’éducation et les services locaux.',
    },
    {
      id: 'gov-004',
      p: 'Who is Canada’s current Prime Minister?',
      pf: 'Qui est l’actuel premier ministre du Canada?',
      o: [
        '{{primeMinister}}',
        'The Governor General',
        'The Chief Justice of Canada',
        'The Speaker of the House of Commons',
      ],
      of: [
        '{{primeMinister}}',
        'Le gouverneur général',
        'Le juge en chef du Canada',
        'Le président de la Chambre des communes',
      ],
      a: 'a',
      e: 'Office-holders change. As of the last verification date in this app, the Prime Minister is {{primeMinister}}.',
      ef: 'Les titulaires de charge changent. À la dernière date de vérification dans cette application, le premier ministre est {{primeMinister}}.',
      k: 'primeMinister',
    },
    {
      id: 'gov-005',
      p: 'Who currently represents the Monarch in Canada as Governor General?',
      pf: 'Qui représente actuellement le souverain au Canada à titre de gouverneur général?',
      o: ['{{governorGeneral}}', 'The Speaker of the Senate', 'The Premier of Ontario', 'The Mayor of Ottawa'],
      of: ['{{governorGeneral}}', 'Le président du Sénat', 'Le premier ministre de l’Ontario', 'Le maire d’Ottawa'],
      a: 'a',
      e: 'The Governor General is {{governorGeneral}}, last verified with the other current office-holders in this app.',
      ef: 'Le gouverneur général est {{governorGeneral}}, selon la dernière vérification des titulaires de charge dans cette application.',
      k: 'governorGeneral',
    },
    {
      id: 'gov-006',
      p: 'Who is Canada’s current Head of State by name?',
      pf: 'Qui est, nommément, l’actuel chef de l’État du Canada?',
      o: ['{{headOfState}}', 'The Prime Minister of France', 'The UN Secretary-General', 'The Premier of Quebec'],
      of: ['{{headOfState}}', 'Le premier ministre de la France', 'Le secrétaire général de l’ONU', 'Le premier ministre du Québec'],
      a: 'a',
      e: 'The office is the Monarch. The current person, last verified here, is {{headOfState}}.',
      ef: 'La charge est celle de souverain. La personne en poste, selon la dernière vérification ici, est {{headOfState}}.',
      k: 'headOfState',
    },
    {
      id: 'gov-007',
      p: 'Which party is currently in power federally, according to this app’s dated file?',
      pf: 'Quel parti est actuellement au pouvoir au fédéral, selon le fichier daté de cette application?',
      o: ['{{partyInPower}}', 'The official opposition in every province at once', 'The Senate Liberal caucus of 1867', 'NATO headquarters'],
      of: ['{{partyInPower}}', 'L’opposition officielle dans toutes les provinces à la fois', 'Le caucus libéral du Sénat de 1867', 'Le quartier général de l’OTAN'],
      a: 'a',
      e: 'The party that can command the House is {{partyInPower}}. Update current.json when that changes.',
      ef: 'Le parti qui obtient l’appui de la Chambre est {{partyInPower}}. Mettez current.json à jour quand cela change.',
      k: 'partyInPower',
    },
    {
      id: 'gov-008',
      p: 'The three parts of Parliament are:',
      pf: 'Les trois éléments du Parlement sont :',
      o: [
        'The Crown, the Senate, and the House of Commons',
        'The RCMP, the Bank of Canada, and NATO',
        'Premiers, mayors, and school boards',
        'The Supreme Court, juries, and police',
      ],
      of: [
        'La Couronne, le Sénat et la Chambre des communes',
        'La GRC, la Banque du Canada et l’OTAN',
        'Les premiers ministres provinciaux, les maires et les conseils scolaires',
        'La Cour suprême, les jurys et la police',
      ],
      a: 'a',
      e: 'A bill typically needs the Commons, the Senate, and Royal Assent (the Crown).',
      ef: 'Un projet de loi doit normalement franchir la Chambre des communes, le Sénat, puis la sanction royale (la Couronne).',
    },
    {
      id: 'gov-009',
      p: 'Senators are:',
      pf: 'Les sénateurs sont :',
      o: [
        'Appointed, on the Prime Minister’s advice',
        'Elected in every riding like MPs',
        'Chosen by a national lottery',
        'Always the provincial premiers',
      ],
      of: [
        'Nommés, sur l’avis du premier ministre',
        'Élus dans chaque circonscription, comme les députés',
        'Choisis par une loterie nationale',
        'Toujours les premiers ministres provinciaux',
      ],
      a: 'a',
      e: 'The Senate is appointed, not elected. It reviews legislation and represents regions in theory.',
      ef: 'Le Sénat est nommé et non élu. Il révise les projets de loi et représente en principe les régions.',
    },
    {
      id: 'gov-010',
      p: 'Members of Parliament in the House of Commons are:',
      pf: 'Les députés de la Chambre des communes sont :',
      o: ['Elected by voters in ridings', 'Appointed for life by the Monarch personally', 'Hired by the RCMP', 'Selected by the Supreme Court'],
      of: ['Élus par les électeurs des circonscriptions', 'Nommés à vie par le souverain en personne', 'Embauchés par la GRC', 'Choisis par la Cour suprême'],
      a: 'a',
      e: 'Each electoral district sends one MP. That is the democratic core of federal power.',
      ef: 'Chaque circonscription électorale envoie un député. C’est le cœur démocratique du pouvoir fédéral.',
    },
    {
      id: 'gov-011',
      p: 'Royal Assent is:',
      pf: 'La sanction royale est :',
      o: [
        'The Crown’s formal approval that turns a bill into law',
        'A Supreme Court dissent',
        'A municipal building permit',
        'A NATO vote',
      ],
      of: [
        'L’approbation officielle de la Couronne qui transforme un projet de loi en loi',
        'Une dissidence de la Cour suprême',
        'Un permis de construire municipal',
        'Un vote de l’OTAN',
      ],
      a: 'a',
      e: 'The Governor General (or a deputy) grants Royal Assent. By convention it is not refused for a properly passed bill.',
      ef: 'Le gouverneur général (ou son suppléant) accorde la sanction royale. Par convention, elle n’est pas refusée à un projet de loi régulièrement adopté.',
    },
    {
      id: 'gov-012',
      p: 'Cabinet is chosen by:',
      pf: 'Le Cabinet est choisi par :',
      o: ['The Prime Minister', 'A random draw of all voters', 'The official opposition whip only', 'The mayor of Ottawa'],
      of: ['Le premier ministre', 'Un tirage au sort parmi tous les électeurs', 'Le whip de l’opposition officielle seulement', 'Le maire d’Ottawa'],
      a: 'a',
      e: 'Ministers are usually MPs, sometimes senators. They are sworn of the Privy Council and bound by solidarity.',
      ef: 'Les ministres sont habituellement des députés, parfois des sénateurs. Ils sont assermentés au Conseil privé et tenus à la solidarité ministérielle.',
    },
    {
      id: 'gov-013',
      t: 'tf',
      p: 'If a government loses a confidence vote in the House of Commons, it must resign or call an election.',
      pf: 'Si un gouvernement perd un vote de confiance à la Chambre des communes, il doit démissionner ou déclencher des élections.',
      a: 'true',
      e: 'That is responsible government. Confidence is tested in the elected Commons, not in the Senate.',
      ef: 'C’est le principe du gouvernement responsable. La confiance se mesure à la Chambre des communes élue, et non au Sénat.',
    },
    {
      id: 'gov-014',
      p: 'The Leader of the Opposition is:',
      pf: 'Le chef de l’opposition est :',
      o: [
        'The leader of the largest party that is not in government',
        'The Governor General’s deputy',
        'Always a senator from Quebec',
        'The Chief Justice',
      ],
      of: [
        'Le chef du plus grand parti qui ne forme pas le gouvernement',
        'Le suppléant du gouverneur général',
        'Toujours un sénateur du Québec',
        'Le juge en chef',
      ],
      a: 'a',
      e: 'Official opposition status comes with funding, questions, and a recognized role in holding government to account.',
      ef: 'Le statut d’opposition officielle donne droit à un financement, à des questions et à un rôle reconnu pour exiger des comptes du gouvernement.',
    },
    {
      id: 'gov-015',
      p: 'The Speaker of the House of Commons is expected to be:',
      pf: 'Le président de la Chambre des communes doit être :',
      o: [
        'Impartial in chairing debates',
        'The Prime Minister’s campaign manager during sittings',
        'A provincial premier',
        'The head of the RCMP',
      ],
      of: [
        'Impartial dans la conduite des débats',
        'Le directeur de campagne du premier ministre pendant les séances',
        'Un premier ministre provincial',
        'Le chef de la GRC',
      ],
      a: 'a',
      e: 'The Speaker keeps order and does not vote except in limited tie-breaking situations.',
      ef: 'Le président maintient l’ordre et ne vote pas, sauf pour briser l’égalité dans des cas limités.',
    },
    {
      id: 'gov-016',
      p: 'Defence, criminal law, money and banking, and foreign affairs are mainly:',
      pf: 'La défense, le droit criminel, la monnaie et les banques ainsi que les affaires étrangères relèvent surtout :',
      o: ['Federal powers', 'Municipal powers', 'School-board powers', 'Powers of the official opposition only'],
      of: ['De compétences fédérales', 'De compétences municipales', 'De compétences des conseils scolaires', 'De compétences de la seule opposition officielle'],
      a: 'a',
      e: 'The Constitution Act, 1867 lists federal heads of power. Provinces have others, such as education and property and civil rights.',
      ef: 'La Loi constitutionnelle de 1867 énumère les compétences fédérales. Les provinces en ont d’autres, comme l’éducation ainsi que la propriété et les droits civils.',
    },
    {
      id: 'gov-017',
      p: 'Education and health-care delivery are mainly:',
      pf: 'L’éducation et la prestation des soins de santé relèvent surtout :',
      o: ['Provincial responsibilities', 'Exclusive NATO duties', 'Senate internal rules', 'Municipal snow-clearing contracts only'],
      of: ['De responsabilités provinciales', 'De fonctions exclusives de l’OTAN', 'Du règlement interne du Sénat', 'Des seuls contrats municipaux de déneigement'],
      a: 'a',
      e: 'Ottawa still spends and sets some national standards, especially in health funding, but delivery is provincial.',
      ef: 'Ottawa dépense encore et fixe certaines normes nationales, surtout par le financement de la santé, mais la prestation est provinciale.',
    },
    {
      id: 'gov-018',
      p: 'Municipal governments get their powers from:',
      pf: 'Les gouvernements municipaux tirent leurs pouvoirs :',
      o: ['The province (or territory)', 'The United Nations', 'The Monarch acting alone without statute', 'NATO'],
      of: ['De la province (ou du territoire)', 'Des Nations Unies', 'Du souverain agissant seul, sans loi', 'De l’OTAN'],
      a: 'a',
      e: 'Cities are “creatures of the province.” Local services such as transit, zoning, and snow clearing sit here.',
      ef: 'Les villes sont des « créatures de la province ». Les services locaux comme le transport en commun, le zonage et le déneigement relèvent d’elles.',
    },
    {
      id: 'gov-019',
      p: 'A Lieutenant Governor represents the Crown in:',
      pf: 'Un lieutenant-gouverneur représente la Couronne dans :',
      o: ['A province', 'A municipality only', 'The Supreme Court locker room', 'Every embassy'],
      of: ['Une province', 'Une municipalité seulement', 'Le vestiaire de la Cour suprême', 'Chaque ambassade'],
      a: 'a',
      e: 'Each province has a Lieutenant Governor. Territories have commissioners, a different office.',
      ef: 'Chaque province a un lieutenant-gouverneur. Les territoires ont des commissaires, une charge différente.',
    },
    {
      id: 'gov-020',
      t: 'tf',
      p: 'Territories were created by federal statute and do not have the same constitutional status as provinces.',
      pf: 'Les territoires ont été créés par une loi fédérale et n’ont pas le même statut constitutionnel que les provinces.',
      a: 'true',
      e: 'They now run most day-to-day services, but their legal starting point is different from a province’s.',
      ef: 'Ils gèrent aujourd’hui la plupart des services courants, mais leur fondement juridique diffère de celui d’une province.',
    },
    {
      id: 'gov-021',
      p: 'After an election, the Governor General invites someone to form a government based on:',
      pf: 'Après une élection, le gouverneur général invite une personne à former le gouvernement selon :',
      o: [
        'Who is most likely to hold the confidence of the House',
        'Who won the popular vote in every province',
        'Who is oldest',
        'Who lives in Rideau Hall already',
      ],
      of: [
        'Qui est le plus susceptible d’avoir la confiance de la Chambre',
        'Qui a remporté le vote populaire dans chaque province',
        'Qui est le plus âgé',
        'Qui habite déjà à Rideau Hall',
      ],
      a: 'a',
      e: 'Usually that is the leader of the party with the most seats, but the test is confidence, not a presidential-style popular vote.',
      ef: 'C’est habituellement le chef du parti ayant le plus de sièges, mais le critère est la confiance, non un vote populaire de type présidentiel.',
    },
    {
      id: 'gov-022',
      p: 'A majority government is one that:',
      pf: 'Un gouvernement majoritaire est celui qui :',
      o: [
        'Holds more than half the seats in the House of Commons',
        'Wins every municipal election',
        'Controls the Supreme Court',
        'Has the Governor General as party leader',
      ],
      of: [
        'Détient plus de la moitié des sièges à la Chambre des communes',
        'Remporte toutes les élections municipales',
        'Contrôle la Cour suprême',
        'A le gouverneur général comme chef de parti',
      ],
      a: 'a',
      e: 'A minority government has fewer than half the seats and needs support from others to survive confidence votes.',
      ef: 'Un gouvernement minoritaire détient moins de la moitié des sièges et a besoin de l’appui d’autres élus pour survivre aux votes de confiance.',
    },
    {
      id: 'gov-023',
      p: 'The Premier of a province is:',
      pf: 'Le premier ministre d’une province est :',
      o: [
        'Head of the provincial government',
        'Head of State of Canada',
        'Always an appointed senator',
        'The federal finance minister automatically',
      ],
      of: [
        'Le chef du gouvernement provincial',
        'Le chef de l’État du Canada',
        'Toujours un sénateur nommé',
        'Automatiquement le ministre fédéral des Finances',
      ],
      a: 'a',
      e: 'Do not confuse Premier (province/territory) with Prime Minister (Canada).',
      ef: 'Ne confondez pas le premier ministre d’une province ou d’un territoire avec le premier ministre du Canada.',
    },
    {
      id: 'gov-024',
      p: 'Making a federal law usually requires:',
      pf: 'L’adoption d’une loi fédérale exige habituellement :',
      o: [
        'Passage in the Commons and Senate and then Royal Assent',
        'A tweet from a mayor',
        'Approval by NATO',
        'A Supreme Court first draft',
      ],
      of: [
        'L’adoption par la Chambre des communes et le Sénat, puis la sanction royale',
        'Un message d’un maire sur les réseaux sociaux',
        'L’approbation de l’OTAN',
        'Une première version rédigée par la Cour suprême',
      ],
      a: 'a',
      e: 'Money bills have extra Commons privileges, but the ordinary path is still both Houses plus the Crown.',
      ef: 'Les projets de loi de finances donnent des privilèges supplémentaires aux Communes, mais le parcours ordinaire passe quand même par les deux chambres et la Couronne.',
    },
    {
      id: 'gov-025',
      t: 'tf',
      p: 'Constitutional conventions are unwritten rules that still structure how government works.',
      pf: 'Les conventions constitutionnelles sont des règles non écrites qui structurent quand même le fonctionnement du gouvernement.',
      a: 'true',
      e: 'Responsible government itself is mostly convention. Not every important rule is in a statute.',
      ef: 'Le gouvernement responsable lui-même relève surtout de la convention. Toutes les règles importantes ne se trouvent pas dans une loi.',
    },
    {
      id: 'gov-026',
      p: 'The written Constitution includes:',
      pf: 'La Constitution écrite comprend :',
      o: [
        'The Constitution Act, 1867 and the Constitution Act, 1982 (including the Charter)',
        'Only the Criminal Code',
        'Only municipal zoning bylaws',
        'The NATO treaty alone',
      ],
      of: [
        'La Loi constitutionnelle de 1867 et la Loi constitutionnelle de 1982 (y compris la Charte)',
        'Seulement le Code criminel',
        'Seulement les règlements municipaux de zonage',
        'Le seul traité de l’OTAN',
      ],
      a: 'a',
      e: 'Those two Acts are the core texts. Other statutes and orders are also part of the Constitution of Canada.',
      ef: 'Ces deux lois sont les textes centraux. D’autres lois et décrets font aussi partie de la Constitution du Canada.',
    },
    {
      id: 'gov-027',
      p: 'Judges are:',
      pf: 'Les juges sont :',
      o: [
        'Independent of Cabinet and of Parliament once appointed',
        'Elected on party lists like MPs',
        'Allowed to sit in Cabinet while judging',
        'Chosen each week by referendum',
      ],
      of: [
        'Indépendants du Cabinet et du Parlement une fois nommés',
        'Élus sur des listes de parti, comme les députés',
        'Autorisés à siéger au Cabinet tout en jugeant',
        'Choisis chaque semaine par référendum',
      ],
      a: 'a',
      e: 'Independence of the courts is a branch-of-government fact, not only a justice-chapter slogan.',
      ef: 'L’indépendance des tribunaux relève de la séparation des pouvoirs; ce n’est pas seulement un slogan du chapitre sur la justice.',
    },
    {
      id: 'gov-028',
      p: 'Which level of government is mainly responsible for citizenship and immigration?',
      pf: 'Quel ordre de gouvernement est principalement responsable de la citoyenneté et de l’immigration?',
      o: ['Federal', 'Municipal', 'School boards', 'The official opposition research office'],
      of: ['Le fédéral', 'Le municipal', 'Les conseils scolaires', 'Le bureau de recherche de l’opposition officielle'],
      a: 'a',
      e: 'Citizenship is a federal head of power. Provinces have roles in selection and settlement in practice, but the status is federal.',
      ef: 'La citoyenneté est une compétence fédérale. En pratique, les provinces ont un rôle dans la sélection et l’établissement, mais le statut est fédéral.',
    },
    {
      id: 'gov-029',
      p: '“Crown land” and “Crown attorney” use “Crown” to mean:',
      pf: 'Dans « terres de la Couronne » et « procureur de la Couronne », le mot « Couronne » désigne :',
      o: [
        'The state as a continuing legal person',
        'A jewellery store in Ottawa',
        'The official opposition',
        'A municipal brand',
      ],
      of: [
        'L’État en tant que personne juridique permanente',
        'Une bijouterie d’Ottawa',
        'L’opposition officielle',
        'Une marque municipale',
      ],
      a: 'a',
      e: 'The Crown is how Canadian law names the state. It is not the Prime Minister’s personal property.',
      ef: 'La Couronne est le nom que le droit canadien donne à l’État. Ce n’est pas la propriété personnelle du premier ministre.',
    },
    {
      id: 'gov-030',
      t: 'tf',
      p: 'The Governor General normally acts on the advice of the Prime Minister and Cabinet.',
      pf: 'Le gouverneur général agit normalement sur l’avis du premier ministre et du Cabinet.',
      a: 'true',
      e: 'Personal discretion is reserved for rare constitutional crises. Everyday powers are exercised on advice.',
      ef: 'Le pouvoir discrétionnaire personnel est réservé à de rares crises constitutionnelles. Les pouvoirs courants s’exercent sur avis.',
    },
    {
      id: 'gov-031',
      p: 'A Member of Parliament is elected to:',
      pf: 'Un député fédéral est élu :',
      o: ['The House of Commons in Ottawa', 'A city council only', 'The Supreme Court bench', 'The UN General Assembly automatically'],
      of: ['À la Chambre des communes, à Ottawa', 'À un conseil municipal seulement', 'À la magistrature de la Cour suprême', 'Automatiquement à l’Assemblée générale des Nations Unies'],
      a: 'a',
      e: 'Provincial legislators have other titles (MPP, MLA, MNA, MHA). Do not mix them with MP.',
      ef: 'Les élus provinciaux portent d’autres titres (député provincial, député de l’Assemblée nationale au Québec). Ne les confondez pas avec un député fédéral.',
    },
    {
      id: 'gov-032',
      p: 'Federalism means that:',
      pf: 'Le fédéralisme signifie que :',
      o: [
        'Power is divided between national and provincial governments',
        'There is only one government in Ottawa for all local roads',
        'The Monarch writes the Criminal Code alone',
        'Cities can declare war',
      ],
      of: [
        'Le pouvoir est partagé entre le gouvernement national et les gouvernements provinciaux',
        'Il n’y a qu’un seul gouvernement, à Ottawa, pour toutes les routes locales',
        'Le souverain rédige seul le Code criminel',
        'Les villes peuvent déclarer la guerre',
      ],
      a: 'a',
      e: 'Division of powers is the Canadian answer to governing a large, diverse country.',
      ef: 'Le partage des compétences est la réponse canadienne à la gouvernance d’un pays vaste et diversifié.',
    },
    {
      id: 'gov-033',
      p: 'Indigenous governments in Canada:',
      pf: 'Les gouvernements autochtones au Canada :',
      o: [
        'Exercise jurisdiction under treaties, statutes, and self-government agreements',
        'Were abolished in 1867',
        'Exist only as social clubs',
        'Replace the Governor General',
      ],
      of: [
        'Exercent des compétences en vertu de traités, de lois et d’accords d’autonomie gouvernementale',
        'Ont été abolis en 1867',
        'N’existent que comme clubs sociaux',
        'Remplacent le gouverneur général',
      ],
      a: 'a',
      e: 'Self-government is part of the modern constitutional landscape, alongside federal and provincial power.',
      ef: 'L’autonomie gouvernementale fait partie du paysage constitutionnel moderne, aux côtés des pouvoirs fédéraux et provinciaux.',
    },
    {
      id: 'gov-034',
      t: 'tf',
      p: 'The Prime Minister is chosen by a direct nationwide popular vote for that office, like a U.S. president.',
      pf: 'Le premier ministre est choisi par un vote populaire direct à l’échelle du pays pour cette charge, comme un président américain.',
      a: 'false',
      e: 'Canadians vote for local MPs. The Prime Minister is the leader who can command the House.',
      ef: 'Les Canadiens votent pour un député local. Le premier ministre est le chef qui obtient l’appui de la Chambre des communes.',
    },
    {
      id: 'gov-035',
      p: 'Question Period is a daily Commons practice in which:',
      pf: 'La période des questions est une pratique quotidienne aux Communes pendant laquelle :',
      o: [
        'Opposition members question the government',
        'Judges quiz Cabinet secretly',
        'Mayors rewrite the Constitution',
        'The Monarch vetoes bills by shouting',
      ],
      of: [
        'Les députés de l’opposition interrogent le gouvernement',
        'Des juges interrogent le Cabinet en secret',
        'Les maires réécrivent la Constitution',
        'Le souverain bloque des projets de loi en criant',
      ],
      a: 'a',
      e: 'It is a visible accountability ritual, even when answers are political.',
      ef: 'C’est un rituel de reddition de comptes bien visible, même quand les réponses sont politiques.',
    },
    {
      id: 'gov-036',
      p: 'A caucus is:',
      pf: 'Un caucus est :',
      o: [
        'The group of MPs (and often senators) belonging to the same party',
        'A type of court',
        'A municipal utility',
        'A military rank',
      ],
      of: [
        'Le groupe des députés (et souvent des sénateurs) d’un même parti',
        'Un type de tribunal',
        'Un service public municipal',
        'Un grade militaire',
      ],
      a: 'a',
      e: 'Caucus discipline is how parties stay united in the House.',
      ef: 'La discipline de caucus est la façon dont les partis restent unis à la Chambre.',
    },
    {
      id: 'gov-037',
      p: 'Which official reads the Speech from the Throne?',
      pf: 'Quel titulaire de charge lit le discours du Trône?',
      o: [
        'The Governor General (or the Monarch if present)',
        'The mayor of Ottawa',
        'The Chief Electoral Officer',
        'The Leader of the Opposition only',
      ],
      of: [
        'Le gouverneur général (ou le souverain s’il est présent)',
        'Le maire d’Ottawa',
        'Le directeur général des élections',
        'Le chef de l’opposition seulement',
      ],
      a: 'a',
      e: 'The speech is written by the government. The Crown delivers it to open a session of Parliament.',
      ef: 'Le discours est rédigé par le gouvernement. La Couronne le prononce pour ouvrir une session du Parlement.',
    },
    {
      id: 'gov-038',
      p: 'Money bills (taxes and borrowing) must originate in:',
      pf: 'Les projets de loi de finances (impôts et emprunts) doivent émaner :',
      o: [
        'The House of Commons',
        'The Senate only',
        'A municipal council in Ottawa',
        'The Supreme Court registry',
      ],
      of: [
        'De la Chambre des communes',
        'Du Sénat seulement',
        'D’un conseil municipal à Ottawa',
        'Du greffe de la Cour suprême',
      ],
      a: 'a',
      e: 'The elected house controls the purse. The Senate may delay some bills but does not start tax measures.',
      ef: 'La chambre élue contrôle les fonds publics. Le Sénat peut retarder certains projets de loi, mais il n’amorce pas les mesures fiscales.',
    },
    {
      id: 'gov-039',
      p: 'Senators must retire at age:',
      pf: 'Les sénateurs doivent prendre leur retraite à l’âge de :',
      o: ['75', '18', '30 on their first day only', 'There is no age rule'],
      of: ['75 ans', '18 ans', '30 ans, mais seulement le premier jour', 'Il n’y a aucune règle d’âge'],
      a: 'a',
      e: 'Appointed until 75 (unless they resign). They are not elected in the federal model taught on the test.',
      ef: 'Ils sont nommés jusqu’à 75 ans (sauf s’ils démissionnent). Ils ne sont pas élus dans le modèle fédéral enseigné pour l’examen.',
    },
    {
      id: 'gov-040',
      t: 'tf',
      p: 'A Cabinet minister is usually an MP (or sometimes a senator) who heads a department.',
      pf: 'Un ministre du Cabinet est habituellement un député (parfois un sénateur) qui dirige un ministère.',
      a: 'true',
      e: 'Ministers are chosen by the Prime Minister. Deputy ministers are public servants, not politicians.',
      ef: 'Les ministres sont choisis par le premier ministre. Les sous-ministres sont des fonctionnaires, non des politiciens.',
    },
    {
      id: 'gov-041',
      p: 'The federal public service is expected to:',
      pf: 'La fonction publique fédérale doit :',
      o: [
        'Give professional advice and carry out the law under ministers of different parties',
        'Campaign for the governing party at work',
        'Sit as a second Senate',
        'Appoint the Governor General each morning',
      ],
      of: [
        'Donner des conseils professionnels et appliquer la loi sous des ministres de partis différents',
        'Faire campagne pour le parti au pouvoir pendant les heures de travail',
        'Siéger comme un second Sénat',
        'Nommer le gouverneur général chaque matin',
      ],
      a: 'a',
      e: 'Non-partisan administration is how government survives a change of party. That is a convention worth knowing.',
      ef: 'Une administration non partisane permet à l’État de survivre à un changement de parti. C’est une convention à connaître.',
    },
    {
      id: 'gov-042',
      p: 'A Lieutenant Governor’s role in a province is most like:',
      pf: 'Le rôle d’un lieutenant-gouverneur dans une province ressemble le plus :',
      o: [
        'The Governor General’s role for Canada as a whole',
        'The Speaker of the House of Commons',
        'A municipal by-law officer',
        'The Chief Electoral Officer',
      ],
      of: [
        'À celui du gouverneur général pour l’ensemble du Canada',
        'À celui du président de la Chambre des communes',
        'À celui d’un agent municipal des règlements',
        'À celui du directeur général des élections',
      ],
      a: 'a',
      e: 'Royal Assent, opening the legislature, and acting on the premier’s advice are the provincial parallel.',
      ef: 'La sanction royale, l’ouverture de la législature et l’action sur l’avis du premier ministre provincial en sont le parallèle provincial.',
    },
    {
      id: 'gov-043',
      p: 'Territorial legislatures:',
      pf: 'Les assemblées législatives territoriales :',
      o: [
        'Make laws for the territory under federal statute, with a premier and cabinet in modern practice',
        'Can amend the Constitution Act, 1867, alone',
        'Replace Parliament in Ottawa',
        'Are appointed by city mayors in Toronto',
      ],
      of: [
        'Adoptent des lois pour le territoire en vertu d’une loi fédérale, avec un premier ministre et un cabinet dans la pratique moderne',
        'Peuvent modifier seules la Loi constitutionnelle de 1867',
        'Remplacent le Parlement à Ottawa',
        'Sont nommées par les maires de Toronto',
      ],
      a: 'a',
      e: 'Yukon, the Northwest Territories, and Nunavut have assemblies. They are not provinces, but they are real governments.',
      ef: 'Le Yukon, les Territoires du Nord-Ouest et le Nunavut ont des assemblées. Ce ne sont pas des provinces, mais ce sont de véritables gouvernements.',
    },
    {
      id: 'gov-044',
      t: 'tf',
      p: 'Municipal governments can levy some local taxes and pass by-laws about things such as zoning, transit, and snow clearing.',
      pf: 'Les gouvernements municipaux peuvent lever certaines taxes locales et adopter des règlements sur des sujets comme le zonage, le transport en commun et le déneigement.',
      a: 'true',
      e: 'Cities are creatures of the province. Their work is still the government most people meet every day.',
      ef: 'Les villes sont des créatures de la province. Leur travail demeure celui du gouvernement que la plupart des gens côtoient chaque jour.',
    },
    {
      id: 'gov-045',
      p: 'The federal spending power refers to Ottawa’s ability to:',
      pf: 'Le pouvoir fédéral de dépenser désigne la capacité d’Ottawa :',
      o: [
        'Spend money in areas of provincial jurisdiction, often with conditions (for example health transfers)',
        'Dissolve every city council',
        'Appoint all mayors',
        'Rewrite provincial constitutions by tweet',
      ],
      of: [
        'De dépenser dans des champs de compétence provinciale, souvent avec des conditions (par exemple les transferts en santé)',
        'De dissoudre tous les conseils municipaux',
        'De nommer tous les maires',
        'De réécrire les constitutions provinciales par un simple message en ligne',
      ],
      a: 'a',
      e: 'It is how national programs appear in fields the Constitution assigns mainly to provinces.',
      ef: 'C’est ainsi que des programmes nationaux apparaissent dans des domaines que la Constitution attribue surtout aux provinces.',
    },
    {
      id: 'gov-046',
      p: 'Opposition parties in the Commons exist to:',
      pf: 'Les partis de l’opposition aux Communes servent :',
      o: [
        'Question the government and offer an alternative',
        'Rubber-stamp every bill in secret',
        'Appoint judges each Friday',
        'Run Elections Canada',
      ],
      of: [
        'À interroger le gouvernement et à proposer une solution de rechange',
        'À approuver sans discuter chaque projet de loi, en secret',
        'À nommer les juges chaque vendredi',
        'À diriger Élections Canada',
      ],
      a: 'a',
      e: 'Official Opposition status goes to the largest party not in government. Smaller parties still have a role.',
      ef: 'Le statut d’opposition officielle va au plus grand parti qui ne forme pas le gouvernement. Les partis plus petits ont quand même un rôle.',
    },
    {
      id: 'gov-047',
      p: 'Royal commissions and public inquiries are tools to:',
      pf: 'Les commissions royales et les enquêtes publiques servent :',
      o: [
        'Investigate a serious public issue and recommend action',
        'Replace general elections',
        'Choose the Monarch',
        'Set hockey scores',
      ],
      of: [
        'À examiner un enjeu public important et à recommander des mesures',
        'À remplacer les élections générales',
        'À choisir le souverain',
        'À fixer les scores de hockey',
      ],
      a: 'a',
      e: 'They are not courts, but they can shape later laws. The test cares that government can study a problem in public.',
      ef: 'Ce ne sont pas des tribunaux, mais elles peuvent façonner des lois futures. Ce qui compte pour l’examen, c’est que l’État puisse étudier un problème publiquement.',
    },
    {
      id: 'gov-048',
      t: 'tf',
      p: 'The Prime Minister and Cabinet are part of the executive, not a fourth elected house of Parliament.',
      pf: 'Le premier ministre et le Cabinet font partie du pouvoir exécutif et ne forment pas une quatrième chambre élue du Parlement.',
      a: 'true',
      e: 'Parliament is Crown, Senate, and Commons. Cabinet directs the executive while remaining accountable to the Commons.',
      ef: 'Le Parlement, ce sont la Couronne, le Sénat et la Chambre des communes. Le Cabinet dirige l’exécutif tout en demeurant responsable devant les Communes.',
    },
    {
      id: 'gov-049',
      p: 'A portfolio in Cabinet is:',
      pf: 'Un portefeuille au Cabinet est :',
      o: [
        'The set of responsibilities given to a minister (for example Finance or Defence)',
        'A senator’s travel bag',
        'A municipal recycling bin',
        'A type of court file only in Quebec',
      ],
      of: [
        'L’ensemble des responsabilités confiées à un ministre (par exemple les Finances ou la Défense)',
        'Le sac de voyage d’un sénateur',
        'Un bac de recyclage municipal',
        'Un type de dossier judiciaire propre au Québec',
      ],
      a: 'a',
      e: 'The Prime Minister assigns portfolios. Titles change; the idea of a responsible minister does not.',
      ef: 'Le premier ministre attribue les portefeuilles. Les titres changent; l’idée d’un ministre responsable demeure.',
    },
    {
      id: 'gov-050',
      p: 'Constitutional monarchy in Canada means:',
      pf: 'La monarchie constitutionnelle au Canada signifie que :',
      o: [
        'The Monarch is Head of State, while elected ministers run the government under the Constitution',
        'The King writes the budget alone',
        'There is no Constitution',
        'Mayors crown themselves',
      ],
      of: [
        'Le souverain est chef de l’État, tandis que des ministres élus dirigent le gouvernement dans le respect de la Constitution',
        'Le roi rédige seul le budget',
        'Il n’existe aucune Constitution',
        'Les maires se couronnent eux-mêmes',
      ],
      a: 'a',
      e: 'Power is constrained by law and convention. The Crown is not a daily policy shop.',
      ef: 'Le pouvoir est encadré par le droit et la convention. La Couronne n’est pas un atelier de politiques au quotidien.',
    },
    {
      id: 'gov-051',
      p: 'Who usually summons, prorogues, or dissolves Parliament in practice?',
      pf: 'En pratique, qui convoque, proroge ou dissout habituellement le Parlement?',
      o: [
        'The Governor General, acting on the Prime Minister’s advice',
        'The mayor of Ottawa',
        'The Chief Justice acting as campaign manager',
        'A random jury in each riding',
      ],
      of: [
        'Le gouverneur général, sur l’avis du premier ministre',
        'Le maire d’Ottawa',
        'Le juge en chef agissant comme directeur de campagne',
        'Un jury tiré au sort dans chaque circonscription',
      ],
      a: 'a',
      e: 'Those are Crown powers. Convention says they follow ministerial advice except in rare controversies.',
      ef: 'Ce sont des pouvoirs de la Couronne. La convention veut qu’ils suivent l’avis ministériel, sauf dans de rares controverses.',
    },
    {
      id: 'gov-052',
      p: 'Who is the current Speaker of the House of Commons?',
      pf: 'Qui est l’actuel président de la Chambre des communes?',
      o: ['{{speakerOfTheHouse}}', '{{primeMinister}}', '{{governorGeneral}}', '{{headOfState}}'],
      of: ['{{speakerOfTheHouse}}', '{{primeMinister}}', '{{governorGeneral}}', '{{headOfState}}'],
      a: 'a',
      e: 'MPs elect the Speaker to chair the Commons impartially. As of the last verification date in this app, the Speaker is {{speakerOfTheHouse}}.',
      ef: 'Les députés élisent le président pour diriger la Chambre de façon impartiale. À la dernière date de vérification dans cette application, le président est {{speakerOfTheHouse}}.',
      k: 'speakerOfTheHouse',
    },
  ],
);
