import { build } from './build.mjs';

export default build(
  'how-canadians-govern-themselves',
  'Discover Canada — How Canadians Govern Themselves',
  [
    {
      id: 'gov-001',
      p: 'Who is the Head of State in Canada?',
      o: ['The Prime Minister', 'The Governor General', 'The Monarch', 'The Chief Justice of Canada'],
      a: 'c',
      e: 'Canada is a constitutional monarchy. The Monarch is Head of State and is represented in Canada by the Governor General.',
    },
    {
      id: 'gov-002',
      p: 'Who is the Head of Government in Canada?',
      o: [
        'The Governor General',
        'The Prime Minister',
        'The Speaker of the Senate',
        'The Lieutenant Governor of Ontario',
      ],
      a: 'b',
      e: 'The Prime Minister is Head of Government, leads the party that can command the House of Commons, and chooses Cabinet.',
    },
    {
      id: 'gov-003',
      p: 'Which three levels of government operate in Canada?',
      o: [
        'Federal, provincial or territorial, and municipal',
        'Royal, colonial, and county',
        'Senate, Cabinet, and Supreme Court',
        'Federal, NATO, and United Nations',
      ],
      a: 'a',
      e: 'Federal, provincial/territorial, and municipal governments share responsibilities such as defence, education, and local services.',
    },
    {
      id: 'gov-004',
      p: 'Who is Canada’s current Prime Minister?',
      o: [
        '{{primeMinister}}',
        'The Governor General',
        'The Chief Justice of Canada',
        'The Speaker of the House of Commons',
      ],
      a: 'a',
      e: 'Office-holders change. As of the last verification date in this app, the Prime Minister is {{primeMinister}}.',
      k: 'primeMinister',
    },
    {
      id: 'gov-005',
      p: 'Who currently represents the Monarch in Canada as Governor General?',
      o: ['{{governorGeneral}}', 'The Speaker of the Senate', 'The Premier of Ontario', 'The Mayor of Ottawa'],
      a: 'a',
      e: 'The Governor General is {{governorGeneral}}, last verified with the other current office-holders in this app.',
      k: 'governorGeneral',
    },
    {
      id: 'gov-006',
      p: 'Who is Canada’s current Head of State by name?',
      o: ['{{headOfState}}', 'The Prime Minister of France', 'The UN Secretary-General', 'The Premier of Quebec'],
      a: 'a',
      e: 'The office is the Monarch. The current person, last verified here, is {{headOfState}}.',
      k: 'headOfState',
    },
    {
      id: 'gov-007',
      p: 'Which party is currently in power federally, according to this app’s dated file?',
      o: ['{{partyInPower}}', 'The official opposition in every province at once', 'The Senate Liberal caucus of 1867', 'NATO headquarters'],
      a: 'a',
      e: 'The party that can command the House is {{partyInPower}}. Update current.json when that changes.',
      k: 'partyInPower',
    },
    {
      id: 'gov-008',
      p: 'The three parts of Parliament are:',
      o: [
        'The Crown, the Senate, and the House of Commons',
        'The RCMP, the Bank of Canada, and NATO',
        'Premiers, mayors, and school boards',
        'The Supreme Court, juries, and police',
      ],
      a: 'a',
      e: 'A bill typically needs the Commons, the Senate, and Royal Assent (the Crown).',
    },
    {
      id: 'gov-009',
      p: 'Senators are:',
      o: [
        'Appointed, on the Prime Minister’s advice',
        'Elected in every riding like MPs',
        'Chosen by a national lottery',
        'Always the provincial premiers',
      ],
      a: 'a',
      e: 'The Senate is appointed, not elected. It reviews legislation and represents regions in theory.',
    },
    {
      id: 'gov-010',
      p: 'Members of Parliament in the House of Commons are:',
      o: ['Elected by voters in ridings', 'Appointed for life by the Monarch personally', 'Hired by the RCMP', 'Selected by the Supreme Court'],
      a: 'a',
      e: 'Each electoral district sends one MP. That is the democratic core of federal power.',
    },
    {
      id: 'gov-011',
      p: 'Royal Assent is:',
      o: [
        'The Crown’s formal approval that turns a bill into law',
        'A Supreme Court dissent',
        'A municipal building permit',
        'A NATO vote',
      ],
      a: 'a',
      e: 'The Governor General (or a deputy) grants Royal Assent. By convention it is not refused for a properly passed bill.',
    },
    {
      id: 'gov-012',
      p: 'Cabinet is chosen by:',
      o: ['The Prime Minister', 'A random draw of all voters', 'The official opposition whip only', 'The mayor of Ottawa'],
      a: 'a',
      e: 'Ministers are usually MPs, sometimes senators. They are sworn of the Privy Council and bound by solidarity.',
    },
    {
      id: 'gov-013',
      t: 'tf',
      p: 'If a government loses a confidence vote in the House of Commons, it must resign or call an election.',
      a: 'true',
      e: 'That is responsible government. Confidence is tested in the elected Commons, not in the Senate.',
    },
    {
      id: 'gov-014',
      p: 'The Leader of the Opposition is:',
      o: [
        'The leader of the largest party that is not in government',
        'The Governor General’s deputy',
        'Always a senator from Quebec',
        'The Chief Justice',
      ],
      a: 'a',
      e: 'Official opposition status comes with funding, questions, and a recognized role in holding government to account.',
    },
    {
      id: 'gov-015',
      p: 'The Speaker of the House of Commons is expected to be:',
      o: [
        'Impartial in chairing debates',
        'The Prime Minister’s campaign manager during sittings',
        'A provincial premier',
        'The head of the RCMP',
      ],
      a: 'a',
      e: 'The Speaker keeps order and does not vote except in limited tie-breaking situations.',
    },
    {
      id: 'gov-016',
      p: 'Defence, criminal law, money and banking, and foreign affairs are mainly:',
      o: ['Federal powers', 'Municipal powers', 'School-board powers', 'Powers of the official opposition only'],
      a: 'a',
      e: 'The Constitution Act, 1867 lists federal heads of power. Provinces have others, such as education and property and civil rights.',
    },
    {
      id: 'gov-017',
      p: 'Education and health-care delivery are mainly:',
      o: ['Provincial responsibilities', 'Exclusive NATO duties', 'Senate internal rules', 'Municipal snow-clearing contracts only'],
      a: 'a',
      e: 'Ottawa still spends and sets some national standards, especially in health funding, but delivery is provincial.',
    },
    {
      id: 'gov-018',
      p: 'Municipal governments get their powers from:',
      o: ['The province (or territory)', 'The United Nations', 'The Monarch acting alone without statute', 'NATO'],
      a: 'a',
      e: 'Cities are “creatures of the province.” Local services such as transit, zoning, and snow clearing sit here.',
    },
    {
      id: 'gov-019',
      p: 'A Lieutenant Governor represents the Crown in:',
      o: ['A province', 'A municipality only', 'The Supreme Court locker room', 'Every embassy'],
      a: 'a',
      e: 'Each province has a Lieutenant Governor. Territories have commissioners, a different office.',
    },
    {
      id: 'gov-020',
      t: 'tf',
      p: 'Territories were created by federal statute and do not have the same constitutional status as provinces.',
      a: 'true',
      e: 'They now run most day-to-day services, but their legal starting point is different from a province’s.',
    },
    {
      id: 'gov-021',
      p: 'After an election, the Governor General invites someone to form a government based on:',
      o: [
        'Who is most likely to hold the confidence of the House',
        'Who won the popular vote in every province',
        'Who is oldest',
        'Who lives in Rideau Hall already',
      ],
      a: 'a',
      e: 'Usually that is the leader of the party with the most seats, but the test is confidence, not a presidential-style popular vote.',
    },
    {
      id: 'gov-022',
      p: 'A majority government is one that:',
      o: [
        'Holds more than half the seats in the House of Commons',
        'Wins every municipal election',
        'Controls the Supreme Court',
        'Has the Governor General as party leader',
      ],
      a: 'a',
      e: 'A minority government has fewer than half the seats and needs support from others to survive confidence votes.',
    },
    {
      id: 'gov-023',
      p: 'The Premier of a province is:',
      o: [
        'Head of the provincial government',
        'Head of State of Canada',
        'Always an appointed senator',
        'The federal finance minister automatically',
      ],
      a: 'a',
      e: 'Do not confuse Premier (province/territory) with Prime Minister (Canada).',
    },
    {
      id: 'gov-024',
      p: 'Making a federal law usually requires:',
      o: [
        'Passage in the Commons and Senate and then Royal Assent',
        'A tweet from a mayor',
        'Approval by NATO',
        'A Supreme Court first draft',
      ],
      a: 'a',
      e: 'Money bills have extra Commons privileges, but the ordinary path is still both Houses plus the Crown.',
    },
    {
      id: 'gov-025',
      t: 'tf',
      p: 'Constitutional conventions are unwritten rules that still structure how government works.',
      a: 'true',
      e: 'Responsible government itself is mostly convention. Not every important rule is in a statute.',
    },
    {
      id: 'gov-026',
      p: 'The written Constitution includes:',
      o: [
        'The Constitution Act, 1867 and the Constitution Act, 1982 (including the Charter)',
        'Only the Criminal Code',
        'Only municipal zoning bylaws',
        'The NATO treaty alone',
      ],
      a: 'a',
      e: 'Those two Acts are the core texts. Other statutes and orders are also part of the Constitution of Canada.',
    },
    {
      id: 'gov-027',
      p: 'Judges are:',
      o: [
        'Independent of Cabinet and of Parliament once appointed',
        'Elected on party lists like MPs',
        'Allowed to sit in Cabinet while judging',
        'Chosen each week by referendum',
      ],
      a: 'a',
      e: 'Independence of the courts is a branch-of-government fact, not only a justice-chapter slogan.',
    },
    {
      id: 'gov-028',
      p: 'Which level of government is mainly responsible for citizenship and immigration?',
      o: ['Federal', 'Municipal', 'School boards', 'The official opposition research office'],
      a: 'a',
      e: 'Citizenship is a federal head of power. Provinces have roles in selection and settlement in practice, but the status is federal.',
    },
    {
      id: 'gov-029',
      p: '“Crown land” and “Crown attorney” use “Crown” to mean:',
      o: [
        'The state as a continuing legal person',
        'A jewellery store in Ottawa',
        'The official opposition',
        'A municipal brand',
      ],
      a: 'a',
      e: 'The Crown is how Canadian law names the state. It is not the Prime Minister’s personal property.',
    },
    {
      id: 'gov-030',
      t: 'tf',
      p: 'The Governor General normally acts on the advice of the Prime Minister and Cabinet.',
      a: 'true',
      e: 'Personal discretion is reserved for rare constitutional crises. Everyday powers are exercised on advice.',
    },
    {
      id: 'gov-031',
      p: 'A Member of Parliament is elected to:',
      o: ['The House of Commons in Ottawa', 'A city council only', 'The Supreme Court bench', 'The UN General Assembly automatically'],
      a: 'a',
      e: 'Provincial legislators have other titles (MPP, MLA, MNA, MHA). Do not mix them with MP.',
    },
    {
      id: 'gov-032',
      p: 'Federalism means that:',
      o: [
        'Power is divided between national and provincial governments',
        'There is only one government in Ottawa for all local roads',
        'The Monarch writes the Criminal Code alone',
        'Cities can declare war',
      ],
      a: 'a',
      e: 'Division of powers is the Canadian answer to governing a large, diverse country.',
    },
    {
      id: 'gov-033',
      p: 'Indigenous governments in Canada:',
      o: [
        'Exercise jurisdiction under treaties, statutes, and self-government agreements',
        'Were abolished in 1867',
        'Exist only as social clubs',
        'Replace the Governor General',
      ],
      a: 'a',
      e: 'Self-government is part of the modern constitutional landscape, alongside federal and provincial power.',
    },
    {
      id: 'gov-034',
      t: 'tf',
      p: 'The Prime Minister is chosen by a direct nationwide popular vote for that office, like a U.S. president.',
      a: 'false',
      e: 'Canadians vote for local MPs. The Prime Minister is the leader who can command the House.',
    },
    {
      id: 'gov-035',
      p: 'Question Period is a daily Commons practice in which:',
      o: [
        'Opposition members question the government',
        'Judges quiz Cabinet secretly',
        'Mayors rewrite the Constitution',
        'The Monarch vetoes bills by shouting',
      ],
      a: 'a',
      e: 'It is a visible accountability ritual, even when answers are political.',
    },
    {
      id: 'gov-036',
      p: 'A caucus is:',
      o: [
        'The group of MPs (and often senators) belonging to the same party',
        'A type of court',
        'A municipal utility',
        'A military rank',
      ],
      a: 'a',
      e: 'Caucus discipline is how parties stay united in the House.',
    },
    {
      id: 'gov-037',
      p: 'Which official reads the Speech from the Throne?',
      o: [
        'The Governor General (or the Monarch if present)',
        'The mayor of Ottawa',
        'The Chief Electoral Officer',
        'The Leader of the Opposition only',
      ],
      a: 'a',
      e: 'The speech is written by the government. The Crown delivers it to open a session of Parliament.',
    },
  ],
);
