import { build } from './build.mjs';

export default build("canadas-history", "Discover Canada — Canada's History", [
  {
    id: 'his-001',
    p: 'When did Canada become a country through Confederation?',
    pf: 'À quelle date le Canada est-il devenu un pays par la Confédération ?',
    o: ['July 1, 1867', 'July 1, 1812', 'April 17, 1982', 'November 11, 1918'],
    of: ['Le 1er juillet 1867', 'Le 1er juillet 1812', 'Le 17 avril 1982', 'Le 11 novembre 1918'],
    a: 'a',
    e: 'The British North America Act created the Dominion of Canada on July 1, 1867, uniting Ontario, Quebec, Nova Scotia, and New Brunswick.',
    ef: 'L’Acte de l’Amérique du Nord britannique a donné naissance au Dominion du Canada le 1er juillet 1867, en réunissant l’Ontario, le Québec, la Nouvelle-Écosse et le Nouveau-Brunswick.',
  },
  {
    id: 'his-002',
    p: 'Who was Canada’s first Prime Minister?',
    pf: 'Qui a été le premier premier ministre du Canada ?',
    o: ['Wilfrid Laurier', 'George-Étienne Cartier', 'Sir John A. Macdonald', 'Robert Borden'],
    of: ['Wilfrid Laurier', 'George-Étienne Cartier', 'Sir John A. Macdonald', 'Robert Borden'],
    a: 'c',
    e: 'Sir John A. Macdonald led the Conservative government after Confederation and is remembered as a principal architect of the new federation.',
    ef: 'Sir John A. Macdonald a dirigé le gouvernement conservateur après la Confédération; on se souvient de lui comme d’un artisan principal de la nouvelle fédération.',
  },
  {
    id: 'his-003',
    p: 'What did the Quebec Act of 1774 do?',
    pf: 'Qu’a fait l’Acte de Québec de 1774 ?',
    o: [
      'It banned the French language in courts',
      'It allowed French Catholics to keep their religion and civil law',
      'It created the Province of Manitoba',
      'It ended the fur trade',
    ],
    of: [
      'Il a interdit l’usage du français devant les tribunaux',
      'Il a permis aux catholiques francophones de conserver leur religion et le droit civil français',
      'Il a créé la province du Manitoba',
      'Il a mis fin à la traite des fourrures',
    ],
    a: 'b',
    e: 'The Quebec Act protected the French language, Catholic faith, and French civil law in Quebec—an early example of accommodation that still shapes Canada.',
    ef: 'L’Acte de Québec a protégé la langue française, la foi catholique et le droit civil français au Québec : un premier geste d’accommodement qui marque encore le pays.',
  },
  {
    id: 'his-004',
    p: 'Who founded Quebec City in 1608?',
    pf: 'Qui a fondé la ville de Québec en 1608 ?',
    o: ['Jacques Cartier', 'Samuel de Champlain', 'John Cabot', 'Lord Durham'],
    of: ['Jacques Cartier', 'Samuel de Champlain', 'Jean Cabot', 'Lord Durham'],
    a: 'b',
    e: 'Champlain established a lasting French settlement at Quebec, a foundation of New France.',
    ef: 'Champlain a implanté à Québec un établissement français durable, pierre d’assise de la Nouvelle-France.',
  },
  {
    id: 'his-005',
    p: 'Jacques Cartier’s voyages in the 1530s are important because he:',
    pf: 'Les voyages de Jacques Cartier, dans les années 1530, sont importants parce qu’il a :',
    o: [
      'Explored the St. Lawrence and claimed the area for France',
      'Built the Canadian Pacific Railway',
      'Patriated the Constitution',
      'Won Vimy Ridge',
    ],
    of: [
      'Exploré le Saint-Laurent et revendiqué la région au nom de la France',
      'Construit le chemin de fer Canadien Pacifique',
      'Rapatrié la Constitution',
      'Remporté la bataille de la crête de Vimy',
    ],
    a: 'a',
    e: 'Cartier’s expeditions opened the St. Lawrence to French claims. Permanent settlement came later.',
    ef: 'Les expéditions de Cartier ont ouvert le Saint-Laurent aux revendications françaises. L’établissement permanent est venu plus tard.',
  },
  {
    id: 'his-006',
    p: 'John Cabot’s 1497 voyage is associated with:',
    pf: 'Le voyage de Jean Cabot, en 1497, est associé à :',
    o: [
      'An English claim and the later Atlantic fishery off Newfoundland',
      'The founding of Montreal',
      'The Persons Case',
      'D-Day',
    ],
    of: [
      'Une revendication anglaise et, plus tard, la pêche atlantique au large de Terre-Neuve',
      'La fondation de Montréal',
      'L’affaire des « personnes »',
      'Le jour J',
    ],
    a: 'a',
    e: 'Cabot (Giovanni Caboto) sailed for England. The rich cod fishery drew Europeans to Newfoundland for centuries.',
    ef: 'Cabot (Giovanni Caboto) naviguait pour l’Angleterre. Les riches bancs de morue ont attiré les Européens à Terre-Neuve pendant des siècles.',
  },
  {
    id: 'his-007',
    p: 'Norse visitors reached the Atlantic around the year 1000. A known site is:',
    pf: 'Des visiteurs scandinaves ont atteint la côte atlantique vers l’an 1000. Un site connu est :',
    o: ['L’Anse aux Meadows in Newfoundland', 'Vimy Ridge', 'Batoche', 'Juno Beach'],
    of: ['L’Anse aux Meadows, à Terre-Neuve', 'La crête de Vimy', 'Batoche', 'La plage Juno'],
    a: 'a',
    e: 'L’Anse aux Meadows is evidence of Viking presence. It did not lead to lasting European settlement.',
    ef: 'L’Anse aux Meadows témoigne de la présence viking. Cette présence n’a pas mené à un établissement européen durable.',
  },
  {
    id: 'his-008',
    p: 'The Hudson’s Bay Company was founded in:',
    pf: 'La Compagnie de la Baie d’Hudson a été fondée en :',
    o: ['1608', '1670', '1867', '1982'],
    of: ['1608', '1670', '1867', '1982'],
    a: 'b',
    e: 'A royal charter in 1670 created a fur-trade empire over a huge drainage basin called Rupert’s Land.',
    ef: 'Une charte royale accordée en 1670 a créé un empire de la fourrure sur un immense bassin hydrographique appelé la Terre de Rupert.',
  },
  {
    id: 'his-009',
    p: 'The Battle of the Plains of Abraham (1759) was fought at:',
    pf: 'La bataille des plaines d’Abraham (1759) s’est déroulée :',
    o: ['Quebec', 'Vancouver', 'Winnipeg', 'Halifax Citadel only in 1917'],
    of: ['À Québec', 'À Vancouver', 'À Winnipeg', 'À la citadelle d’Halifax, seulement en 1917'],
    a: 'a',
    e: 'British forces under Wolfe defeated the French under Montcalm. New France fell; 1763 confirmed British control.',
    ef: 'Les troupes britanniques de Wolfe ont vaincu les forces françaises de Montcalm. La Nouvelle-France est tombée et 1763 a confirmé la domination britannique.',
  },
  {
    id: 'his-010',
    p: 'The Royal Proclamation of 1763 is important in Indigenous history because it:',
    pf: 'La Proclamation royale de 1763 est importante dans l’histoire autochtone parce qu’elle a :',
    o: [
      'Set rules for Crown dealings with Indigenous lands',
      'Created the Province of Alberta',
      'Banned all treaties',
      'Ended the fur trade',
    ],
    of: [
      'Établi des règles encadrant les rapports de la Couronne avec les terres autochtones',
      'Créé la province de l’Alberta',
      'Interdit tous les traités',
      'Mis fin à la traite des fourrures',
    ],
    a: 'a',
    e: 'It recognized Indigenous land interests and required Crown treaties before settlement in many areas. It is still cited in law.',
    ef: 'Elle reconnaissait les intérêts fonciers des peuples autochtones et exigeait des traités avec la Couronne avant la colonisation dans bien des régions. On l’invoque encore devant les tribunaux.',
  },
  {
    id: 'his-011',
    p: 'The Constitutional Act of 1791 created:',
    pf: 'L’Acte constitutionnel de 1791 a créé :',
    o: ['Upper Canada and Lower Canada', 'Nunavut and Yukon', 'NATO and NORAD', 'The Senate and the Bank of Canada'],
    of: ['Le Haut-Canada et le Bas-Canada', 'Le Nunavut et le Yukon', 'L’OTAN et NORAD', 'Le Sénat et la Banque du Canada'],
    a: 'a',
    e: 'Upper Canada (Ontario) was mainly English and Protestant; Lower Canada (Quebec) remained mainly French and Catholic.',
    ef: 'Le Haut-Canada (l’Ontario) était surtout anglophone et protestant; le Bas-Canada (le Québec) est demeuré surtout francophone et catholique.',
  },
  {
    id: 'his-012',
    p: 'A result of the War of 1812 in British North America was that:',
    pf: 'Une conséquence de la guerre de 1812 en Amérique du Nord britannique est que :',
    o: [
      'The colonies remained British rather than being absorbed by the United States',
      'Canada joined the United States',
      'Confederation happened immediately',
      'The French language was banned',
    ],
    of: [
      'Les colonies sont restées britanniques au lieu d’être absorbées par les États-Unis',
      'Le Canada s’est joint aux États-Unis',
      'La Confédération a eu lieu immédiatement',
      'La langue française a été interdite',
    ],
    a: 'a',
    e: 'American invasions failed to take the colonies. The war became part of English-Canadian founding mythology, alongside Indigenous and Québécois stories.',
    ef: 'Les invasions américaines n’ont pas réussi à prendre les colonies. Cette guerre est devenue un récit fondateur du Canada anglais, aux côtés des récits autochtones et québécois.',
  },
  {
    id: 'his-013',
    p: 'Laura Secord is remembered for:',
    pf: 'On se souvient de Laura Secord pour :',
    o: [
      'Warning British forces of an American attack during the War of 1812',
      'Founding the RCMP',
      'Writing O Canada',
      'Discovering gold in the Yukon',
    ],
    of: [
      'Avoir prévenu les troupes britanniques d’une attaque américaine pendant la guerre de 1812',
      'Avoir fondé la GRC',
      'Avoir écrit l’hymne Ô Canada',
      'Avoir découvert de l’or au Yukon',
    ],
    a: 'a',
    e: 'Her walk to warn of a planned attack is a classic War of 1812 story taught in the guide.',
    ef: 'Sa longue marche pour annoncer une attaque prévue est un récit classique de la guerre de 1812 présenté dans le guide.',
  },
  {
    id: 'his-014',
    p: 'Sir Isaac Brock is associated with:',
    pf: 'Sir Isaac Brock est associé à :',
    o: ['Defending Upper Canada in the War of 1812', 'The Quiet Revolution', 'The Charter of 1982', 'D-Day planning'],
    of: [
      'La défense du Haut-Canada pendant la guerre de 1812',
      'La Révolution tranquille',
      'La Charte de 1982',
      'La planification du jour J',
    ],
    a: 'a',
    e: 'Brock, with Indigenous allies including Tecumseh’s confederacy, was a key commander. He was killed at Queenston Heights.',
    ef: 'Brock, appuyé par des alliés autochtones dont la confédération de Tecumseh, était un commandant clé. Il est mort à Queenston Heights.',
  },
  {
    id: 'his-015',
    p: 'The Underground Railroad refers to:',
    pf: 'Le chemin de fer clandestin désigne :',
    o: [
      'A network that helped enslaved people reach freedom in Canada',
      'The first subway in Toronto',
      'A CPR tunnel in the Rockies only',
      'A World War II spy ring in Ottawa',
    ],
    of: [
      'Un réseau qui aidait les personnes réduites en esclavage à gagner la liberté au Canada',
      'Le premier métro de Toronto',
      'Uniquement un tunnel du Canadien Pacifique dans les Rocheuses',
      'Un réseau d’espionnage à Ottawa pendant la Seconde Guerre mondiale',
    ],
    a: 'a',
    e: 'British North America, especially Canada West, became a destination after slavery was abolished in the British Empire.',
    ef: 'L’Amérique du Nord britannique, surtout le Canada-Ouest, est devenue une terre d’accueil après l’abolition de l’esclavage dans l’Empire britannique.',
  },
  {
    id: 'his-016',
    p: 'Responsible government means that:',
    pf: 'Le gouvernement responsable signifie que :',
    o: [
      'Cabinet must keep the confidence of the elected assembly',
      'The Monarch writes all laws alone',
      'Judges run elections',
      'Municipalities control the army',
    ],
    of: [
      'Le Cabinet doit conserver la confiance de l’assemblée élue',
      'Le monarque rédige seul toutes les lois',
      'Les juges organisent les élections',
      'Les municipalités dirigent l’armée',
    ],
    a: 'a',
    e: 'Nova Scotia achieved it first (1847–48). The Province of Canada followed. It is still the core convention of Canadian democracy.',
    ef: 'La Nouvelle-Écosse l’a obtenu la première (1847-1848), puis la Province du Canada a suivi. C’est toujours la convention centrale de la démocratie canadienne.',
  },
  {
    id: 'his-017',
    p: 'Reformers Robert Baldwin and Sir Louis-Hippolyte La Fontaine are associated with:',
    pf: 'Les réformistes Robert Baldwin et sir Louis-Hippolyte La Fontaine sont associés à :',
    o: [
      'Responsible government and French–English political partnership',
      'Building NATO',
      'The Persons Case',
      'Creating Nunavut',
    ],
    of: [
      'Le gouvernement responsable et le partenariat politique entre francophones et anglophones',
      'La création de l’OTAN',
      'L’affaire des « personnes »',
      'La création du Nunavut',
    ],
    a: 'a',
    e: 'They showed that French- and English-speaking reformers could govern together in the 1840s.',
    ef: 'Ils ont démontré, dans les années 1840, que des réformistes francophones et anglophones pouvaient gouverner ensemble.',
  },
  {
    id: 'his-018',
    p: 'Which four provinces joined Confederation in 1867?',
    pf: 'Quelles quatre provinces se sont unies lors de la Confédération de 1867 ?',
    o: [
      'Ontario, Quebec, Nova Scotia, and New Brunswick',
      'Ontario, Quebec, Manitoba, and British Columbia',
      'Nova Scotia, PEI, Newfoundland, and New Brunswick',
      'Alberta, Saskatchewan, Manitoba, and Ontario',
    ],
    of: [
      'L’Ontario, le Québec, la Nouvelle-Écosse et le Nouveau-Brunswick',
      'L’Ontario, le Québec, le Manitoba et la Colombie-Britannique',
      'La Nouvelle-Écosse, l’Île-du-Prince-Édouard, Terre-Neuve et le Nouveau-Brunswick',
      'L’Alberta, la Saskatchewan, le Manitoba et l’Ontario',
    ],
    a: 'a',
    e: 'Those four formed the Dominion. Other provinces joined later.',
    ef: 'Ces quatre provinces ont formé le Dominion. Les autres se sont joints plus tard.',
  },
  {
    id: 'his-019',
    p: 'Sir George-Étienne Cartier is best known as:',
    pf: 'Sir George-Étienne Cartier est surtout connu comme :',
    o: [
      'A leading Quebec Father of Confederation',
      'Canada’s first woman MP',
      'The designer of the maple leaf flag',
      'Governor General in 1982',
    ],
    of: [
      'Un grand Père de la Confédération venu du Québec',
      'La première députée du Canada',
      'Le concepteur du drapeau à la feuille d’érable',
      'Le gouverneur général en 1982',
    ],
    a: 'a',
    e: 'Cartier helped bring Canada East (Quebec) into Confederation and was Macdonald’s key partner.',
    ef: 'Cartier a contribué à faire entrer le Canada-Est (le Québec) dans la Confédération et il était le principal allié de Macdonald.',
  },
  {
    id: 'his-020',
    p: 'The Charlottetown Conference of 1864 is important because:',
    pf: 'La Conférence de Charlottetown de 1864 est importante parce que :',
    o: [
      'It began the talks that led to Confederation',
      'It created the Charter',
      'It ended World War I',
      'It founded the Hudson’s Bay Company',
    ],
    of: [
      'Elle a lancé les pourparlers qui ont mené à la Confédération',
      'Elle a créé la Charte',
      'Elle a mis fin à la Première Guerre mondiale',
      'Elle a fondé la Compagnie de la Baie d’Hudson',
    ],
    a: 'a',
    e: 'Maritime union talks widened into a federal project. Quebec and London conferences followed.',
    ef: 'Des discussions sur une union des Maritimes se sont élargies en projet fédéral. Les conférences de Québec et de Londres ont suivi.',
  },
  {
    id: 'his-021',
    p: 'Manitoba entered Confederation in:',
    pf: 'Le Manitoba est entré dans la Confédération en :',
    o: ['1867', '1870', '1905', '1949'],
    of: ['1867', '1870', '1905', '1949'],
    a: 'b',
    e: 'After the Red River Resistance, the Manitoba Act created a new province in 1870.',
    ef: 'Après la résistance de la rivière Rouge, la Loi sur le Manitoba a créé une nouvelle province en 1870.',
  },
  {
    id: 'his-022',
    p: 'Louis Riel is a central figure in:',
    pf: 'Louis Riel est une figure centrale de :',
    o: [
      'The Red River Resistance and the later North-West Resistance',
      'The Dieppe raid',
      'The Official Languages Act',
      'The founding of Halifax',
    ],
    of: [
      'La résistance de la rivière Rouge et, plus tard, de la résistance du Nord-Ouest',
      'Le raid de Dieppe',
      'La Loi sur les langues officielles',
      'La fondation d’Halifax',
    ],
    a: 'a',
    e: 'Riel led Métis at Red River (1869–70) and in 1885. He remains a contested founder of Manitoba and a Métis hero.',
    ef: 'Riel a dirigé les Métis à la rivière Rouge (1869-1870) et en 1885. Il demeure un fondateur contesté du Manitoba et un héros métis.',
  },
  {
    id: 'his-023',
    p: 'British Columbia joined Canada in 1871 after Ottawa promised:',
    pf: 'La Colombie-Britannique s’est jointe au Canada en 1871 après qu’Ottawa a promis :',
    o: ['A transcontinental railway', 'Immediate Senate abolition', 'Free oil', 'A new official language: Spanish'],
    of: [
      'Un chemin de fer transcontinental',
      'L’abolition immédiate du Sénat',
      'Du pétrole gratuit',
      'Une nouvelle langue officielle : l’espagnol',
    ],
    a: 'a',
    e: 'The railway promise bound B.C. to the Dominion. The CPR was completed in 1885.',
    ef: 'La promesse ferroviaire a lié la Colombie-Britannique au Dominion. Le Canadien Pacifique a été achevé en 1885.',
  },
  {
    id: 'his-024',
    p: 'Prince Edward Island joined Confederation in:',
    pf: 'L’Île-du-Prince-Édouard est entrée dans la Confédération en :',
    o: ['1867', '1873', '1949', '1999'],
    of: ['1867', '1873', '1949', '1999'],
    a: 'b',
    e: 'PEI hosted the 1864 talks but joined later, in 1873, after financial and railway pressures.',
    ef: 'L’Île a accueilli les pourparlers de 1864, mais elle n’a adhéré qu’en 1873, sous la pression des finances et du chemin de fer.',
  },
  {
    id: 'his-025',
    p: 'The North-West Mounted Police (forerunner of the RCMP) were created in the 1870s to:',
    pf: 'La Police à cheval du Nord-Ouest (ancêtre de la GRC) a été créée dans les années 1870 pour :',
    o: [
      'Bring Canadian authority to the Plains and the North-West',
      'Command NATO',
      'Replace the Supreme Court',
      'Run federal elections',
    ],
    of: [
      'Étendre l’autorité canadienne aux Prairies et au Nord-Ouest',
      'Commander l’OTAN',
      'Remplacer la Cour suprême',
      'Organiser les élections fédérales',
    ],
    a: 'a',
    e: 'Ottawa wanted order, Canadian sovereignty, and a presence as settlement and treaties expanded westward.',
    ef: 'Ottawa voulait de l’ordre, une souveraineté canadienne affirmée et une présence sur le terrain à mesure que la colonisation et les traités progressaient vers l’ouest.',
  },
  {
    id: 'his-026',
    p: 'The last spike of the Canadian Pacific Railway was driven in:',
    pf: 'Le dernier crampon du chemin de fer Canadien Pacifique a été posé en :',
    o: ['1867', '1885', '1917', '1945'],
    of: ['1867', '1885', '1917', '1945'],
    a: 'b',
    e: 'Completion in 1885 linked British Columbia to the east by rail and is a standard test date.',
    ef: 'L’achèvement du chemin de fer en 1885 a relié la Colombie-Britannique à l’est du pays; c’est une date d’examen courante.',
  },
  {
    id: 'his-027',
    p: 'The North-West Resistance of 1885 ended with:',
    pf: 'La résistance du Nord-Ouest de 1885 s’est terminée par :',
    o: [
      'Defeat of the Métis and First Nations forces and the hanging of Louis Riel',
      'Quebec independence',
      'The Statute of Westminster',
      'Victory at Vimy',
    ],
    of: [
      'La défaite des forces métisses et des Premières Nations et la pendaison de Louis Riel',
      'L’indépendance du Québec',
      'Le Statut de Westminster',
      'La victoire de Vimy',
    ],
    a: 'a',
    e: 'The 1885 conflict and Riel’s execution deepened divides, especially in Quebec, and remain historically charged.',
    ef: 'Le conflit de 1885 et l’exécution de Riel ont creusé les divisions, surtout au Québec, et restent une question historique très sensible.',
  },
  {
    id: 'his-028',
    p: 'The Klondike Gold Rush of the late 1890s took place mainly in:',
    pf: 'La ruée vers l’or du Klondike, à la fin des années 1890, s’est déroulée principalement :',
    o: ['Yukon', 'Prince Edward Island', 'Nova Scotia’s Annapolis Valley', 'Downtown Ottawa'],
    of: [
      'Au Yukon',
      'À l’Île-du-Prince-Édouard',
      'Dans la vallée de l’Annapolis, en Nouvelle-Écosse',
      'Au centre-ville d’Ottawa',
    ],
    a: 'a',
    e: 'Dawson and the Yukon River basin drew tens of thousands. The rush is Yukon’s classic historic hook.',
    ef: 'Dawson et le bassin du fleuve Yukon ont attiré des dizaines de milliers de personnes. Cette ruée est le grand repère historique du Yukon.',
  },
  {
    id: 'his-029',
    p: 'Newfoundland and Labrador joined Canada in:',
    pf: 'Terre-Neuve-et-Labrador est entrée dans la Confédération en :',
    o: ['1867', '1871', '1905', '1949'],
    of: ['1867', '1871', '1905', '1949'],
    a: 'd',
    e: 'After referendums, Newfoundland became the tenth province in 1949.',
    ef: 'Après des référendums, Terre-Neuve est devenue la dixième province en 1949.',
  },
  {
    id: 'his-030',
    p: 'Canada entered the First World War in 1914 because:',
    pf: 'Le Canada est entré dans la Première Guerre mondiale en 1914 parce que :',
    o: [
      'It was part of the British Empire, which was at war',
      'NATO required it',
      'The United Nations voted for it',
      'Nunavut asked for it',
    ],
    of: [
      'Il faisait partie de l’Empire britannique, qui était en guerre',
      'L’OTAN l’exigeait',
      'Les Nations Unies l’avaient voté',
      'Le Nunavut l’avait demandé',
    ],
    a: 'a',
    e: 'In 1914 Canada did not make a separate declaration. Military contribution still became a national coming-of-age story.',
    ef: 'En 1914, le Canada n’a pas fait de déclaration distincte. Sa contribution militaire est tout de même devenue un récit d’affirmation nationale.',
  },
  {
    id: 'his-031',
    p: 'The Canadian Corps’ capture of Vimy Ridge happened in:',
    pf: 'La prise de la crête de Vimy par le Corps canadien a eu lieu en :',
    o: ['1867', '1917', '1944', '1982'],
    of: ['1867', '1917', '1944', '1982'],
    a: 'b',
    e: 'April 1917 at Vimy became a symbol of Canadian skill and sacrifice in the First World War.',
    ef: 'Avril 1917, à Vimy, est devenu un symbole du savoir-faire et du sacrifice des Canadiens pendant la Première Guerre mondiale.',
  },
  {
    id: 'his-032',
    p: 'Most women gained the right to vote in federal elections in:',
    pf: 'La plupart des femmes ont obtenu le droit de vote aux élections fédérales en :',
    o: ['1867', '1918', '1982', '1999'],
    of: ['1867', '1918', '1982', '1999'],
    a: 'b',
    e: 'Wartime measures in 1917 and a 1918 law extended the federal vote to many women. Status Indian women and some others waited longer.',
    ef: 'Des mesures de guerre en 1917, puis une loi de 1918, ont accordé le vote fédéral à de nombreuses femmes. Les femmes ayant le statut d’Indienne et certaines autres ont dû attendre bien plus longtemps.',
  },
  {
    id: 'his-033',
    p: 'Agnes Macphail is remembered as:',
    pf: 'On se souvient d’Agnes Macphail comme :',
    o: [
      'The first woman elected to the House of Commons (1921)',
      'Canada’s first Prime Minister',
      'The designer of the beaver emblem',
      'The founder of New France',
    ],
    of: [
      'La première femme élue à la Chambre des communes (1921)',
      'La première personne à occuper le poste de premier ministre du Canada',
      'La conceptrice de l’emblème du castor',
      'La fondatrice de la Nouvelle-France',
    ],
    a: 'a',
    e: 'She entered Parliament after women won the federal vote. She is a standard name on women’s political history.',
    ef: 'Elle est entrée au Parlement après l’obtention du droit de vote fédéral par les femmes. Son nom revient toujours dans l’histoire politique des femmes.',
  },
  {
    id: 'his-034',
    p: 'The Persons Case (1929) decided that:',
    pf: 'L’affaire des « personnes » (1929) a établi que :',
    o: [
      'Women are “persons” who can be appointed to the Senate',
      'Only men can be judges',
      'Quebec is not a province',
      'The Charter has no equality rights',
    ],
    of: [
      'Les femmes sont des « personnes » pouvant être nommées au Sénat',
      'Seuls les hommes peuvent être juges',
      'Le Québec n’est pas une province',
      'La Charte ne contient aucun droit à l’égalité',
    ],
    a: 'a',
    e: 'The Famous Five took the case to the Judicial Committee of the Privy Council, which reversed a narrower Canadian ruling.',
    ef: 'Les Célèbres cinq ont porté la cause devant le Comité judiciaire du Conseil privé, qui a renversé une décision canadienne plus restrictive.',
  },
  {
    id: 'his-035',
    p: 'The Statute of Westminster (1931) is important because it:',
    pf: 'Le Statut de Westminster (1931) est important parce qu’il a :',
    o: [
      'Recognized Canada’s autonomy in making its own laws and treaties',
      'Created Confederation',
      'Adopted the maple leaf flag',
      'Founded the RCMP',
    ],
    of: [
      'Reconnu l’autonomie du Canada pour adopter ses propres lois et conclure ses traités',
      'Créé la Confédération',
      'Adopté le drapeau à la feuille d’érable',
      'Fondé la GRC',
    ],
    a: 'a',
    e: 'It is a key step from Dominion status toward full sovereignty. Patriation in 1982 completed the constitutional story.',
    ef: 'C’est une étape clé entre le statut de dominion et la pleine souveraineté. Le rapatriement de 1982 a complété ce parcours constitutionnel.',
  },
  {
    id: 'his-036',
    p: 'Canada entered the Second World War in 1939 by:',
    pf: 'Le Canada est entré dans la Seconde Guerre mondiale en 1939 :',
    o: [
      'A Canadian declaration of war, a week after Britain',
      'Automatic imperial entry with no Canadian decision',
      'A United Nations command',
      'Joining the United States in 1941 only',
    ],
    of: [
      'Par une déclaration de guerre canadienne, une semaine après la Grande-Bretagne',
      'Automatiquement, par l’Empire, sans décision canadienne',
      'Par un commandement des Nations Unies',
      'En se joignant aux États-Unis, seulement en 1941',
    ],
    a: 'a',
    e: 'Unlike 1914, Canada’s Parliament made its own declaration (10 September 1939). That showed growing independence.',
    ef: 'Contrairement à 1914, le Parlement du Canada a fait sa propre déclaration, le 10 septembre 1939. Cela montrait une indépendance grandissante.',
  },
  {
    id: 'his-037',
    p: 'The Dieppe raid of 1942 was:',
    pf: 'Le raid de Dieppe, en 1942, a été :',
    o: [
      'A costly Allied attack on the French coast with heavy Canadian losses',
      'The liberation of the Netherlands',
      'The capture of Vimy Ridge',
      'A gold rush',
    ],
    of: [
      'Une attaque alliée très coûteuse sur la côte française, avec de lourdes pertes canadiennes',
      'La libération des Pays-Bas',
      'La prise de la crête de Vimy',
      'Une ruée vers l’or',
    ],
    a: 'a',
    e: 'Dieppe failed with terrible casualties. It is still taught as a hard lesson before later invasions.',
    ef: 'Dieppe s’est soldé par un échec et des pertes terribles. On l’enseigne encore comme une dure leçon avant les débarquements ultérieurs.',
  },
  {
    id: 'his-038',
    p: 'On D-Day, 6 June 1944, Canadian forces landed at:',
    pf: 'Le jour J, le 6 juin 1944, les forces canadiennes ont débarqué :',
    o: ['Juno Beach in Normandy', 'Pearl Harbor', 'Vimy Ridge', 'Dieppe only'],
    of: ['À la plage Juno, en Normandie', 'À Pearl Harbor', 'À la crête de Vimy', 'À Dieppe seulement'],
    a: 'a',
    e: 'Juno was the Canadian beach in the Normandy invasion, a turning point in the war in Europe.',
    ef: 'Juno était la plage canadienne du débarquement de Normandie, un tournant de la guerre en Europe.',
  },
  {
    id: 'his-039',
    p: 'Canadian troops are especially remembered in 1944–45 for helping to liberate:',
    pf: 'En 1944-1945, on se souvient particulièrement des troupes canadiennes pour avoir aidé à libérer :',
    o: ['The Netherlands', 'Mexico', 'Australia', 'Ethiopia in 1867'],
    of: ['Les Pays-Bas', 'Le Mexique', 'L’Australie', 'L’Éthiopie en 1867'],
    a: 'a',
    e: 'The Dutch–Canadian wartime bond, including the Hongerwinter relief, is a standard Second World War fact.',
    ef: 'Le lien néerlando-canadien né de la guerre, y compris l’aide apportée pendant l’hiver de la faim, est un fait classique de la Seconde Guerre mondiale.',
  },
  {
    id: 'his-040',
    p: 'During the Second World War, Japanese Canadians were:',
    pf: 'Pendant la Seconde Guerre mondiale, les Canadiens d’origine japonaise ont été :',
    o: [
      'Interned, dispossessed, and uprooted from the Pacific coast',
      'Appointed to Cabinet as a group',
      'Exempt from all wartime rules',
      'Sent as ambassadors to Tokyo',
    ],
    of: [
      'Internés, dépossédés et déracinés de la côte du Pacifique',
      'Nommés en bloc au Cabinet',
      'Exemptés de toutes les règles du temps de guerre',
      'Envoyés comme ambassadeurs à Tokyo',
    ],
    a: 'a',
    e: 'Internment was a grave injustice. Redress came much later. The test still expects you to know it happened.',
    ef: 'L’internement a été une grave injustice. Les réparations sont venues bien plus tard. L’examen s’attend à ce que vous sachiez que cela a eu lieu.',
  },
  {
    id: 'his-041',
    p: 'Canada’s Constitution was patriated, with the Charter, in:',
    pf: 'La Constitution du Canada a été rapatriée, avec la Charte, en :',
    o: ['1867', '1931', '1982', '1999'],
    of: ['1867', '1931', '1982', '1999'],
    a: 'c',
    e: '17 April 1982 in Ottawa, with Queen Elizabeth II and Prime Minister Pierre Trudeau. Quebec did not sign the package.',
    ef: 'Le 17 avril 1982, à Ottawa, en présence de la reine Elizabeth II et du premier ministre Pierre Trudeau. Le Québec n’a pas signé l’entente.',
  },
  {
    id: 'his-042',
    p: 'Lord Durham’s report after the 1837–38 rebellions recommended:',
    pf: 'Après les rébellions de 1837-1838, le rapport de lord Durham recommandait :',
    o: [
      'Responsible government and a union of Upper and Lower Canada',
      'Immediate independence as a republic',
      'Joining the United States',
      'Abolishing French immediately with no assembly',
    ],
    of: [
      'Le gouvernement responsable et l’union du Haut-Canada et du Bas-Canada',
      'L’indépendance immédiate sous forme de république',
      'L’annexion aux États-Unis',
      'L’abolition immédiate du français, sans assemblée élue',
    ],
    a: 'a',
    e: 'Durham also hoped French Canadians would assimilate—a goal that failed. The union and responsible government still reshaped politics.',
    ef: 'Durham espérait aussi l’assimilation des Canadiens français, un objectif qui a échoué. L’union et le gouvernement responsable ont tout de même transformé la vie politique.',
  },
  {
    id: 'his-043',
    t: 'tf',
    p: 'The British North America Act of 1867 is now known as the Constitution Act, 1867.',
    pf: 'L’Acte de l’Amérique du Nord britannique de 1867 porte aujourd’hui le nom de Loi constitutionnelle de 1867.',
    a: 'true',
    e: 'The 1982 patriation renamed it. It still divides federal and provincial powers.',
    ef: 'Le rapatriement de 1982 l’a renommé. Il partage toujours les compétences entre le fédéral et les provinces.',
  },
  {
    id: 'his-044',
    p: 'Sir Wilfrid Laurier, Prime Minister from 1896, is associated with:',
    pf: 'Sir Wilfrid Laurier, premier ministre à partir de 1896, est associé à :',
    o: [
      'Immigration and western settlement at the turn of the 20th century',
      'D-Day',
      'The first transatlantic cable in 1608',
      'Creating the Charter',
    ],
    of: [
      'L’immigration et la colonisation de l’Ouest au tournant du XXe siècle',
      'Le jour J',
      'Le premier câble transatlantique en 1608',
      'La création de la Charte',
    ],
    a: 'a',
    e: 'Laurier’s era saw a wheat boom and a surge of settlers onto the Prairies.',
    ef: 'L’époque de Laurier a connu un boom du blé et une vague de colons dans les Prairies.',
  },
  {
    id: 'his-045',
    p: 'Alberta and Saskatchewan became provinces in:',
    pf: 'L’Alberta et la Saskatchewan sont devenues des provinces en :',
    o: ['1867', '1870', '1905', '1949'],
    of: ['1867', '1870', '1905', '1949'],
    a: 'c',
    e: 'They were carved from the North-West Territories in 1905.',
    ef: 'Elles ont été détachées des Territoires du Nord-Ouest en 1905.',
  },
  {
    id: 'his-046',
    p: 'Conscription crises in 1917 and 1944 were especially bitter in:',
    pf: 'Les crises de la conscription de 1917 et de 1944 ont été particulièrement vives :',
    o: [
      'Quebec, where many opposed compulsory overseas service',
      'Nunavut only',
      'Prince Edward Island potato farms only',
      'The Senate of 1867',
    ],
    of: [
      'Au Québec, où beaucoup s’opposaient au service militaire obligatoire outre-mer',
      'Au Nunavut seulement',
      'Seulement dans les fermes de pommes de terre de l’Île-du-Prince-Édouard',
      'Au Sénat de 1867',
    ],
    a: 'a',
    e: 'English Canada and French Canada split over forcing men to fight overseas. It is a classic national-unity fact.',
    ef: 'Le Canada anglais et le Canada français se sont divisés sur l’obligation d’aller combattre outre-mer. C’est un fait classique en matière d’unité nationale.',
  },
  {
    id: 'his-047',
    t: 'tf',
    p: 'Indigenous nations had trade, diplomacy, and conflict among themselves long before Europeans arrived.',
    pf: 'Les nations autochtones entretenaient entre elles des échanges commerciaux, des relations diplomatiques et des conflits bien avant l’arrivée des Européens.',
    a: 'true',
    e: 'The history chapter does not begin with Cabot. The land was already a political world.',
    ef: 'Le chapitre d’histoire ne commence pas avec Cabot. Le territoire formait déjà un monde politique.',
  },
  {
    id: 'his-048',
    p: 'Thayendanegea (Joseph Brant) is remembered as:',
    pf: 'On se souvient de Thayendanegea (Joseph Brant) comme :',
    o: [
      'A Mohawk leader who allied with the British and later settled in what became Ontario',
      'Canada’s first Prime Minister',
      'The founder of the Hudson’s Bay Company',
      'A French governor at Louisbourg only',
    ],
    of: [
      'Un chef mohawk allié des Britanniques, établi plus tard dans ce qui est devenu l’Ontario',
      'Le premier premier ministre du Canada',
      'Le fondateur de la Compagnie de la Baie d’Hudson',
      'Uniquement un gouverneur français à Louisbourg',
    ],
    a: 'a',
    e: 'Brant and Loyalist Haudenosaunee communities are part of the post-Revolution story in Canada.',
    ef: 'Brant et les communautés haudenosaunee loyalistes font partie de l’histoire canadienne qui suit la Révolution américaine.',
  },
  {
    id: 'his-049',
    p: 'The Halifax Explosion of 1917 was:',
    pf: 'L’explosion d’Halifax, en 1917, a été :',
    o: [
      'A wartime harbour disaster that devastated the city',
      'A Quiet Revolution protest',
      'The last spike ceremony',
      'A gold-rush stampede',
    ],
    of: [
      'Une catastrophe portuaire, en temps de guerre, qui a dévasté la ville',
      'Une manifestation de la Révolution tranquille',
      'La cérémonie du dernier crampon',
      'Une ruée vers l’or',
    ],
    a: 'a',
    e: 'Two ships collided, one carrying explosives. It is one of the worst disasters in Canadian history.',
    ef: 'Deux navires sont entrés en collision, dont un chargé d’explosifs. C’est l’une des pires catastrophes de l’histoire du Canada.',
  },
  {
    id: 'his-050',
    p: 'Canada’s soldiers in the First World War included a famous all-Black unit known as:',
    pf: 'Pendant la Première Guerre mondiale, une célèbre unité canadienne entièrement composée de soldats noirs portait le nom de :',
    o: [
      'No. 2 Construction Battalion',
      'The Famous Five',
      'The North-West Mounted Police cavalry only',
      'The Senate Guard',
    ],
    of: [
      'Bataillon de construction no 2',
      'Les Célèbres cinq',
      'Uniquement la cavalerie de la Police à cheval du Nord-Ouest',
      'La garde du Sénat',
    ],
    a: 'a',
    e: 'Black volunteers were long kept out of combat roles; this construction battalion is the unit the guide-era story highlights.',
    ef: 'Les volontaires noirs ont longtemps été écartés des rôles de combat; ce bataillon de construction est l’unité que met en lumière le récit de l’époque du guide.',
  },
  {
    id: 'his-051',
    t: 'tf',
    p: 'Women were legally “persons” for Senate appointments before the Persons Case.',
    pf: 'Avant l’affaire des « personnes », les femmes étaient juridiquement des « personnes » aux fins des nominations au Sénat.',
    a: 'false',
    e: 'The Canadian courts had said no. The 1929 decision reversed that and opened the Senate to women.',
    ef: 'Les tribunaux canadiens avaient dit non. La décision de 1929 a renversé cette position et ouvert le Sénat aux femmes.',
  },
  {
    id: 'his-052',
    p: 'Responsible government in the 1840s meant that:',
    pf: 'Dans les années 1840, le gouvernement responsable signifiait que :',
    o: [
      'Colonial cabinets had to keep the confidence of an elected assembly',
      'The Monarch moved to Ottawa permanently',
      'Canada joined NATO',
      'The Senate elected the Prime Minister',
    ],
    of: [
      'Les cabinets coloniaux devaient conserver la confiance d’une assemblée élue',
      'Le monarque déménageait à Ottawa de façon permanente',
      'Le Canada se joignait à l’OTAN',
      'Le Sénat élisait le premier ministre',
    ],
    a: 'a',
    e: 'Nova Scotia (1848) and the Province of Canada soon after are the usual examples. It is the root of today’s confidence convention.',
    ef: 'La Nouvelle-Écosse (1848), puis peu après la Province du Canada, en sont les exemples habituels. C’est la source de l’actuelle convention de confiance.',
  },
  {
    id: 'his-053',
    p: 'The Fenian raids of the 1860s are part of Confederation’s context because they:',
    pf: 'Les raids des Fenians, dans les années 1860, font partie du contexte de la Confédération parce qu’ils ont :',
    o: [
      'Showed British North America needed better defence and political union',
      'Created Nunavut',
      'Ended the fur trade',
      'Wrote the Charter of Rights',
    ],
    of: [
      'Montré que l’Amérique du Nord britannique avait besoin d’une meilleure défense et d’une union politique',
      'Créé le Nunavut',
      'Mis fin à la traite des fourrures',
      'Rédigé la Charte des droits',
    ],
    a: 'a',
    e: 'Irish-American veterans attacked from the United States. The threat helped sell a stronger union.',
    ef: 'Des vétérans irlando-américains ont attaqué depuis les États-Unis. Cette menace a aidé à faire accepter l’idée d’une union plus solide.',
  },
  {
    id: 'his-054',
    p: 'Canadian troops served in South Africa around 1900 in:',
    pf: 'Vers 1900, des soldats canadiens ont servi en Afrique du Sud dans :',
    o: [
      'The South African (Boer) War',
      'The Korean War',
      'The Quiet Revolution',
      'The War of 1812',
    ],
    of: [
      'La guerre d’Afrique du Sud (guerre des Boers)',
      'La guerre de Corée',
      'La Révolution tranquille',
      'La guerre de 1812',
    ],
    a: 'a',
    e: 'It was an early overseas expedition of the new Dominion and a preview of later imperial wars.',
    ef: 'C’était l’une des premières expéditions outre-mer du nouveau Dominion et un avant-goût des guerres impériales à venir.',
  },
  {
    id: 'his-055',
    t: 'tf',
    p: 'Canadian soldiers were captured at Hong Kong after Japan attacked in December 1941.',
    pf: 'Des soldats canadiens ont été faits prisonniers à Hong Kong après l’attaque japonaise de décembre 1941.',
    a: 'true',
    e: 'Two battalions sent to Hong Kong suffered terrible losses and long imprisonment. It is an early Second World War Canadian story.',
    ef: 'Deux bataillons envoyés à Hong Kong ont subi des pertes terribles et une longue captivité. C’est un épisode canadien du début de la Seconde Guerre mondiale.',
  },
  {
    id: 'his-056',
    p: 'The Battle of the Atlantic was important to Canada because:',
    pf: 'La bataille de l’Atlantique a été importante pour le Canada parce que :',
    o: [
      'The Royal Canadian Navy and merchant sailors fought to keep supply convoys moving',
      'It was a prairie land battle in 1885',
      'It decided the Persons Case',
      'It was a municipal election in Halifax',
    ],
    of: [
      'La Marine royale canadienne et les marins marchands se sont battus pour maintenir la circulation des convois de ravitaillement',
      'C’était une bataille terrestre dans les Prairies en 1885',
      'Elle a tranché l’affaire des « personnes »',
      'C’était une élection municipale à Halifax',
    ],
    a: 'a',
    e: 'U-boats hunted ships in the North Atlantic. Canada’s navy grew from a tiny force into a major convoy escort.',
    ef: 'Les sous-marins allemands traquaient les navires dans l’Atlantique Nord. La marine canadienne est passée d’une force minuscule à une grande flotte d’escorte.',
  },
  {
    id: 'his-057',
    p: 'Canadian soldiers in Italy in 1943–44 are especially associated with hard fighting at places such as:',
    pf: 'En Italie, en 1943-1944, les soldats canadiens sont surtout associés à de durs combats dans des lieux comme :',
    o: ['Ortona', 'Vimy Ridge in 1917 only', 'Batoche', 'Charlottetown in 1864'],
    of: ['Ortona', 'La crête de Vimy, en 1917 seulement', 'Batoche', 'Charlottetown en 1864'],
    a: 'a',
    e: 'The Italian campaign is a Second World War chapter distinct from Normandy. Ortona became a symbol of that fighting.',
    ef: 'La campagne d’Italie est un chapitre de la Seconde Guerre mondiale distinct de la Normandie. Ortona est devenue le symbole de ces combats.',
  },
  {
    id: 'his-058',
    p: 'The British Commonwealth Air Training Plan in Canada:',
    pf: 'Le Programme d’entraînement aérien du Commonwealth britannique, au Canada :',
    o: [
      'Trained Allied aircrew on Canadian airfields during the Second World War',
      'Built the CPR',
      'Created the Senate',
      'Was a 19th-century fur-trade school',
    ],
    of: [
      'A formé des équipages alliés sur des aérodromes canadiens pendant la Seconde Guerre mondiale',
      'A construit le Canadien Pacifique',
      'A créé le Sénat',
      'Était une école de la traite des fourrures au XIXe siècle',
    ],
    a: 'a',
    e: 'Canada’s skies and space made it a training ground. It is a home-front contribution as well as a military one.',
    ef: 'Le ciel et les grands espaces du Canada en faisaient un terrain d’entraînement idéal. C’est une contribution du front intérieur autant qu’une contribution militaire.',
  },
  {
    id: 'his-059',
    p: 'The seigneurial system in New France was:',
    pf: 'Le régime seigneurial en Nouvelle-France était :',
    o: [
      'A way of granting land along the St. Lawrence to seigneurs and tenant farmers',
      'A type of Senate committee',
      'The first past the post voting rule',
      'A 1982 constitutional amendment',
    ],
    of: [
      'Une façon de concéder des terres le long du Saint-Laurent à des seigneurs et à des censitaires',
      'Un type de comité du Sénat',
      'La règle du scrutin uninominal majoritaire à un tour',
      'Une modification constitutionnelle de 1982',
    ],
    a: 'a',
    e: 'Long, narrow river lots are still visible from the air. British rule later phased the system out.',
    ef: 'Les terres longues et étroites perpendiculaires au fleuve sont encore visibles du haut des airs. Le régime britannique a plus tard aboli progressivement ce système.',
  },
  {
    id: 'his-060',
    t: 'tf',
    p: 'Slavery was abolished throughout the British Empire in the 1830s, including in what is now Canada.',
    pf: 'L’esclavage a été aboli dans tout l’Empire britannique dans les années 1830, y compris sur le territoire de l’actuel Canada.',
    a: 'true',
    e: 'Enslavement had existed in New France and British colonies. Imperial abolition, plus later Underground Railroad arrivals, is the testable arc.',
    ef: 'L’esclavage avait existé en Nouvelle-France et dans les colonies britanniques. L’abolition impériale, puis l’arrivée de personnes par le chemin de fer clandestin, forment la trame à retenir.',
  },
  {
    id: 'his-061',
    p: 'The conscription crisis of 1917 strained unity because:',
    pf: 'La crise de la conscription de 1917 a mis l’unité à l’épreuve parce que :',
    o: [
      'Many in Quebec opposed compulsory overseas service while English Canada largely supported it',
      'Nunavut refused to join NATO',
      'The Senate banned wheat exports',
      'Women were forbidden from factory work',
    ],
    of: [
      'Beaucoup de Québécois s’opposaient au service obligatoire outre-mer, alors que le Canada anglais l’appuyait largement',
      'Le Nunavut refusait de se joindre à l’OTAN',
      'Le Sénat avait interdit l’exportation du blé',
      'Il était interdit aux femmes de travailler en usine',
    ],
    a: 'a',
    e: 'Borden’s Union government and the wartime election left scars. A similar fight returned in the Second World War.',
    ef: 'Le gouvernement d’union de Borden et l’élection en temps de guerre ont laissé des cicatrices. Le même affrontement est revenu pendant la Seconde Guerre mondiale.',
  },
  {
    id: 'his-062',
    p: 'Sir Robert Borden led Canada during:',
    pf: 'Sir Robert Borden a dirigé le Canada pendant :',
    o: [
      'The First World War',
      'Confederation in 1867',
      'The Quiet Revolution only',
      'The Korean War as Prime Minister',
    ],
    of: [
      'La Première Guerre mondiale',
      'La Confédération de 1867',
      'La Révolution tranquille seulement',
      'La guerre de Corée, à titre de premier ministre',
    ],
    a: 'a',
    e: 'Borden’s wartime government also pushed for a stronger Canadian voice at the peace table.',
    ef: 'Le gouvernement de guerre de Borden a aussi réclamé une voix canadienne plus forte à la table des négociations de paix.',
  },
  {
    id: 'his-063',
    p: 'Representation by population was a Confederation bargaining issue because:',
    pf: 'La représentation proportionnelle à la population a été un enjeu de négociation à la Confédération parce que :',
    o: [
      'Canada West wanted seats by population while Canada East feared being outvoted',
      'Only the territories had people',
      'Senators are elected by riding',
      'Municipalities write the Constitution',
    ],
    of: [
      'Le Canada-Ouest voulait des sièges répartis selon la population, alors que le Canada-Est craignait d’être mis en minorité',
      'Seuls les territoires étaient peuplés',
      'Les sénateurs sont élus par circonscription',
      'Les municipalités rédigent la Constitution',
    ],
    a: 'a',
    e: 'The compromise was an elected Commons by population and a Senate with regional balance.',
    ef: 'Le compromis a été une Chambre des communes élue selon la population et un Sénat assurant un équilibre régional.',
  },
  {
    id: 'his-064',
    p: 'William Lyon Mackenzie King is associated with:',
    pf: 'William Lyon Mackenzie King est associé à :',
    o: [
      'Leading Canada through most of the Second World War as Prime Minister',
      'Founding Quebec City in 1608',
      'Driving the last CPR spike himself',
      'Writing Magna Carta',
    ],
    of: [
      'La direction du Canada, comme premier ministre, pendant la majeure partie de la Seconde Guerre mondiale',
      'La fondation de la ville de Québec en 1608',
      'La pose, de ses propres mains, du dernier crampon du Canadien Pacifique',
      'La rédaction de la Grande Charte',
    ],
    a: 'a',
    e: 'King is Canada’s longest-serving Prime Minister. The wartime home front and later social programs sit in his era.',
    ef: 'King est le premier ministre canadien ayant servi le plus longtemps. Le front intérieur en temps de guerre et les programmes sociaux qui ont suivi appartiennent à son époque.',
  },
  {
    id: 'his-065',
    t: 'tf',
    p: 'The Fathers of Confederation included leaders from several colonies, not only Sir John A. Macdonald.',
    pf: 'Les Pères de la Confédération comptaient des dirigeants de plusieurs colonies, et non seulement sir John A. Macdonald.',
    a: 'true',
    e: 'Cartier, Brown, Tupper, Tilley, and others were essential. Macdonald is first among them, not the only one.',
    ef: 'Cartier, Brown, Tupper, Tilley et d’autres ont été essentiels. Macdonald est le premier d’entre eux, mais pas le seul.',
  },
]);
