import { build } from './build.mjs';

export default build("canadas-history", "Discover Canada — Canada's History", [
  {
    id: 'his-001',
    p: 'When did Canada become a country through Confederation?',
    o: ['July 1, 1867', 'July 1, 1812', 'April 17, 1982', 'November 11, 1918'],
    a: 'a',
    e: 'The British North America Act created the Dominion of Canada on July 1, 1867, uniting Ontario, Quebec, Nova Scotia, and New Brunswick.',
  },
  {
    id: 'his-002',
    p: 'Who was Canada’s first Prime Minister?',
    o: ['Wilfrid Laurier', 'George-Étienne Cartier', 'Sir John A. Macdonald', 'Robert Borden'],
    a: 'c',
    e: 'Sir John A. Macdonald led the Conservative government after Confederation and is remembered as a principal architect of the new federation.',
  },
  {
    id: 'his-003',
    p: 'What did the Quebec Act of 1774 do?',
    o: [
      'It banned the French language in courts',
      'It allowed French Catholics to keep their religion and civil law',
      'It created the Province of Manitoba',
      'It ended the fur trade',
    ],
    a: 'b',
    e: 'The Quebec Act protected the French language, Catholic faith, and French civil law in Quebec—an early example of accommodation that still shapes Canada.',
  },
  {
    id: 'his-004',
    p: 'Who founded Quebec City in 1608?',
    o: ['Jacques Cartier', 'Samuel de Champlain', 'John Cabot', 'Lord Durham'],
    a: 'b',
    e: 'Champlain established a lasting French settlement at Quebec, a foundation of New France.',
  },
  {
    id: 'his-005',
    p: 'Jacques Cartier’s voyages in the 1530s are important because he:',
    o: [
      'Explored the St. Lawrence and claimed the area for France',
      'Built the Canadian Pacific Railway',
      'Patriated the Constitution',
      'Won Vimy Ridge',
    ],
    a: 'a',
    e: 'Cartier’s expeditions opened the St. Lawrence to French claims. Permanent settlement came later.',
  },
  {
    id: 'his-006',
    p: 'John Cabot’s 1497 voyage is associated with:',
    o: [
      'An English claim and the later Atlantic fishery off Newfoundland',
      'The founding of Montreal',
      'The Persons Case',
      'D-Day',
    ],
    a: 'a',
    e: 'Cabot (Giovanni Caboto) sailed for England. The rich cod fishery drew Europeans to Newfoundland for centuries.',
  },
  {
    id: 'his-007',
    p: 'Norse visitors reached the Atlantic around the year 1000. A known site is:',
    o: ['L’Anse aux Meadows in Newfoundland', 'Vimy Ridge', 'Batoche', 'Juno Beach'],
    a: 'a',
    e: 'L’Anse aux Meadows is evidence of Viking presence. It did not lead to lasting European settlement.',
  },
  {
    id: 'his-008',
    p: 'The Hudson’s Bay Company was founded in:',
    o: ['1608', '1670', '1867', '1982'],
    a: 'b',
    e: 'A royal charter in 1670 created a fur-trade empire over a huge drainage basin called Rupert’s Land.',
  },
  {
    id: 'his-009',
    p: 'The Battle of the Plains of Abraham (1759) was fought at:',
    o: ['Quebec', 'Vancouver', 'Winnipeg', 'Halifax Citadel only in 1917'],
    a: 'a',
    e: 'British forces under Wolfe defeated the French under Montcalm. New France fell; 1763 confirmed British control.',
  },
  {
    id: 'his-010',
    p: 'The Royal Proclamation of 1763 is important in Indigenous history because it:',
    o: [
      'Set rules for Crown dealings with Indigenous lands',
      'Created the Province of Alberta',
      'Banned all treaties',
      'Ended the fur trade',
    ],
    a: 'a',
    e: 'It recognized Indigenous land interests and required Crown treaties before settlement in many areas. It is still cited in law.',
  },
  {
    id: 'his-011',
    p: 'The Constitutional Act of 1791 created:',
    o: ['Upper Canada and Lower Canada', 'Nunavut and Yukon', 'NATO and NORAD', 'The Senate and the Bank of Canada'],
    a: 'a',
    e: 'Upper Canada (Ontario) was mainly English and Protestant; Lower Canada (Quebec) remained mainly French and Catholic.',
  },
  {
    id: 'his-012',
    p: 'A result of the War of 1812 in British North America was that:',
    o: [
      'The colonies remained British rather than being absorbed by the United States',
      'Canada joined the United States',
      'Confederation happened immediately',
      'The French language was banned',
    ],
    a: 'a',
    e: 'American invasions failed to take the colonies. The war became part of English-Canadian founding mythology, alongside Indigenous and Québécois stories.',
  },
  {
    id: 'his-013',
    p: 'Laura Secord is remembered for:',
    o: [
      'Warning British forces of an American attack during the War of 1812',
      'Founding the RCMP',
      'Writing O Canada',
      'Discovering gold in the Yukon',
    ],
    a: 'a',
    e: 'Her walk to warn of a planned attack is a classic War of 1812 story taught in the guide.',
  },
  {
    id: 'his-014',
    p: 'Sir Isaac Brock is associated with:',
    o: ['Defending Upper Canada in the War of 1812', 'The Quiet Revolution', 'The Charter of 1982', 'D-Day planning'],
    a: 'a',
    e: 'Brock, with Indigenous allies including Tecumseh’s confederacy, was a key commander. He was killed at Queenston Heights.',
  },
  {
    id: 'his-015',
    p: 'The Underground Railroad refers to:',
    o: [
      'A network that helped enslaved people reach freedom in Canada',
      'The first subway in Toronto',
      'A CPR tunnel in the Rockies only',
      'A World War II spy ring in Ottawa',
    ],
    a: 'a',
    e: 'British North America, especially Canada West, became a destination after slavery was abolished in the British Empire.',
  },
  {
    id: 'his-016',
    p: 'Responsible government means that:',
    o: [
      'Cabinet must keep the confidence of the elected assembly',
      'The Monarch writes all laws alone',
      'Judges run elections',
      'Municipalities control the army',
    ],
    a: 'a',
    e: 'Nova Scotia achieved it first (1847–48). The Province of Canada followed. It is still the core convention of Canadian democracy.',
  },
  {
    id: 'his-017',
    p: 'Reformers Robert Baldwin and Sir Louis-Hippolyte La Fontaine are associated with:',
    o: [
      'Responsible government and French–English political partnership',
      'Building NATO',
      'The Persons Case',
      'Creating Nunavut',
    ],
    a: 'a',
    e: 'They showed that French- and English-speaking reformers could govern together in the 1840s.',
  },
  {
    id: 'his-018',
    p: 'Which four provinces joined Confederation in 1867?',
    o: [
      'Ontario, Quebec, Nova Scotia, and New Brunswick',
      'Ontario, Quebec, Manitoba, and British Columbia',
      'Nova Scotia, PEI, Newfoundland, and New Brunswick',
      'Alberta, Saskatchewan, Manitoba, and Ontario',
    ],
    a: 'a',
    e: 'Those four formed the Dominion. Other provinces joined later.',
  },
  {
    id: 'his-019',
    p: 'Sir George-Étienne Cartier is best known as:',
    o: [
      'A leading Quebec Father of Confederation',
      'Canada’s first woman MP',
      'The designer of the maple leaf flag',
      'Governor General in 1982',
    ],
    a: 'a',
    e: 'Cartier helped bring Canada East (Quebec) into Confederation and was Macdonald’s key partner.',
  },
  {
    id: 'his-020',
    p: 'The Charlottetown Conference of 1864 is important because:',
    o: [
      'It began the talks that led to Confederation',
      'It created the Charter',
      'It ended World War I',
      'It founded the Hudson’s Bay Company',
    ],
    a: 'a',
    e: 'Maritime union talks widened into a federal project. Quebec and London conferences followed.',
  },
  {
    id: 'his-021',
    p: 'Manitoba entered Confederation in:',
    o: ['1867', '1870', '1905', '1949'],
    a: 'b',
    e: 'After the Red River Resistance, the Manitoba Act created a new province in 1870.',
  },
  {
    id: 'his-022',
    p: 'Louis Riel is a central figure in:',
    o: [
      'The Red River Resistance and the later North-West Resistance',
      'The Dieppe raid',
      'The Official Languages Act',
      'The founding of Halifax',
    ],
    a: 'a',
    e: 'Riel led Métis at Red River (1869–70) and in 1885. He remains a contested founder of Manitoba and a Métis hero.',
  },
  {
    id: 'his-023',
    p: 'British Columbia joined Canada in 1871 after Ottawa promised:',
    o: ['A transcontinental railway', 'Immediate Senate abolition', 'Free oil', 'A new official language: Spanish'],
    a: 'a',
    e: 'The railway promise bound B.C. to the Dominion. The CPR was completed in 1885.',
  },
  {
    id: 'his-024',
    p: 'Prince Edward Island joined Confederation in:',
    o: ['1867', '1873', '1949', '1999'],
    a: 'b',
    e: 'PEI hosted the 1864 talks but joined later, in 1873, after financial and railway pressures.',
  },
  {
    id: 'his-025',
    p: 'The North-West Mounted Police (forerunner of the RCMP) were created in the 1870s to:',
    o: [
      'Bring Canadian authority to the Plains and the North-West',
      'Command NATO',
      'Replace the Supreme Court',
      'Run federal elections',
    ],
    a: 'a',
    e: 'Ottawa wanted order, Canadian sovereignty, and a presence as settlement and treaties expanded westward.',
  },
  {
    id: 'his-026',
    p: 'The last spike of the Canadian Pacific Railway was driven in:',
    o: ['1867', '1885', '1917', '1945'],
    a: 'b',
    e: 'Completion in 1885 linked British Columbia to the east by rail and is a standard test date.',
  },
  {
    id: 'his-027',
    p: 'The North-West Resistance of 1885 ended with:',
    o: [
      'Defeat of the Métis and First Nations forces and the hanging of Louis Riel',
      'Quebec independence',
      'The Statute of Westminster',
      'Victory at Vimy',
    ],
    a: 'a',
    e: 'The 1885 conflict and Riel’s execution deepened divides, especially in Quebec, and remain historically charged.',
  },
  {
    id: 'his-028',
    p: 'The Klondike Gold Rush of the late 1890s took place mainly in:',
    o: ['Yukon', 'Prince Edward Island', 'Nova Scotia’s Annapolis Valley', 'Downtown Ottawa'],
    a: 'a',
    e: 'Dawson and the Yukon River basin drew tens of thousands. The rush is Yukon’s classic historic hook.',
  },
  {
    id: 'his-029',
    p: 'Newfoundland and Labrador joined Canada in:',
    o: ['1867', '1871', '1905', '1949'],
    a: 'd',
    e: 'After referendums, Newfoundland became the tenth province in 1949.',
  },
  {
    id: 'his-030',
    p: 'Canada entered the First World War in 1914 because:',
    o: [
      'It was part of the British Empire, which was at war',
      'NATO required it',
      'The United Nations voted for it',
      'Nunavut asked for it',
    ],
    a: 'a',
    e: 'In 1914 Canada did not make a separate declaration. Military contribution still became a national coming-of-age story.',
  },
  {
    id: 'his-031',
    p: 'The Canadian Corps’ capture of Vimy Ridge happened in:',
    o: ['1867', '1917', '1944', '1982'],
    a: 'b',
    e: 'April 1917 at Vimy became a symbol of Canadian skill and sacrifice in the First World War.',
  },
  {
    id: 'his-032',
    p: 'Most women gained the right to vote in federal elections in:',
    o: ['1867', '1918', '1982', '1999'],
    a: 'b',
    e: 'Wartime measures in 1917 and a 1918 law extended the federal vote to many women. Status Indian women and some others waited longer.',
  },
  {
    id: 'his-033',
    p: 'Agnes Macphail is remembered as:',
    o: [
      'The first woman elected to the House of Commons (1921)',
      'Canada’s first Prime Minister',
      'The designer of the beaver emblem',
      'The founder of New France',
    ],
    a: 'a',
    e: 'She entered Parliament after women won the federal vote. She is a standard name on women’s political history.',
  },
  {
    id: 'his-034',
    p: 'The Persons Case (1929) decided that:',
    o: [
      'Women are “persons” who can be appointed to the Senate',
      'Only men can be judges',
      'Quebec is not a province',
      'The Charter has no equality rights',
    ],
    a: 'a',
    e: 'The Famous Five took the case to the Judicial Committee of the Privy Council, which reversed a narrower Canadian ruling.',
  },
  {
    id: 'his-035',
    p: 'The Statute of Westminster (1931) is important because it:',
    o: [
      'Recognized Canada’s autonomy in making its own laws and treaties',
      'Created Confederation',
      'Adopted the maple leaf flag',
      'Founded the RCMP',
    ],
    a: 'a',
    e: 'It is a key step from Dominion status toward full sovereignty. Patriation in 1982 completed the constitutional story.',
  },
  {
    id: 'his-036',
    p: 'Canada entered the Second World War in 1939 by:',
    o: [
      'A Canadian declaration of war, a week after Britain',
      'Automatic imperial entry with no Canadian decision',
      'A United Nations command',
      'Joining the United States in 1941 only',
    ],
    a: 'a',
    e: 'Unlike 1914, Canada’s Parliament made its own declaration (10 September 1939). That showed growing independence.',
  },
  {
    id: 'his-037',
    p: 'The Dieppe raid of 1942 was:',
    o: [
      'A costly Allied attack on the French coast with heavy Canadian losses',
      'The liberation of the Netherlands',
      'The capture of Vimy Ridge',
      'A gold rush',
    ],
    a: 'a',
    e: 'Dieppe failed with terrible casualties. It is still taught as a hard lesson before later invasions.',
  },
  {
    id: 'his-038',
    p: 'On D-Day, 6 June 1944, Canadian forces landed at:',
    o: ['Juno Beach in Normandy', 'Pearl Harbor', 'Vimy Ridge', 'Dieppe only'],
    a: 'a',
    e: 'Juno was the Canadian beach in the Normandy invasion, a turning point in the war in Europe.',
  },
  {
    id: 'his-039',
    p: 'Canadian troops are especially remembered in 1944–45 for helping to liberate:',
    o: ['The Netherlands', 'Mexico', 'Australia', 'Ethiopia in 1867'],
    a: 'a',
    e: 'The Dutch–Canadian wartime bond, including the Hongerwinter relief, is a standard Second World War fact.',
  },
  {
    id: 'his-040',
    p: 'During the Second World War, Japanese Canadians were:',
    o: [
      'Interned, dispossessed, and uprooted from the Pacific coast',
      'Appointed to Cabinet as a group',
      'Exempt from all wartime rules',
      'Sent as ambassadors to Tokyo',
    ],
    a: 'a',
    e: 'Internment was a grave injustice. Redress came much later. The test still expects you to know it happened.',
  },
  {
    id: 'his-041',
    p: 'Canada’s Constitution was patriated, with the Charter, in:',
    o: ['1867', '1931', '1982', '1999'],
    a: 'c',
    e: '17 April 1982 in Ottawa, with Queen Elizabeth II and Prime Minister Pierre Trudeau. Quebec did not sign the package.',
  },
  {
    id: 'his-042',
    p: 'Lord Durham’s report after the 1837–38 rebellions recommended:',
    o: [
      'Responsible government and a union of Upper and Lower Canada',
      'Immediate independence as a republic',
      'Joining the United States',
      'Abolishing French immediately with no assembly',
    ],
    a: 'a',
    e: 'Durham also hoped French Canadians would assimilate—a goal that failed. The union and responsible government still reshaped politics.',
  },
  {
    id: 'his-043',
    t: 'tf',
    p: 'The British North America Act of 1867 is now known as the Constitution Act, 1867.',
    a: 'true',
    e: 'The 1982 patriation renamed it. It still divides federal and provincial powers.',
  },
  {
    id: 'his-044',
    p: 'Sir Wilfrid Laurier, Prime Minister from 1896, is associated with:',
    o: [
      'Immigration and western settlement at the turn of the 20th century',
      'D-Day',
      'The first transatlantic cable in 1608',
      'Creating the Charter',
    ],
    a: 'a',
    e: 'Laurier’s era saw a wheat boom and a surge of settlers onto the Prairies.',
  },
  {
    id: 'his-045',
    p: 'Alberta and Saskatchewan became provinces in:',
    o: ['1867', '1870', '1905', '1949'],
    a: 'c',
    e: 'They were carved from the North-West Territories in 1905.',
  },
  {
    id: 'his-046',
    p: 'Conscription crises in 1917 and 1944 were especially bitter in:',
    o: [
      'Quebec, where many opposed compulsory overseas service',
      'Nunavut only',
      'Prince Edward Island potato farms only',
      'The Senate of 1867',
    ],
    a: 'a',
    e: 'English Canada and French Canada split over forcing men to fight overseas. It is a classic national-unity fact.',
  },
  {
    id: 'his-047',
    t: 'tf',
    p: 'Indigenous nations had trade, diplomacy, and conflict among themselves long before Europeans arrived.',
    a: 'true',
    e: 'The history chapter does not begin with Cabot. The land was already a political world.',
  },
  {
    id: 'his-048',
    p: 'Thayendanegea (Joseph Brant) is remembered as:',
    o: [
      'A Mohawk leader who allied with the British and later settled in what became Ontario',
      'Canada’s first Prime Minister',
      'The founder of the Hudson’s Bay Company',
      'A French governor at Louisbourg only',
    ],
    a: 'a',
    e: 'Brant and Loyalist Haudenosaunee communities are part of the post-Revolution story in Canada.',
  },
  {
    id: 'his-049',
    p: 'The Halifax Explosion of 1917 was:',
    o: [
      'A wartime harbour disaster that devastated the city',
      'A Quiet Revolution protest',
      'The last spike ceremony',
      'A gold-rush stampede',
    ],
    a: 'a',
    e: 'Two ships collided, one carrying explosives. It is one of the worst disasters in Canadian history.',
  },
  {
    id: 'his-050',
    p: 'Canada’s soldiers in the First World War included a famous all-Black unit known as:',
    o: [
      'No. 2 Construction Battalion',
      'The Famous Five',
      'The North-West Mounted Police cavalry only',
      'The Senate Guard',
    ],
    a: 'a',
    e: 'Black volunteers were long kept out of combat roles; this construction battalion is the unit the guide-era story highlights.',
  },
  {
    id: 'his-051',
    t: 'tf',
    p: 'Women were legally “persons” for Senate appointments before the Persons Case.',
    a: 'false',
    e: 'The Canadian courts had said no. The 1929 decision reversed that and opened the Senate to women.',
  },
]);
