import { build } from './build.mjs';

export default build('the-justice-system', 'Discover Canada — The Justice System', [
  {
    id: 'jus-001',
    p: 'What is Canada’s highest court?',
    o: [
      'The Federal Court of Appeal',
      'The Supreme Court of Canada',
      'The Provincial Court of Ontario',
      'The Senate',
    ],
    a: 'b',
    e: 'The Supreme Court of Canada is the final court of appeal. It includes a Chief Justice and eight other judges.',
  },
  {
    id: 'jus-002',
    p: 'In Canadian criminal law, a person accused of a crime is:',
    o: [
      'Assumed guilty until a lawyer is hired',
      'Presumed innocent until proven guilty',
      'Tried by the Prime Minister',
      'Unable to remain silent',
    ],
    a: 'b',
    e: 'The presumption of innocence is a core legal right. The Crown must prove guilt beyond a reasonable doubt.',
  },
  {
    id: 'jus-003',
    t: 'tf',
    p: 'Police in Canada always have the right to search a home without a warrant.',
    a: 'false',
    e: 'Legal rights include protection against unreasonable search and seizure. In most cases police need lawful authority, often a warrant, before searching a home.',
  },
  {
    id: 'jus-004',
    p: 'The rule of law means that:',
    o: [
      'Everyone, including government, is subject to the law',
      'The Prime Minister is above the Criminal Code',
      'Police make the law as they go',
      'Only citizens have to obey statutes',
    ],
    a: 'a',
    e: 'No one is officially above the law. That is a foundation of Canadian justice.',
  },
  {
    id: 'jus-005',
    p: 'Criminal law in Canada is mainly made by:',
    o: ['Parliament (federal)', 'City councils', 'School boards', 'The official opposition research office'],
    a: 'a',
    e: 'The Criminal Code is federal. Provinces run many of the courts and some prosecutions, but the offences are national.',
  },
  {
    id: 'jus-006',
    p: 'Civil law (in the sense of private disputes) covers things like:',
    o: [
      'Contracts, family property, and personal injuries',
      'Treason and murder only',
      'Declaring war',
      'Issuing passports',
    ],
    a: 'a',
    e: 'The Crown is not always a party. The standard of proof is the balance of probabilities, not reasonable doubt.',
  },
  {
    id: 'jus-007',
    p: 'Quebec’s private law tradition is:',
    o: [
      'Civil law inherited from France',
      'Identical to Yukon custom only',
      'Sharia as provincial statute',
      'U.S. Supreme Court precedent as binding',
    ],
    a: 'a',
    e: 'Quebec uses a civil code for private law. Other provinces use English-derived common law. Criminal law is statutory and common-law-based nationwide.',
  },
  {
    id: 'jus-008',
    t: 'tf',
    p: 'Canadian courts are independent of Cabinet.',
    a: 'true',
    e: 'Judges are not the government’s lawyers. They can rule against the government. That independence is the point.',
  },
  {
    id: 'jus-009',
    p: 'How many judges sit on the Supreme Court of Canada?',
    o: ['Nine, including the Chief Justice', 'One', 'One hundred', 'Three, all from Ontario'],
    a: 'a',
    e: 'Nine is the number to remember. By statute, a set number come from Quebec because of its civil-law system.',
  },
  {
    id: 'jus-010',
    p: 'The RCMP is:',
    o: [
      'The federal police force, which also contracts as provincial police in much of Canada',
      'The Supreme Court’s security contractor only in 1867',
      'A municipal parking authority',
      'The Senate fire brigade',
    ],
    a: 'a',
    e: 'Ontario and Quebec have their own provincial police. Elsewhere the RCMP often fills that role by contract.',
  },
  {
    id: 'jus-011',
    p: 'If you are arrested, you should:',
    o: [
      'Ask to speak to a lawyer and not guess your way through questioning',
      'Invent a story to please the officer',
      'Name the Prime Minister as your surety automatically',
      'Refuse to give your name in every circumstance, even when legally required',
    ],
    a: 'a',
    e: 'The right to counsel is practical, not theoretical. Use it.',
  },
  {
    id: 'jus-012',
    p: 'A jury in a serious criminal trial is meant to be:',
    o: [
      'Impartial members of the public who hear the evidence',
      'The accused’s relatives',
      'Cabinet ministers',
      'The arresting officers',
    ],
    a: 'a',
    e: 'Jury service is a citizenship duty. Jurors decide facts; the judge explains the law.',
  },
  {
    id: 'jus-013',
    t: 'tf',
    p: 'You can be forced to testify against yourself in a criminal trial as the accused.',
    a: 'false',
    e: 'The right against self-incrimination and the right to silence are legal rights. The Crown must make its own case.',
  },
  {
    id: 'jus-014',
    p: '“Beyond a reasonable doubt” is the standard of proof in:',
    o: ['Criminal cases', 'Small-claims fights over a fence', 'Municipal dog-licence hearings only', 'Senate seating disputes'],
    a: 'a',
    e: 'It is a high standard because a conviction can take away liberty.',
  },
  {
    id: 'jus-015',
    p: 'Provincial and territorial courts typically handle:',
    o: [
      'Most everyday criminal charges and many family or youth matters',
      'Only constitutional cases about the Monarch',
      'NATO disputes',
      'Federal elections recounts exclusively',
    ],
    a: 'a',
    e: 'Superior courts take the most serious trials and large civil cases. Appeals go further up.',
  },
  {
    id: 'jus-016',
    p: 'Judges in Canada are:',
    o: ['Appointed, not elected', 'Elected on party slogans', 'Chosen by televised talent shows', 'Always sitting MPs'],
    a: 'a',
    e: 'Appointment plus security of tenure is how Canada tries to keep judging off the campaign trail.',
  },
  {
    id: 'jus-017',
    p: 'Legal aid exists because:',
    o: [
      'Rights mean little if you cannot afford a lawyer in serious matters',
      'Only corporations may have counsel',
      'The Charter bans lawyers',
      'Police must defend the accused',
    ],
    a: 'a',
    e: 'Eligibility is limited, but the principle is access to justice, not justice only for the rich.',
  },
  {
    id: 'jus-018',
    t: 'tf',
    p: 'Police decide guilt or innocence.',
    a: 'false',
    e: 'Police investigate and may charge. Courts decide. That separation is basic.',
  },
  {
    id: 'jus-019',
    p: 'Habeas corpus lets a detained person:',
    o: [
      'Ask a court whether the detention is lawful',
      'Rewrite the Criminal Code',
      'Elect a new Chief Justice',
      'Cancel a federal election',
    ],
    a: 'a',
    e: 'It is an old writ and a living Charter-era protection against arbitrary holding.',
  },
  {
    id: 'jus-020',
    p: 'A “Crown attorney” or Crown prosecutor represents:',
    o: ['The state in a criminal case', 'The accused as a public defender always', 'The municipal parks board', 'NATO'],
    a: 'a',
    e: 'The Crown is the state’s lawyer. Defence counsel represents the accused. They are not the same job.',
  },
  {
    id: 'jus-021',
    p: 'Youth criminal justice in Canada is:',
    o: [
      'A separate system with extra emphasis on rehabilitation, still with real consequences',
      'Identical to adult court in every respect, including naming children in the media as a rule',
      'Handled only by school principals',
      'Abolished in 1867',
    ],
    a: 'a',
    e: 'Young people have a distinct statute. It is not a free pass.',
  },
  {
    id: 'jus-022',
    t: 'tf',
    p: 'You have the right to a fair and public hearing before an independent court in criminal matters.',
    a: 'true',
    e: 'Open courts and impartial judges are legal rights. Some limits exist (youth, publication bans), but secrecy is the exception.',
  },
  {
    id: 'jus-023',
    p: 'Common law, in the provinces that use it, develops through:',
    o: [
      'Court decisions as well as statutes',
      'Only United Nations resolutions',
      'Mayoral decrees',
      'Hockey rulebooks',
    ],
    a: 'a',
    e: 'Judges follow precedent. Legislatures can still change the law by statute.',
  },
  {
    id: 'jus-024',
    p: 'Which of these is a typical police service level in Canada?',
    o: [
      'Municipal, provincial, and federal',
      'Only a single continental force run by Washington',
      'Only railway police from 1670',
      'Only Senate security',
    ],
    a: 'a',
    e: 'Cities often have their own services. Provinces may have provincial police. The RCMP is federal.',
  },
  {
    id: 'jus-025',
    p: 'A warrant is commonly required because the Charter protects you against:',
    o: [
      'Unreasonable search and seizure',
      'Paying taxes',
      'Jury duty',
      'Being called as a witness in a civil trial ever',
    ],
    a: 'a',
    e: 'Urgent exceptions exist. The default for a home search is prior judicial authorization.',
  },
  {
    id: 'jus-026',
    t: 'tf',
    p: 'The Prime Minister can overturn a Supreme Court decision by memo.',
    a: 'false',
    e: 'Parliament can try to pass a new law, sometimes using the notwithstanding clause in limited areas. It cannot quietly ignore a ruling by memo.',
  },
  {
    id: 'jus-027',
    p: 'Restitution and sentencing circles are examples of:',
    o: [
      'Efforts, in some cases, to include repairing harm—not a replacement for the whole criminal law',
      'Abolishing courts',
      'Senate procedure',
      'Municipal compost rules',
    ],
    a: 'a',
    e: 'The guide stresses fairness and the rule of law. Community processes can sit beside, not instead of, core rights.',
  },
  {
    id: 'jus-028',
    p: 'Appeals exist so that:',
    o: [
      'A higher court can review alleged legal errors',
      'The accused can keep retrying until a friend is on the jury',
      'Cabinet can pick a winner',
      'Newspapers can veto verdicts',
    ],
    a: 'a',
    e: 'You do not get unlimited new trials for fun. You get review of law and, in some cases, of unreasonable verdicts.',
  },
  {
    id: 'jus-029',
    p: 'Which statement is correct?',
    o: [
      'Getting a lawyer is a right on arrest or detention; remaining silent is usually wise until you have advice',
      'You must answer every police question or you automatically go to prison',
      'Only citizens may call a lawyer',
      'Judges must also be your defence counsel',
    ],
    a: 'a',
    e: 'Citizenship is not required for basic legal rights on arrest in Canada.',
  },
  {
    id: 'jus-030',
    t: 'tf',
    p: 'All Canadian private law is identical in every province, including Quebec.',
    a: 'false',
    e: 'Quebec’s civil-law tradition is a testable difference. Criminal law is the part that is mainly unified.',
  },
  {
    id: 'jus-031',
    p: 'The Federal Court of Canada mainly hears:',
    o: [
      'Certain federal-law disputes, such as immigration and some government decisions—not the same caseload as the Supreme Court',
      'Every murder trial in Canada',
      'Only municipal parking tickets in Ottawa',
      'Senate privilege fights exclusively',
    ],
    a: 'a',
    e: 'The Supreme Court is the final appeal court. Trial and specialist federal work sits lower.',
  },
  {
    id: 'jus-032',
    p: 'Solicitor-client privilege means that:',
    o: [
      'Confidential legal advice to a client is generally protected',
      'Lawyers must report every conversation to Cabinet',
      'Only senators may hire lawyers',
      'Police may sit in on all defence meetings',
    ],
    a: 'a',
    e: 'It is a pillar of a fair legal system. It is not a licence to commit new crimes.',
  },
  {
    id: 'jus-033',
    t: 'tf',
    p: 'Ontario and Quebec maintain provincial police services (the OPP and the Sûreté du Québec) in addition to municipal forces and the RCMP.',
    a: 'true',
    e: 'Policing is layered. The RCMP also contracts to serve as the provincial police in several other provinces.',
  },
  {
    id: 'jus-034',
    p: 'The Charter’s “notwithstanding clause” (section 33) allows:',
    o: [
      'Parliament or a legislature to temporarily override certain Charter rights in a statute',
      'The Prime Minister to jail opponents without a law',
      'Cities to ban the Supreme Court',
      'Juries to ignore all evidence',
    ],
    a: 'a',
    e: 'It is a controversial safety valve in the 1982 deal. It does not cover every right, and it must be written into a law.',
  },
  {
    id: 'jus-035',
    p: 'Small-claims court is designed for:',
    o: [
      'Lower-value private disputes without the full cost of a superior-court trial',
      'Treason only',
      'Choosing the Governor General',
      'Federal election recounts only',
    ],
    a: 'a',
    e: 'It is access to justice, not a second Supreme Court.',
  },
  {
    id: 'jus-036',
    p: 'A justice of the peace or provincial court judge often handles:',
    o: [
      'Bail hearings, warrants, and many first-instance criminal matters',
      'Amending the Constitution',
      'Appointing Cabinet',
      'Command of NORAD',
    ],
    a: 'a',
    e: 'Most people’s contact with criminal court is not at the Supreme Court. It starts locally.',
  },
  {
    id: 'jus-037',
    t: 'tf',
    p: 'You may sue the government in Canada; the Crown is not above all private-law duties.',
    a: 'true',
    e: 'Crown liability is limited and technical, but the rule of law means officials are not personally a law unto themselves.',
  },
  {
    id: 'jus-038',
    p: 'Perjury is a crime because:',
    o: [
      'Courts depend on truthful evidence under oath',
      'Newspapers dislike long trials',
      'Senators prefer short speeches',
      'It is a municipal zoning offence only',
    ],
    a: 'a',
    e: 'Lying in court attacks the trial itself. It is not a minor manners issue.',
  },
  {
    id: 'jus-039',
    p: 'Legal rights such as the right to counsel apply:',
    o: [
      'To everyone in Canada, not only citizens',
      'Only to people born in Ottawa',
      'Only to MPs',
      'Only after a conviction',
    ],
    a: 'a',
    e: 'Citizenship matters for voting and mobility. Fair-trial rights are broader.',
  },
  {
    id: 'jus-040',
    p: 'Family law (divorce, parenting) is an example of:',
    o: [
      'Law that mixes federal and provincial rules and is handled in courts, not by a Cabinet vote on your case',
      'A Senate sports league',
      'Military conscription',
      'The royal anthem',
    ],
    a: 'a',
    e: 'Divorce is federal; many related matters are provincial. Politicians do not sit as your trial judges.',
  },
  {
    id: 'jus-041',
    t: 'tf',
    p: 'An independent judiciary includes security of tenure: judges are not fired because the government dislikes a ruling.',
    a: 'true',
    e: 'Removal is a rare, formal process. That independence is how the Constitution stays more than a pamphlet.',
  },
  {
    id: 'jus-042',
    p: 'Alternative dispute resolution (mediation, arbitration) exists to:',
    o: [
      'Settle some civil disputes without a full trial',
      'Replace the Criminal Code for murder',
      'Elect the Prime Minister',
      'Issue passports',
    ],
    a: 'a',
    e: 'It is common in private disputes. Serious crime still goes through the criminal courts.',
  },
  {
    id: 'jus-043',
    p: 'Search warrants are issued by:',
    o: [
      'A judge or justice of the peace, not by the investigating officer acting alone as a rule',
      'The local MP',
      'A newspaper editor',
      'The Leader of the Opposition',
    ],
    a: 'a',
    e: 'Prior authorization is the Charter’s usual bargain: police investigate; an independent official checks the grounds.',
  },
  {
    id: 'jus-044',
    p: 'Correctional services (prisons) after a sentence are mainly about:',
    o: [
      'Carrying out the sentence imposed by the court, not retrying the trial',
      'Letting Cabinet rewrite the verdict each month',
      'Municipal snow clearing',
      'Choosing senators',
    ],
    a: 'a',
    e: 'Parole boards and prison rules are later stages. Guilt was supposed to be decided in court.',
  },
]);
