import { build } from './build.mjs';

export default build('the-justice-system', 'Discover Canada — The Justice System', [
  {
    id: 'jus-001',
    p: 'What is Canada’s highest court?',
    pf: 'Quel est le tribunal le plus élevé au Canada?',
    o: [
      'The Federal Court of Appeal',
      'The Supreme Court of Canada',
      'The Provincial Court of Ontario',
      'The Senate',
    ],
    of: [
      'La Cour d’appel fédérale',
      'La Cour suprême du Canada',
      'La Cour provinciale de l’Ontario',
      'Le Sénat',
    ],
    a: 'b',
    e: 'The Supreme Court of Canada is the final court of appeal. It includes a Chief Justice and eight other judges.',
    ef: 'La Cour suprême du Canada est le dernier tribunal d’appel. Elle compte un juge en chef et huit autres juges.',
  },
  {
    id: 'jus-002',
    p: 'In Canadian criminal law, a person accused of a crime is:',
    pf: 'En droit criminel canadien, la personne accusée d’un crime est :',
    o: [
      'Assumed guilty until a lawyer is hired',
      'Presumed innocent until proven guilty',
      'Tried by the Prime Minister',
      'Unable to remain silent',
    ],
    of: [
      'Présumée coupable jusqu’à ce qu’elle engage un avocat',
      'Présumée innocente jusqu’à preuve de culpabilité',
      'Jugée par le premier ministre',
      'Incapable de garder le silence',
    ],
    a: 'b',
    e: 'The presumption of innocence is a core legal right. The Crown must prove guilt beyond a reasonable doubt.',
    ef: 'La présomption d’innocence est un droit juridique fondamental. La Couronne doit prouver la culpabilité hors de tout doute raisonnable.',
  },
  {
    id: 'jus-003',
    t: 'tf',
    p: 'Police in Canada always have the right to search a home without a warrant.',
    pf: 'Au Canada, les policiers ont toujours le droit de perquisitionner une maison sans mandat.',
    a: 'false',
    e: 'Legal rights include protection against unreasonable search and seizure. In most cases police need lawful authority, often a warrant, before searching a home.',
    ef: 'Les droits juridiques comprennent la protection contre les fouilles, les perquisitions et les saisies abusives. Dans la plupart des cas, les policiers doivent détenir une autorisation légale, souvent un mandat, avant de perquisitionner une maison.',
  },
  {
    id: 'jus-004',
    p: 'The rule of law means that:',
    pf: 'La primauté du droit signifie que :',
    o: [
      'Everyone, including government, is subject to the law',
      'The Prime Minister is above the Criminal Code',
      'Police make the law as they go',
      'Only citizens have to obey statutes',
    ],
    of: [
      'Tout le monde, y compris le gouvernement, est assujetti à la loi',
      'Le premier ministre est au-dessus du Code criminel',
      'Les policiers créent la loi au fur et à mesure',
      'Seuls les citoyens doivent respecter les lois',
    ],
    a: 'a',
    e: 'No one is officially above the law. That is a foundation of Canadian justice.',
    ef: 'Personne n’est officiellement au-dessus de la loi. C’est un fondement de la justice canadienne.',
  },
  {
    id: 'jus-005',
    p: 'Criminal law in Canada is mainly made by:',
    pf: 'Au Canada, le droit criminel est principalement établi par :',
    o: ['Parliament (federal)', 'City councils', 'School boards', 'The official opposition research office'],
    of: ['Le Parlement (fédéral)', 'Les conseils municipaux', 'Les conseils scolaires', 'Le bureau de recherche de l’opposition officielle'],
    a: 'a',
    e: 'The Criminal Code is federal. Provinces run many of the courts and some prosecutions, but the offences are national.',
    ef: 'Le Code criminel relève du fédéral. Les provinces administrent bon nombre de tribunaux et certaines poursuites, mais les infractions sont les mêmes partout au pays.',
  },
  {
    id: 'jus-006',
    p: 'Civil law (in the sense of private disputes) covers things like:',
    pf: 'Le droit civil, au sens des litiges privés, porte sur des questions comme :',
    o: [
      'Contracts, family property, and personal injuries',
      'Treason and murder only',
      'Declaring war',
      'Issuing passports',
    ],
    of: [
      'Les contrats, les biens familiaux et les blessures corporelles',
      'La trahison et le meurtre seulement',
      'La déclaration de guerre',
      'La délivrance des passeports',
    ],
    a: 'a',
    e: 'The Crown is not always a party. The standard of proof is the balance of probabilities, not reasonable doubt.',
    ef: 'La Couronne n’est pas toujours partie au litige. La norme de preuve est la prépondérance des probabilités, et non le doute raisonnable.',
  },
  {
    id: 'jus-007',
    p: 'Quebec’s private law tradition is:',
    pf: 'La tradition de droit privé du Québec est :',
    o: [
      'Civil law inherited from France',
      'Identical to Yukon custom only',
      'Sharia as provincial statute',
      'U.S. Supreme Court precedent as binding',
    ],
    of: [
      'Le droit civil hérité de la France',
      'Identique à la seule coutume du Yukon',
      'La charia comme loi provinciale',
      'La jurisprudence de la Cour suprême des États-Unis, avec force obligatoire',
    ],
    a: 'a',
    e: 'Quebec uses a civil code for private law. Other provinces use English-derived common law. Criminal law is statutory and common-law-based nationwide.',
    ef: 'Le Québec applique un code civil en droit privé. Les autres provinces suivent la common law d’origine anglaise. Le droit criminel, lui, est législatif et s’appuie sur la common law dans tout le pays.',
  },
  {
    id: 'jus-008',
    t: 'tf',
    p: 'Canadian courts are independent of Cabinet.',
    pf: 'Les tribunaux canadiens sont indépendants du Cabinet.',
    a: 'true',
    e: 'Judges are not the government’s lawyers. They can rule against the government. That independence is the point.',
    ef: 'Les juges ne sont pas les avocats du gouvernement. Ils peuvent trancher contre lui. C’est tout l’intérêt de leur indépendance.',
  },
  {
    id: 'jus-009',
    p: 'How many judges sit on the Supreme Court of Canada?',
    pf: 'Combien de juges siègent à la Cour suprême du Canada?',
    o: ['Nine, including the Chief Justice', 'One', 'One hundred', 'Three, all from Ontario'],
    of: ['Neuf, y compris le juge en chef', 'Un', 'Cent', 'Trois, tous originaires de l’Ontario'],
    a: 'a',
    e: 'Nine is the number to remember. By statute, a set number come from Quebec because of its civil-law system.',
    ef: 'Retenez le chiffre neuf. La loi exige qu’un nombre déterminé d’entre eux viennent du Québec, en raison de son système de droit civil.',
  },
  {
    id: 'jus-010',
    p: 'The RCMP is:',
    pf: 'La Gendarmerie royale du Canada est :',
    o: [
      'The federal police force, which also contracts as provincial police in much of Canada',
      'The Supreme Court’s security contractor only in 1867',
      'A municipal parking authority',
      'The Senate fire brigade',
    ],
    of: [
      'Le corps policier fédéral, qui agit aussi comme police provinciale par contrat dans une grande partie du Canada',
      'Le fournisseur de sécurité de la Cour suprême, uniquement en 1867',
      'Une autorité municipale du stationnement',
      'Le service d’incendie du Sénat',
    ],
    a: 'a',
    e: 'Ontario and Quebec have their own provincial police. Elsewhere the RCMP often fills that role by contract.',
    ef: 'L’Ontario et le Québec ont leur propre police provinciale. Ailleurs, la Gendarmerie royale du Canada remplit souvent ce rôle par contrat.',
  },
  {
    id: 'jus-011',
    p: 'If you are arrested, you should:',
    pf: 'Si vous êtes arrêté, vous devriez :',
    o: [
      'Ask to speak to a lawyer and not guess your way through questioning',
      'Invent a story to please the officer',
      'Name the Prime Minister as your surety automatically',
      'Refuse to give your name in every circumstance, even when legally required',
    ],
    of: [
      'Demander à parler à un avocat plutôt que de répondre à l’aveuglette à l’interrogatoire',
      'Inventer une histoire pour plaire au policier',
      'Désigner automatiquement le premier ministre comme caution',
      'Refuser de donner votre nom en toute circonstance, même lorsque la loi l’exige',
    ],
    a: 'a',
    e: 'The right to counsel is practical, not theoretical. Use it.',
    ef: 'Le droit à l’assistance d’un avocat est concret, et non théorique. Exercez-le.',
  },
  {
    id: 'jus-012',
    p: 'A jury in a serious criminal trial is meant to be:',
    pf: 'Dans un procès criminel grave, le jury doit être composé :',
    o: [
      'Impartial members of the public who hear the evidence',
      'The accused’s relatives',
      'Cabinet ministers',
      'The arresting officers',
    ],
    of: [
      'De membres impartiaux du public qui entendent la preuve',
      'Des proches de l’accusé',
      'Des ministres du Cabinet',
      'Des policiers qui ont procédé à l’arrestation',
    ],
    a: 'a',
    e: 'Jury service is a citizenship duty. Jurors decide facts; the judge explains the law.',
    ef: 'Faire partie d’un jury est un devoir de citoyenneté. Les jurés tranchent les faits; le juge explique le droit.',
  },
  {
    id: 'jus-013',
    t: 'tf',
    p: 'You can be forced to testify against yourself in a criminal trial as the accused.',
    pf: 'À titre d’accusé dans un procès criminel, on peut vous obliger à témoigner contre vous-même.',
    a: 'false',
    e: 'The right against self-incrimination and the right to silence are legal rights. The Crown must make its own case.',
    ef: 'La protection contre l’auto-incrimination et le droit au silence font partie des droits juridiques. La Couronne doit monter sa propre preuve.',
  },
  {
    id: 'jus-014',
    p: '“Beyond a reasonable doubt” is the standard of proof in:',
    pf: 'La norme de preuve « hors de tout doute raisonnable » s’applique :',
    o: ['Criminal cases', 'Small-claims fights over a fence', 'Municipal dog-licence hearings only', 'Senate seating disputes'],
    of: ['Aux affaires criminelles', 'Aux petites créances au sujet d’une clôture', 'Aux seules audiences municipales sur les permis pour chiens', 'Aux différends sur les sièges au Sénat'],
    a: 'a',
    e: 'It is a high standard because a conviction can take away liberty.',
    ef: 'La norme est exigeante parce qu’une condamnation peut priver une personne de sa liberté.',
  },
  {
    id: 'jus-015',
    p: 'Provincial and territorial courts typically handle:',
    pf: 'Les cours provinciales et territoriales traitent généralement :',
    o: [
      'Most everyday criminal charges and many family or youth matters',
      'Only constitutional cases about the Monarch',
      'NATO disputes',
      'Federal elections recounts exclusively',
    ],
    of: [
      'La plupart des accusations criminelles courantes ainsi que de nombreuses affaires familiales ou de justice pour les adolescents',
      'Seulement les causes constitutionnelles portant sur le monarque',
      'Les différends de l’OTAN',
      'Exclusivement les recomptages des élections fédérales',
    ],
    a: 'a',
    e: 'Superior courts take the most serious trials and large civil cases. Appeals go further up.',
    ef: 'Les cours supérieures entendent les procès les plus graves et les grands litiges civils. Les appels montent encore plus haut.',
  },
  {
    id: 'jus-016',
    p: 'Judges in Canada are:',
    pf: 'Au Canada, les juges sont :',
    o: ['Appointed, not elected', 'Elected on party slogans', 'Chosen by televised talent shows', 'Always sitting MPs'],
    of: ['Nommés, et non élus', 'Élus au moyen de slogans de parti', 'Choisis dans des concours télévisés', 'Toujours des députés en poste'],
    a: 'a',
    e: 'Appointment plus security of tenure is how Canada tries to keep judging off the campaign trail.',
    ef: 'La nomination jointe à l’inamovibilité est le moyen par lequel le Canada tient la fonction de juger à l’écart des campagnes électorales.',
  },
  {
    id: 'jus-017',
    p: 'Legal aid exists because:',
    pf: 'L’aide juridique existe parce que :',
    o: [
      'Rights mean little if you cannot afford a lawyer in serious matters',
      'Only corporations may have counsel',
      'The Charter bans lawyers',
      'Police must defend the accused',
    ],
    of: [
      'Les droits valent peu si vous n’avez pas les moyens de payer un avocat dans une affaire grave',
      'Seules les sociétés peuvent être représentées par un avocat',
      'La Charte interdit les avocats',
      'Les policiers doivent défendre l’accusé',
    ],
    a: 'a',
    e: 'Eligibility is limited, but the principle is access to justice, not justice only for the rich.',
    ef: 'L’admissibilité est limitée, mais le principe demeure l’accès à la justice, et non une justice réservée aux riches.',
  },
  {
    id: 'jus-018',
    t: 'tf',
    p: 'Police decide guilt or innocence.',
    pf: 'Ce sont les policiers qui décident de la culpabilité ou de l’innocence.',
    a: 'false',
    e: 'Police investigate and may charge. Courts decide. That separation is basic.',
    ef: 'Les policiers enquêtent et peuvent porter des accusations. Les tribunaux tranchent. Cette séparation est fondamentale.',
  },
  {
    id: 'jus-019',
    p: 'Habeas corpus lets a detained person:',
    pf: 'L’habeas corpus permet à une personne détenue :',
    o: [
      'Ask a court whether the detention is lawful',
      'Rewrite the Criminal Code',
      'Elect a new Chief Justice',
      'Cancel a federal election',
    ],
    of: [
      'De demander à un tribunal si sa détention est légale',
      'De réécrire le Code criminel',
      'D’élire un nouveau juge en chef',
      'D’annuler une élection fédérale',
    ],
    a: 'a',
    e: 'It is an old writ and a living Charter-era protection against arbitrary holding.',
    ef: 'C’est un recours ancien qui demeure, à l’ère de la Charte, une protection bien vivante contre la détention arbitraire.',
  },
  {
    id: 'jus-020',
    p: 'A “Crown attorney” or Crown prosecutor represents:',
    pf: 'Le procureur de la Couronne représente :',
    o: ['The state in a criminal case', 'The accused as a public defender always', 'The municipal parks board', 'NATO'],
    of: ['L’État dans une affaire criminelle', 'L’accusé, toujours à titre d’avocat de la défense', 'La commission municipale des parcs', 'L’OTAN'],
    a: 'a',
    e: 'The Crown is the state’s lawyer. Defence counsel represents the accused. They are not the same job.',
    ef: 'Le procureur de la Couronne est l’avocat de l’État. L’avocat de la défense représente l’accusé. Ce ne sont pas les mêmes fonctions.',
  },
  {
    id: 'jus-021',
    p: 'Youth criminal justice in Canada is:',
    pf: 'Au Canada, la justice pénale pour les adolescents est :',
    o: [
      'A separate system with extra emphasis on rehabilitation, still with real consequences',
      'Identical to adult court in every respect, including naming children in the media as a rule',
      'Handled only by school principals',
      'Abolished in 1867',
    ],
    of: [
      'Un système distinct qui met davantage l’accent sur la réadaptation, tout en imposant de véritables conséquences',
      'Identique en tout point au tribunal pour adultes, y compris la règle de nommer les enfants dans les médias',
      'Confiée uniquement aux directions d’école',
      'Abolie en 1867',
    ],
    a: 'a',
    e: 'Young people have a distinct statute. It is not a free pass.',
    ef: 'Les adolescents sont visés par une loi distincte. Ce n’est pas pour autant une impunité.',
  },
  {
    id: 'jus-022',
    t: 'tf',
    p: 'You have the right to a fair and public hearing before an independent court in criminal matters.',
    pf: 'En matière criminelle, vous avez droit à une audience publique et équitable devant un tribunal indépendant.',
    a: 'true',
    e: 'Open courts and impartial judges are legal rights. Some limits exist (youth, publication bans), but secrecy is the exception.',
    ef: 'La publicité des débats et l’impartialité des juges font partie des droits juridiques. Certaines limites existent (adolescents, interdictions de publication), mais le secret reste l’exception.',
  },
  {
    id: 'jus-023',
    p: 'Common law, in the provinces that use it, develops through:',
    pf: 'Dans les provinces qui l’appliquent, la common law évolue :',
    o: [
      'Court decisions as well as statutes',
      'Only United Nations resolutions',
      'Mayoral decrees',
      'Hockey rulebooks',
    ],
    of: [
      'Par les décisions des tribunaux autant que par les lois',
      'Uniquement par les résolutions des Nations Unies',
      'Par les décrets des maires',
      'Par les règlements du hockey',
    ],
    a: 'a',
    e: 'Judges follow precedent. Legislatures can still change the law by statute.',
    ef: 'Les juges suivent les précédents. Les législatures peuvent tout de même modifier le droit par une loi.',
  },
  {
    id: 'jus-024',
    p: 'Which of these is a typical police service level in Canada?',
    pf: 'Lequel de ces paliers de services policiers est courant au Canada?',
    o: [
      'Municipal, provincial, and federal',
      'Only a single continental force run by Washington',
      'Only railway police from 1670',
      'Only Senate security',
    ],
    of: [
      'Municipal, provincial et fédéral',
      'Une seule force continentale dirigée depuis Washington',
      'Uniquement la police des chemins de fer depuis 1670',
      'Uniquement la sécurité du Sénat',
    ],
    a: 'a',
    e: 'Cities often have their own services. Provinces may have provincial police. The RCMP is federal.',
    ef: 'Les villes ont souvent leur propre service. Les provinces peuvent avoir une police provinciale. La Gendarmerie royale du Canada est fédérale.',
  },
  {
    id: 'jus-025',
    p: 'A warrant is commonly required because the Charter protects you against:',
    pf: 'Un mandat est habituellement exigé parce que la Charte vous protège contre :',
    o: [
      'Unreasonable search and seizure',
      'Paying taxes',
      'Jury duty',
      'Being called as a witness in a civil trial ever',
    ],
    of: [
      'Les fouilles, les perquisitions et les saisies abusives',
      'Le paiement des impôts',
      'Le devoir de juré',
      'Toute assignation comme témoin dans un procès civil',
    ],
    a: 'a',
    e: 'Urgent exceptions exist. The default for a home search is prior judicial authorization.',
    ef: 'Des exceptions existent en cas d’urgence. Pour perquisitionner une maison, la règle demeure l’autorisation judiciaire préalable.',
  },
  {
    id: 'jus-026',
    t: 'tf',
    p: 'The Prime Minister can overturn a Supreme Court decision by memo.',
    pf: 'Le premier ministre peut renverser une décision de la Cour suprême par une simple note de service.',
    a: 'false',
    e: 'Parliament can try to pass a new law, sometimes using the notwithstanding clause in limited areas. It cannot quietly ignore a ruling by memo.',
    ef: 'Le Parlement peut tenter d’adopter une nouvelle loi, parfois en invoquant la clause dérogatoire dans certains domaines limités. Il ne peut pas écarter discrètement un jugement par une note de service.',
  },
  {
    id: 'jus-027',
    p: 'Restitution and sentencing circles are examples of:',
    pf: 'Le dédommagement et les cercles de détermination de la peine sont des exemples :',
    o: [
      'Efforts, in some cases, to include repairing harm—not a replacement for the whole criminal law',
      'Abolishing courts',
      'Senate procedure',
      'Municipal compost rules',
    ],
    of: [
      'D’efforts qui visent, dans certains cas, à réparer le tort causé, sans remplacer l’ensemble du droit criminel',
      'De l’abolition des tribunaux',
      'De la procédure du Sénat',
      'Des règles municipales sur le compostage',
    ],
    a: 'a',
    e: 'The guide stresses fairness and the rule of law. Community processes can sit beside, not instead of, core rights.',
    ef: 'Le guide insiste sur l’équité et la primauté du droit. Les processus communautaires peuvent s’ajouter aux droits fondamentaux, sans les remplacer.',
  },
  {
    id: 'jus-028',
    p: 'Appeals exist so that:',
    pf: 'Les appels existent afin :',
    o: [
      'A higher court can review alleged legal errors',
      'The accused can keep retrying until a friend is on the jury',
      'Cabinet can pick a winner',
      'Newspapers can veto verdicts',
    ],
    of: [
      'Qu’un tribunal supérieur puisse examiner les erreurs de droit alléguées',
      'Que l’accusé puisse recommencer jusqu’à ce qu’un ami siège au jury',
      'Que le Cabinet puisse désigner un gagnant',
      'Que les journaux puissent bloquer les verdicts',
    ],
    a: 'a',
    e: 'You do not get unlimited new trials for fun. You get review of law and, in some cases, of unreasonable verdicts.',
    ef: 'On n’obtient pas de nouveaux procès à l’infini. On obtient un examen du droit et, dans certains cas, des verdicts déraisonnables.',
  },
  {
    id: 'jus-029',
    p: 'Which statement is correct?',
    pf: 'Quel énoncé est exact?',
    o: [
      'Getting a lawyer is a right on arrest or detention; remaining silent is usually wise until you have advice',
      'You must answer every police question or you automatically go to prison',
      'Only citizens may call a lawyer',
      'Judges must also be your defence counsel',
    ],
    of: [
      'Le droit à un avocat s’applique dès l’arrestation ou la détention; il est généralement prudent de garder le silence jusqu’à ce que vous ayez obtenu des conseils',
      'Vous devez répondre à toutes les questions des policiers, sinon vous allez automatiquement en prison',
      'Seuls les citoyens peuvent appeler un avocat',
      'Les juges doivent aussi agir comme votre avocat de la défense',
    ],
    a: 'a',
    e: 'Citizenship is not required for basic legal rights on arrest in Canada.',
    ef: 'La citoyenneté n’est pas nécessaire pour bénéficier des droits juridiques de base lors d’une arrestation au Canada.',
  },
  {
    id: 'jus-030',
    t: 'tf',
    p: 'All Canadian private law is identical in every province, including Quebec.',
    pf: 'Au Canada, le droit privé est identique dans toutes les provinces, y compris au Québec.',
    a: 'false',
    e: 'Quebec’s civil-law tradition is a testable difference. Criminal law is the part that is mainly unified.',
    ef: 'La tradition civiliste du Québec est une différence susceptible d’être évaluée à l’examen. C’est le droit criminel qui est essentiellement uniforme.',
  },
  {
    id: 'jus-031',
    p: 'The Federal Court of Canada mainly hears:',
    pf: 'La Cour fédérale du Canada entend principalement :',
    o: [
      'Certain federal-law disputes, such as immigration and some government decisions—not the same caseload as the Supreme Court',
      'Every murder trial in Canada',
      'Only municipal parking tickets in Ottawa',
      'Senate privilege fights exclusively',
    ],
    of: [
      'Certains litiges de compétence fédérale, comme l’immigration et certaines décisions gouvernementales, ce qui n’est pas la charge de travail de la Cour suprême',
      'Tous les procès pour meurtre au Canada',
      'Uniquement les contraventions de stationnement à Ottawa',
      'Exclusivement les conflits sur les privilèges du Sénat',
    ],
    a: 'a',
    e: 'The Supreme Court is the final appeal court. Trial and specialist federal work sits lower.',
    ef: 'La Cour suprême est le tribunal d’appel de dernière instance. Les procès et le travail fédéral spécialisé se déroulent à des paliers inférieurs.',
  },
  {
    id: 'jus-032',
    p: 'Solicitor-client privilege means that:',
    pf: 'Le secret professionnel de l’avocat signifie que :',
    o: [
      'Confidential legal advice to a client is generally protected',
      'Lawyers must report every conversation to Cabinet',
      'Only senators may hire lawyers',
      'Police may sit in on all defence meetings',
    ],
    of: [
      'Les conseils juridiques confidentiels donnés à un client sont généralement protégés',
      'Les avocats doivent rapporter chaque conversation au Cabinet',
      'Seuls les sénateurs peuvent retenir les services d’un avocat',
      'Les policiers peuvent assister à toutes les rencontres avec la défense',
    ],
    a: 'a',
    e: 'It is a pillar of a fair legal system. It is not a licence to commit new crimes.',
    ef: 'C’est un pilier d’un système juridique équitable. Ce n’est pas un permis de commettre de nouveaux crimes.',
  },
  {
    id: 'jus-033',
    t: 'tf',
    p: 'Ontario and Quebec maintain provincial police services (the OPP and the Sûreté du Québec) in addition to municipal forces and the RCMP.',
    pf: 'L’Ontario et le Québec maintiennent des services de police provinciaux (la Police provinciale de l’Ontario et la Sûreté du Québec), en plus des corps municipaux et de la Gendarmerie royale du Canada.',
    a: 'true',
    e: 'Policing is layered. The RCMP also contracts to serve as the provincial police in several other provinces.',
    ef: 'Les services policiers sont organisés en paliers. La Gendarmerie royale du Canada agit aussi comme police provinciale par contrat dans plusieurs autres provinces.',
  },
  {
    id: 'jus-034',
    p: 'The Charter’s “notwithstanding clause” (section 33) allows:',
    pf: 'La « clause dérogatoire » de la Charte (article 33) permet :',
    o: [
      'Parliament or a legislature to temporarily override certain Charter rights in a statute',
      'The Prime Minister to jail opponents without a law',
      'Cities to ban the Supreme Court',
      'Juries to ignore all evidence',
    ],
    of: [
      'Au Parlement ou à une législature de suspendre temporairement certains droits garantis par la Charte au moyen d’une loi',
      'Au premier ministre d’emprisonner ses adversaires sans loi',
      'Aux villes d’interdire la Cour suprême',
      'Aux jurys d’ignorer toute la preuve',
    ],
    a: 'a',
    e: 'It is a controversial safety valve in the 1982 deal. It does not cover every right, and it must be written into a law.',
    ef: 'C’est une soupape controversée de l’entente de 1982. Elle ne vise pas tous les droits et doit être inscrite dans une loi.',
  },
  {
    id: 'jus-035',
    p: 'Small-claims court is designed for:',
    pf: 'La cour des petites créances est conçue pour :',
    o: [
      'Lower-value private disputes without the full cost of a superior-court trial',
      'Treason only',
      'Choosing the Governor General',
      'Federal election recounts only',
    ],
    of: [
      'Les litiges privés de moindre valeur, sans le coût complet d’un procès en cour supérieure',
      'La trahison seulement',
      'Le choix du gouverneur général',
      'Uniquement les recomptages des élections fédérales',
    ],
    a: 'a',
    e: 'It is access to justice, not a second Supreme Court.',
    ef: 'Il s’agit d’un moyen d’accès à la justice, et non d’une deuxième Cour suprême.',
  },
  {
    id: 'jus-036',
    p: 'A justice of the peace or provincial court judge often handles:',
    pf: 'Un juge de paix ou un juge de la cour provinciale s’occupe souvent :',
    o: [
      'Bail hearings, warrants, and many first-instance criminal matters',
      'Amending the Constitution',
      'Appointing Cabinet',
      'Command of NORAD',
    ],
    of: [
      'Des enquêtes sur remise en liberté, des mandats et de nombreuses affaires criminelles de première instance',
      'De la modification de la Constitution',
      'De la nomination du Cabinet',
      'Du commandement du NORAD',
    ],
    a: 'a',
    e: 'Most people’s contact with criminal court is not at the Supreme Court. It starts locally.',
    ef: 'Pour la plupart des gens, le contact avec la justice criminelle ne commence pas à la Cour suprême. Il commence à l’échelle locale.',
  },
  {
    id: 'jus-037',
    t: 'tf',
    p: 'You may sue the government in Canada; the Crown is not above all private-law duties.',
    pf: 'Au Canada, on peut poursuivre le gouvernement; la Couronne n’est pas dispensée de toute obligation de droit privé.',
    a: 'true',
    e: 'Crown liability is limited and technical, but the rule of law means officials are not personally a law unto themselves.',
    ef: 'La responsabilité de l’État est limitée et technique, mais la primauté du droit veut que les représentants de l’État ne soient pas une loi à eux seuls.',
  },
  {
    id: 'jus-038',
    p: 'Perjury is a crime because:',
    pf: 'Le parjure est un crime parce que :',
    o: [
      'Courts depend on truthful evidence under oath',
      'Newspapers dislike long trials',
      'Senators prefer short speeches',
      'It is a municipal zoning offence only',
    ],
    of: [
      'Les tribunaux dépendent d’une preuve véridique donnée sous serment',
      'Les journaux n’aiment pas les longs procès',
      'Les sénateurs préfèrent les discours courts',
      'Il s’agit uniquement d’une infraction municipale de zonage',
    ],
    a: 'a',
    e: 'Lying in court attacks the trial itself. It is not a minor manners issue.',
    ef: 'Mentir devant le tribunal attaque le procès lui-même. Ce n’est pas une simple question de savoir-vivre.',
  },
  {
    id: 'jus-039',
    p: 'Legal rights such as the right to counsel apply:',
    pf: 'Les droits juridiques comme le droit à un avocat s’appliquent :',
    o: [
      'To everyone in Canada, not only citizens',
      'Only to people born in Ottawa',
      'Only to MPs',
      'Only after a conviction',
    ],
    of: [
      'À toute personne au Canada, et non seulement aux citoyens',
      'Seulement aux personnes nées à Ottawa',
      'Seulement aux députés',
      'Seulement après une condamnation',
    ],
    a: 'a',
    e: 'Citizenship matters for voting and mobility. Fair-trial rights are broader.',
    ef: 'La citoyenneté compte pour le droit de vote et la liberté de circulation. Les droits à un procès équitable sont plus larges.',
  },
  {
    id: 'jus-040',
    p: 'Family law (divorce, parenting) is an example of:',
    pf: 'Le droit de la famille (divorce, rôle parental) est un exemple :',
    o: [
      'Law that mixes federal and provincial rules and is handled in courts, not by a Cabinet vote on your case',
      'A Senate sports league',
      'Military conscription',
      'The royal anthem',
    ],
    of: [
      'D’un domaine qui mêle règles fédérales et provinciales et qui se règle devant les tribunaux, non par un vote du Cabinet sur votre dossier',
      'D’une ligue sportive du Sénat',
      'De la conscription militaire',
      'De l’hymne royal',
    ],
    a: 'a',
    e: 'Divorce is federal; many related matters are provincial. Politicians do not sit as your trial judges.',
    ef: 'Le divorce relève du fédéral; beaucoup de questions connexes sont provinciales. Les politiciens ne siègent pas comme juges de votre procès.',
  },
  {
    id: 'jus-041',
    t: 'tf',
    p: 'An independent judiciary includes security of tenure: judges are not fired because the government dislikes a ruling.',
    pf: 'L’indépendance de la magistrature comprend l’inamovibilité : on ne congédie pas un juge parce que le gouvernement n’aime pas une décision.',
    a: 'true',
    e: 'Removal is a rare, formal process. That independence is how the Constitution stays more than a pamphlet.',
    ef: 'La révocation est un processus rare et formel. C’est grâce à cette indépendance que la Constitution reste plus qu’un dépliant.',
  },
  {
    id: 'jus-042',
    p: 'Alternative dispute resolution (mediation, arbitration) exists to:',
    pf: 'Les modes alternatifs de règlement des différends (médiation, arbitrage) servent :',
    o: [
      'Settle some civil disputes without a full trial',
      'Replace the Criminal Code for murder',
      'Elect the Prime Minister',
      'Issue passports',
    ],
    of: [
      'À régler certains litiges civils sans procès complet',
      'À remplacer le Code criminel en matière de meurtre',
      'À élire le premier ministre',
      'À délivrer les passeports',
    ],
    a: 'a',
    e: 'It is common in private disputes. Serious crime still goes through the criminal courts.',
    ef: 'Ils sont courants dans les litiges privés. Les crimes graves passent toujours par les tribunaux criminels.',
  },
  {
    id: 'jus-043',
    p: 'Search warrants are issued by:',
    pf: 'Les mandats de perquisition sont délivrés par :',
    o: [
      'A judge or justice of the peace, not by the investigating officer acting alone as a rule',
      'The local MP',
      'A newspaper editor',
      'The Leader of the Opposition',
    ],
    of: [
      'Un juge ou un juge de paix, et non, en règle générale, par l’enquêteur agissant seul',
      'Le député local',
      'Un rédacteur en chef de journal',
      'Le chef de l’opposition',
    ],
    a: 'a',
    e: 'Prior authorization is the Charter’s usual bargain: police investigate; an independent official checks the grounds.',
    ef: 'L’autorisation préalable est le compromis habituel de la Charte : les policiers enquêtent, et un officier de justice indépendant vérifie les motifs.',
  },
  {
    id: 'jus-044',
    p: 'Correctional services (prisons) after a sentence are mainly about:',
    pf: 'Après la peine, les services correctionnels (les prisons) visent surtout :',
    o: [
      'Carrying out the sentence imposed by the court, not retrying the trial',
      'Letting Cabinet rewrite the verdict each month',
      'Municipal snow clearing',
      'Choosing senators',
    ],
    of: [
      'À exécuter la peine imposée par le tribunal, et non à refaire le procès',
      'À laisser le Cabinet réécrire le verdict chaque mois',
      'Le déneigement municipal',
      'Le choix des sénateurs',
    ],
    a: 'a',
    e: 'Parole boards and prison rules are later stages. Guilt was supposed to be decided in court.',
    ef: 'Les commissions des libérations conditionnelles et les règles carcérales viennent plus tard. La culpabilité devait être tranchée devant le tribunal.',
  },
]);
