import { build } from './build.mjs';

export default build('modern-canada', 'Discover Canada — Modern Canada', [
  {
    id: 'mod-001',
    p: 'What was the Quiet Revolution in Quebec?',
    o: [
      'A rapid period of social and government reform in the 1960s',
      'The building of the Canadian Pacific Railway',
      'The wartime internment of Japanese Canadians',
      'The founding of the Hudson’s Bay Company',
    ],
    a: 'a',
    e: 'In the 1960s, Quebec modernized education, health care, and the provincial state, and a stronger Québécois identity took hold in public life.',
  },
  {
    id: 'mod-002',
    t: 'tf',
    p: 'Canada is a founding member of the North Atlantic Treaty Organization (NATO).',
    a: 'true',
    e: 'After the Second World War, Canada helped found NATO and also belongs to NORAD with the United States, as well as the United Nations and the Commonwealth.',
  },
  {
    id: 'mod-003',
    p: 'Which law made English and French official languages of the Parliament and Government of Canada?',
    o: ['The War Measures Act', 'The Official Languages Act (1969)', 'The Manitoba Act', 'The Indian Act'],
    a: 'b',
    e: 'The Official Languages Act confirmed bilingual federal institutions. The Charter later entrenched official language rights more firmly.',
  },
  {
    id: 'mod-004',
    p: 'Publicly funded hospital and medical insurance in Canada was pioneered at the provincial level in:',
    o: ['Saskatchewan, associated with Tommy Douglas', 'Prince Edward Island in 1864', 'Yukon during the gold rush', 'New France in 1608'],
    a: 'a',
    e: 'Saskatchewan’s medical-care plan led the way. A federal–provincial model then spread nationwide.',
  },
  {
    id: 'mod-005',
    p: 'The Canadian Bill of Rights (1960) is associated with Prime Minister:',
    o: ['John Diefenbaker', 'Sir John A. Macdonald', 'Robert Borden', 'Lester B. Pearson’s successor in 1867'],
    a: 'a',
    e: 'Diefenbaker’s Bill of Rights was a federal statute, not a constitutional charter. The 1982 Charter went further.',
  },
  {
    id: 'mod-006',
    p: 'Lester B. Pearson is remembered internationally for:',
    o: [
      'Helping create UN peacekeeping during the Suez Crisis (Nobel Peace Prize, 1957)',
      'Founding Quebec City',
      'Leading at Vimy Ridge',
      'Writing Magna Carta',
    ],
    a: 'a',
    e: 'Pearson’s Suez role made peacekeeping part of Canada’s modern story. At home he also oversaw the flag, the pension plan, and medicare negotiations.',
  },
  {
    id: 'mod-007',
    p: 'Federal multiculturalism became official policy in:',
    o: ['1867', '1918', '1971', '1999'],
    a: 'c',
    e: 'Pierre Trudeau’s government announced multiculturalism within a bilingual framework in 1971.',
  },
  {
    id: 'mod-008',
    p: 'The October Crisis of 1970 involved:',
    o: [
      'FLQ kidnappings and the use of the War Measures Act',
      'The last spike ceremony',
      'The founding of NATO',
      'The Persons Case',
    ],
    a: 'a',
    e: 'The Front de libération du Québec kidnapped officials. Ottawa invoked emergency powers—still a controversial moment.',
  },
  {
    id: 'mod-009',
    p: 'Quebec sovereignty referendums were held in:',
    o: ['1980 and 1995', '1867 and 1870', '1917 and 1944', '1608 and 1759'],
    a: 'a',
    e: 'Both votes rejected sovereignty (the 1995 “No” was very close). Quebec remains a province of Canada.',
  },
  {
    id: 'mod-010',
    t: 'tf',
    p: 'Canada is a founding member of the United Nations.',
    a: 'true',
    e: 'Canada helped found the UN in 1945 and has been active in its work, including peacekeeping and later missions.',
  },
  {
    id: 'mod-011',
    p: 'NORAD is:',
    o: [
      'A Canada–United States arrangement for aerospace warning and defence',
      'A provincial health plan',
      'The French name of the Senate',
      'A railway company',
    ],
    a: 'a',
    e: 'The North American Aerospace Defence Command dates from the late 1950s. It is a core military partnership with the United States.',
  },
  {
    id: 'mod-012',
    p: 'Canada belongs to the Commonwealth because:',
    o: [
      'It shares history with other former British territories and recognizes the same monarch as Head of the Commonwealth',
      'It is a U.S. state',
      'It left the UN',
      'It has no Constitution',
    ],
    a: 'a',
    e: 'Membership is voluntary. It is not a government that passes Canadian laws.',
  },
  {
    id: 'mod-013',
    p: 'La Francophonie is:',
    o: [
      'An international organization of French-speaking states and governments, which Canada joined',
      'A Quebec-only political party',
      'A type of maple syrup',
      'The name of the RCMP cavalry',
    ],
    a: 'a',
    e: 'Canada, Quebec, and New Brunswick all have roles in La Francophonie. It reflects the French fact in Canadian foreign policy.',
  },
  {
    id: 'mod-014',
    p: 'Old Age Security, the Canada Pension Plan, and Employment Insurance are examples of:',
    o: [
      'Social programs built mainly in the decades after the Second World War',
      'Confederation terms in 1867',
      'Municipal parking rules',
      'Senate seating plans',
    ],
    a: 'a',
    e: 'The postwar welfare state is a “modern Canada” topic: pensions, unemployment insurance, and later medicare.',
  },
  {
    id: 'mod-015',
    t: 'tf',
    p: 'Health-care delivery is a provincial responsibility, with federal funding tied to national standards.',
    a: 'true',
    e: 'Provinces run hospitals and medical insurance. Ottawa contributes money and sets conditions under federal law.',
  },
  {
    id: 'mod-016',
    p: 'After 1945, Canadian immigration policy gradually:',
    o: [
      'Moved away from racial preferences toward more universal criteria',
      'Banned all immigration',
      'Allowed only French speakers',
      'Returned to the Chinese head tax',
    ],
    a: 'a',
    e: 'The points system and later reforms opened the door more widely to people from Asia, the Caribbean, Africa, and Latin America.',
  },
  {
    id: 'mod-017',
    p: 'Canada fought in the Korean War:',
    o: ['As part of a United Nations force in the early 1950s', 'In 1867', 'Instead of joining NATO', 'Only with the War Measures Act'],
    a: 'a',
    e: 'Thousands of Canadians served in Korea (1950–53). It was Canada’s first UN-era shooting war.',
  },
  {
    id: 'mod-018',
    p: 'Free trade with the United States (and later Mexico) is a modern economic theme because:',
    o: [
      'The U.S. is Canada’s largest trading partner and supply chains cross the border',
      'Canada does not trade',
      'Only the territories export',
      'Trade is banned by the Charter',
    ],
    a: 'a',
    e: 'The study guide discusses North American free trade. The legal name of the agreement has changed; the integration has not.',
  },
  {
    id: 'mod-019',
    p: 'The maple leaf flag was adopted in:',
    o: ['1867', '1945', '1965', '1982'],
    a: 'c',
    e: 'Pearson’s government replaced the Canadian Red Ensign after a fierce flag debate. 1965 is a modern-Canada and symbols date.',
  },
  {
    id: 'mod-020',
    t: 'tf',
    p: 'Quebec did not sign the 1982 constitutional package, but it remains a province of Canada.',
    a: 'true',
    e: 'Patriation went ahead without Quebec’s signature. Later amendment attempts (Meech Lake, Charlottetown) failed.',
  },
  {
    id: 'mod-021',
    p: 'Meech Lake and Charlottetown were:',
    o: [
      'Failed attempts to amend the Constitution in 1990 and 1992',
      'World War II battles',
      'Gold rushes',
      'UN peacekeeping missions in Egypt only',
    ],
    a: 'a',
    e: 'They tried, among other things, to address Quebec’s place in the Constitution. Both failed.',
  },
  {
    id: 'mod-022',
    p: 'The Canada–U.S. Auto Pact (1965) mattered because it:',
    o: [
      'Integrated the two countries’ auto industries',
      'Banned car manufacturing',
      'Created the Senate',
      'Founded NATO',
    ],
    a: 'a',
    e: 'It is a classic example of postwar economic integration in central Canada’s manufacturing belt.',
  },
  {
    id: 'mod-023',
    p: 'Which scientist’s team in Canada is credited with the discovery of insulin (1921)?',
    o: ['Frederick Banting (with colleagues in Toronto)', 'Alexander Graham Bell only in 1867', 'Tommy Douglas', 'Wilfrid Laurier'],
    a: 'a',
    e: 'Insulin is a Canadian medical achievement the guide-era narrative still highlights.',
  },
  {
    id: 'mod-024',
    p: 'Terry Fox is remembered for:',
    o: [
      'The Marathon of Hope, running across Canada to raise money for cancer research',
      'Leading at Vimy',
      'Patriating the Constitution',
      'Founding the Hudson’s Bay Company',
    ],
    a: 'a',
    e: 'His 1980 run, cut short by cancer, became a national memory and an annual fundraising tradition.',
  },
  {
    id: 'mod-025',
    t: 'tf',
    p: 'Japanese-Canadian internment was later recognized as a wrong, with a formal apology and redress.',
    a: 'true',
    e: 'Brian Mulroney’s government apologized in 1988. Knowing both the wartime injustice and the later redress is part of modern citizenship.',
  },
  {
    id: 'mod-026',
    p: 'The Chinese head tax and later exclusion laws were:',
    o: [
      'Racist immigration measures that Canada later apologized for',
      'Ordinary municipal fees in 2000',
      'Charter requirements',
      'NATO contributions',
    ],
    a: 'a',
    e: 'They restricted Chinese immigration for decades. An apology came in 2006.',
  },
  {
    id: 'mod-027',
    p: 'Canada’s mission in Afghanistan after 2001 is an example of:',
    o: [
      'A 21st-century combat and reconstruction role, not only classic peacekeeping',
      'The War of 1812',
      'The Quiet Revolution',
      'The Klondike',
    ],
    a: 'a',
    e: 'Modern Canada still fights as well as peacekeeps. Kandahar was a hard combat mission.',
  },
  {
    id: 'mod-028',
    p: 'The Canada Council for the Arts (1957) reflects a modern decision to:',
    o: [
      'Fund literature, music, and the arts at the national level',
      'Abolish French',
      'Replace the Supreme Court',
      'Sell the Prairies',
    ],
    a: 'a',
    e: 'Postwar governments invested in culture as well as in pensions and hospitals.',
  },
  {
    id: 'mod-029',
    p: 'Which Prime Minister is most closely tied to the 1982 Charter?',
    o: ['Pierre Elliott Trudeau', 'Sir John A. Macdonald', 'R.B. Bennett', 'Alexander Mackenzie'],
    a: 'a',
    e: 'Trudeau made the Charter the centrepiece of patriation.',
  },
  {
    id: 'mod-030',
    t: 'tf',
    p: 'The Quiet Revolution made Quebec more secular in its public institutions.',
    a: 'true',
    e: 'Education and social services shifted from church-centred systems toward the provincial state.',
  },
  {
    id: 'mod-031',
    p: 'Refugee policy after the Second World War included a dark pre-history: in 1939 Canada famously:',
    o: [
      'Turned away the MS St. Louis, carrying Jewish refugees',
      'Founded Israel',
      'Banned all ocean travel',
      'Opened Nunavut',
    ],
    a: 'a',
    e: '“None is too many” is the phrase later used for that era’s anti-Jewish immigration practice. Modern Canada teaches it as a warning.',
  },
  {
    id: 'mod-032',
    p: 'The Official Languages Act requires federal institutions to:',
    o: [
      'Serve the public in English and French, where numbers warrant',
      'Use only English west of Ottawa',
      'Use only French in the Territories',
      'Ban Indigenous languages',
    ],
    a: 'a',
    e: 'It is about federal services and the workplace of the public service—not about erasing other languages in private life.',
  },
  {
    id: 'mod-033',
    p: 'Which of these is a social program created or expanded in modern Canada?',
    o: ['The Canada Pension Plan', 'The Quebec Act of 1774', 'The Hudson’s Bay monopoly', 'The Fenian raids'],
    a: 'a',
    e: 'CPP (and QPP in Quebec), OAS, EI, and medicare are the postwar package.',
  },
  {
    id: 'mod-034',
    t: 'tf',
    p: 'Canada is a member of La Francophonie and of the Commonwealth at the same time.',
    a: 'true',
    e: 'Those memberships reflect both British and French historical ties. They sit beside UN and NATO membership.',
  },
  {
    id: 'mod-035',
    p: 'The 1960s “points system” for immigrants was designed to:',
    o: [
      'Select newcomers by skills and other neutral criteria rather than by race',
      'Admit only British farmers',
      'End all immigration',
      'Replace elections',
    ],
    a: 'a',
    e: 'It is a landmark of modern immigration policy, even though discrimination did not vanish overnight.',
  },
  {
    id: 'mod-036',
    p: 'The Avro Arrow was:',
    o: [
      'A Canadian-designed interceptor jet cancelled in 1959',
      'A Confederation railway engine',
      'The first maple-leaf flag',
      'A Senate reform bill',
    ],
    a: 'a',
    e: 'Its cancellation is a modern-Canada industrial and political story, not a 19th-century one.',
  },
  {
    id: 'mod-037',
    p: 'Canada’s armed forces were unified in 1968 so that:',
    o: [
      'Navy, army, and air force were brought under one Canadian Forces structure',
      'The RCMP replaced the military',
      'NATO was dissolved',
      'Conscription became permanent',
    ],
    a: 'a',
    e: 'Unification is a Pearson/Trudeau-era defence reform. Distinct navy and air identities later returned in branding, but one force remains.',
  },
  {
    id: 'mod-038',
    t: 'tf',
    p: 'Expo 67 in Montreal was a world’s fair that marked Canada’s centennial year.',
    a: 'true',
    e: 'Centennial celebrations in 1967, including Expo, are a modern-Canada cultural landmark.'
  },
  {
    id: 'mod-039',
    p: 'The Clarity Act (2000) is about:',
    o: [
      'Rules for any future secession referendum and negotiation',
      'How to sing O Canada',
      'Municipal snow clearing',
      'The colour of the penny',
    ],
    a: 'a',
    e: 'After the close 1995 Quebec vote, Parliament set conditions for a clear question and a clear majority before talks.',
  },
  {
    id: 'mod-040',
    p: 'Same-sex marriage became legal across Canada in the 2000s through:',
    o: [
      'Court decisions and then a federal civil-marriage law',
      'The Quebec Act of 1774',
      'A 1867 Confederation term',
      'A municipal by-law in Whitehorse only',
    ],
    a: 'a',
    e: 'It is a modern equality-rights story, not a colonial one.',
  },
  {
    id: 'mod-041',
    p: 'The Canada Health Act is meant to:',
    o: [
      'Set national principles for insured health services that provinces must meet to receive full federal funding',
      'Put Ottawa in charge of every hospital’s daily staffing',
      'Abolish provincial health ministries',
      'Replace the Charter',
    ],
    a: 'a',
    e: 'Public administration, comprehensiveness, universality, portability, and accessibility are the usual principles. Delivery stays provincial.'
  },
  {
    id: 'mod-042',
    t: 'tf',
    p: 'The Canadian Broadcasting Corporation (CBC/Radio-Canada) is a public broadcaster created by Parliament.',
    a: 'true',
    e: 'It is a Crown corporation in culture and information, not a private cable shop and not a political party.'
  },
  {
    id: 'mod-043',
    p: 'The 1988 Winter Olympics in Calgary are an example of:',
    o: [
      'Modern Canada hosting the world and projecting a national image',
      'A Fathers of Confederation meeting',
      'The founding of New France',
      'The Statute of Westminster signing ceremony',
    ],
    a: 'a',
    e: 'Montreal 1976 (summer) and Calgary 1988 (winter) are the usual Olympic landmarks in the modern chapter.',
  },
  {
    id: 'mod-044',
    p: 'Residential-school survivors received a formal federal apology in:',
    o: ['2008', '1867', '1917', '1670'],
    a: 'a',
    e: 'Stephen Harper’s 2008 apology, and the Truth and Reconciliation Commission that followed, are modern-Canada facts.',
  },
  {
    id: 'mod-045',
    p: 'The GST (Goods and Services Tax) is:',
    o: [
      'A federal value-added tax introduced in the Mulroney era',
      'A type of Senate veto',
      'A provincial flower',
      'A NATO military rank',
    ],
    a: 'a',
    e: 'It replaced the old manufacturers’ sales tax. Provinces later harmonized in some regions.',
  },
  {
    id: 'mod-046',
    t: 'tf',
    p: 'Equalization is a federal program that transfers money so that provincial governments can offer reasonably comparable services.',
    a: 'true',
    e: 'It is in the Constitution’s commitment to comparable public services. It is not a municipal parking grant.',
  },
  {
    id: 'mod-047',
    p: 'Canada’s Constitution was “patriated” in 1982, which means:',
    o: [
      'Canada gained a domestic amending formula and no longer needed the British Parliament to change it',
      'Ottawa moved to Montreal',
      'The monarchy was abolished',
      'Quebec became independent',
    ],
    a: 'a',
    e: 'The Charter arrived in the same package. The Crown remained.',
  },
  {
    id: 'mod-048',
    p: 'The Group of Seven is best known for:',
    o: [
      'Paintings of the Canadian landscape in the early 20th century',
      'Writing the British North America Act',
      'Command at Vimy Ridge',
      'Founding NATO',
    ],
    a: 'a',
    e: 'They helped define a visual idea of Canada. Emily Carr is often taught alongside them, though she was not a member.'
  },
  {
    id: 'mod-049',
    p: 'The Emergencies Act replaced the old War Measures Act so that:',
    o: [
      'Emergency powers are narrower and more accountable to Parliament',
      'The Prime Minister can cancel elections forever',
      'Provinces disappear during a snowstorm',
      'The Charter is suspended automatically every winter',
    ],
    a: 'a',
    e: 'After the October Crisis, Canada redesigned emergency law. It is still exceptional, not a routine governing tool.'
  },
]);
