import { build } from './build.mjs';

export default build('modern-canada', 'Discover Canada — Modern Canada', [
  {
    id: 'mod-001',
    p: 'What was the Quiet Revolution in Quebec?',
    pf: 'Qu’a été la Révolution tranquille au Québec ?',
    o: [
      'A rapid period of social and government reform in the 1960s',
      'The building of the Canadian Pacific Railway',
      'The wartime internment of Japanese Canadians',
      'The founding of the Hudson’s Bay Company',
    ],
    of: [
      'Une période de réformes sociales et gouvernementales rapides, dans les années 1960',
      'La construction du chemin de fer Canadien Pacifique',
      'L’internement des Canadiens d’origine japonaise pendant la guerre',
      'La fondation de la Compagnie de la Baie d’Hudson',
    ],
    a: 'a',
    e: 'In the 1960s, Quebec modernized education, health care, and the provincial state, and a stronger Québécois identity took hold in public life.',
    ef: 'Dans les années 1960, le Québec a modernisé l’éducation, la santé et l’État provincial, et une identité québécoise plus affirmée s’est imposée dans la vie publique.',
  },
  {
    id: 'mod-002',
    t: 'tf',
    p: 'Canada is a founding member of the North Atlantic Treaty Organization (NATO).',
    pf: 'Le Canada est un membre fondateur de l’Organisation du Traité de l’Atlantique Nord (OTAN).',
    a: 'true',
    e: 'After the Second World War, Canada helped found NATO and also belongs to NORAD with the United States, as well as the United Nations and the Commonwealth.',
    ef: 'Après la Seconde Guerre mondiale, le Canada a contribué à fonder l’OTAN. Il fait aussi partie de NORAD avec les États-Unis, ainsi que des Nations Unies et du Commonwealth.',
  },
  {
    id: 'mod-003',
    p: 'Which law made English and French official languages of the Parliament and Government of Canada?',
    pf: 'Quelle loi a fait de l’anglais et du français les langues officielles du Parlement et du gouvernement du Canada ?',
    o: ['The War Measures Act', 'The Official Languages Act (1969)', 'The Manitoba Act', 'The Indian Act'],
    of: [
      'La Loi sur les mesures de guerre',
      'La Loi sur les langues officielles (1969)',
      'La Loi sur le Manitoba',
      'La Loi sur les Indiens',
    ],
    a: 'b',
    e: 'The Official Languages Act confirmed bilingual federal institutions. The Charter later entrenched official language rights more firmly.',
    ef: 'La Loi sur les langues officielles a confirmé le caractère bilingue des institutions fédérales. La Charte a ensuite enchâssé plus solidement les droits linguistiques.',
  },
  {
    id: 'mod-004',
    p: 'Publicly funded hospital and medical insurance in Canada was pioneered at the provincial level in:',
    pf: 'L’assurance hospitalisation et l’assurance maladie financées par l’État ont d’abord vu le jour, à l’échelle provinciale :',
    o: ['Saskatchewan, associated with Tommy Douglas', 'Prince Edward Island in 1864', 'Yukon during the gold rush', 'New France in 1608'],
    of: [
      'En Saskatchewan, sous l’impulsion de Tommy Douglas',
      'À l’Île-du-Prince-Édouard, en 1864',
      'Au Yukon, pendant la ruée vers l’or',
      'En Nouvelle-France, en 1608',
    ],
    a: 'a',
    e: 'Saskatchewan’s medical-care plan led the way. A federal–provincial model then spread nationwide.',
    ef: 'Le régime de soins médicaux de la Saskatchewan a ouvert la voie. Un modèle fédéral-provincial s’est ensuite étendu à tout le pays.',
  },
  {
    id: 'mod-005',
    p: 'The Canadian Bill of Rights (1960) is associated with Prime Minister:',
    pf: 'La Déclaration canadienne des droits (1960) est associée au premier ministre :',
    o: ['John Diefenbaker', 'Sir John A. Macdonald', 'Robert Borden', 'Lester B. Pearson’s successor in 1867'],
    of: [
      'John Diefenbaker',
      'Sir John A. Macdonald',
      'Robert Borden',
      'Le successeur de Lester B. Pearson en 1867',
    ],
    a: 'a',
    e: 'Diefenbaker’s Bill of Rights was a federal statute, not a constitutional charter. The 1982 Charter went further.',
    ef: 'La Déclaration des droits de Diefenbaker était une loi fédérale et non une charte constitutionnelle. La Charte de 1982 est allée beaucoup plus loin.',
  },
  {
    id: 'mod-006',
    p: 'Lester B. Pearson is remembered internationally for:',
    pf: 'Sur la scène internationale, on se souvient de Lester B. Pearson pour :',
    o: [
      'Helping create UN peacekeeping during the Suez Crisis (Nobel Peace Prize, 1957)',
      'Founding Quebec City',
      'Leading at Vimy Ridge',
      'Writing Magna Carta',
    ],
    of: [
      'Avoir contribué à créer le maintien de la paix de l’ONU lors de la crise de Suez (prix Nobel de la paix, 1957)',
      'Avoir fondé la ville de Québec',
      'Avoir commandé les troupes à la crête de Vimy',
      'Avoir rédigé la Grande Charte',
    ],
    a: 'a',
    e: 'Pearson’s Suez role made peacekeeping part of Canada’s modern story. At home he also oversaw the flag, the pension plan, and medicare negotiations.',
    ef: 'Le rôle de Pearson à Suez a fait du maintien de la paix un élément du récit canadien moderne. Au pays, il a aussi présidé à l’adoption du drapeau, à la création du régime de pensions et aux négociations sur l’assurance maladie.',
  },
  {
    id: 'mod-007',
    p: 'Federal multiculturalism became official policy in:',
    pf: 'Le multiculturalisme est devenu une politique officielle du gouvernement fédéral en :',
    o: ['1867', '1918', '1971', '1999'],
    of: ['1867', '1918', '1971', '1999'],
    a: 'c',
    e: 'Pierre Trudeau’s government announced multiculturalism within a bilingual framework in 1971.',
    ef: 'Le gouvernement de Pierre Trudeau a annoncé le multiculturalisme dans un cadre bilingue en 1971.',
  },
  {
    id: 'mod-008',
    p: 'The October Crisis of 1970 involved:',
    pf: 'La crise d’Octobre de 1970 a mis en cause :',
    o: [
      'FLQ kidnappings and the use of the War Measures Act',
      'The last spike ceremony',
      'The founding of NATO',
      'The Persons Case',
    ],
    of: [
      'Des enlèvements commis par le FLQ et le recours à la Loi sur les mesures de guerre',
      'La cérémonie du dernier crampon',
      'La fondation de l’OTAN',
      'L’affaire des « personnes »',
    ],
    a: 'a',
    e: 'The Front de libération du Québec kidnapped officials. Ottawa invoked emergency powers—still a controversial moment.',
    ef: 'Le Front de libération du Québec a enlevé des personnalités publiques. Ottawa a invoqué des pouvoirs d’urgence, un geste encore controversé aujourd’hui.',
  },
  {
    id: 'mod-009',
    p: 'Quebec sovereignty referendums were held in:',
    pf: 'Les référendums sur la souveraineté du Québec ont eu lieu en :',
    o: ['1980 and 1995', '1867 and 1870', '1917 and 1944', '1608 and 1759'],
    of: ['1980 et 1995', '1867 et 1870', '1917 et 1944', '1608 et 1759'],
    a: 'a',
    e: 'Both votes rejected sovereignty (the 1995 “No” was very close). Quebec remains a province of Canada.',
    ef: 'Les deux votes ont rejeté la souveraineté (le « Non » de 1995 a été très serré). Le Québec demeure une province du Canada.',
  },
  {
    id: 'mod-010',
    t: 'tf',
    p: 'Canada is a founding member of the United Nations.',
    pf: 'Le Canada est un membre fondateur des Nations Unies.',
    a: 'true',
    e: 'Canada helped found the UN in 1945 and has been active in its work, including peacekeeping and later missions.',
    ef: 'Le Canada a contribué à fonder l’ONU en 1945 et participe activement à ses travaux, y compris au maintien de la paix et aux missions plus récentes.',
  },
  {
    id: 'mod-011',
    p: 'NORAD is:',
    pf: 'NORAD est :',
    o: [
      'A Canada–United States arrangement for aerospace warning and defence',
      'A provincial health plan',
      'The French name of the Senate',
      'A railway company',
    ],
    of: [
      'Une entente entre le Canada et les États-Unis pour l’alerte et la défense aérospatiales',
      'Un régime provincial d’assurance maladie',
      'Le nom français du Sénat',
      'Une compagnie de chemin de fer',
    ],
    a: 'a',
    e: 'The North American Aerospace Defence Command dates from the late 1950s. It is a core military partnership with the United States.',
    ef: 'Le Commandement de la défense aérospatiale de l’Amérique du Nord date de la fin des années 1950. C’est un partenariat militaire central avec les États-Unis.',
  },
  {
    id: 'mod-012',
    p: 'Canada belongs to the Commonwealth because:',
    pf: 'Le Canada fait partie du Commonwealth parce que :',
    o: [
      'It shares history with other former British territories and recognizes the same monarch as Head of the Commonwealth',
      'It is a U.S. state',
      'It left the UN',
      'It has no Constitution',
    ],
    of: [
      'Il partage une histoire avec d’autres anciens territoires britanniques et reconnaît le même monarque comme chef du Commonwealth',
      'C’est un État américain',
      'Il a quitté l’ONU',
      'Il n’a pas de Constitution',
    ],
    a: 'a',
    e: 'Membership is voluntary. It is not a government that passes Canadian laws.',
    ef: 'L’adhésion est volontaire. Ce n’est pas un gouvernement qui adopte des lois canadiennes.',
  },
  {
    id: 'mod-013',
    p: 'La Francophonie is:',
    pf: 'La Francophonie est :',
    o: [
      'An international organization of French-speaking states and governments, which Canada joined',
      'A Quebec-only political party',
      'A type of maple syrup',
      'The name of the RCMP cavalry',
    ],
    of: [
      'Une organisation internationale d’États et de gouvernements de langue française, à laquelle le Canada a adhéré',
      'Un parti politique présent seulement au Québec',
      'Une sorte de sirop d’érable',
      'Le nom de la cavalerie de la GRC',
    ],
    a: 'a',
    e: 'Canada, Quebec, and New Brunswick all have roles in La Francophonie. It reflects the French fact in Canadian foreign policy.',
    ef: 'Le Canada, le Québec et le Nouveau-Brunswick y jouent tous un rôle. Elle traduit le fait français dans la politique étrangère canadienne.',
  },
  {
    id: 'mod-014',
    p: 'Old Age Security, the Canada Pension Plan, and Employment Insurance are examples of:',
    pf: 'La Sécurité de la vieillesse, le Régime de pensions du Canada et l’assurance-emploi sont des exemples :',
    o: [
      'Social programs built mainly in the decades after the Second World War',
      'Confederation terms in 1867',
      'Municipal parking rules',
      'Senate seating plans',
    ],
    of: [
      'De programmes sociaux bâtis surtout dans les décennies qui ont suivi la Seconde Guerre mondiale',
      'De conditions de la Confédération de 1867',
      'De règles municipales de stationnement',
      'De plans de sièges au Sénat',
    ],
    a: 'a',
    e: 'The postwar welfare state is a “modern Canada” topic: pensions, unemployment insurance, and later medicare.',
    ef: 'L’État-providence d’après-guerre est un sujet du « Canada moderne » : pensions, assurance-chômage et, plus tard, assurance maladie.',
  },
  {
    id: 'mod-015',
    t: 'tf',
    p: 'Health-care delivery is a provincial responsibility, with federal funding tied to national standards.',
    pf: 'La prestation des soins de santé relève des provinces, et le financement fédéral est assorti de normes nationales.',
    a: 'true',
    e: 'Provinces run hospitals and medical insurance. Ottawa contributes money and sets conditions under federal law.',
    ef: 'Les provinces gèrent les hôpitaux et l’assurance maladie. Ottawa verse des fonds et fixe des conditions en vertu d’une loi fédérale.',
  },
  {
    id: 'mod-016',
    p: 'After 1945, Canadian immigration policy gradually:',
    pf: 'Après 1945, la politique canadienne d’immigration s’est peu à peu :',
    o: [
      'Moved away from racial preferences toward more universal criteria',
      'Banned all immigration',
      'Allowed only French speakers',
      'Returned to the Chinese head tax',
    ],
    of: [
      'Éloignée des préférences raciales pour adopter des critères plus universels',
      'Fermée à toute immigration',
      'Limitée aux seuls francophones',
      'Ramenée à la taxe d’entrée imposée aux immigrants chinois',
    ],
    a: 'a',
    e: 'The points system and later reforms opened the door more widely to people from Asia, the Caribbean, Africa, and Latin America.',
    ef: 'Le système de points et les réformes suivantes ont ouvert la porte plus largement aux personnes venues d’Asie, des Caraïbes, d’Afrique et d’Amérique latine.',
  },
  {
    id: 'mod-017',
    p: 'Canada fought in the Korean War:',
    pf: 'Le Canada a combattu dans la guerre de Corée :',
    o: ['As part of a United Nations force in the early 1950s', 'In 1867', 'Instead of joining NATO', 'Only with the War Measures Act'],
    of: [
      'Au sein d’une force des Nations Unies, au début des années 1950',
      'En 1867',
      'Au lieu de se joindre à l’OTAN',
      'Uniquement en vertu de la Loi sur les mesures de guerre',
    ],
    a: 'a',
    e: 'Thousands of Canadians served in Korea (1950–53). It was Canada’s first UN-era shooting war.',
    ef: 'Des milliers de Canadiens ont servi en Corée (1950-1953). C’était le premier conflit armé auquel le Canada a participé à l’époque de l’ONU.',
  },
  {
    id: 'mod-018',
    p: 'Free trade with the United States (and later Mexico) is a modern economic theme because:',
    pf: 'Le libre-échange avec les États-Unis (puis avec le Mexique) est un thème économique moderne parce que :',
    o: [
      'The U.S. is Canada’s largest trading partner and supply chains cross the border',
      'Canada does not trade',
      'Only the territories export',
      'Trade is banned by the Charter',
    ],
    of: [
      'Les États-Unis sont le principal partenaire commercial du Canada et les chaînes d’approvisionnement traversent la frontière',
      'Le Canada ne fait pas de commerce',
      'Seuls les territoires exportent',
      'Le commerce est interdit par la Charte',
    ],
    a: 'a',
    e: 'The study guide discusses North American free trade. The legal name of the agreement has changed; the integration has not.',
    ef: 'Le guide d’étude traite du libre-échange nord-américain. Le nom officiel de l’accord a changé; l’intégration économique, non.',
  },
  {
    id: 'mod-019',
    p: 'The maple leaf flag was adopted in:',
    pf: 'Le drapeau à la feuille d’érable a été adopté en :',
    o: ['1867', '1945', '1965', '1982'],
    of: ['1867', '1945', '1965', '1982'],
    a: 'c',
    e: 'Pearson’s government replaced the Canadian Red Ensign after a fierce flag debate. 1965 is a modern-Canada and symbols date.',
    ef: 'Le gouvernement de Pearson a remplacé le Red Ensign canadien après un débat féroce sur le drapeau. 1965 est une date qui touche à la fois le Canada moderne et les symboles.',
  },
  {
    id: 'mod-020',
    t: 'tf',
    p: 'Quebec did not sign the 1982 constitutional package, but it remains a province of Canada.',
    pf: 'Le Québec n’a pas signé l’entente constitutionnelle de 1982, mais il demeure une province du Canada.',
    a: 'true',
    e: 'Patriation went ahead without Quebec’s signature. Later amendment attempts (Meech Lake, Charlottetown) failed.',
    ef: 'Le rapatriement a eu lieu sans la signature du Québec. Les tentatives de modification qui ont suivi (lac Meech, Charlottetown) ont échoué.',
  },
  {
    id: 'mod-021',
    p: 'Meech Lake and Charlottetown were:',
    pf: 'L’accord du lac Meech et celui de Charlottetown ont été :',
    o: [
      'Failed attempts to amend the Constitution in 1990 and 1992',
      'World War II battles',
      'Gold rushes',
      'UN peacekeeping missions in Egypt only',
    ],
    of: [
      'Des tentatives ratées de modifier la Constitution, en 1990 et en 1992',
      'Des batailles de la Seconde Guerre mondiale',
      'Des ruées vers l’or',
      'Des missions de maintien de la paix de l’ONU, en Égypte seulement',
    ],
    a: 'a',
    e: 'They tried, among other things, to address Quebec’s place in the Constitution. Both failed.',
    ef: 'Ils cherchaient notamment à régler la place du Québec dans la Constitution. Les deux ont échoué.',
  },
  {
    id: 'mod-022',
    p: 'The Canada–U.S. Auto Pact (1965) mattered because it:',
    pf: 'Le Pacte de l’automobile entre le Canada et les États-Unis (1965) a compté parce qu’il a :',
    o: [
      'Integrated the two countries’ auto industries',
      'Banned car manufacturing',
      'Created the Senate',
      'Founded NATO',
    ],
    of: [
      'Intégré les industries automobiles des deux pays',
      'Interdit la fabrication d’automobiles',
      'Créé le Sénat',
      'Fondé l’OTAN',
    ],
    a: 'a',
    e: 'It is a classic example of postwar economic integration in central Canada’s manufacturing belt.',
    ef: 'C’est un exemple classique de l’intégration économique d’après-guerre dans la ceinture manufacturière du centre du Canada.',
  },
  {
    id: 'mod-023',
    p: 'Which scientist’s team in Canada is credited with the discovery of insulin (1921)?',
    pf: 'Au Canada, l’équipe de quel scientifique est créditée de la découverte de l’insuline (1921) ?',
    o: ['Frederick Banting (with colleagues in Toronto)', 'Alexander Graham Bell only in 1867', 'Tommy Douglas', 'Wilfrid Laurier'],
    of: [
      'Frederick Banting (avec des collègues à Toronto)',
      'Alexander Graham Bell, seulement en 1867',
      'Tommy Douglas',
      'Wilfrid Laurier',
    ],
    a: 'a',
    e: 'Insulin is a Canadian medical achievement the guide-era narrative still highlights.',
    ef: 'L’insuline est une réussite médicale canadienne que le récit de l’époque du guide met encore en valeur.',
  },
  {
    id: 'mod-024',
    p: 'Terry Fox is remembered for:',
    pf: 'On se souvient de Terry Fox pour :',
    o: [
      'The Marathon of Hope, running across Canada to raise money for cancer research',
      'Leading at Vimy',
      'Patriating the Constitution',
      'Founding the Hudson’s Bay Company',
    ],
    of: [
      'Le Marathon de l’espoir, sa course à travers le Canada afin de recueillir des fonds pour la recherche sur le cancer',
      'Avoir commandé les troupes à Vimy',
      'Avoir rapatrié la Constitution',
      'Avoir fondé la Compagnie de la Baie d’Hudson',
    ],
    a: 'a',
    e: 'His 1980 run, cut short by cancer, became a national memory and an annual fundraising tradition.',
    ef: 'Sa course de 1980, interrompue par le cancer, est devenue un souvenir national et une tradition annuelle de collecte de fonds.',
  },
  {
    id: 'mod-025',
    t: 'tf',
    p: 'Japanese-Canadian internment was later recognized as a wrong, with a formal apology and redress.',
    pf: 'L’internement des Canadiens d’origine japonaise a plus tard été reconnu comme une injustice, avec des excuses officielles et des réparations.',
    a: 'true',
    e: 'Brian Mulroney’s government apologized in 1988. Knowing both the wartime injustice and the later redress is part of modern citizenship.',
    ef: 'Le gouvernement de Brian Mulroney a présenté des excuses en 1988. Connaître à la fois l’injustice commise en temps de guerre et les réparations qui ont suivi fait partie de la citoyenneté moderne.',
  },
  {
    id: 'mod-026',
    p: 'The Chinese head tax and later exclusion laws were:',
    pf: 'La taxe d’entrée imposée aux immigrants chinois et les lois d’exclusion qui ont suivi étaient :',
    o: [
      'Racist immigration measures that Canada later apologized for',
      'Ordinary municipal fees in 2000',
      'Charter requirements',
      'NATO contributions',
    ],
    of: [
      'Des mesures d’immigration racistes pour lesquelles le Canada s’est plus tard excusé',
      'De simples frais municipaux, en 2000',
      'Des exigences de la Charte',
      'Des contributions à l’OTAN',
    ],
    a: 'a',
    e: 'They restricted Chinese immigration for decades. An apology came in 2006.',
    ef: 'Elles ont restreint l’immigration chinoise pendant des décennies. Des excuses ont été présentées en 2006.',
  },
  {
    id: 'mod-027',
    p: 'Canada’s mission in Afghanistan after 2001 is an example of:',
    pf: 'La mission du Canada en Afghanistan après 2001 est un exemple :',
    o: [
      'A 21st-century combat and reconstruction role, not only classic peacekeeping',
      'The War of 1812',
      'The Quiet Revolution',
      'The Klondike',
    ],
    of: [
      'D’un rôle de combat et de reconstruction du XXIe siècle, et non seulement de maintien de la paix classique',
      'De la guerre de 1812',
      'De la Révolution tranquille',
      'Du Klondike',
    ],
    a: 'a',
    e: 'Modern Canada still fights as well as peacekeeps. Kandahar was a hard combat mission.',
    ef: 'Le Canada moderne combat encore, en plus de maintenir la paix. Kandahar a été une dure mission de combat.',
  },
  {
    id: 'mod-028',
    p: 'The Canada Council for the Arts (1957) reflects a modern decision to:',
    pf: 'Le Conseil des arts du Canada (1957) témoigne d’une décision moderne :',
    o: [
      'Fund literature, music, and the arts at the national level',
      'Abolish French',
      'Replace the Supreme Court',
      'Sell the Prairies',
    ],
    of: [
      'De financer la littérature, la musique et les arts à l’échelle nationale',
      'D’abolir le français',
      'De remplacer la Cour suprême',
      'De vendre les Prairies',
    ],
    a: 'a',
    e: 'Postwar governments invested in culture as well as in pensions and hospitals.',
    ef: 'Les gouvernements d’après-guerre ont investi dans la culture autant que dans les pensions et les hôpitaux.',
  },
  {
    id: 'mod-029',
    p: 'Which Prime Minister is most closely tied to the 1982 Charter?',
    pf: 'Quel premier ministre est le plus étroitement associé à la Charte de 1982 ?',
    o: ['Pierre Elliott Trudeau', 'Sir John A. Macdonald', 'R.B. Bennett', 'Alexander Mackenzie'],
    of: ['Pierre Elliott Trudeau', 'Sir John A. Macdonald', 'R.B. Bennett', 'Alexander Mackenzie'],
    a: 'a',
    e: 'Trudeau made the Charter the centrepiece of patriation.',
    ef: 'Trudeau a fait de la Charte la pièce maîtresse du rapatriement.',
  },
  {
    id: 'mod-030',
    t: 'tf',
    p: 'The Quiet Revolution made Quebec more secular in its public institutions.',
    pf: 'La Révolution tranquille a rendu les institutions publiques du Québec plus laïques.',
    a: 'true',
    e: 'Education and social services shifted from church-centred systems toward the provincial state.',
    ef: 'L’éducation et les services sociaux sont passés de réseaux dirigés par l’Église à l’État provincial.',
  },
  {
    id: 'mod-031',
    p: 'Refugee policy after the Second World War included a dark pre-history: in 1939 Canada famously:',
    pf: 'La politique d’accueil des réfugiés d’après-guerre a une sombre préhistoire : en 1939, le Canada a notamment :',
    o: [
      'Turned away the MS St. Louis, carrying Jewish refugees',
      'Founded Israel',
      'Banned all ocean travel',
      'Opened Nunavut',
    ],
    of: [
      'Refusé le MS St. Louis, qui transportait des réfugiés juifs',
      'Fondé Israël',
      'Interdit tout voyage en mer',
      'Ouvert le Nunavut',
    ],
    a: 'a',
    e: '“None is too many” is the phrase later used for that era’s anti-Jewish immigration practice. Modern Canada teaches it as a warning.',
    ef: '« Aucun, c’est encore trop » est la formule employée plus tard pour décrire la pratique d’immigration antijuive de cette époque. Le Canada moderne l’enseigne comme un avertissement.',
  },
  {
    id: 'mod-032',
    p: 'The Official Languages Act requires federal institutions to:',
    pf: 'La Loi sur les langues officielles oblige les institutions fédérales à :',
    o: [
      'Serve the public in English and French, where numbers warrant',
      'Use only English west of Ottawa',
      'Use only French in the Territories',
      'Ban Indigenous languages',
    ],
    of: [
      'Servir le public en anglais et en français là où la demande est importante',
      'N’utiliser que l’anglais à l’ouest d’Ottawa',
      'N’utiliser que le français dans les territoires',
      'Interdire les langues autochtones',
    ],
    a: 'a',
    e: 'It is about federal services and the workplace of the public service—not about erasing other languages in private life.',
    ef: 'Elle porte sur les services fédéraux et la langue de travail de la fonction publique, et non sur l’effacement des autres langues dans la vie privée.',
  },
  {
    id: 'mod-033',
    p: 'Which of these is a social program created or expanded in modern Canada?',
    pf: 'Lequel des éléments suivants est un programme social créé ou élargi dans le Canada moderne ?',
    o: ['The Canada Pension Plan', 'The Quebec Act of 1774', 'The Hudson’s Bay monopoly', 'The Fenian raids'],
    of: [
      'Le Régime de pensions du Canada',
      'L’Acte de Québec de 1774',
      'Le monopole de la Compagnie de la Baie d’Hudson',
      'Les raids des Fenians',
    ],
    a: 'a',
    e: 'CPP (and QPP in Quebec), OAS, EI, and medicare are the postwar package.',
    ef: 'Le RPC (et le RRQ au Québec), la Sécurité de la vieillesse, l’assurance-emploi et l’assurance maladie forment l’ensemble d’après-guerre.',
  },
  {
    id: 'mod-034',
    t: 'tf',
    p: 'Canada is a member of La Francophonie and of the Commonwealth at the same time.',
    pf: 'Le Canada est à la fois membre de la Francophonie et du Commonwealth.',
    a: 'true',
    e: 'Those memberships reflect both British and French historical ties. They sit beside UN and NATO membership.',
    ef: 'Ces adhésions reflètent les liens historiques tant britanniques que français. Elles s’ajoutent à l’appartenance à l’ONU et à l’OTAN.',
  },
  {
    id: 'mod-035',
    p: 'The 1960s “points system” for immigrants was designed to:',
    pf: 'Le « système de points » pour les immigrants, dans les années 1960, visait à :',
    o: [
      'Select newcomers by skills and other neutral criteria rather than by race',
      'Admit only British farmers',
      'End all immigration',
      'Replace elections',
    ],
    of: [
      'Sélectionner les nouveaux arrivants selon leurs compétences et d’autres critères neutres plutôt que selon la race',
      'N’admettre que des agriculteurs britanniques',
      'Mettre fin à toute immigration',
      'Remplacer les élections',
    ],
    a: 'a',
    e: 'It is a landmark of modern immigration policy, even though discrimination did not vanish overnight.',
    ef: 'C’est un jalon de la politique d’immigration moderne, même si la discrimination n’a pas disparu du jour au lendemain.',
  },
  {
    id: 'mod-036',
    p: 'The Avro Arrow was:',
    pf: 'L’Avro Arrow était :',
    o: [
      'A Canadian-designed interceptor jet cancelled in 1959',
      'A Confederation railway engine',
      'The first maple-leaf flag',
      'A Senate reform bill',
    ],
    of: [
      'Un avion intercepteur de conception canadienne, dont le projet a été annulé en 1959',
      'Une locomotive du chemin de fer de la Confédération',
      'Le premier drapeau à la feuille d’érable',
      'Un projet de loi sur la réforme du Sénat',
    ],
    a: 'a',
    e: 'Its cancellation is a modern-Canada industrial and political story, not a 19th-century one.',
    ef: 'Son annulation est une histoire industrielle et politique du Canada moderne, et non du XIXe siècle.',
  },
  {
    id: 'mod-037',
    p: 'Canada’s armed forces were unified in 1968 so that:',
    pf: 'Les forces armées du Canada ont été unifiées en 1968, de sorte que :',
    o: [
      'Navy, army, and air force were brought under one Canadian Forces structure',
      'The RCMP replaced the military',
      'NATO was dissolved',
      'Conscription became permanent',
    ],
    of: [
      'La marine, l’armée de terre et l’aviation ont été regroupées dans une seule structure, les Forces canadiennes',
      'La GRC a remplacé les militaires',
      'L’OTAN a été dissoute',
      'La conscription est devenue permanente',
    ],
    a: 'a',
    e: 'Unification is a Pearson/Trudeau-era defence reform. Distinct navy and air identities later returned in branding, but one force remains.',
    ef: 'L’unification est une réforme de la défense de l’ère Pearson-Trudeau. Des identités distinctes pour la marine et l’aviation sont revenues plus tard dans l’image de marque, mais la force demeure unique.',
  },
  {
    id: 'mod-038',
    t: 'tf',
    p: 'Expo 67 in Montreal was a world’s fair that marked Canada’s centennial year.',
    pf: 'Expo 67, à Montréal, était une exposition universelle qui a marqué l’année du centenaire du Canada.',
    a: 'true',
    e: 'Centennial celebrations in 1967, including Expo, are a modern-Canada cultural landmark.',
    ef: 'Les fêtes du centenaire de 1967, dont Expo, sont un repère culturel du Canada moderne.'
  },
  {
    id: 'mod-039',
    p: 'The Clarity Act (2000) is about:',
    pf: 'La Loi sur la clarté référendaire (2000) porte sur :',
    o: [
      'Rules for any future secession referendum and negotiation',
      'How to sing O Canada',
      'Municipal snow clearing',
      'The colour of the penny',
    ],
    of: [
      'Les règles encadrant tout futur référendum sur la sécession et les négociations qui suivraient',
      'La façon de chanter Ô Canada',
      'Le déneigement municipal',
      'La couleur de la pièce de un cent',
    ],
    a: 'a',
    e: 'After the close 1995 Quebec vote, Parliament set conditions for a clear question and a clear majority before talks.',
    ef: 'Après le vote serré de 1995 au Québec, le Parlement a fixé des conditions : une question claire et une majorité claire avant toute négociation.',
  },
  {
    id: 'mod-040',
    p: 'Same-sex marriage became legal across Canada in the 2000s through:',
    pf: 'Le mariage entre personnes de même sexe est devenu légal partout au Canada dans les années 2000 :',
    o: [
      'Court decisions and then a federal civil-marriage law',
      'The Quebec Act of 1774',
      'A 1867 Confederation term',
      'A municipal by-law in Whitehorse only',
    ],
    of: [
      'Par des décisions des tribunaux, puis par une loi fédérale sur le mariage civil',
      'Par l’Acte de Québec de 1774',
      'Par une condition de la Confédération de 1867',
      'Par un règlement municipal de Whitehorse seulement',
    ],
    a: 'a',
    e: 'It is a modern equality-rights story, not a colonial one.',
    ef: 'C’est une histoire moderne de droits à l’égalité, et non une histoire de l’époque coloniale.',
  },
  {
    id: 'mod-041',
    p: 'The Canada Health Act is meant to:',
    pf: 'La Loi canadienne sur la santé vise à :',
    o: [
      'Set national principles for insured health services that provinces must meet to receive full federal funding',
      'Put Ottawa in charge of every hospital’s daily staffing',
      'Abolish provincial health ministries',
      'Replace the Charter',
    ],
    of: [
      'Fixer des principes nationaux pour les services de santé assurés, que les provinces doivent respecter pour recevoir la pleine contribution fédérale',
      'Confier à Ottawa la gestion quotidienne du personnel de chaque hôpital',
      'Abolir les ministères provinciaux de la Santé',
      'Remplacer la Charte',
    ],
    a: 'a',
    e: 'Public administration, comprehensiveness, universality, portability, and accessibility are the usual principles. Delivery stays provincial.',
    ef: 'Gestion publique, intégralité, universalité, transférabilité et accessibilité sont les principes habituels. La prestation des services demeure provinciale.'
  },
  {
    id: 'mod-042',
    t: 'tf',
    p: 'The Canadian Broadcasting Corporation (CBC/Radio-Canada) is a public broadcaster created by Parliament.',
    pf: 'La Société Radio-Canada (CBC/Radio-Canada) est un radiodiffuseur public créé par le Parlement.',
    a: 'true',
    e: 'It is a Crown corporation in culture and information, not a private cable shop and not a political party.',
    ef: 'C’est une société d’État dans le domaine de la culture et de l’information, et non un câblodistributeur privé ni un parti politique.'
  },
  {
    id: 'mod-043',
    p: 'The 1988 Winter Olympics in Calgary are an example of:',
    pf: 'Les Jeux olympiques d’hiver de 1988, à Calgary, sont un exemple :',
    o: [
      'Modern Canada hosting the world and projecting a national image',
      'A Fathers of Confederation meeting',
      'The founding of New France',
      'The Statute of Westminster signing ceremony',
    ],
    of: [
      'Du Canada moderne qui accueille le monde et projette une image nationale',
      'D’une rencontre des Pères de la Confédération',
      'De la fondation de la Nouvelle-France',
      'De la cérémonie de signature du Statut de Westminster',
    ],
    a: 'a',
    e: 'Montreal 1976 (summer) and Calgary 1988 (winter) are the usual Olympic landmarks in the modern chapter.',
    ef: 'Montréal 1976 (été) et Calgary 1988 (hiver) sont les repères olympiques habituels du chapitre moderne.',
  },
  {
    id: 'mod-044',
    p: 'Residential-school survivors received a formal federal apology in:',
    pf: 'Les survivants des pensionnats ont reçu des excuses officielles du gouvernement fédéral en :',
    o: ['2008', '1867', '1917', '1670'],
    of: ['2008', '1867', '1917', '1670'],
    a: 'a',
    e: 'Stephen Harper’s 2008 apology, and the Truth and Reconciliation Commission that followed, are modern-Canada facts.',
    ef: 'Les excuses présentées par Stephen Harper en 2008, puis la Commission de vérité et réconciliation qui a suivi, sont des faits du Canada moderne.',
  },
  {
    id: 'mod-045',
    p: 'The GST (Goods and Services Tax) is:',
    pf: 'La TPS (taxe sur les produits et services) est :',
    o: [
      'A federal value-added tax introduced in the Mulroney era',
      'A type of Senate veto',
      'A provincial flower',
      'A NATO military rank',
    ],
    of: [
      'Une taxe fédérale sur la valeur ajoutée instaurée à l’époque de Mulroney',
      'Un type de veto du Sénat',
      'Une fleur provinciale',
      'Un grade militaire de l’OTAN',
    ],
    a: 'a',
    e: 'It replaced the old manufacturers’ sales tax. Provinces later harmonized in some regions.',
    ef: 'Elle a remplacé l’ancienne taxe de vente des fabricants. Certaines provinces l’ont ensuite harmonisée avec leur propre taxe.',
  },
  {
    id: 'mod-046',
    t: 'tf',
    p: 'Equalization is a federal program that transfers money so that provincial governments can offer reasonably comparable services.',
    pf: 'La péréquation est un programme fédéral qui transfère des fonds afin que les gouvernements provinciaux puissent offrir des services sensiblement comparables.',
    a: 'true',
    e: 'It is in the Constitution’s commitment to comparable public services. It is not a municipal parking grant.',
    ef: 'Elle découle de l’engagement constitutionnel envers des services publics comparables. Ce n’est pas une subvention municipale de stationnement.',
  },
  {
    id: 'mod-047',
    p: 'Canada’s Constitution was “patriated” in 1982, which means:',
    pf: 'La Constitution du Canada a été « rapatriée » en 1982, ce qui signifie que :',
    o: [
      'Canada gained a domestic amending formula and no longer needed the British Parliament to change it',
      'Ottawa moved to Montreal',
      'The monarchy was abolished',
      'Quebec became independent',
    ],
    of: [
      'Le Canada s’est doté d’une formule de modification interne et n’avait plus besoin du Parlement britannique pour la modifier',
      'Ottawa a déménagé à Montréal',
      'La monarchie a été abolie',
      'Le Québec est devenu indépendant',
    ],
    a: 'a',
    e: 'The Charter arrived in the same package. The Crown remained.',
    ef: 'La Charte est arrivée dans la même entente. La Couronne est demeurée.',
  },
  {
    id: 'mod-048',
    p: 'The Group of Seven is best known for:',
    pf: 'Le Groupe des Sept est surtout connu pour :',
    o: [
      'Paintings of the Canadian landscape in the early 20th century',
      'Writing the British North America Act',
      'Command at Vimy Ridge',
      'Founding NATO',
    ],
    of: [
      'Ses tableaux du paysage canadien, au début du XXe siècle',
      'Avoir rédigé l’Acte de l’Amérique du Nord britannique',
      'Le commandement à la crête de Vimy',
      'Avoir fondé l’OTAN',
    ],
    a: 'a',
    e: 'They helped define a visual idea of Canada. Emily Carr is often taught alongside them, though she was not a member.',
    ef: 'Ils ont aidé à définir une représentation visuelle du Canada. On enseigne souvent Emily Carr à leurs côtés, même si elle n’était pas membre du groupe.'
  },
  {
    id: 'mod-049',
    p: 'The Emergencies Act replaced the old War Measures Act so that:',
    pf: 'La Loi sur les mesures d’urgence a remplacé l’ancienne Loi sur les mesures de guerre afin que :',
    o: [
      'Emergency powers are narrower and more accountable to Parliament',
      'The Prime Minister can cancel elections forever',
      'Provinces disappear during a snowstorm',
      'The Charter is suspended automatically every winter',
    ],
    of: [
      'Les pouvoirs d’urgence soient plus restreints et davantage redevables au Parlement',
      'Le premier ministre puisse annuler les élections à jamais',
      'Les provinces disparaissent pendant une tempête de neige',
      'La Charte soit suspendue automatiquement chaque hiver',
    ],
    a: 'a',
    e: 'After the October Crisis, Canada redesigned emergency law. It is still exceptional, not a routine governing tool.',
    ef: 'Après la crise d’Octobre, le Canada a repensé son droit d’urgence. Il demeure exceptionnel et n’est pas un outil de gouvernance courant.'
  },
]);
