import { build } from './build.mjs';

export default build("canadas-regions", "Discover Canada — Canada's Regions", [
  {
    id: 'reg-001',
    p: 'What is the capital city of Canada?',
    o: ['Toronto', 'Ottawa', 'Vancouver', 'Montreal'],
    a: 'b',
    e: 'Ottawa, in Ontario, is the national capital and home to Parliament and many federal institutions.',
  },
  {
    id: 'reg-002',
    region: 'on',
    p: 'What is the capital of Ontario?',
    o: ['Ottawa', 'Hamilton', 'Toronto', 'London'],
    a: 'c',
    e: 'Toronto is Ontario’s capital and Canada’s largest city. Ottawa is the national capital, also located in Ontario.',
  },
  {
    id: 'reg-003',
    p: 'Which is Canada’s smallest province by land area?',
    o: ['Nova Scotia', 'Prince Edward Island', 'New Brunswick', 'Manitoba'],
    a: 'b',
    e: 'Prince Edward Island is the smallest province. It is known for agriculture, tourism, and being the birthplace of Confederation talks in 1864.',
  },
  {
    id: 'reg-004',
    p: 'Canada has how many provinces and territories?',
    o: ['Ten provinces and three territories', 'Thirteen provinces and no territories', 'Five provinces and five territories', 'Nine provinces and one territory'],
    a: 'a',
    e: 'Ten provinces have constitutional status of their own. Three territories were created by federal statute.',
  },
  {
    id: 'reg-005',
    p: 'In the study guide’s grouping, Atlantic Canada includes:',
    o: [
      'Newfoundland and Labrador, Prince Edward Island, Nova Scotia, and New Brunswick',
      'Quebec and Ontario',
      'Manitoba, Saskatchewan, and Alberta',
      'Yukon, Northwest Territories, and Nunavut',
    ],
    a: 'a',
    e: 'Those four provinces face the Atlantic. Quebec is Central Canada in the guide, not Atlantic.',
  },
  {
    id: 'reg-006',
    p: 'Central Canada, in the official study-guide regions, means:',
    o: ['Quebec and Ontario', 'Manitoba and Saskatchewan', 'Only Toronto', 'The three territories'],
    a: 'a',
    e: 'It is a population and history grouping, not “the geographic centre of the map.”',
  },
  {
    id: 'reg-007',
    p: 'The Prairie provinces are:',
    o: ['Manitoba, Saskatchewan, and Alberta', 'B.C., Yukon, and Alberta', 'Ontario, Quebec, and Manitoba', 'Nova Scotia, PEI, and New Brunswick'],
    a: 'a',
    e: 'They sit between the Shield and the Rockies. All three joined after 1867.',
  },
  {
    id: 'reg-008',
    p: 'The West Coast region in the guide is:',
    o: ['British Columbia', 'Yukon', 'Alberta', 'Manitoba'],
    a: 'a',
    e: 'Yukon is grouped with the Northern Territories, not with the West Coast region.',
  },
  {
    id: 'reg-009',
    p: 'The Northern Territories are:',
    o: ['Yukon, Northwest Territories, and Nunavut', 'Labrador, Yukon, and PEI', 'NWT, Manitoba, and Nunavut', 'Yukon, B.C., and Alaska'],
    a: 'a',
    e: 'Three territories, vast land, small populations.',
  },
  {
    id: 'reg-010',
    t: 'tf',
    p: 'Most Canadians live within a few hundred kilometres of the United States border.',
    a: 'true',
    e: 'The populated belt is southern and thin. The North is huge and sparsely peopled.',
  },
  {
    id: 'reg-011',
    p: 'The five Great Lakes include:',
    o: [
      'Superior, Michigan, Huron, Erie, and Ontario',
      'Winnipeg, Athabasca, Great Slave, Great Bear, and Ontario',
      'Ontario, Erie, Champlain, Simcoe, and Nipissing',
      'Michigan, Superior, Winnipeg, Erie, and Huron only four names',
    ],
    a: 'a',
    e: 'They drain to the Atlantic via the St. Lawrence. Michigan is shared with the United States.',
  },
  {
    id: 'reg-012',
    p: 'The Canadian Shield is:',
    o: [
      'A vast rocky region rich in forests and minerals around Hudson Bay',
      'A police badge',
      'The roof of the Peace Tower',
      'A prairie grassland only',
    ],
    a: 'a',
    e: 'It covers much of Quebec, Ontario, Manitoba, and the Territories. Mining and hydro are classic Shield economies.',
  },
  {
    id: 'reg-013',
    p: 'The Cordillera is:',
    o: ['The western mountain system', 'A river in PEI', 'A Toronto neighbourhood', 'The Senate’s Latin name'],
    a: 'a',
    e: 'The Rockies and Coast Mountains dominate British Columbia and stretch into Alberta and the Yukon.',
  },
  {
    id: 'reg-014',
    region: 'qc',
    p: 'What is the capital of Quebec?',
    o: ['Montreal', 'Quebec City', 'Gatineau', 'Sherbrooke'],
    a: 'b',
    e: 'Quebec City is the capital. Montreal is the largest city. Mixing them is a classic test trap.',
  },
  {
    id: 'reg-015',
    region: 'qc',
    p: 'Which city is Quebec’s metropolis and Canada’s largest French-speaking city?',
    o: ['Montreal', 'Quebec City', 'Trois-Rivières', 'Ottawa'],
    a: 'a',
    e: 'Montreal is the economic and cultural giant. Quebec City is the political capital, founded in 1608.',
  },
  {
    id: 'reg-016',
    region: 'bc',
    p: 'What is the capital of British Columbia?',
    o: ['Vancouver', 'Victoria', 'Kelowna', 'Prince George'],
    a: 'b',
    e: 'Victoria, on Vancouver Island, is the capital. Vancouver is the largest city and main port.',
  },
  {
    id: 'reg-017',
    region: 'bc',
    p: 'British Columbia joined Confederation in 1871 after a promise of:',
    o: ['A transcontinental railway', 'Immediate Senate seats for every village', 'Free ferries forever with no terms', 'Official status for Spanish'],
    a: 'a',
    e: 'The railway bound the Pacific province to Canada. Vancouver later became the great Pacific gateway.',
  },
  {
    id: 'reg-018',
    region: 'ab',
    p: 'What is the capital of Alberta?',
    o: ['Calgary', 'Edmonton', 'Red Deer', 'Lethbridge'],
    a: 'b',
    e: 'Edmonton is the capital. Calgary is the largest city. Energy and agriculture define much of the economy.',
  },
  {
    id: 'reg-019',
    region: 'ab',
    p: 'Alberta’s largest city is:',
    o: ['Edmonton', 'Calgary', 'Banff', 'Fort McMurray'],
    a: 'b',
    e: 'Calgary is larger; Edmonton is the seat of government. The Rockies lie on the B.C. boundary.',
  },
  {
    id: 'reg-020',
    region: 'sk',
    p: 'What is the capital of Saskatchewan?',
    o: ['Saskatoon', 'Regina', 'Moose Jaw', 'Prince Albert'],
    a: 'b',
    e: 'Regina is the capital. Saskatoon is the largest city. Wheat and potash are classic study-guide hooks.',
  },
  {
    id: 'reg-021',
    region: 'sk',
    p: 'Saskatchewan is especially associated with:',
    o: ['Grain farming and potash', 'Pacific shipping', 'Cod stocks', 'The national capital'],
    a: 'a',
    e: 'It is also the birthplace of a major strain of Canadian social democracy, including early public hospital insurance.',
  },
  {
    id: 'reg-022',
    region: 'mb',
    p: 'What is the capital of Manitoba?',
    o: ['Brandon', 'Winnipeg', 'Churchill', 'Thompson'],
    a: 'b',
    e: 'Winnipeg sits at the forks of the Red and Assiniboine. Red River Métis history is central to the province’s entry into Canada.',
  },
  {
    id: 'reg-023',
    region: 'mb',
    p: 'Manitoba entered Confederation in 1870 after:',
    o: ['The Red River Resistance and the Manitoba Act', 'The Klondike gold rush', 'D-Day', 'The Quiet Revolution'],
    a: 'a',
    e: 'Louis Riel and the Métis provisional government are part of that founding story.',
  },
  {
    id: 'reg-024',
    region: 'ns',
    p: 'What is the capital of Nova Scotia?',
    o: ['Halifax', 'Sydney', 'Yarmouth', 'Lunenburg'],
    a: 'a',
    e: 'Halifax is the largest Atlantic city and a major port, with a long military and naval history.',
  },
  {
    id: 'reg-025',
    region: 'nb',
    p: 'What is the capital of New Brunswick?',
    o: ['Saint John', 'Moncton', 'Fredericton', 'Bathurst'],
    a: 'c',
    e: 'Fredericton is the capital. New Brunswick is the only officially bilingual province, with a large Acadian population.',
  },
  {
    id: 'reg-026',
    region: 'nb',
    p: 'Which is the only officially bilingual province?',
    o: ['Quebec', 'New Brunswick', 'Ontario', 'Manitoba'],
    a: 'b',
    e: 'Quebec’s official language is French. Federally, Canada is bilingual. Among provinces, only New Brunswick is officially bilingual.',
  },
  {
    id: 'reg-027',
    region: 'pe',
    p: 'What is the capital of Prince Edward Island?',
    o: ['Summerside', 'Charlottetown', 'Cavendish', 'Georgetown'],
    a: 'b',
    e: 'Charlottetown hosted the 1864 conference that began Confederation talks. PEI joined Canada in 1873.',
  },
  {
    id: 'reg-028',
    region: 'nl',
    p: 'What is the capital of Newfoundland and Labrador?',
    o: ['Corner Brook', 'Happy Valley-Goose Bay', "St. John's", 'Gander'],
    a: 'c',
    e: 'St. John’s is one of the oldest European-founded cities in North America. The province joined Canada in 1949.',
  },
  {
    id: 'reg-029',
    region: 'nl',
    p: 'Newfoundland and Labrador consists of:',
    o: [
      'An island (Newfoundland) plus a mainland region (Labrador)',
      'Only an Arctic archipelago',
      'Only Prairie farmland',
      'Only Vancouver Island',
    ],
    a: 'a',
    e: 'Labrador is on the mainland next to Quebec. Newfoundland time is a half-hour ahead of Atlantic time.',
  },
  {
    id: 'reg-030',
    region: 'yt',
    p: 'What is the capital of Yukon?',
    o: ['Dawson City', 'Whitehorse', 'Watson Lake', 'Yellowknife'],
    a: 'b',
    e: 'Whitehorse is the capital. Dawson is tied to the Klondike Gold Rush of the late 1890s.',
  },
  {
    id: 'reg-031',
    region: 'yt',
    p: 'Yukon’s classic historic event in the study guide is:',
    o: ['The Klondike Gold Rush', 'The Quiet Revolution', 'The Dieppe raid', 'The Charlottetown Conference'],
    a: 'a',
    e: 'The rush brought a stampede of prospectors and made the territory famous.',
  },
  {
    id: 'reg-032',
    region: 'nt',
    p: 'What is the capital of the Northwest Territories?',
    o: ['Inuvik', 'Hay River', 'Yellowknife', 'Iqaluit'],
    a: 'c',
    e: 'Yellowknife sits on Great Slave Lake. Diamonds, gold, and public administration are economic pillars.',
  },
  {
    id: 'reg-033',
    region: 'nu',
    p: 'What is the capital of Nunavut?',
    o: ['Rankin Inlet', 'Iqaluit', 'Cambridge Bay', 'Yellowknife'],
    a: 'b',
    e: 'Iqaluit is the capital. Nunavut was created in 1999 from the eastern Northwest Territories.',
  },
  {
    id: 'reg-034',
    region: 'nu',
    p: 'Nunavut was created in:',
    o: ['1867', '1949', '1999', '1927'],
    a: 'c',
    e: 'It is a majority-Inuit territory. Inuktut languages are central to public life. Many communities are fly-in.',
  },
  {
    id: 'reg-035',
    t: 'tf',
    p: 'Nunavut is a province.',
    a: 'false',
    e: 'It is a territory. That legal distinction still matters, even as territorial governments run most daily services.',
  },
  {
    id: 'reg-036',
    p: 'Which province has the largest population?',
    o: ['Quebec', 'Ontario', 'British Columbia', 'Alberta'],
    a: 'b',
    e: 'Ontario is the most populous. Quebec is second. Population, not land area, drives House of Commons seat counts.',
  },
  {
    id: 'reg-037',
    p: 'Which is the largest province by land area?',
    o: ['Ontario', 'Quebec', 'British Columbia', 'Alberta'],
    a: 'b',
    e: 'Quebec is the largest province. Nunavut is larger still, but it is a territory.',
  },
  {
    id: 'reg-038',
    p: 'The St. Lawrence River is historically important as:',
    o: [
      'The highway from the Atlantic into the interior of the continent',
      'A prairie creek',
      'A Yukon gold stream only',
      'A British Columbia fjord only',
    ],
    a: 'a',
    e: 'New France, Montreal, Quebec City, and later the Seaway all sit on this system.',
  },
  {
    id: 'reg-039',
    p: 'Niagara Falls lies on the border of:',
    o: ['Ontario and the United States', 'B.C. and Alaska', 'Manitoba and Nunavut', 'PEI and New Brunswick'],
    a: 'a',
    e: 'It is a hydroelectric and tourism landmark of the Great Lakes–St. Lawrence system.',
  },
  {
    id: 'reg-040',
    region: 'on',
    p: 'Ottawa is in Ontario, but the National Capital Region also includes:',
    o: ['Gatineau, Quebec, across the river', 'Winnipeg', 'Halifax', 'Victoria'],
    a: 'a',
    e: 'Federal institutions sit on both sides of the Ottawa River. Do not call Gatineau the national capital.',
  },
  {
    id: 'reg-041',
    region: 'pe',
    p: 'Prince Edward Island is linked to the mainland by:',
    o: ['The Confederation Bridge (and also by ferry)', 'A subway to Montreal', 'A rail tunnel to Yukon', 'A dam across Hudson Bay'],
    a: 'a',
    e: 'The bridge is a modern fact; the 1864 talks are the historic one. Agriculture and tourism remain economic staples.',
  },
  {
    id: 'reg-042',
    region: 'ns',
    p: 'Nova Scotia’s name means:',
    o: ['New Scotland', 'New France', 'New Ireland', 'New Wales'],
    a: 'a',
    e: 'Scottish settlement, the Halifax port, Acadian communities, and Black Loyalist history all mark the province.',
  },
  {
    id: 'reg-043',
    p: 'Which region is sparsely populated, strategically important in the Arctic, and home to Inuit and other northern peoples?',
    o: ['The North', 'Prince Edward Island’s interior cities', 'Downtown Toronto', 'The Niagara fruit belt only'],
    a: 'a',
    e: 'Permafrost, fly-in communities, and sovereignty issues are part of the northern story.',
  },
  {
    id: 'reg-044',
    t: 'tf',
    p: 'Toronto is the capital of Canada.',
    a: 'false',
    e: 'Toronto is Ontario’s capital and the largest city. Ottawa is the national capital.',
  },
  {
    id: 'reg-045',
    p: 'Hudson Bay is bordered by:',
    o: [
      'Several provinces and territories, with the Shield around much of it',
      'Only British Columbia',
      'Only Prince Edward Island',
      'Only the island of Newfoundland',
    ],
    a: 'a',
    e: 'It is a geographic centre of gravity for the Shield and for historic fur-trade routes.',
  },
  {
    id: 'reg-046',
    region: 'bc',
    p: 'Vancouver is important as:',
    o: ['A major Pacific port and B.C.’s largest city', 'The provincial capital', 'The national capital', 'Nunavut’s seaport'],
    a: 'a',
    e: 'Victoria is the capital. Vancouver is the metropolis and a gateway to Asia-Pacific trade.',
  },
  {
    id: 'reg-047',
    p: 'Which province is an original 1867 member and remains the heart of French-speaking North America?',
    o: ['Quebec', 'Alberta', 'Saskatchewan', 'Newfoundland and Labrador'],
    a: 'a',
    e: 'Quebec was Canada East. Its civil law, language, and national capital (Quebec City) are core regional facts.',
  },
  {
    id: 'reg-048',
    region: 'on',
    p: 'Southern Ontario’s economy has long included:',
    o: ['Manufacturing (including autos) and services', 'Only Arctic mining', 'Only offshore oil', 'Only potato farming'],
    a: 'a',
    e: 'The Golden Horseshoe around Toronto is one of the country’s main industrial and service regions.',
  },
  {
    id: 'reg-049',
    t: 'tf',
    p: 'Territories have commissioners rather than lieutenant governors.',
    a: 'true',
    e: 'The Crown’s provincial representative is a Lieutenant Governor. Territorial commissioners are a different office.',
  },
  {
    id: 'reg-050',
    p: 'If a citizenship question asks about “your region,” it often wants:',
    o: [
      'Your province or territory’s capital and a local geographic or historic hook',
      'The name of your landlord',
      'Your federal riding’s polling-station number only',
      'The Mayor of Ottawa in every case',
    ],
    a: 'a',
    e: 'National facts first, then lock in your capital city and one distinctive fact. This app tags such items by province code.',
  },
  {
    id: 'reg-051',
    region: 'pe',
    p: 'Prince Edward Island is especially known for:',
    o: ['Potato farming and a compact agricultural landscape', 'Oil sands only', 'Arctic diamond mines', 'Coastal rainforests of cedar only'],
    a: 'a',
    e: 'It is Canada’s smallest province. Potatoes, tourism, and Confederation history are the usual hooks.',
  },
  {
    id: 'reg-052',
    region: 'nb',
    p: 'New Brunswick’s landscape and economy have long included:',
    o: ['Acadian communities, forests, and the Bay of Fundy tides', 'Only prairie wheat', 'Only Inuit hamlets', 'Only auto assembly in Windsor'],
    a: 'a',
    e: 'It is the only officially bilingual province. Forestry and the Fundy coast are classic geography.',
  },
  {
    id: 'reg-053',
    region: 'nl',
    p: 'Newfoundland and Labrador’s historic staple was:',
    o: ['The Atlantic fishery (especially cod)', 'Prairie potash only', 'Ontario auto parts only', 'B.C. wine only'],
    a: 'a',
    e: 'The fishery shaped settlement. Offshore oil is a later chapter; Labrador adds mines and hydro.',
  },
  {
    id: 'reg-054',
    region: 'ns',
    p: 'Halifax is important in Canadian geography as:',
    o: [
      'A major Atlantic port and historic naval and immigration harbour',
      'The capital of Canada',
      'The capital of Alberta',
      'A prairie railway town only',
    ],
    a: 'a',
    e: 'The Citadel overlooks a year-round ice-free harbour. It is Nova Scotia’s capital and the Maritimes’ largest city.',
  },
  {
    id: 'reg-055',
    region: 'qc',
    p: 'Large hydroelectric projects in northern Quebec (including the James Bay area) matter because they:',
    o: [
      'Supply much of Quebec’s electricity and export power',
      'Are Ontario’s only oil sands',
      'Replaced the St. Lawrence River',
      'Are Yukon’s territorial assembly',
    ],
    a: 'a',
    e: 'Hydro is a Quebec economic signature. It also raised lasting Indigenous-rights issues.',
  },
  {
    id: 'reg-056',
    region: 'on',
    p: 'The Niagara fruit belt and wine region lie in:',
    o: ['Southern Ontario, between the lakes', 'Nunavut', 'Northern Labrador', 'The Yukon gold fields'],
    a: 'a',
    e: 'Mild lakeshore climate is an Ontario geography fact beyond Toronto and Ottawa.',
  },
  {
    id: 'reg-057',
    region: 'mb',
    p: 'Winnipeg has historically been called a gateway because it:',
    o: [
      'Sits where eastern rail and western Prairie routes meet',
      'Is Canada’s Pacific port',
      'Is the capital of Nova Scotia',
      'Lies on the Alaska Highway start in Dawson only',
    ],
    a: 'a',
    e: 'The Forks, the railway, and later air links made it a prairie hub. It is Manitoba’s capital.',
  },
  {
    id: 'reg-058',
    region: 'sk',
    p: 'Uranium mining is especially associated with:',
    o: ['Northern Saskatchewan', 'Prince Edward Island beaches only', 'Downtown Halifax', 'The Ottawa River islands only'],
    a: 'a',
    e: 'The Canadian Shield in the north holds major mines. Grain remains the southern Prairie story.',
  },
  {
    id: 'reg-059',
    region: 'ab',
    p: 'The Calgary Stampede is:',
    o: [
      'A famous western festival and rodeo that has become an Alberta cultural emblem',
      'The name of the Alberta legislature',
      'A Confederation conference of 1864',
      'Yukon’s capital',
    ],
    a: 'a',
    e: 'Oil and cattle both shape Alberta’s image. The Stampede is the cultural postcard; Edmonton is the capital.',
  },
  {
    id: 'reg-060',
    region: 'bc',
    p: 'Pacific salmon and mountain forests are especially associated with:',
    o: ['British Columbia', 'Prince Edward Island only', 'Saskatchewan wheat pools only', 'Nunavut hamlets only'],
    a: 'a',
    e: 'The Cordillera plus a mild coast define B.C. Vancouver is the big port; Victoria is the capital.',
  },
  {
    id: 'reg-061',
    region: 'yt',
    p: 'The Alaska Highway is a northern geography fact because it:',
    o: [
      'Links British Columbia and Yukon toward Alaska, built in the Second World War',
      'Crosses PEI on the Confederation Bridge',
      'Is Ottawa’s main street',
      'Is a subway in Montreal',
    ],
    a: 'a',
    e: 'Wartime building opened the northwest. Whitehorse is Yukon’s capital.',
  },
  {
    id: 'reg-062',
    region: 'nt',
    p: 'Yellowknife grew as a modern capital especially because of:',
    o: ['Gold, and later diamond, mining plus government', 'Potato farming like PEI', 'The auto pact plants', 'The Halifax Citadel'],
    a: 'a',
    e: 'It sits on Great Slave Lake. The Northwest Territories’ legislature is there, not in Ottawa.',
  },
  {
    id: 'reg-063',
    region: 'nu',
    p: 'Iqaluit is:',
    o: [
      'The capital of Nunavut, on Baffin Island',
      'The capital of Ontario',
      'A prairie wheat pool headquarters',
      'New Brunswick’s only city',
    ],
    a: 'a',
    e: 'Nunavut is majority Inuit. Iqaluit is the political centre created when the territory was born in 1999.',
  },
  {
    id: 'reg-064',
    t: 'tf',
    p: 'The Great Lakes–St. Lawrence system is a shared Ontario–Quebec (and U.S.) water highway for cities, industry, and shipping.',
    a: 'true',
    e: 'It is the core of central Canada’s geography. The Seaway lets ocean ships reach inland ports.',
  },
]);
