import { build } from './build.mjs';

export default build("canadas-regions", "Discover Canada — Canada's Regions", [
  {
    id: 'reg-001',
    p: 'What is the capital city of Canada?',
    pf: 'Quelle est la capitale du Canada?',
    o: ['Toronto', 'Ottawa', 'Vancouver', 'Montreal'],
    of: ['Toronto', 'Ottawa', 'Vancouver', 'Montréal'],
    a: 'b',
    e: 'Ottawa, in Ontario, is the national capital and home to Parliament and many federal institutions.',
    ef: 'Ottawa, en Ontario, est la capitale nationale : on y trouve le Parlement et de nombreuses institutions fédérales.',
  },
  {
    id: 'reg-002',
    region: 'on',
    p: 'What is the capital of Ontario?',
    pf: 'Quelle est la capitale de l’Ontario?',
    o: ['Ottawa', 'Hamilton', 'Toronto', 'London'],
    of: ['Ottawa', 'Hamilton', 'Toronto', 'London'],
    a: 'c',
    e: 'Toronto is Ontario’s capital and Canada’s largest city. Ottawa is the national capital, also located in Ontario.',
    ef: 'Toronto est la capitale de l’Ontario et la plus grande ville du Canada. Ottawa, la capitale nationale, se trouve aussi en Ontario.',
  },
  {
    id: 'reg-003',
    p: 'Which is Canada’s smallest province by land area?',
    pf: 'Quelle est la plus petite province du Canada par sa superficie?',
    o: ['Nova Scotia', 'Prince Edward Island', 'New Brunswick', 'Manitoba'],
    of: ['La Nouvelle-Écosse', 'L’Île-du-Prince-Édouard', 'Le Nouveau-Brunswick', 'Le Manitoba'],
    a: 'b',
    e: 'Prince Edward Island is the smallest province. It is known for agriculture, tourism, and being the birthplace of Confederation talks in 1864.',
    ef: 'L’Île-du-Prince-Édouard est la plus petite province. Elle est connue pour son agriculture, son tourisme et pour avoir accueilli les premiers pourparlers de la Confédération en 1864.',
  },
  {
    id: 'reg-004',
    p: 'Canada has how many provinces and territories?',
    pf: 'Combien de provinces et de territoires compte le Canada?',
    o: ['Ten provinces and three territories', 'Thirteen provinces and no territories', 'Five provinces and five territories', 'Nine provinces and one territory'],
    of: ['Dix provinces et trois territoires', 'Treize provinces et aucun territoire', 'Cinq provinces et cinq territoires', 'Neuf provinces et un territoire'],
    a: 'a',
    e: 'Ten provinces have constitutional status of their own. Three territories were created by federal statute.',
    ef: 'Les dix provinces possèdent leur propre statut constitutionnel. Les trois territoires ont été créés par une loi fédérale.',
  },
  {
    id: 'reg-005',
    p: 'In the study guide’s grouping, Atlantic Canada includes:',
    pf: 'Selon le regroupement du guide d’étude, le Canada atlantique comprend :',
    o: [
      'Newfoundland and Labrador, Prince Edward Island, Nova Scotia, and New Brunswick',
      'Quebec and Ontario',
      'Manitoba, Saskatchewan, and Alberta',
      'Yukon, Northwest Territories, and Nunavut',
    ],
    of: [
      'Terre-Neuve-et-Labrador, l’Île-du-Prince-Édouard, la Nouvelle-Écosse et le Nouveau-Brunswick',
      'Le Québec et l’Ontario',
      'Le Manitoba, la Saskatchewan et l’Alberta',
      'Le Yukon, les Territoires du Nord-Ouest et le Nunavut',
    ],
    a: 'a',
    e: 'Those four provinces face the Atlantic. Quebec is Central Canada in the guide, not Atlantic.',
    ef: 'Ces quatre provinces bordent l’Atlantique. Dans le guide, le Québec fait partie du Canada central et non de la région atlantique.',
  },
  {
    id: 'reg-006',
    p: 'Central Canada, in the official study-guide regions, means:',
    pf: 'Dans les régions du guide d’étude officiel, le Canada central désigne :',
    o: ['Quebec and Ontario', 'Manitoba and Saskatchewan', 'Only Toronto', 'The three territories'],
    of: ['Le Québec et l’Ontario', 'Le Manitoba et la Saskatchewan', 'Toronto seulement', 'Les trois territoires'],
    a: 'a',
    e: 'It is a population and history grouping, not “the geographic centre of the map.”',
    ef: 'Il s’agit d’un regroupement fondé sur la population et l’histoire, et non du « centre géographique de la carte ».',
  },
  {
    id: 'reg-007',
    p: 'The Prairie provinces are:',
    pf: 'Les provinces des Prairies sont :',
    o: ['Manitoba, Saskatchewan, and Alberta', 'B.C., Yukon, and Alberta', 'Ontario, Quebec, and Manitoba', 'Nova Scotia, PEI, and New Brunswick'],
    of: ['Le Manitoba, la Saskatchewan et l’Alberta', 'La Colombie-Britannique, le Yukon et l’Alberta', 'L’Ontario, le Québec et le Manitoba', 'La Nouvelle-Écosse, l’Île-du-Prince-Édouard et le Nouveau-Brunswick'],
    a: 'a',
    e: 'They sit between the Shield and the Rockies. All three joined after 1867.',
    ef: 'Elles se situent entre le Bouclier canadien et les Rocheuses. Les trois se sont jointes au Canada après 1867.',
  },
  {
    id: 'reg-008',
    p: 'The West Coast region in the guide is:',
    pf: 'Dans le guide, la région de la côte du Pacifique correspond :',
    o: ['British Columbia', 'Yukon', 'Alberta', 'Manitoba'],
    of: ['À la Colombie-Britannique', 'Au Yukon', 'À l’Alberta', 'Au Manitoba'],
    a: 'a',
    e: 'Yukon is grouped with the Northern Territories, not with the West Coast region.',
    ef: 'Le Yukon est regroupé avec les territoires du Nord, et non avec la région de la côte du Pacifique.',
  },
  {
    id: 'reg-009',
    p: 'The Northern Territories are:',
    pf: 'Les territoires du Nord sont :',
    o: ['Yukon, Northwest Territories, and Nunavut', 'Labrador, Yukon, and PEI', 'NWT, Manitoba, and Nunavut', 'Yukon, B.C., and Alaska'],
    of: ['Le Yukon, les Territoires du Nord-Ouest et le Nunavut', 'Le Labrador, le Yukon et l’Île-du-Prince-Édouard', 'Les Territoires du Nord-Ouest, le Manitoba et le Nunavut', 'Le Yukon, la Colombie-Britannique et l’Alaska'],
    a: 'a',
    e: 'Three territories, vast land, small populations.',
    ef: 'Trois territoires, un immense espace et de faibles populations.',
  },
  {
    id: 'reg-010',
    t: 'tf',
    p: 'Most Canadians live within a few hundred kilometres of the United States border.',
    pf: 'La majorité des Canadiens vivent à quelques centaines de kilomètres de la frontière américaine.',
    a: 'true',
    e: 'The populated belt is southern and thin. The North is huge and sparsely peopled.',
    ef: 'La bande peuplée du pays est étroite et située au sud. Le Nord est immense et très peu peuplé.',
  },
  {
    id: 'reg-011',
    p: 'The five Great Lakes include:',
    pf: 'Les cinq Grands Lacs sont :',
    o: [
      'Superior, Michigan, Huron, Erie, and Ontario',
      'Winnipeg, Athabasca, Great Slave, Great Bear, and Ontario',
      'Ontario, Erie, Champlain, Simcoe, and Nipissing',
      'Michigan, Superior, Winnipeg, Erie, and Huron only four names',
    ],
    of: [
      'Supérieur, Michigan, Huron, Érié et Ontario',
      'Winnipeg, Athabasca, Grand Lac des Esclaves, Grand Lac de l’Ours et Ontario',
      'Ontario, Érié, Champlain, Simcoe et Nipissing',
      'Michigan, Supérieur, Winnipeg, Érié et Huron, soit quatre noms seulement',
    ],
    a: 'a',
    e: 'They drain to the Atlantic via the St. Lawrence. Michigan is shared with the United States.',
    ef: 'Ils se déversent dans l’Atlantique par le Saint-Laurent. Le lac Michigan est partagé avec les États-Unis.',
  },
  {
    id: 'reg-012',
    p: 'The Canadian Shield is:',
    pf: 'Le Bouclier canadien est :',
    o: [
      'A vast rocky region rich in forests and minerals around Hudson Bay',
      'A police badge',
      'The roof of the Peace Tower',
      'A prairie grassland only',
    ],
    of: [
      'Une vaste région rocheuse riche en forêts et en minéraux qui entoure la baie d’Hudson',
      'Un insigne de police',
      'Le toit de la Tour de la Paix',
      'Une prairie herbeuse seulement',
    ],
    a: 'a',
    e: 'It covers much of Quebec, Ontario, Manitoba, and the Territories. Mining and hydro are classic Shield economies.',
    ef: 'Il couvre une grande partie du Québec, de l’Ontario, du Manitoba et des territoires. Les mines et l’hydroélectricité sont les activités économiques typiques du Bouclier.',
  },
  {
    id: 'reg-013',
    p: 'The Cordillera is:',
    pf: 'La Cordillère est :',
    o: ['The western mountain system', 'A river in PEI', 'A Toronto neighbourhood', 'The Senate’s Latin name'],
    of: ['Le système montagneux de l’Ouest', 'Une rivière de l’Île-du-Prince-Édouard', 'Un quartier de Toronto', 'Le nom latin du Sénat'],
    a: 'a',
    e: 'The Rockies and Coast Mountains dominate British Columbia and stretch into Alberta and the Yukon.',
    ef: 'Les Rocheuses et la chaîne Côtière dominent la Colombie-Britannique et se prolongent en Alberta et au Yukon.',
  },
  {
    id: 'reg-014',
    region: 'qc',
    p: 'What is the capital of Quebec?',
    pf: 'Quelle est la capitale du Québec?',
    o: ['Montreal', 'Quebec City', 'Gatineau', 'Sherbrooke'],
    of: ['Montréal', 'Québec', 'Gatineau', 'Sherbrooke'],
    a: 'b',
    e: 'Quebec City is the capital. Montreal is the largest city. Mixing them is a classic test trap.',
    ef: 'La ville de Québec est la capitale; Montréal est la plus grande ville. Les confondre est un piège classique à l’examen.',
  },
  {
    id: 'reg-015',
    region: 'qc',
    p: 'Which city is Quebec’s metropolis and Canada’s largest French-speaking city?',
    pf: 'Quelle ville est la métropole du Québec et la plus grande ville francophone du Canada?',
    o: ['Montreal', 'Quebec City', 'Trois-Rivières', 'Ottawa'],
    of: ['Montréal', 'Québec', 'Trois-Rivières', 'Ottawa'],
    a: 'a',
    e: 'Montreal is the economic and cultural giant. Quebec City is the political capital, founded in 1608.',
    ef: 'Montréal est le géant économique et culturel. La ville de Québec, fondée en 1608, est la capitale politique.',
  },
  {
    id: 'reg-016',
    region: 'bc',
    p: 'What is the capital of British Columbia?',
    pf: 'Quelle est la capitale de la Colombie-Britannique?',
    o: ['Vancouver', 'Victoria', 'Kelowna', 'Prince George'],
    of: ['Vancouver', 'Victoria', 'Kelowna', 'Prince George'],
    a: 'b',
    e: 'Victoria, on Vancouver Island, is the capital. Vancouver is the largest city and main port.',
    ef: 'Victoria, sur l’île de Vancouver, est la capitale. Vancouver est la plus grande ville et le principal port.',
  },
  {
    id: 'reg-017',
    region: 'bc',
    p: 'British Columbia joined Confederation in 1871 after a promise of:',
    pf: 'La Colombie-Britannique s’est joint à la Confédération en 1871 après la promesse :',
    o: ['A transcontinental railway', 'Immediate Senate seats for every village', 'Free ferries forever with no terms', 'Official status for Spanish'],
    of: ['D’un chemin de fer transcontinental', 'De sièges immédiats au Sénat pour chaque village', 'De traversiers gratuits à perpétuité et sans conditions', 'Du statut de langue officielle pour l’espagnol'],
    a: 'a',
    e: 'The railway bound the Pacific province to Canada. Vancouver later became the great Pacific gateway.',
    ef: 'Le chemin de fer a rattaché la province du Pacifique au Canada. Vancouver est ensuite devenue la grande porte d’entrée du Pacifique.',
  },
  {
    id: 'reg-018',
    region: 'ab',
    p: 'What is the capital of Alberta?',
    pf: 'Quelle est la capitale de l’Alberta?',
    o: ['Calgary', 'Edmonton', 'Red Deer', 'Lethbridge'],
    of: ['Calgary', 'Edmonton', 'Red Deer', 'Lethbridge'],
    a: 'b',
    e: 'Edmonton is the capital. Calgary is the largest city. Energy and agriculture define much of the economy.',
    ef: 'Edmonton est la capitale; Calgary est la plus grande ville. L’énergie et l’agriculture façonnent une bonne part de l’économie.',
  },
  {
    id: 'reg-019',
    region: 'ab',
    p: 'Alberta’s largest city is:',
    pf: 'La plus grande ville de l’Alberta est :',
    o: ['Edmonton', 'Calgary', 'Banff', 'Fort McMurray'],
    of: ['Edmonton', 'Calgary', 'Banff', 'Fort McMurray'],
    a: 'b',
    e: 'Calgary is larger; Edmonton is the seat of government. The Rockies lie on the B.C. boundary.',
    ef: 'Calgary est plus grande, tandis qu’Edmonton est le siège du gouvernement. Les Rocheuses longent la frontière avec la Colombie-Britannique.',
  },
  {
    id: 'reg-020',
    region: 'sk',
    p: 'What is the capital of Saskatchewan?',
    pf: 'Quelle est la capitale de la Saskatchewan?',
    o: ['Saskatoon', 'Regina', 'Moose Jaw', 'Prince Albert'],
    of: ['Saskatoon', 'Regina', 'Moose Jaw', 'Prince Albert'],
    a: 'b',
    e: 'Regina is the capital. Saskatoon is the largest city. Wheat and potash are classic study-guide hooks.',
    ef: 'Regina est la capitale; Saskatoon est la plus grande ville. Le blé et la potasse sont les repères classiques du guide d’étude.',
  },
  {
    id: 'reg-021',
    region: 'sk',
    p: 'Saskatchewan is especially associated with:',
    pf: 'La Saskatchewan est surtout associée :',
    o: ['Grain farming and potash', 'Pacific shipping', 'Cod stocks', 'The national capital'],
    of: ['À la culture des céréales et à la potasse', 'Au transport maritime du Pacifique', 'Aux stocks de morue', 'À la capitale nationale'],
    a: 'a',
    e: 'It is also the birthplace of a major strain of Canadian social democracy, including early public hospital insurance.',
    ef: 'Elle est aussi le berceau d’un important courant social-démocrate canadien, dont les premiers régimes publics d’assurance hospitalisation.',
  },
  {
    id: 'reg-022',
    region: 'mb',
    p: 'What is the capital of Manitoba?',
    pf: 'Quelle est la capitale du Manitoba?',
    o: ['Brandon', 'Winnipeg', 'Churchill', 'Thompson'],
    of: ['Brandon', 'Winnipeg', 'Churchill', 'Thompson'],
    a: 'b',
    e: 'Winnipeg sits at the forks of the Red and Assiniboine. Red River Métis history is central to the province’s entry into Canada.',
    ef: 'Winnipeg se trouve à la fourche des rivières Rouge et Assiniboine. L’histoire des Métis de la rivière Rouge est au cœur de l’entrée de la province dans le Canada.',
  },
  {
    id: 'reg-023',
    region: 'mb',
    p: 'Manitoba entered Confederation in 1870 after:',
    pf: 'Le Manitoba est entré dans la Confédération en 1870 à la suite :',
    o: ['The Red River Resistance and the Manitoba Act', 'The Klondike gold rush', 'D-Day', 'The Quiet Revolution'],
    of: ['De la résistance de la rivière Rouge et de la Loi sur le Manitoba', 'De la ruée vers l’or du Klondike', 'Du jour J', 'De la Révolution tranquille'],
    a: 'a',
    e: 'Louis Riel and the Métis provisional government are part of that founding story.',
    ef: 'Louis Riel et le gouvernement provisoire des Métis font partie de ce récit de fondation.',
  },
  {
    id: 'reg-024',
    region: 'ns',
    p: 'What is the capital of Nova Scotia?',
    pf: 'Quelle est la capitale de la Nouvelle-Écosse?',
    o: ['Halifax', 'Sydney', 'Yarmouth', 'Lunenburg'],
    of: ['Halifax', 'Sydney', 'Yarmouth', 'Lunenburg'],
    a: 'a',
    e: 'Halifax is the largest Atlantic city and a major port, with a long military and naval history.',
    ef: 'Halifax est la plus grande ville de l’Atlantique et un port important, doté d’une longue histoire militaire et navale.',
  },
  {
    id: 'reg-025',
    region: 'nb',
    p: 'What is the capital of New Brunswick?',
    pf: 'Quelle est la capitale du Nouveau-Brunswick?',
    o: ['Saint John', 'Moncton', 'Fredericton', 'Bathurst'],
    of: ['Saint-Jean', 'Moncton', 'Fredericton', 'Bathurst'],
    a: 'c',
    e: 'Fredericton is the capital. New Brunswick is the only officially bilingual province, with a large Acadian population.',
    ef: 'Fredericton est la capitale. Le Nouveau-Brunswick est la seule province officiellement bilingue et compte une importante population acadienne.',
  },
  {
    id: 'reg-026',
    region: 'nb',
    p: 'Which is the only officially bilingual province?',
    pf: 'Quelle est la seule province officiellement bilingue?',
    o: ['Quebec', 'New Brunswick', 'Ontario', 'Manitoba'],
    of: ['Le Québec', 'Le Nouveau-Brunswick', 'L’Ontario', 'Le Manitoba'],
    a: 'b',
    e: 'Quebec’s official language is French. Federally, Canada is bilingual. Among provinces, only New Brunswick is officially bilingual.',
    ef: 'La langue officielle du Québec est le français. Sur le plan fédéral, le Canada est bilingue. Parmi les provinces, seul le Nouveau-Brunswick est officiellement bilingue.',
  },
  {
    id: 'reg-027',
    region: 'pe',
    p: 'What is the capital of Prince Edward Island?',
    pf: 'Quelle est la capitale de l’Île-du-Prince-Édouard?',
    o: ['Summerside', 'Charlottetown', 'Cavendish', 'Georgetown'],
    of: ['Summerside', 'Charlottetown', 'Cavendish', 'Georgetown'],
    a: 'b',
    e: 'Charlottetown hosted the 1864 conference that began Confederation talks. PEI joined Canada in 1873.',
    ef: 'Charlottetown a accueilli la conférence de 1864 qui a lancé les pourparlers de la Confédération. L’Île-du-Prince-Édouard s’est joint au Canada en 1873.',
  },
  {
    id: 'reg-028',
    region: 'nl',
    p: 'What is the capital of Newfoundland and Labrador?',
    pf: 'Quelle est la capitale de Terre-Neuve-et-Labrador?',
    o: ['Corner Brook', 'Happy Valley-Goose Bay', "St. John's", 'Gander'],
    of: ['Corner Brook', 'Happy Valley-Goose Bay', 'St. John’s', 'Gander'],
    a: 'c',
    e: 'St. John’s is one of the oldest European-founded cities in North America. The province joined Canada in 1949.',
    ef: 'St. John’s est l’une des plus anciennes villes fondées par des Européens en Amérique du Nord. La province est entrée dans le Canada en 1949.',
  },
  {
    id: 'reg-029',
    region: 'nl',
    p: 'Newfoundland and Labrador consists of:',
    pf: 'Terre-Neuve-et-Labrador se compose :',
    o: [
      'An island (Newfoundland) plus a mainland region (Labrador)',
      'Only an Arctic archipelago',
      'Only Prairie farmland',
      'Only Vancouver Island',
    ],
    of: [
      'D’une île (Terre-Neuve) et d’une région continentale (le Labrador)',
      'D’un archipel arctique seulement',
      'De terres agricoles des Prairies seulement',
      'De l’île de Vancouver seulement',
    ],
    a: 'a',
    e: 'Labrador is on the mainland next to Quebec. Newfoundland time is a half-hour ahead of Atlantic time.',
    ef: 'Le Labrador se trouve sur le continent, voisin du Québec. L’heure de Terre-Neuve est en avance d’une demi-heure sur l’heure de l’Atlantique.',
  },
  {
    id: 'reg-030',
    region: 'yt',
    p: 'What is the capital of Yukon?',
    pf: 'Quelle est la capitale du Yukon?',
    o: ['Dawson City', 'Whitehorse', 'Watson Lake', 'Yellowknife'],
    of: ['Dawson', 'Whitehorse', 'Watson Lake', 'Yellowknife'],
    a: 'b',
    e: 'Whitehorse is the capital. Dawson is tied to the Klondike Gold Rush of the late 1890s.',
    ef: 'Whitehorse est la capitale. Dawson est liée à la ruée vers l’or du Klondike, à la fin des années 1890.',
  },
  {
    id: 'reg-031',
    region: 'yt',
    p: 'Yukon’s classic historic event in the study guide is:',
    pf: 'Dans le guide d’étude, l’événement historique classique du Yukon est :',
    o: ['The Klondike Gold Rush', 'The Quiet Revolution', 'The Dieppe raid', 'The Charlottetown Conference'],
    of: ['La ruée vers l’or du Klondike', 'La Révolution tranquille', 'Le raid de Dieppe', 'La Conférence de Charlottetown'],
    a: 'a',
    e: 'The rush brought a stampede of prospectors and made the territory famous.',
    ef: 'Cette ruée a attiré une foule de prospecteurs et rendu le territoire célèbre.',
  },
  {
    id: 'reg-032',
    region: 'nt',
    p: 'What is the capital of the Northwest Territories?',
    pf: 'Quelle est la capitale des Territoires du Nord-Ouest?',
    o: ['Inuvik', 'Hay River', 'Yellowknife', 'Iqaluit'],
    of: ['Inuvik', 'Hay River', 'Yellowknife', 'Iqaluit'],
    a: 'c',
    e: 'Yellowknife sits on Great Slave Lake. Diamonds, gold, and public administration are economic pillars.',
    ef: 'Yellowknife est située sur le Grand Lac des Esclaves. Le diamant, l’or et l’administration publique sont les piliers de son économie.',
  },
  {
    id: 'reg-033',
    region: 'nu',
    p: 'What is the capital of Nunavut?',
    pf: 'Quelle est la capitale du Nunavut?',
    o: ['Rankin Inlet', 'Iqaluit', 'Cambridge Bay', 'Yellowknife'],
    of: ['Rankin Inlet', 'Iqaluit', 'Cambridge Bay', 'Yellowknife'],
    a: 'b',
    e: 'Iqaluit is the capital. Nunavut was created in 1999 from the eastern Northwest Territories.',
    ef: 'Iqaluit est la capitale. Le Nunavut a été créé en 1999 à partir de la partie est des Territoires du Nord-Ouest.',
  },
  {
    id: 'reg-034',
    region: 'nu',
    p: 'Nunavut was created in:',
    pf: 'Le Nunavut a été créé en :',
    o: ['1867', '1949', '1999', '1927'],
    of: ['1867', '1949', '1999', '1927'],
    a: 'c',
    e: 'It is a majority-Inuit territory. Inuktut languages are central to public life. Many communities are fly-in.',
    ef: 'C’est un territoire à majorité inuite. Les langues inuites occupent une place centrale dans la vie publique. De nombreuses communautés ne sont accessibles que par avion.',
  },
  {
    id: 'reg-035',
    t: 'tf',
    p: 'Nunavut is a province.',
    pf: 'Le Nunavut est une province.',
    a: 'false',
    e: 'It is a territory. That legal distinction still matters, even as territorial governments run most daily services.',
    ef: 'C’est un territoire. Cette distinction juridique compte encore, même si les gouvernements territoriaux administrent la plupart des services quotidiens.',
  },
  {
    id: 'reg-036',
    p: 'Which province has the largest population?',
    pf: 'Quelle province est la plus peuplée?',
    o: ['Quebec', 'Ontario', 'British Columbia', 'Alberta'],
    of: ['Le Québec', 'L’Ontario', 'La Colombie-Britannique', 'L’Alberta'],
    a: 'b',
    e: 'Ontario is the most populous. Quebec is second. Population, not land area, drives House of Commons seat counts.',
    ef: 'L’Ontario est la province la plus peuplée, suivie du Québec. C’est la population, et non la superficie, qui détermine le nombre de sièges à la Chambre des communes.',
  },
  {
    id: 'reg-037',
    p: 'Which is the largest province by land area?',
    pf: 'Quelle est la plus grande province par sa superficie?',
    o: ['Ontario', 'Quebec', 'British Columbia', 'Alberta'],
    of: ['L’Ontario', 'Le Québec', 'La Colombie-Britannique', 'L’Alberta'],
    a: 'b',
    e: 'Quebec is the largest province. Nunavut is larger still, but it is a territory.',
    ef: 'Le Québec est la plus grande province. Le Nunavut est encore plus vaste, mais c’est un territoire.',
  },
  {
    id: 'reg-038',
    p: 'The St. Lawrence River is historically important as:',
    pf: 'Le fleuve Saint-Laurent revêt une importance historique en tant que :',
    o: [
      'The highway from the Atlantic into the interior of the continent',
      'A prairie creek',
      'A Yukon gold stream only',
      'A British Columbia fjord only',
    ],
    of: [
      'Voie de passage de l’Atlantique vers l’intérieur du continent',
      'Ruisseau des Prairies',
      'Ruisseau aurifère du Yukon seulement',
      'Fjord de la Colombie-Britannique seulement',
    ],
    a: 'a',
    e: 'New France, Montreal, Quebec City, and later the Seaway all sit on this system.',
    ef: 'La Nouvelle-France, Montréal, la ville de Québec et, plus tard, la Voie maritime s’inscrivent tous dans ce réseau.',
  },
  {
    id: 'reg-039',
    p: 'Niagara Falls lies on the border of:',
    pf: 'Les chutes Niagara se trouvent à la frontière :',
    o: ['Ontario and the United States', 'B.C. and Alaska', 'Manitoba and Nunavut', 'PEI and New Brunswick'],
    of: ['De l’Ontario et des États-Unis', 'De la Colombie-Britannique et de l’Alaska', 'Du Manitoba et du Nunavut', 'De l’Île-du-Prince-Édouard et du Nouveau-Brunswick'],
    a: 'a',
    e: 'It is a hydroelectric and tourism landmark of the Great Lakes–St. Lawrence system.',
    ef: 'C’est un haut lieu de l’hydroélectricité et du tourisme dans le réseau des Grands Lacs et du Saint-Laurent.',
  },
  {
    id: 'reg-040',
    region: 'on',
    p: 'Ottawa is in Ontario, but the National Capital Region also includes:',
    pf: 'Ottawa est en Ontario, mais la région de la capitale nationale comprend aussi :',
    o: ['Gatineau, Quebec, across the river', 'Winnipeg', 'Halifax', 'Victoria'],
    of: ['Gatineau, au Québec, de l’autre côté de la rivière', 'Winnipeg', 'Halifax', 'Victoria'],
    a: 'a',
    e: 'Federal institutions sit on both sides of the Ottawa River. Do not call Gatineau the national capital.',
    ef: 'Des institutions fédérales se trouvent des deux côtés de la rivière des Outaouais. Attention : Gatineau n’est pas la capitale nationale.',
  },
  {
    id: 'reg-041',
    region: 'pe',
    p: 'Prince Edward Island is linked to the mainland by:',
    pf: 'L’Île-du-Prince-Édouard est reliée au continent par :',
    o: ['The Confederation Bridge (and also by ferry)', 'A subway to Montreal', 'A rail tunnel to Yukon', 'A dam across Hudson Bay'],
    of: ['Le pont de la Confédération (ainsi que par traversier)', 'Un métro jusqu’à Montréal', 'Un tunnel ferroviaire jusqu’au Yukon', 'Un barrage traversant la baie d’Hudson'],
    a: 'a',
    e: 'The bridge is a modern fact; the 1864 talks are the historic one. Agriculture and tourism remain economic staples.',
    ef: 'Le pont est un fait moderne; les pourparlers de 1864 constituent le fait historique. L’agriculture et le tourisme demeurent les bases de l’économie.',
  },
  {
    id: 'reg-042',
    region: 'ns',
    p: 'Nova Scotia’s name means:',
    pf: 'Le nom « Nouvelle-Écosse » signifie :',
    o: ['New Scotland', 'New France', 'New Ireland', 'New Wales'],
    of: ['Nouvelle-Écosse', 'Nouvelle-France', 'Nouvelle-Irlande', 'Nouveau-Pays de Galles'],
    a: 'a',
    e: 'Scottish settlement, the Halifax port, Acadian communities, and Black Loyalist history all mark the province.',
    ef: 'Le peuplement écossais, le port d’Halifax, les communautés acadiennes et l’histoire des loyalistes noirs marquent tous la province.',
  },
  {
    id: 'reg-043',
    p: 'Which region is sparsely populated, strategically important in the Arctic, and home to Inuit and other northern peoples?',
    pf: 'Quelle région est peu peuplée, stratégiquement importante dans l’Arctique et habitée par les Inuits et d’autres peuples du Nord?',
    o: ['The North', 'Prince Edward Island’s interior cities', 'Downtown Toronto', 'The Niagara fruit belt only'],
    of: ['Le Nord', 'Les villes de l’intérieur de l’Île-du-Prince-Édouard', 'Le centre-ville de Toronto', 'La ceinture fruitière du Niagara seulement'],
    a: 'a',
    e: 'Permafrost, fly-in communities, and sovereignty issues are part of the northern story.',
    ef: 'Le pergélisol, les communautés accessibles par avion et les questions de souveraineté font partie de la réalité du Nord.',
  },
  {
    id: 'reg-044',
    t: 'tf',
    p: 'Toronto is the capital of Canada.',
    pf: 'Toronto est la capitale du Canada.',
    a: 'false',
    e: 'Toronto is Ontario’s capital and the largest city. Ottawa is the national capital.',
    ef: 'Toronto est la capitale de l’Ontario et la plus grande ville du pays. Ottawa est la capitale nationale.',
  },
  {
    id: 'reg-045',
    p: 'Hudson Bay is bordered by:',
    pf: 'La baie d’Hudson est bordée :',
    o: [
      'Several provinces and territories, with the Shield around much of it',
      'Only British Columbia',
      'Only Prince Edward Island',
      'Only the island of Newfoundland',
    ],
    of: [
      'Par plusieurs provinces et territoires, le Bouclier canadien en entourant une bonne partie',
      'Par la Colombie-Britannique seulement',
      'Par l’Île-du-Prince-Édouard seulement',
      'Par l’île de Terre-Neuve seulement',
    ],
    a: 'a',
    e: 'It is a geographic centre of gravity for the Shield and for historic fur-trade routes.',
    ef: 'Elle constitue un centre de gravité géographique pour le Bouclier canadien et pour les anciennes routes de la traite des fourrures.',
  },
  {
    id: 'reg-046',
    region: 'bc',
    p: 'Vancouver is important as:',
    pf: 'Vancouver est importante en tant que :',
    o: ['A major Pacific port and B.C.’s largest city', 'The provincial capital', 'The national capital', 'Nunavut’s seaport'],
    of: ['Grand port du Pacifique et plus grande ville de la Colombie-Britannique', 'Capitale provinciale', 'Capitale nationale', 'Port maritime du Nunavut'],
    a: 'a',
    e: 'Victoria is the capital. Vancouver is the metropolis and a gateway to Asia-Pacific trade.',
    ef: 'Victoria est la capitale. Vancouver est la métropole et une porte d’entrée du commerce avec l’Asie-Pacifique.',
  },
  {
    id: 'reg-047',
    p: 'Which province is an original 1867 member and remains the heart of French-speaking North America?',
    pf: 'Quelle province fait partie des membres fondateurs de 1867 et demeure le cœur de l’Amérique du Nord francophone?',
    o: ['Quebec', 'Alberta', 'Saskatchewan', 'Newfoundland and Labrador'],
    of: ['Le Québec', 'L’Alberta', 'La Saskatchewan', 'Terre-Neuve-et-Labrador'],
    a: 'a',
    e: 'Quebec was Canada East. Its civil law, language, and national capital (Quebec City) are core regional facts.',
    ef: 'Le Québec était le Canada-Est. Son droit civil, sa langue et sa capitale (la ville de Québec) sont des faits régionaux essentiels.',
  },
  {
    id: 'reg-048',
    region: 'on',
    p: 'Southern Ontario’s economy has long included:',
    pf: 'L’économie du sud de l’Ontario comprend depuis longtemps :',
    o: ['Manufacturing (including autos) and services', 'Only Arctic mining', 'Only offshore oil', 'Only potato farming'],
    of: ['La fabrication (dont l’automobile) et les services', 'L’exploitation minière arctique seulement', 'Le pétrole extracôtier seulement', 'La culture de la pomme de terre seulement'],
    a: 'a',
    e: 'The Golden Horseshoe around Toronto is one of the country’s main industrial and service regions.',
    ef: 'Le Golden Horseshoe, autour de Toronto, est l’une des principales régions industrielles et de services du pays.',
  },
  {
    id: 'reg-049',
    t: 'tf',
    p: 'Territories have commissioners rather than lieutenant governors.',
    pf: 'Les territoires ont des commissaires plutôt que des lieutenants-gouverneurs.',
    a: 'true',
    e: 'The Crown’s provincial representative is a Lieutenant Governor. Territorial commissioners are a different office.',
    ef: 'Le représentant de la Couronne dans une province est le lieutenant-gouverneur. Le commissaire d’un territoire occupe une fonction différente.',
  },
  {
    id: 'reg-050',
    p: 'If a citizenship question asks about “your region,” it often wants:',
    pf: 'Si une question de l’examen porte sur « votre région », on attend souvent :',
    o: [
      'Your province or territory’s capital and a local geographic or historic hook',
      'The name of your landlord',
      'Your federal riding’s polling-station number only',
      'The Mayor of Ottawa in every case',
    ],
    of: [
      'La capitale de votre province ou territoire et un repère géographique ou historique local',
      'Le nom de votre propriétaire',
      'Le numéro du bureau de scrutin de votre circonscription fédérale seulement',
      'Le nom du maire d’Ottawa dans tous les cas',
    ],
    a: 'a',
    e: 'National facts first, then lock in your capital city and one distinctive fact. This app tags such items by province code.',
    ef: 'Retenez d’abord les faits nationaux, puis mémorisez votre capitale et un fait distinctif. L’application classe ces questions selon le code de la province.',
  },
  {
    id: 'reg-051',
    region: 'pe',
    p: 'Prince Edward Island is especially known for:',
    pf: 'L’Île-du-Prince-Édouard est surtout connue pour :',
    o: ['Potato farming and a compact agricultural landscape', 'Oil sands only', 'Arctic diamond mines', 'Coastal rainforests of cedar only'],
    of: ['La culture de la pomme de terre et un paysage agricole compact', 'Les sables bitumineux seulement', 'Les mines de diamants de l’Arctique', 'Les forêts pluviales côtières de cèdres seulement'],
    a: 'a',
    e: 'It is Canada’s smallest province. Potatoes, tourism, and Confederation history are the usual hooks.',
    ef: 'C’est la plus petite province du Canada. La pomme de terre, le tourisme et l’histoire de la Confédération en sont les repères habituels.',
  },
  {
    id: 'reg-052',
    region: 'nb',
    p: 'New Brunswick’s landscape and economy have long included:',
    pf: 'Le paysage et l’économie du Nouveau-Brunswick comprennent depuis longtemps :',
    o: ['Acadian communities, forests, and the Bay of Fundy tides', 'Only prairie wheat', 'Only Inuit hamlets', 'Only auto assembly in Windsor'],
    of: ['Des communautés acadiennes, des forêts et les marées de la baie de Fundy', 'Le blé des Prairies seulement', 'Des hameaux inuits seulement', 'L’assemblage automobile à Windsor seulement'],
    a: 'a',
    e: 'It is the only officially bilingual province. Forestry and the Fundy coast are classic geography.',
    ef: 'C’est la seule province officiellement bilingue. La foresterie et le littoral de la baie de Fundy sont des éléments géographiques classiques.',
  },
  {
    id: 'reg-053',
    region: 'nl',
    p: 'Newfoundland and Labrador’s historic staple was:',
    pf: 'Le produit de base historique de Terre-Neuve-et-Labrador était :',
    o: ['The Atlantic fishery (especially cod)', 'Prairie potash only', 'Ontario auto parts only', 'B.C. wine only'],
    of: ['La pêche atlantique (surtout la morue)', 'La potasse des Prairies seulement', 'Les pièces automobiles de l’Ontario seulement', 'Le vin de la Colombie-Britannique seulement'],
    a: 'a',
    e: 'The fishery shaped settlement. Offshore oil is a later chapter; Labrador adds mines and hydro.',
    ef: 'La pêche a façonné le peuplement. Le pétrole extracôtier est un chapitre plus récent, tandis que le Labrador ajoute les mines et l’hydroélectricité.',
  },
  {
    id: 'reg-054',
    region: 'ns',
    p: 'Halifax is important in Canadian geography as:',
    pf: 'Dans la géographie canadienne, Halifax est importante en tant que :',
    o: [
      'A major Atlantic port and historic naval and immigration harbour',
      'The capital of Canada',
      'The capital of Alberta',
      'A prairie railway town only',
    ],
    of: [
      'Grand port de l’Atlantique et havre historique de la marine et de l’immigration',
      'Capitale du Canada',
      'Capitale de l’Alberta',
      'Simple ville ferroviaire des Prairies',
    ],
    a: 'a',
    e: 'The Citadel overlooks a year-round ice-free harbour. It is Nova Scotia’s capital and the Maritimes’ largest city.',
    ef: 'La Citadelle surplombe un port libre de glace toute l’année. Halifax est la capitale de la Nouvelle-Écosse et la plus grande ville des Maritimes.',
  },
  {
    id: 'reg-055',
    region: 'qc',
    p: 'Large hydroelectric projects in northern Quebec (including the James Bay area) matter because they:',
    pf: 'Les grands projets hydroélectriques du nord du Québec (dont ceux de la Baie-James) sont importants parce qu’ils :',
    o: [
      'Supply much of Quebec’s electricity and export power',
      'Are Ontario’s only oil sands',
      'Replaced the St. Lawrence River',
      'Are Yukon’s territorial assembly',
    ],
    of: [
      'Fournissent une grande part de l’électricité du Québec et permettent d’en exporter',
      'Constituent les seuls sables bitumineux de l’Ontario',
      'Ont remplacé le fleuve Saint-Laurent',
      'Forment l’assemblée territoriale du Yukon',
    ],
    a: 'a',
    e: 'Hydro is a Quebec economic signature. It also raised lasting Indigenous-rights issues.',
    ef: 'L’hydroélectricité est une signature économique du Québec. Elle a aussi soulevé des questions durables sur les droits des Autochtones.',
  },
  {
    id: 'reg-056',
    region: 'on',
    p: 'The Niagara fruit belt and wine region lie in:',
    pf: 'La ceinture fruitière et la région viticole du Niagara se trouvent :',
    o: ['Southern Ontario, between the lakes', 'Nunavut', 'Northern Labrador', 'The Yukon gold fields'],
    of: ['Dans le sud de l’Ontario, entre les lacs', 'Au Nunavut', 'Dans le nord du Labrador', 'Dans les champs aurifères du Yukon'],
    a: 'a',
    e: 'Mild lakeshore climate is an Ontario geography fact beyond Toronto and Ottawa.',
    ef: 'Le climat doux des rives des lacs est un fait géographique ontarien qui dépasse Toronto et Ottawa.',
  },
  {
    id: 'reg-057',
    region: 'mb',
    p: 'Winnipeg has historically been called a gateway because it:',
    pf: 'Winnipeg a longtemps été appelée une porte d’entrée parce qu’elle :',
    o: [
      'Sits where eastern rail and western Prairie routes meet',
      'Is Canada’s Pacific port',
      'Is the capital of Nova Scotia',
      'Lies on the Alaska Highway start in Dawson only',
    ],
    of: [
      'Se trouve au point de rencontre des chemins de fer de l’Est et des routes des Prairies de l’Ouest',
      'Est le port canadien du Pacifique',
      'Est la capitale de la Nouvelle-Écosse',
      'Se situe au départ de la route de l’Alaska, à Dawson seulement',
    ],
    a: 'a',
    e: 'The Forks, the railway, and later air links made it a prairie hub. It is Manitoba’s capital.',
    ef: 'La Fourche, le chemin de fer et, plus tard, les liaisons aériennes en ont fait une plaque tournante des Prairies. C’est la capitale du Manitoba.',
  },
  {
    id: 'reg-058',
    region: 'sk',
    p: 'Uranium mining is especially associated with:',
    pf: 'L’extraction de l’uranium est surtout associée :',
    o: ['Northern Saskatchewan', 'Prince Edward Island beaches only', 'Downtown Halifax', 'The Ottawa River islands only'],
    of: ['Au nord de la Saskatchewan', 'Aux plages de l’Île-du-Prince-Édouard seulement', 'Au centre-ville d’Halifax', 'Aux îles de la rivière des Outaouais seulement'],
    a: 'a',
    e: 'The Canadian Shield in the north holds major mines. Grain remains the southern Prairie story.',
    ef: 'Le Bouclier canadien, dans le nord, abrite d’importantes mines. Les céréales demeurent l’histoire du sud des Prairies.',
  },
  {
    id: 'reg-059',
    region: 'ab',
    p: 'The Calgary Stampede is:',
    pf: 'Le Stampede de Calgary est :',
    o: [
      'A famous western festival and rodeo that has become an Alberta cultural emblem',
      'The name of the Alberta legislature',
      'A Confederation conference of 1864',
      'Yukon’s capital',
    ],
    of: [
      'Un célèbre festival et rodéo de l’Ouest devenu un emblème culturel de l’Alberta',
      'Le nom de l’assemblée législative de l’Alberta',
      'Une conférence de la Confédération tenue en 1864',
      'La capitale du Yukon',
    ],
    a: 'a',
    e: 'Oil and cattle both shape Alberta’s image. The Stampede is the cultural postcard; Edmonton is the capital.',
    ef: 'Le pétrole et l’élevage bovin façonnent tous deux l’image de l’Alberta. Le Stampede en est la carte postale culturelle; Edmonton est la capitale.',
  },
  {
    id: 'reg-060',
    region: 'bc',
    p: 'Pacific salmon and mountain forests are especially associated with:',
    pf: 'Le saumon du Pacifique et les forêts de montagne sont surtout associés :',
    o: ['British Columbia', 'Prince Edward Island only', 'Saskatchewan wheat pools only', 'Nunavut hamlets only'],
    of: ['À la Colombie-Britannique', 'À l’Île-du-Prince-Édouard seulement', 'Aux coopératives de blé de la Saskatchewan seulement', 'Aux hameaux du Nunavut seulement'],
    a: 'a',
    e: 'The Cordillera plus a mild coast define B.C. Vancouver is the big port; Victoria is the capital.',
    ef: 'La Cordillère et un littoral au climat doux définissent la Colombie-Britannique. Vancouver est le grand port; Victoria est la capitale.',
  },
  {
    id: 'reg-061',
    region: 'yt',
    p: 'The Alaska Highway is a northern geography fact because it:',
    pf: 'La route de l’Alaska est un fait géographique du Nord parce qu’elle :',
    o: [
      'Links British Columbia and Yukon toward Alaska, built in the Second World War',
      'Crosses PEI on the Confederation Bridge',
      'Is Ottawa’s main street',
      'Is a subway in Montreal',
    ],
    of: [
      'Relie la Colombie-Britannique et le Yukon vers l’Alaska et a été construite pendant la Seconde Guerre mondiale',
      'Traverse l’Île-du-Prince-Édouard par le pont de la Confédération',
      'Est la rue principale d’Ottawa',
      'Est une ligne de métro à Montréal',
    ],
    a: 'a',
    e: 'Wartime building opened the northwest. Whitehorse is Yukon’s capital.',
    ef: 'Sa construction en temps de guerre a ouvert le Nord-Ouest. Whitehorse est la capitale du Yukon.',
  },
  {
    id: 'reg-062',
    region: 'nt',
    p: 'Yellowknife grew as a modern capital especially because of:',
    pf: 'Yellowknife s’est développée comme capitale moderne surtout grâce :',
    o: ['Gold, and later diamond, mining plus government', 'Potato farming like PEI', 'The auto pact plants', 'The Halifax Citadel'],
    of: ['À l’extraction de l’or, puis du diamant, et à l’administration publique', 'À la culture de la pomme de terre, comme à l’Île-du-Prince-Édouard', 'Aux usines du Pacte de l’automobile', 'À la Citadelle d’Halifax'],
    a: 'a',
    e: 'It sits on Great Slave Lake. The Northwest Territories’ legislature is there, not in Ottawa.',
    ef: 'Elle est située sur le Grand Lac des Esclaves. L’assemblée législative des Territoires du Nord-Ouest s’y trouve, et non à Ottawa.',
  },
  {
    id: 'reg-063',
    region: 'nu',
    p: 'Iqaluit is:',
    pf: 'Iqaluit est :',
    o: [
      'The capital of Nunavut, on Baffin Island',
      'The capital of Ontario',
      'A prairie wheat pool headquarters',
      'New Brunswick’s only city',
    ],
    of: [
      'La capitale du Nunavut, sur l’île de Baffin',
      'La capitale de l’Ontario',
      'Le siège d’une coopérative de blé des Prairies',
      'La seule ville du Nouveau-Brunswick',
    ],
    a: 'a',
    e: 'Nunavut is majority Inuit. Iqaluit is the political centre created when the territory was born in 1999.',
    ef: 'Le Nunavut est majoritairement inuit. Iqaluit est le centre politique établi à la création du territoire, en 1999.',
  },
  {
    id: 'reg-065',
    region: 'nt',
    p: 'Great Slave Lake, beside the capital Yellowknife, is in:',
    pf: 'Le Grand Lac des Esclaves, près de la capitale Yellowknife, se trouve :',
    o: [
      'The Northwest Territories',
      'Prince Edward Island',
      'Nova Scotia',
      'Manitoba only',
    ],
    of: [
      'Dans les Territoires du Nord-Ouest',
      'À l’Île-du-Prince-Édouard',
      'En Nouvelle-Écosse',
      'Au Manitoba seulement',
    ],
    a: 'a',
    e: 'Yellowknife sits on Great Slave Lake. The Northwest Territories’ legislature is there.',
    ef: 'Yellowknife est située sur le Grand Lac des Esclaves. L’assemblée législative des Territoires du Nord-Ouest s’y trouve.',
  },
  {
    id: 'reg-066',
    region: 'nt',
    t: 'tf',
    p: 'The Northwest Territories recognizes several Indigenous languages as official, alongside English and French.',
    pf: 'Les Territoires du Nord-Ouest reconnaissent plusieurs langues autochtones comme langues officielles, en plus de l’anglais et du français.',
    a: 'true',
    e: 'It is a large territory with many Indigenous languages. Several regions also have land-claim and self-government agreements.',
    ef: 'C’est un vaste territoire où l’on parle de nombreuses langues autochtones. Plusieurs régions ont aussi conclu des ententes sur les revendications territoriales et l’autonomie gouvernementale.',
  },
  {
    id: 'reg-064',
    t: 'tf',
    p: 'The Great Lakes–St. Lawrence system is a shared Ontario–Quebec (and U.S.) water highway for cities, industry, and shipping.',
    pf: 'Le réseau des Grands Lacs et du Saint-Laurent est une voie navigable partagée entre l’Ontario, le Québec et les États-Unis, au service des villes, de l’industrie et du transport maritime.',
    a: 'true',
    e: 'It is the core of central Canada’s geography. The Seaway lets ocean ships reach inland ports.',
    ef: 'C’est le cœur de la géographie du Canada central. La Voie maritime permet aux navires océaniques d’atteindre des ports intérieurs.',
  },
  {
    id: 'reg-067',
    p: 'What three oceans border Canada?',
    pf: 'Quels trois océans bordent le Canada?',
    o: [
      'Atlantic, Pacific, and Arctic',
      'Atlantic, Indian, and Pacific',
      'Pacific, Southern, and Atlantic',
      'Arctic, Baltic, and Pacific',
    ],
    of: [
      'L’Atlantique, le Pacifique et l’Arctique',
      'L’Atlantique, l’océan Indien et le Pacifique',
      'Le Pacifique, l’océan Austral et l’Atlantique',
      'L’Arctique, la Baltique et le Pacifique',
    ],
    a: 'a',
    e: 'Canada faces three oceans. Hudson Bay is a huge inland sea, but it is not counted as a fourth ocean on the test.',
    ef: 'Le Canada donne sur trois océans. La baie d’Hudson est une immense mer intérieure, mais elle n’est pas comptée comme un quatrième océan à l’examen.',
  },
  {
    id: 'reg-068',
    p: 'Name the five regions of Canada used in the official study guide.',
    pf: 'Nommez les cinq régions du Canada utilisées dans le guide d’étude officiel.',
    o: [
      'Atlantic, Central, Prairie, West Coast, and North',
      'East, West, North, South, and Midwest',
      'Maritimes, Ontario, Quebec, Prairies, and Territories only',
      'Pacific, Atlantic, Great Lakes, Prairies, and Shield',
    ],
    of: [
      'Atlantique, Centre, Prairies, côte du Pacifique et Nord',
      'Est, Ouest, Nord, Sud et Midwest',
      'Maritimes, Ontario, Québec, Prairies et territoires seulement',
      'Pacifique, Atlantique, Grands Lacs, Prairies et Bouclier',
    ],
    a: 'a',
    e: 'Memorize the five-region list exactly as the guide groups them, then learn which provinces sit in each.',
    ef: 'Mémorisez exactement la liste des cinq régions du guide, puis retenez quelles provinces s’y trouvent.',
  },
  {
    id: 'reg-069',
    p: 'About one third of all Canadians live in which province?',
    pf: 'Environ le tiers de tous les Canadiens habitent quelle province?',
    o: ['Ontario', 'Quebec', 'British Columbia', 'Alberta'],
    of: ['L’Ontario', 'Le Québec', 'La Colombie-Britannique', 'L’Alberta'],
    a: 'a',
    e: 'Ontario is by far the most populous province. Quebec is second; neither is “about half” on its own.',
    ef: 'L’Ontario est de loin la province la plus peuplée. Le Québec arrive deuxième; aucune des deux ne représente à elle seule « environ la moitié ».',
  },
  {
    id: 'reg-070',
    p: 'In which region do more than half the people in Canada live?',
    pf: 'Dans quelle région habite plus de la moitié de la population du Canada?',
    o: ['Central Canada', 'Atlantic Canada', 'Prairie provinces', 'Northern Territories'],
    of: ['Le Canada central', 'Le Canada atlantique', 'Les provinces des Prairies', 'Les territoires du Nord'],
    a: 'a',
    e: 'Central Canada means Ontario and Quebec together. That is where most Canadians live.',
    ef: 'Le Canada central désigne l’Ontario et le Québec ensemble. C’est là que vit la majorité des Canadiens.',
  },
  {
    id: 'reg-071',
    p: 'Which region covers more than one third of Canada’s land area?',
    pf: 'Quelle région couvre plus du tiers de la superficie du Canada?',
    o: ['The Northern Territories', 'Atlantic Canada', 'Central Canada', 'The Prairie provinces'],
    of: ['Les territoires du Nord', 'Le Canada atlantique', 'Le Canada central', 'Les provinces des Prairies'],
    a: 'a',
    e: 'Yukon, the Northwest Territories, and Nunavut are vast and sparsely populated. Land area is not the same as population.',
    ef: 'Le Yukon, les Territoires du Nord-Ouest et le Nunavut sont immenses et peu peuplés. La superficie n’équivaut pas à la population.',
  },
  {
    id: 'reg-072',
    p: 'Which region is known as the industrial and manufacturing heartland of Canada?',
    pf: 'Quelle région est connue comme le cœur industriel et manufacturier du Canada?',
    o: ['Central Canada', 'Atlantic Canada', 'The North', 'Prince Edward Island alone'],
    of: ['Le Canada central', 'Le Canada atlantique', 'Le Nord', 'L’Île-du-Prince-Édouard seule'],
    a: 'a',
    e: 'Ontario and Quebec together hold the largest share of manufacturing, including the auto sector in southern Ontario.',
    ef: 'L’Ontario et le Québec concentrent ensemble la plus grande part de la fabrication, notamment l’automobile dans le sud de l’Ontario.',
  },
  {
    id: 'reg-073',
    region: 'nl',
    p: 'Which province has its own time zone, half an hour ahead of Atlantic Time?',
    pf: 'Quelle province a son propre fuseau horaire, une demi-heure en avance sur l’heure de l’Atlantique?',
    o: ['Newfoundland and Labrador', 'Nova Scotia', 'New Brunswick', 'Prince Edward Island'],
    of: ['Terre-Neuve-et-Labrador', 'La Nouvelle-Écosse', 'Le Nouveau-Brunswick', 'L’Île-du-Prince-Édouard'],
    a: 'a',
    e: 'Newfoundland Time is a classic geography trivia item. Most of Labrador follows Atlantic Time, but the province is still the one associated with the half-hour zone.',
    ef: 'L’heure de Terre-Neuve est un classique de géographie. La plus grande partie du Labrador suit l’heure de l’Atlantique, mais la province reste associée au fuseau décalé d’une demi-heure.',
  },
  {
    id: 'reg-074',
    p: 'Which region of Canada is known for both fertile agricultural land and valuable energy resources?',
    pf: 'Quelle région du Canada est connue à la fois pour ses terres agricoles fertiles et ses précieuses ressources énergétiques?',
    o: ['The Prairie provinces', 'Atlantic Canada', 'The Northern Territories only', 'Prince Edward Island alone'],
    of: ['Les provinces des Prairies', 'Le Canada atlantique', 'Les territoires du Nord seulement', 'L’Île-du-Prince-Édouard seule'],
    a: 'a',
    e: 'Grain and other farming sit beside oil, gas, potash, and uranium across Manitoba, Saskatchewan, and Alberta.',
    ef: 'Les céréales et d’autres cultures côtoient le pétrole, le gaz, la potasse et l’uranium au Manitoba, en Saskatchewan et en Alberta.',
  },
  {
    id: 'reg-075',
    region: 'bc',
    p: 'Which port is the largest and busiest in Canada?',
    pf: 'Quel est le plus grand et le plus achalandé des ports du Canada?',
    o: ['The Port of Vancouver', 'The Port of Charlottetown', 'The Port of Regina', 'The Port of Yellowknife'],
    of: ['Le port de Vancouver', 'Le port de Charlottetown', 'Le port de Regina', 'Le port de Yellowknife'],
    a: 'a',
    e: 'Vancouver is Canada’s Pacific gateway. Huge volumes of trade goods move through it.',
    ef: 'Vancouver est la porte d’entrée canadienne sur le Pacifique. D’énormes volumes de marchandises y transitent.',
  },
]);
