import { build } from './build.mjs';

export default build(
  'rights-and-responsibilities',
  'Discover Canada — Rights and Responsibilities of Citizenship',
  [
    {
      id: 'rnr-001',
      p: 'Which of these is a mobility right of Canadian citizens?',
      o: [
        'The right to live and work in any province or territory',
        'The right to set provincial tax rates',
        'The right to appoint judges',
        'The right to dissolve Parliament',
      ],
      a: 'a',
      e: 'Canadian citizens may take up residence and pursue a livelihood anywhere in Canada, with limited exceptions set out in law.',
    },
    {
      id: 'rnr-002',
      p: 'Which document is the highest law protecting rights and freedoms in Canada?',
      o: [
        'The Criminal Code',
        'The Canadian Charter of Rights and Freedoms',
        'The British North America Act of 1931',
        'The Official Languages Act',
      ],
      a: 'b',
      e: 'The Charter, part of the Constitution, guarantees fundamental, democratic, mobility, legal, equality, and language rights.',
    },
    {
      id: 'rnr-003',
      t: 'tf',
      p: 'Serving on a jury when called is a responsibility of Canadian citizenship.',
      a: 'true',
      e: 'Citizenship comes with duties as well as rights. Those duties include obeying the law, serving on a jury if summoned, voting in elections, and helping others in the community.',
    },
    {
      id: 'rnr-004',
      p: 'Habeas corpus means that:',
      o: [
        'The Prime Minister can jail opponents without trial',
        'You can ask a court to review whether you are being lawfully detained',
        'Only the Senate can grant pardons',
        'Police never need a reason to arrest someone',
      ],
      a: 'b',
      e: 'Habeas corpus is a historic legal protection: detention must have a lawful basis, and a court can test it. Canada inherited this principle from English law.',
    },
    {
      id: 'rnr-005',
      p: 'Which of these is a fundamental freedom in the Charter?',
      o: [
        'Freedom of conscience and religion',
        'Freedom to ignore a jury summons',
        'Freedom to set the Bank of Canada’s interest rate',
        'Freedom to appoint Supreme Court judges',
      ],
      a: 'a',
      e: 'Fundamental freedoms include conscience and religion; thought, belief, opinion, and expression; peaceful assembly; and association.',
    },
    {
      id: 'rnr-006',
      p: 'The right of citizens to vote and to run for office is an example of:',
      o: ['Mobility rights', 'Democratic rights', 'Aboriginal rights', 'Property rights in the Charter'],
      a: 'b',
      e: 'Democratic rights include voting in elections for the House of Commons (and provincial legislatures) and being eligible to seek office, with limited exceptions in law.',
    },
    {
      id: 'rnr-007',
      p: 'Equality rights in the Charter are meant to protect people from:',
      o: [
        'Having to pay any taxes',
        'Discrimination by government based on grounds such as race, sex, or religion',
        'Losing a private lawsuit',
        'Provincial sales tax',
      ],
      a: 'b',
      e: 'Section 15 equality rights promise equal protection and benefit of the law without discrimination. They bind government, not every private disagreement.',
    },
    {
      id: 'rnr-008',
      t: 'tf',
      p: 'Men and women are equal under Canadian law.',
      a: 'true',
      e: 'Equality of women and men is a core Canadian value and is protected by the Charter’s equality rights.',
    },
    {
      id: 'rnr-009',
      p: 'Which statement about religion in Canada is correct?',
      o: [
        'Canada has an official state church',
        'Only Christian worship is legal',
        'Freedom of religion is protected; there is no official state church',
        'Religious schools are banned in every province',
      ],
      a: 'c',
      e: 'People may practise their faith—or none—within the limits of the law. Canada does not have an established church.',
    },
    {
      id: 'rnr-010',
      p: 'Aboriginal and treaty rights of the Indigenous peoples of Canada are:',
      o: [
        'Abolished by the Charter',
        'Recognized and not taken away by the Charter',
        'Valid only in Yukon',
        'Decided each year by referendum',
      ],
      a: 'b',
      e: 'The Constitution, including the Charter, affirms that it does not abrogate Aboriginal and treaty rights. Those rights have their own constitutional protection.',
    },
    {
      id: 'rnr-011',
      p: 'English and French have equal status in:',
      o: [
        'Every municipal council meeting in Canada',
        'Parliament and the Government of Canada',
        'The courts of Alberta only',
        'Private workplaces nationwide by default',
      ],
      a: 'b',
      e: 'Official-language rights apply to Parliament and federal institutions. Provinces have their own language rules; New Brunswick is officially bilingual as a province.',
    },
    {
      id: 'rnr-012',
      p: 'Which of the following is a responsibility of citizenship listed in the study guide?',
      o: [
        'Obeying the law',
        'Joining a political party',
        'Serving as a senator',
        'Owning land',
      ],
      a: 'a',
      e: 'Obeying the law is a basic duty. Other listed responsibilities include voting, jury service when called, and helping in the community.',
    },
    {
      id: 'rnr-013',
      t: 'tf',
      p: 'Voting in elections is only a right, never described as a responsibility.',
      a: 'false',
      e: 'The study guide treats voting as both a democratic right and a civic responsibility of citizens.',
    },
    {
      id: 'rnr-014',
      p: 'In a time of war, Canadian law has historically provided that:',
      o: [
        'Only senators must enlist',
        'Military-age men may be required to serve in the armed forces',
        'Children must serve on juries',
        'The Governor General must command a regiment',
      ],
      a: 'b',
      e: 'The guide notes that men may be subject to military service in wartime. Canada has not used conscription for many decades, but the historic duty is still taught.',
    },
    {
      id: 'rnr-015',
      p: 'Peaceful assembly and association are protected so that people may:',
      o: [
        'Form unions, parties, and protest groups within the law',
        'Block hospitals by force with no limits',
        'Ignore Criminal Code offences if they are in a crowd',
        'Appoint judges by petition',
      ],
      a: 'a',
      e: 'You may gather and join groups peacefully. Violence, intimidation, and other crimes are still crimes.',
    },
    {
      id: 'rnr-016',
      p: 'A citizen’s mobility rights generally include the right to:',
      o: [
        'Enter, remain in, and leave Canada',
        'Demand a passport from another country',
        'Set immigration quotas',
        'Close a provincial border permanently',
      ],
      a: 'a',
      e: 'Citizens have the right to enter, remain in, and leave Canada, and to live and seek work in any province, subject to limited legal exceptions.',
    },
    {
      id: 'rnr-017',
      p: 'Legal rights in the Charter include protection against:',
      o: [
        'Unreasonable search and seizure',
        'Having to testify as a witness when subpoenaed in every civil case',
        'Paying income tax',
        'Jury duty',
      ],
      a: 'a',
      e: 'Legal rights cover life, liberty, and security of the person; search and seizure; detention and arrest; and fair criminal process, among others.',
    },
    {
      id: 'rnr-018',
      t: 'tf',
      p: 'The Charter applies only to Canadian citizens in all of its sections.',
      a: 'false',
      e: 'Some rights, such as democratic rights, are for citizens. Many legal and equality rights protect “everyone” or “every individual,” including non-citizens, in Canada.',
    },
    {
      id: 'rnr-019',
      p: 'Helping others in the community is presented in the guide as:',
      o: [
        'A legal requirement to join a church',
        'A responsibility of citizenship',
        'A duty only for mayors',
        'A substitute for paying taxes',
      ],
      a: 'b',
      e: 'Volunteerism and looking out for neighbours are taught as civic responsibilities alongside formal legal duties.',
    },
    {
      id: 'rnr-020',
      p: 'Which of these is not a Charter “fundamental freedom”?',
      o: [
        'Freedom of expression',
        'Freedom of peaceful assembly',
        'Freedom from ever being taxed',
        'Freedom of association',
      ],
      a: 'c',
      e: 'Taxation is a lawful government power. Fundamental freedoms are conscience and religion, expression, peaceful assembly, and association.',
    },
    {
      id: 'rnr-021',
      p: 'Minority-language education rights generally protect:',
      o: [
        'English or French minority communities educating their children in their language, where numbers warrant',
        'Every language in the world in every school',
        'Latin as a compulsory subject',
        'Only Indigenous-language schools in Toronto',
      ],
      a: 'a',
      e: 'The Charter protects English or French minority-language education in specified circumstances, typically where numbers are sufficient.',
    },
    {
      id: 'rnr-022',
      t: 'tf',
      p: 'Courts can strike down laws that unjustifiably violate the Charter.',
      a: 'true',
      e: 'Because the Charter is part of the Constitution, inconsistent laws can be declared of no force, subject to limited override rules in some cases.',
    },
    {
      id: 'rnr-023',
      p: 'Hate propaganda that wilfully promotes hatred against an identifiable group is:',
      o: [
        'Fully protected as ordinary political speech with no limits',
        'Restricted by criminal law because it attacks other people’s rights and safety',
        'Required reading in Parliament',
        'A municipal zoning issue only',
      ],
      a: 'b',
      e: 'Expression has limits. Promoting genocide or wilfully promoting hatred is a crime; rights are balanced in a free and democratic society.',
    },
    {
      id: 'rnr-024',
      p: 'Which English legal landmark is often cited as a root of the rule of law that Canada inherited?',
      o: ['The Quebec Act', 'Magna Carta (1215)', 'The Official Languages Act', 'The Clarity Act'],
      a: 'b',
      e: 'Magna Carta is taught as an early limit on arbitrary royal power. Canadian law also draws on later English and French sources and Canadian statutes.',
    },
    {
      id: 'rnr-025',
      p: 'Protecting Canada’s heritage and environment is described as:',
      o: [
        'A responsibility shared by citizens',
        'The exclusive job of the Senate',
        'Illegal for private persons',
        'A municipal bylaw in Ottawa only',
      ],
      a: 'a',
      e: 'The guide asks citizens to help care for the natural and cultural heritage of the country, not only to claim rights.',
    },
    {
      id: 'rnr-026',
      t: 'tf',
      p: 'You may legally refuse a jury summons whenever you are busy at work, with no process.',
      a: 'false',
      e: 'Jury service is a duty. There are limited legal excuses and a process; simply ignoring a summons is not a right.',
    },
    {
      id: 'rnr-027',
      p: 'If you are arrested or detained, a key legal right is:',
      o: [
        'To be told why, and to retain and instruct counsel without delay',
        'To choose your trial judge by name',
        'To have the Prime Minister attend',
        'To skip the trial if you pay a fee',
      ],
      a: 'a',
      e: 'On arrest or detention you have the right to be informed of the reasons and to counsel. Use those rights; do not guess your way through an interrogation.',
    },
    {
      id: 'rnr-028',
      p: 'Forced or underage marriage, “honour” violence, and female genital mutilation are:',
      o: [
        'Protected as religious freedoms with no limits',
        'Crimes in Canada; culture or religion is not a defence',
        'Civil matters only in Quebec',
        'Legal if both families agree',
      ],
      a: 'b',
      e: 'Equality and security of the person outweigh claims that violence or coercion is a cultural right. These acts are crimes.',
    },
    {
      id: 'rnr-029',
      p: 'Who is expected to work to eliminate discrimination and injustice?',
      o: [
        'Only the Governor General',
        'Citizens and Canadian society as a whole',
        'Only people born in Canada',
        'Only the official opposition',
      ],
      a: 'b',
      e: 'The guide frames fighting discrimination as a shared civic responsibility, not a task for one office.',
    },
    {
      id: 'rnr-030',
      t: 'tf',
      p: 'The Constitution is the supreme law of Canada.',
      a: 'true',
      e: 'Ordinary statutes must be consistent with the Constitution, including the Charter. That is the legal meaning of a supreme law.',
    },
    {
      id: 'rnr-031',
      p: 'A reasonable limit on a Charter right must be:',
      o: [
        'Whatever a police officer prefers that day',
        'Prescribed by law and demonstrably justified in a free and democratic society',
        'Approved in a municipal tweet',
        'Impossible; rights have no limits',
      ],
      a: 'b',
      e: 'Section 1 of the Charter allows limits that are set out in law and can be justified. It does not allow arbitrary official action.',
    },
    {
      id: 'rnr-032',
      p: 'Filling out the census when required is best understood as:',
      o: [
        'Optional trivia for hobbyists',
        'A legal duty that helps governments plan services',
        'A Senate privilege',
        'Only for landowners',
      ],
      a: 'b',
      e: 'The census is required by law. Accurate counts affect representation and public services. Completing it is part of obeying the law.',
    },
  ],
);
