import { build } from './build.mjs';

export default build(
  'rights-and-responsibilities',
  'Discover Canada — Rights and Responsibilities of Citizenship',
  [
    {
      id: 'rnr-001',
      p: 'Which of these is a mobility right of Canadian citizens?',
      pf: 'Lequel de ces éléments est un droit de circulation et d’établissement des citoyens canadiens?',
      o: [
        'The right to live and work in any province or territory',
        'The right to set provincial tax rates',
        'The right to appoint judges',
        'The right to dissolve Parliament',
      ],
      of: [
        'Le droit de vivre et de travailler dans n’importe quelle province ou n’importe quel territoire',
        'Le droit de fixer les taux d’imposition provinciaux',
        'Le droit de nommer les juges',
        'Le droit de dissoudre le Parlement',
      ],
      a: 'a',
      e: 'Canadian citizens may take up residence and pursue a livelihood anywhere in Canada, with limited exceptions set out in law.',
      ef: 'Les citoyens canadiens peuvent s’établir et gagner leur vie partout au Canada, sous réserve de quelques exceptions prévues par la loi.',
    },
    {
      id: 'rnr-002',
      p: 'Which document is the highest law protecting rights and freedoms in Canada?',
      pf: 'Quel document est la loi suprême qui protège les droits et libertés au Canada?',
      o: [
        'The Criminal Code',
        'The Canadian Charter of Rights and Freedoms',
        'The British North America Act of 1931',
        'The Official Languages Act',
      ],
      of: [
        'Le Code criminel',
        'La Charte canadienne des droits et libertés',
        'L’Acte de l’Amérique du Nord britannique de 1931',
        'La Loi sur les langues officielles',
      ],
      a: 'b',
      e: 'The Charter, part of the Constitution, guarantees fundamental, democratic, mobility, legal, equality, and language rights.',
      ef: 'La Charte, qui fait partie de la Constitution, garantit les libertés fondamentales ainsi que les droits démocratiques, les droits de circulation, les droits juridiques, les droits à l’égalité et les droits linguistiques.',
    },
    {
      id: 'rnr-003',
      t: 'tf',
      p: 'Serving on a jury when called is a responsibility of Canadian citizenship.',
      pf: 'Faire partie d’un jury lorsqu’on est convoqué est une responsabilité de la citoyenneté canadienne.',
      a: 'true',
      e: 'Citizenship comes with duties as well as rights. Those duties include obeying the law, serving on a jury if summoned, voting in elections, and helping others in the community.',
      ef: 'La citoyenneté comporte des devoirs autant que des droits. Ces devoirs comprennent respecter la loi, faire partie d’un jury sur convocation, voter aux élections et aider les autres dans la collectivité.',
    },
    {
      id: 'rnr-004',
      p: 'Habeas corpus means that:',
      pf: 'L’habeas corpus signifie que :',
      o: [
        'The Prime Minister can jail opponents without trial',
        'You can ask a court to review whether you are being lawfully detained',
        'Only the Senate can grant pardons',
        'Police never need a reason to arrest someone',
      ],
      of: [
        'Le premier ministre peut emprisonner ses adversaires sans procès',
        'Vous pouvez demander à un tribunal de vérifier si votre détention est légale',
        'Seul le Sénat peut accorder un pardon',
        'Les policiers n’ont jamais besoin d’un motif pour arrêter quelqu’un',
      ],
      a: 'b',
      e: 'Habeas corpus is a historic legal protection: detention must have a lawful basis, and a court can test it. Canada inherited this principle from English law.',
      ef: 'L’habeas corpus est une protection juridique historique : la détention doit avoir un fondement légal, et un tribunal peut en vérifier la validité. Le Canada a hérité ce principe du droit anglais.',
    },
    {
      id: 'rnr-005',
      p: 'Which of these is a fundamental freedom in the Charter?',
      pf: 'Laquelle de ces libertés est une liberté fondamentale garantie par la Charte?',
      o: [
        'Freedom of conscience and religion',
        'Freedom to ignore a jury summons',
        'Freedom to set the Bank of Canada’s interest rate',
        'Freedom to appoint Supreme Court judges',
      ],
      of: [
        'La liberté de conscience et de religion',
        'La liberté d’ignorer une convocation à un jury',
        'La liberté de fixer le taux d’intérêt de la Banque du Canada',
        'La liberté de nommer les juges de la Cour suprême',
      ],
      a: 'a',
      e: 'Fundamental freedoms include conscience and religion; thought, belief, opinion, and expression; peaceful assembly; and association.',
      ef: 'Les libertés fondamentales comprennent la conscience et la religion; la pensée, la croyance, l’opinion et l’expression; la réunion pacifique; et l’association.',
    },
    {
      id: 'rnr-006',
      p: 'The right of citizens to vote and to run for office is an example of:',
      pf: 'Le droit des citoyens de voter et de se porter candidat est un exemple de :',
      o: ['Mobility rights', 'Democratic rights', 'Aboriginal rights', 'Property rights in the Charter'],
      of: ['Droits de circulation et d’établissement', 'Droits démocratiques', 'Droits ancestraux', 'Droits de propriété dans la Charte'],
      a: 'b',
      e: 'Democratic rights include voting in elections for the House of Commons (and provincial legislatures) and being eligible to seek office, with limited exceptions in law.',
      ef: 'Les droits démocratiques comprennent le vote aux élections à la Chambre des communes (et aux assemblées législatives provinciales) ainsi que l’admissibilité à se porter candidat, sous réserve de quelques exceptions prévues par la loi.',
    },
    {
      id: 'rnr-007',
      p: 'Equality rights in the Charter are meant to protect people from:',
      pf: 'Les droits à l’égalité garantis par la Charte visent à protéger les personnes contre :',
      o: [
        'Having to pay any taxes',
        'Discrimination by government based on grounds such as race, sex, or religion',
        'Losing a private lawsuit',
        'Provincial sales tax',
      ],
      of: [
        'L’obligation de payer quelque impôt que ce soit',
        'La discrimination par l’État fondée sur des motifs comme la race, le sexe ou la religion',
        'La perte d’une poursuite privée',
        'La taxe de vente provinciale',
      ],
      a: 'b',
      e: 'Section 15 equality rights promise equal protection and benefit of the law without discrimination. They bind government, not every private disagreement.',
      ef: 'L’article 15 sur les droits à l’égalité promet la même protection et le même bénéfice de la loi, sans discrimination. Ces droits lient l’État, et non chaque désaccord entre particuliers.',
    },
    {
      id: 'rnr-008',
      t: 'tf',
      p: 'Men and women are equal under Canadian law.',
      pf: 'Les hommes et les femmes sont égaux devant la loi canadienne.',
      a: 'true',
      e: 'Equality of women and men is a core Canadian value and is protected by the Charter’s equality rights.',
      ef: 'L’égalité des femmes et des hommes est une valeur canadienne fondamentale, protégée par les droits à l’égalité de la Charte.',
    },
    {
      id: 'rnr-009',
      p: 'Which statement about religion in Canada is correct?',
      pf: 'Quel énoncé au sujet de la religion au Canada est exact?',
      o: [
        'Canada has an official state church',
        'Only Christian worship is legal',
        'Freedom of religion is protected; there is no official state church',
        'Religious schools are banned in every province',
      ],
      of: [
        'Le Canada a une Église d’État officielle',
        'Seul le culte chrétien est légal',
        'La liberté de religion est protégée; il n’y a pas d’Église d’État officielle',
        'Les écoles religieuses sont interdites dans toutes les provinces',
      ],
      a: 'c',
      e: 'People may practise their faith—or none—within the limits of the law. Canada does not have an established church.',
      ef: 'Chacun peut pratiquer sa foi — ou n’en pratiquer aucune — dans les limites de la loi. Le Canada n’a pas d’Église établie.',
    },
    {
      id: 'rnr-010',
      p: 'Aboriginal and treaty rights of the Indigenous peoples of Canada are:',
      pf: 'Les droits ancestraux et issus de traités des peuples autochtones du Canada sont :',
      o: [
        'Abolished by the Charter',
        'Recognized and not taken away by the Charter',
        'Valid only in Yukon',
        'Decided each year by referendum',
      ],
      of: [
        'Abolis par la Charte',
        'Reconnus et maintenus par la Charte',
        'Valides au Yukon seulement',
        'Décidés chaque année par référendum',
      ],
      a: 'b',
      e: 'The Constitution, including the Charter, affirms that it does not abrogate Aboriginal and treaty rights. Those rights have their own constitutional protection.',
      ef: 'La Constitution, y compris la Charte, confirme qu’elle ne porte pas atteinte aux droits ancestraux et issus de traités. Ces droits bénéficient de leur propre protection constitutionnelle.',
    },
    {
      id: 'rnr-011',
      p: 'English and French have equal status in:',
      pf: 'L’anglais et le français ont un statut égal :',
      o: [
        'Every municipal council meeting in Canada',
        'Parliament and the Government of Canada',
        'The courts of Alberta only',
        'Private workplaces nationwide by default',
      ],
      of: [
        'À toutes les séances des conseils municipaux du Canada',
        'Au Parlement et au gouvernement du Canada',
        'Devant les tribunaux de l’Alberta seulement',
        'Dans tous les milieux de travail privés du pays, par défaut',
      ],
      a: 'b',
      e: 'Official-language rights apply to Parliament and federal institutions. Provinces have their own language rules; New Brunswick is officially bilingual as a province.',
      ef: 'Les droits linguistiques officiels s’appliquent au Parlement et aux institutions fédérales. Les provinces ont leurs propres règles linguistiques; le Nouveau-Brunswick est officiellement bilingue en tant que province.',
    },
    {
      id: 'rnr-012',
      p: 'Which of the following is a responsibility of citizenship listed in the study guide?',
      pf: 'Laquelle des options suivantes est une responsabilité de la citoyenneté énumérée dans le guide d’étude?',
      o: [
        'Obeying the law',
        'Joining a political party',
        'Serving as a senator',
        'Owning land',
      ],
      of: [
        'Respecter la loi',
        'Adhérer à un parti politique',
        'Siéger comme sénateur',
        'Posséder une terre',
      ],
      a: 'a',
      e: 'Obeying the law is a basic duty. Other listed responsibilities include voting, jury service when called, and helping in the community.',
      ef: 'Respecter la loi est un devoir de base. Les autres responsabilités énumérées comprennent voter, faire partie d’un jury sur convocation et aider dans la collectivité.',
    },
    {
      id: 'rnr-013',
      t: 'tf',
      p: 'Voting in elections is only a right, never described as a responsibility.',
      pf: 'Voter aux élections est uniquement un droit et n’est jamais présenté comme une responsabilité.',
      a: 'false',
      e: 'The study guide treats voting as both a democratic right and a civic responsibility of citizens.',
      ef: 'Le guide d’étude présente le vote à la fois comme un droit démocratique et comme une responsabilité civique des citoyens.',
    },
    {
      id: 'rnr-014',
      p: 'In a time of war, Canadian law has historically provided that:',
      pf: 'En temps de guerre, le droit canadien a historiquement prévu que :',
      o: [
        'Only senators must enlist',
        'Military-age men may be required to serve in the armed forces',
        'Children must serve on juries',
        'The Governor General must command a regiment',
      ],
      of: [
        'Seuls les sénateurs doivent s’enrôler',
        'Les hommes en âge de servir peuvent être tenus de servir dans les forces armées',
        'Les enfants doivent faire partie des jurys',
        'Le gouverneur général doit commander un régiment',
      ],
      a: 'b',
      e: 'The guide notes that men may be subject to military service in wartime. Canada has not used conscription for many decades, but the historic duty is still taught.',
      ef: 'Le guide signale que les hommes peuvent être assujettis au service militaire en temps de guerre. Le Canada n’a pas eu recours à la conscription depuis des décennies, mais ce devoir historique est toujours enseigné.',
    },
    {
      id: 'rnr-015',
      p: 'Peaceful assembly and association are protected so that people may:',
      pf: 'La réunion pacifique et l’association sont protégées afin que les personnes puissent :',
      o: [
        'Form unions, parties, and protest groups within the law',
        'Block hospitals by force with no limits',
        'Ignore Criminal Code offences if they are in a crowd',
        'Appoint judges by petition',
      ],
      of: [
        'Former des syndicats, des partis et des groupes de protestation dans le respect de la loi',
        'Bloquer des hôpitaux par la force, sans aucune limite',
        'Ignorer les infractions au Code criminel lorsqu’elles se trouvent dans une foule',
        'Nommer des juges par pétition',
      ],
      a: 'a',
      e: 'You may gather and join groups peacefully. Violence, intimidation, and other crimes are still crimes.',
      ef: 'Vous pouvez vous rassembler et adhérer à des groupes de façon pacifique. La violence, l’intimidation et les autres crimes demeurent des crimes.',
    },
    {
      id: 'rnr-016',
      p: 'A citizen’s mobility rights generally include the right to:',
      pf: 'Les droits de circulation et d’établissement d’un citoyen comprennent généralement le droit :',
      o: [
        'Enter, remain in, and leave Canada',
        'Demand a passport from another country',
        'Set immigration quotas',
        'Close a provincial border permanently',
      ],
      of: [
        'D’entrer au Canada, d’y demeurer et d’en sortir',
        'D’exiger un passeport d’un autre pays',
        'De fixer les quotas d’immigration',
        'De fermer une frontière provinciale de façon permanente',
      ],
      a: 'a',
      e: 'Citizens have the right to enter, remain in, and leave Canada, and to live and seek work in any province, subject to limited legal exceptions.',
      ef: 'Les citoyens ont le droit d’entrer au Canada, d’y demeurer et d’en sortir, ainsi que de vivre et de chercher du travail dans toute province, sous réserve de quelques exceptions prévues par la loi.',
    },
    {
      id: 'rnr-017',
      p: 'Legal rights in the Charter include protection against:',
      pf: 'Les droits juridiques garantis par la Charte comprennent la protection contre :',
      o: [
        'Unreasonable search and seizure',
        'Having to testify as a witness when subpoenaed in every civil case',
        'Paying income tax',
        'Jury duty',
      ],
      of: [
        'Les fouilles, les perquisitions et les saisies abusives',
        'L’obligation de témoigner lorsqu’on est assigné dans toute affaire civile',
        'Le paiement de l’impôt sur le revenu',
        'Le devoir de juré',
      ],
      a: 'a',
      e: 'Legal rights cover life, liberty, and security of the person; search and seizure; detention and arrest; and fair criminal process, among others.',
      ef: 'Les droits juridiques visent notamment la vie, la liberté et la sécurité de la personne; les fouilles et les saisies; la détention et l’arrestation; et l’équité du processus criminel.',
    },
    {
      id: 'rnr-018',
      t: 'tf',
      p: 'The Charter applies only to Canadian citizens in all of its sections.',
      pf: 'Tous les articles de la Charte s’appliquent uniquement aux citoyens canadiens.',
      a: 'false',
      e: 'Some rights, such as democratic rights, are for citizens. Many legal and equality rights protect “everyone” or “every individual,” including non-citizens, in Canada.',
      ef: 'Certains droits, comme les droits démocratiques, sont réservés aux citoyens. Beaucoup de droits juridiques et de droits à l’égalité protègent « chacun » ou « toute personne » au Canada, y compris les non-citoyens.',
    },
    {
      id: 'rnr-019',
      p: 'Helping others in the community is presented in the guide as:',
      pf: 'Aider les autres dans la collectivité est présenté dans le guide comme :',
      o: [
        'A legal requirement to join a church',
        'A responsibility of citizenship',
        'A duty only for mayors',
        'A substitute for paying taxes',
      ],
      of: [
        'Une obligation légale d’adhérer à une église',
        'Une responsabilité de la citoyenneté',
        'Un devoir réservé aux maires',
        'Un substitut au paiement des impôts',
      ],
      a: 'b',
      e: 'Volunteerism and looking out for neighbours are taught as civic responsibilities alongside formal legal duties.',
      ef: 'Le bénévolat et l’entraide entre voisins sont enseignés comme des responsabilités civiques, au même titre que les devoirs juridiques officiels.',
    },
    {
      id: 'rnr-020',
      p: 'Which of these is not a Charter “fundamental freedom”?',
      pf: 'Laquelle de ces libertés n’est pas une « liberté fondamentale » de la Charte?',
      o: [
        'Freedom of expression',
        'Freedom of peaceful assembly',
        'Freedom from ever being taxed',
        'Freedom of association',
      ],
      of: [
        'La liberté d’expression',
        'La liberté de réunion pacifique',
        'La liberté de ne jamais être imposé',
        'La liberté d’association',
      ],
      a: 'c',
      e: 'Taxation is a lawful government power. Fundamental freedoms are conscience and religion, expression, peaceful assembly, and association.',
      ef: 'L’imposition est un pouvoir légitime de l’État. Les libertés fondamentales sont la conscience et la religion, l’expression, la réunion pacifique et l’association.',
    },
    {
      id: 'rnr-021',
      p: 'Minority-language education rights generally protect:',
      pf: 'Les droits à l’instruction dans la langue de la minorité protègent généralement :',
      o: [
        'English or French minority communities educating their children in their language, where numbers warrant',
        'Every language in the world in every school',
        'Latin as a compulsory subject',
        'Only Indigenous-language schools in Toronto',
      ],
      of: [
        'Le droit des communautés minoritaires anglophones ou francophones de faire instruire leurs enfants dans leur langue, là où le nombre le justifie',
        'Toutes les langues du monde dans toutes les écoles',
        'Le latin comme matière obligatoire',
        'Uniquement les écoles de langues autochtones à Toronto',
      ],
      a: 'a',
      e: 'The Charter protects English or French minority-language education in specified circumstances, typically where numbers are sufficient.',
      ef: 'La Charte protège l’instruction en anglais ou en français pour la minorité dans certaines circonstances, généralement là où le nombre le justifie.',
    },
    {
      id: 'rnr-022',
      t: 'tf',
      p: 'Courts can strike down laws that unjustifiably violate the Charter.',
      pf: 'Les tribunaux peuvent invalider les lois qui violent la Charte sans justification.',
      a: 'true',
      e: 'Because the Charter is part of the Constitution, inconsistent laws can be declared of no force, subject to limited override rules in some cases.',
      ef: 'Comme la Charte fait partie de la Constitution, les lois incompatibles peuvent être déclarées inopérantes, sous réserve de règles de dérogation limitées dans certains cas.',
    },
    {
      id: 'rnr-023',
      p: 'Hate propaganda that wilfully promotes hatred against an identifiable group is:',
      pf: 'La propagande haineuse qui fomente volontairement la haine contre un groupe identifiable est :',
      o: [
        'Fully protected as ordinary political speech with no limits',
        'Restricted by criminal law because it attacks other people’s rights and safety',
        'Required reading in Parliament',
        'A municipal zoning issue only',
      ],
      of: [
        'Entièrement protégée comme un discours politique ordinaire, sans limites',
        'Restreinte par le droit criminel parce qu’elle porte atteinte aux droits et à la sécurité d’autrui',
        'Une lecture obligatoire au Parlement',
        'Une simple question de zonage municipal',
      ],
      a: 'b',
      e: 'Expression has limits. Promoting genocide or wilfully promoting hatred is a crime; rights are balanced in a free and democratic society.',
      ef: 'L’expression a des limites. Encourager le génocide ou fomenter volontairement la haine est un crime; les droits s’équilibrent dans une société libre et démocratique.',
    },
    {
      id: 'rnr-024',
      p: 'Which English legal landmark is often cited as a root of the rule of law that Canada inherited?',
      pf: 'Quel jalon du droit anglais est souvent cité comme une racine de la primauté du droit dont le Canada a hérité?',
      o: ['The Quebec Act', 'Magna Carta (1215)', 'The Official Languages Act', 'The Clarity Act'],
      of: ['L’Acte de Québec', 'La Magna Carta (1215)', 'La Loi sur les langues officielles', 'La Loi sur la clarté'],
      a: 'b',
      e: 'Magna Carta is taught as an early limit on arbitrary royal power. Canadian law also draws on later English and French sources and Canadian statutes.',
      ef: 'La Magna Carta est enseignée comme une première limite au pouvoir royal arbitraire. Le droit canadien puise aussi dans des sources anglaises et françaises plus récentes et dans les lois canadiennes.',
    },
    {
      id: 'rnr-025',
      p: 'Protecting Canada’s heritage and environment is described as:',
      pf: 'La protection du patrimoine et de l’environnement du Canada est décrite comme :',
      o: [
        'A responsibility shared by citizens',
        'The exclusive job of the Senate',
        'Illegal for private persons',
        'A municipal bylaw in Ottawa only',
      ],
      of: [
        'Une responsabilité partagée par les citoyens',
        'La tâche exclusive du Sénat',
        'Une activité illégale pour les particuliers',
        'Un règlement municipal d’Ottawa seulement',
      ],
      a: 'a',
      e: 'The guide asks citizens to help care for the natural and cultural heritage of the country, not only to claim rights.',
      ef: 'Le guide demande aux citoyens de contribuer à protéger le patrimoine naturel et culturel du pays, et pas seulement de revendiquer des droits.',
    },
    {
      id: 'rnr-026',
      t: 'tf',
      p: 'You may legally refuse a jury summons whenever you are busy at work, with no process.',
      pf: 'Vous pouvez légalement refuser une convocation à un jury chaque fois que vous êtes occupé au travail, sans aucune démarche.',
      a: 'false',
      e: 'Jury service is a duty. There are limited legal excuses and a process; simply ignoring a summons is not a right.',
      ef: 'Le service de juré est un devoir. Il existe des motifs d’exemption limités et une procédure à suivre; simplement ignorer une convocation n’est pas un droit.',
    },
    {
      id: 'rnr-027',
      p: 'If you are arrested or detained, a key legal right is:',
      pf: 'Si vous êtes arrêté ou détenu, un droit juridique essentiel est :',
      o: [
        'To be told why, and to retain and instruct counsel without delay',
        'To choose your trial judge by name',
        'To have the Prime Minister attend',
        'To skip the trial if you pay a fee',
      ],
      of: [
        'D’être informé des motifs et d’avoir recours sans délai à l’assistance d’un avocat',
        'De choisir votre juge par son nom',
        'D’exiger la présence du premier ministre',
        'D’éviter le procès en payant des frais',
      ],
      a: 'a',
      e: 'On arrest or detention you have the right to be informed of the reasons and to counsel. Use those rights; do not guess your way through an interrogation.',
      ef: 'Lors d’une arrestation ou d’une détention, vous avez le droit d’être informé des motifs et d’être assisté d’un avocat. Exercez ces droits; n’improvisez pas pendant un interrogatoire.',
    },
    {
      id: 'rnr-028',
      p: 'Forced or underage marriage, “honour” violence, and female genital mutilation are:',
      pf: 'Le mariage forcé ou de mineurs, la violence dite « d’honneur » et la mutilation génitale féminine sont :',
      o: [
        'Protected as religious freedoms with no limits',
        'Crimes in Canada; culture or religion is not a defence',
        'Civil matters only in Quebec',
        'Legal if both families agree',
      ],
      of: [
        'Protégés comme des libertés religieuses, sans limites',
        'Des crimes au Canada; la culture ou la religion n’est pas une défense',
        'Des questions civiles, au Québec seulement',
        'Légaux si les deux familles y consentent',
      ],
      a: 'b',
      e: 'Equality and security of the person outweigh claims that violence or coercion is a cultural right. These acts are crimes.',
      ef: 'L’égalité et la sécurité de la personne priment sur toute prétention voulant que la violence ou la contrainte soit un droit culturel. Ces actes sont des crimes.',
    },
    {
      id: 'rnr-029',
      p: 'Who is expected to work to eliminate discrimination and injustice?',
      pf: 'Qui doit travailler à éliminer la discrimination et l’injustice?',
      o: [
        'Only the Governor General',
        'Citizens and Canadian society as a whole',
        'Only people born in Canada',
        'Only the official opposition',
      ],
      of: [
        'Le gouverneur général seulement',
        'Les citoyens et l’ensemble de la société canadienne',
        'Les personnes nées au Canada seulement',
        'L’opposition officielle seulement',
      ],
      a: 'b',
      e: 'The guide frames fighting discrimination as a shared civic responsibility, not a task for one office.',
      ef: 'Le guide présente la lutte contre la discrimination comme une responsabilité civique partagée, et non comme la tâche d’une seule charge publique.',
    },
    {
      id: 'rnr-030',
      t: 'tf',
      p: 'The Constitution is the supreme law of Canada.',
      pf: 'La Constitution est la loi suprême du Canada.',
      a: 'true',
      e: 'Ordinary statutes must be consistent with the Constitution, including the Charter. That is the legal meaning of a supreme law.',
      ef: 'Les lois ordinaires doivent être compatibles avec la Constitution, y compris la Charte. C’est le sens juridique d’une loi suprême.',
    },
    {
      id: 'rnr-031',
      p: 'A reasonable limit on a Charter right must be:',
      pf: 'Une limite raisonnable à un droit garanti par la Charte doit être :',
      o: [
        'Whatever a police officer prefers that day',
        'Prescribed by law and demonstrably justified in a free and democratic society',
        'Approved in a municipal tweet',
        'Impossible; rights have no limits',
      ],
      of: [
        'Ce qu’un policier préfère ce jour-là',
        'Prescrite par une règle de droit et justifiée dans le cadre d’une société libre et démocratique',
        'Approuvée dans une publication municipale sur les réseaux sociaux',
        'Impossible; les droits n’ont aucune limite',
      ],
      a: 'b',
      e: 'Section 1 of the Charter allows limits that are set out in law and can be justified. It does not allow arbitrary official action.',
      ef: 'L’article 1 de la Charte permet des limites prévues par une règle de droit et dont la justification peut se démontrer. Il n’autorise pas l’action arbitraire des autorités.',
    },
    {
      id: 'rnr-032',
      p: 'Filling out the census when required is best understood as:',
      pf: 'Remplir le recensement lorsque la loi l’exige se comprend le mieux comme :',
      o: [
        'Optional trivia for hobbyists',
        'A legal duty that helps governments plan services',
        'A Senate privilege',
        'Only for landowners',
      ],
      of: [
        'Un jeu-questionnaire facultatif pour amateurs',
        'Un devoir légal qui aide les gouvernements à planifier les services',
        'Un privilège du Sénat',
        'Une obligation réservée aux propriétaires fonciers',
      ],
      a: 'b',
      e: 'The census is required by law. Accurate counts affect representation and public services. Completing it is part of obeying the law.',
      ef: 'Le recensement est exigé par la loi. Des données exactes influent sur la représentation et les services publics. Le remplir fait partie du respect de la loi.',
    },
    {
      id: 'rnr-033',
      p: 'The Charter right to life, liberty, and security of the person is an example of:',
      pf: 'Le droit à la vie, à la liberté et à la sécurité de la personne garanti par la Charte est un exemple de :',
      o: [
        'A legal right',
        'A municipal zoning power',
        'A Senate privilege only',
        'A sports eligibility rule',
      ],
      of: [
        'Un droit juridique',
        'Un pouvoir municipal de zonage',
        'Un privilège du Sénat seulement',
        'Une règle d’admissibilité sportive',
      ],
      a: 'a',
      e: 'It sits with other legal rights such as a fair trial and protection against unreasonable search. It is not a municipal by-law topic.',
      ef: 'Il figure parmi les autres droits juridiques, comme le procès équitable et la protection contre les fouilles abusives. Ce n’est pas une question de règlement municipal.',
    },
    {
      id: 'rnr-034',
      t: 'tf',
      p: 'Freedom of the press in Canada is protected as part of freedom of expression.',
      pf: 'Au Canada, la liberté de la presse est protégée dans le cadre de la liberté d’expression.',
      a: 'true',
      e: 'Thought, belief, opinion, and expression include a free press. Limits still exist, such as laws against hate propaganda and defamation.',
      ef: 'La pensée, la croyance, l’opinion et l’expression englobent une presse libre. Des limites subsistent, comme les lois contre la propagande haineuse et la diffamation.',
    },
    {
      id: 'rnr-035',
      p: 'A Canadian citizen who wants to leave the country to live abroad is generally protected by:',
      pf: 'Un citoyen canadien qui souhaite quitter le pays pour vivre à l’étranger est généralement protégé par :',
      o: [
        'Mobility rights',
        'The right to appoint Cabinet',
        'Municipal snow-clearing by-laws',
        'The royal anthem',
      ],
      of: [
        'Les droits de circulation et d’établissement',
        'Le droit de nommer le Cabinet',
        'Les règlements municipaux de déneigement',
        'L’hymne royal',
      ],
      a: 'a',
      e: 'Citizens may enter, remain in, and leave Canada. Living abroad does not, by itself, erase citizenship.',
      ef: 'Les citoyens peuvent entrer au Canada, y demeurer et en sortir. Vivre à l’étranger n’efface pas en soi la citoyenneté.',
    },
    {
      id: 'rnr-036',
      p: 'Taking the Oath of Citizenship means you promise, among other things, to:',
      pf: 'Prêter le serment de citoyenneté signifie que vous promettez, entre autres :',
      o: [
        'Be faithful to the King and observe the laws of Canada',
        'Join a political party',
        'Speak only English',
        'Serve in Cabinet',
      ],
      of: [
        'D’être fidèle au Roi et d’observer les lois du Canada',
        'D’adhérer à un parti politique',
        'De parler uniquement l’anglais',
        'De siéger au Cabinet',
      ],
      a: 'a',
      e: 'The oath is a public commitment to the Crown, the Constitution, and the laws. It is not a party membership form.',
      ef: 'Le serment est un engagement public envers la Couronne, la Constitution et les lois. Ce n’est pas un formulaire d’adhésion à un parti.',
    },
    {
      id: 'rnr-037',
      p: 'Paying legally required taxes is best classified as:',
      pf: 'Payer les impôts exigés par la loi se classe le mieux comme :',
      o: [
        'Part of obeying the law',
        'Optional if you dislike the government',
        'A Senate-only duty',
        'A municipal hobby',
      ],
      of: [
        'Une composante du respect de la loi',
        'Une option si le gouvernement vous déplaît',
        'Un devoir réservé au Sénat',
        'Un passe-temps municipal',
      ],
      a: 'a',
      e: 'The guide’s list of responsibilities starts with obeying the law. Taxes fund the services the rest of the guide describes.',
      ef: 'La liste des responsabilités du guide commence par le respect de la loi. Les impôts financent les services décrits dans le reste du guide.',
    },
    {
      id: 'rnr-038',
      t: 'tf',
      p: 'The Charter’s equality rights allow governments to run programs that help disadvantaged groups.',
      pf: 'Les droits à l’égalité de la Charte permettent aux gouvernements de mener des programmes qui aident les groupes défavorisés.',
      a: 'true',
      e: 'Equality is not a ban on every distinction. Ameliorative programs can be consistent with equality rights.',
      ef: 'L’égalité n’interdit pas toute distinction. Les programmes d’amélioration peuvent être compatibles avec les droits à l’égalité.',
    },
    {
      id: 'rnr-039',
      p: 'Which of these is a democratic right of citizens?',
      pf: 'Lequel de ces éléments est un droit démocratique des citoyens?',
      o: [
        'To run for office, subject to rules set by law',
        'To sit as a Supreme Court judge automatically',
        'To dissolve a provincial legislature by tweet',
        'To skip jury duty without a process',
      ],
      of: [
        'Se porter candidat à une charge publique, sous réserve des règles prévues par la loi',
        'Siéger automatiquement comme juge de la Cour suprême',
        'Dissoudre une assemblée législative provinciale par une publication sur les réseaux sociaux',
        'Se soustraire au devoir de juré sans aucune démarche',
      ],
      a: 'a',
      e: 'Citizens may vote and seek election. Qualifications (age, citizenship, and a few legal bars) still apply.',
      ef: 'Les citoyens peuvent voter et briguer un siège. Des conditions (âge, citoyenneté et quelques empêchements légaux) s’appliquent toujours.',
    },
    {
      id: 'rnr-040',
      p: 'Freedom of association protects, among other things, the right to:',
      pf: 'La liberté d’association protège notamment le droit :',
      o: [
        'Join a union or a peaceful group',
        'Commit a crime with friends',
        'Ignore a court order',
        'Set the Bank of Canada rate',
      ],
      of: [
        'D’adhérer à un syndicat ou à un groupe pacifique',
        'De commettre un crime entre amis',
        'D’ignorer une ordonnance judiciaire',
        'De fixer le taux de la Banque du Canada',
      ],
      a: 'a',
      e: 'Association covers unions, parties, and civic groups. It does not legalize crime.',
      ef: 'L’association vise les syndicats, les partis et les groupes civiques. Elle ne légalise pas le crime.',
    },
    {
      id: 'rnr-041',
      p: 'A person in Canada is presumed innocent until:',
      pf: 'Au Canada, une personne est présumée innocente jusqu’à ce qu’elle soit :',
      o: [
        'Proven guilty according to law in a fair trial',
        'Named in a newspaper',
        'Questioned by police',
        'The Prime Minister comments',
      ],
      of: [
        'Déclarée coupable conformément à la loi, à l’issue d’un procès équitable',
        'Nommée dans un journal',
        'Interrogée par la police',
        'Visée par un commentaire du premier ministre',
      ],
      a: 'a',
      e: 'Presumption of innocence is a core legal right. Media attention is not a verdict.',
      ef: 'La présomption d’innocence est un droit juridique fondamental. L’attention médiatique n’est pas un verdict.',
    },
    {
      id: 'rnr-042',
      t: 'tf',
      p: 'English and French have equal status as official languages of the Parliament of Canada.',
      pf: 'L’anglais et le français ont un statut égal comme langues officielles du Parlement du Canada.',
      a: 'true',
      e: 'That is a constitutional language right, separate from which language a private person uses at home.',
      ef: 'Il s’agit d’un droit linguistique constitutionnel, distinct de la langue qu’une personne utilise chez elle.',
    },
    {
      id: 'rnr-043',
      p: 'Working to protect Canada’s natural environment is presented as:',
      pf: 'Travailler à protéger l’environnement naturel du Canada est présenté comme :',
      o: [
        'A civic responsibility, not only a job for scientists',
        'Illegal under the Charter',
        'A duty of tourists only',
        'A Senate monopoly',
      ],
      of: [
        'Une responsabilité civique, et non l’affaire des seuls scientifiques',
        'Une activité illégale selon la Charte',
        'Un devoir réservé aux touristes',
        'Un monopole du Sénat',
      ],
      a: 'a',
      e: 'The guide pairs heritage and environment as things citizens should enjoy and protect.',
      ef: 'Le guide associe le patrimoine et l’environnement comme des biens que les citoyens doivent apprécier et protéger.',
    },
    {
      id: 'rnr-044',
      p: 'If a law is found to violate the Charter without justification, a court may:',
      pf: 'Si une loi est jugée contraire à la Charte sans justification, un tribunal peut :',
      o: [
        'Strike it down or limit how it applies',
        'Appoint a new Prime Minister',
        'Rewrite the national anthem',
        'Close Elections Canada',
      ],
      of: [
        'L’invalider ou en restreindre l’application',
        'Nommer un nouveau premier ministre',
        'Réécrire l’hymne national',
        'Fermer Élections Canada',
      ],
      a: 'a',
      e: 'Judicial review is how the supreme law is enforced. Courts do not take over elections.',
      ef: 'Le contrôle judiciaire est le moyen de faire respecter la loi suprême. Les tribunaux ne prennent pas en charge les élections.',
    },
    {
      id: 'rnr-045',
      p: 'Volunteering in your community is closest to which citizenship idea in the guide?',
      pf: 'Le bénévolat dans votre collectivité correspond le mieux à quelle idée de la citoyenneté dans le guide?',
      o: [
        'Helping others in the community',
        'The federal spending power',
        'Royal Assent',
        'First past the post',
      ],
      of: [
        'Aider les autres dans la collectivité',
        'Le pouvoir fédéral de dépenser',
        'La sanction royale',
        'Le scrutin majoritaire uninominal',
      ],
      a: 'a',
      e: 'The guide lists helping others as a responsibility. Formal volunteering is one way to live that idea.',
      ef: 'Le guide énumère l’entraide comme une responsabilité. Le bénévolat encadré est une façon de vivre cette idée.',
    },
    {
      id: 'rnr-046',
      t: 'tf',
      p: 'You can be a Canadian citizen and still be expected to obey Canadian law when you are in Canada.',
      pf: 'On peut être citoyen canadien et devoir tout de même respecter la loi canadienne lorsqu’on se trouve au Canada.',
      a: 'true',
      e: 'Citizenship does not create a personal exemption from the Criminal Code or tax law. Obeying the law is a listed duty.',
      ef: 'La citoyenneté ne crée aucune exemption personnelle au Code criminel ni aux lois fiscales. Respecter la loi est un devoir énuméré.',
    },
  ],
);
