import { build } from './build.mjs';

export default build('canadian-symbols', 'Discover Canada — Canadian Symbols', [
  {
    id: 'sym-001',
    p: 'Which plant appears on the Canadian flag?',
    o: ['A fleur-de-lis', 'A maple leaf', 'A shamrock', 'A rose'],
    a: 'b',
    e: 'The National Flag of Canada, adopted in 1965, is red and white with a red maple leaf at the centre.',
  },
  {
    id: 'sym-002',
    p: 'What is Canada’s national animal?',
    o: ['The moose', 'The beaver', 'The polar bear', 'The Canada goose'],
    a: 'b',
    e: 'The beaver, long tied to the fur trade, is an official emblem of Canada.',
  },
  {
    id: 'sym-003',
    p: 'Where do the Parliament Buildings stand?',
    o: ['Toronto', 'Montreal', 'Ottawa', 'Quebec City'],
    a: 'c',
    e: 'Parliament Hill in Ottawa is the seat of the federal Parliament and a widely recognized national symbol.',
  },
  {
    id: 'sym-004',
    p: 'Canada’s official colours, from a 1921 royal proclamation, are:',
    o: ['Red and white', 'Blue and gold only', 'Green and brown', 'Black and orange'],
    a: 'a',
    e: 'King George V assigned red and white. They appear on the flag and in many other emblems.',
  },
  {
    id: 'sym-005',
    p: 'The Peace Tower is part of:',
    o: ['The Parliament Buildings in Ottawa', 'Casa Loma', 'The Halifax Citadel only', 'Rideau Cottage’s garage'],
    a: 'a',
    e: 'It holds a memorial chamber for the dead of the world wars and later conflicts.',
  },
  {
    id: 'sym-006',
    p: 'Canada’s national anthem is:',
    o: ['O Canada', 'The Star-Spangled Banner', 'God Save the King only', 'La Marseillaise'],
    a: 'a',
    e: 'O Canada is the national anthem. God Save the King is the royal anthem.',
  },
  {
    id: 'sym-007',
    t: 'tf',
    p: 'God Save the King is Canada’s royal anthem.',
    a: 'true',
    e: 'It honours the Crown. It is not a replacement for O Canada at ordinary sports events.',
  },
  {
    id: 'sym-008',
    p: 'Remembrance Day is:',
    o: ['November 11', 'July 1', 'April 17', 'December 25'],
    a: 'a',
    e: 'The eleventh hour of the eleventh day of the eleventh month marks the Armistice of 1918. Wear a poppy; keep a silence.',
  },
  {
    id: 'sym-009',
    p: '“In Flanders Fields” was written by:',
    o: ['John McCrae', 'Sir John A. Macdonald', 'Calixa Lavallée', 'Emily Murphy'],
    a: 'a',
    e: 'McCrae, a Canadian medical officer in the First World War, wrote the poem that made the poppy a remembrance symbol.',
  },
  {
    id: 'sym-010',
    p: 'The Crown as a symbol stands for:',
    o: [
      'The state and the constitutional monarchy',
      'A hockey trophy only',
      'The official opposition',
      'A grocery chain',
    ],
    a: 'a',
    e: 'It appears on police and military badges, some coins, and in legal language such as Crown land.',
  },
  {
    id: 'sym-011',
    p: 'The fleur-de-lis is especially associated with:',
    o: ['French-Canadian heritage', 'Inuit drum dancing only', 'The Klondike stampede', 'NATO stars'],
    a: 'a',
    e: 'It appears on Quebec’s flag and in many French-Canadian emblems.',
  },
  {
    id: 'sym-012',
    p: 'The RCMP (“Mounties”) are a national symbol as well as:',
    o: ['A police service', 'A hockey team', 'A railway', 'A brand of maple syrup'],
    a: 'a',
    e: 'The red serge and Musical Ride are ceremonial; the force’s daily work is policing.',
  },
  {
    id: 'sym-013',
    p: 'The Order of Canada motto is:',
    o: [
      'Desiderantes meliorem patriam (they desire a better country)',
      'From sea to sea, in Latin only on hockey jerseys',
      'Liberty, equality, fraternity',
      'E pluribus unum',
    ],
    a: 'a',
    e: 'The Order honours outstanding contribution to Canada. The motto is taken from Hebrews 11:16.',
  },
  {
    id: 'sym-014',
    t: 'tf',
    p: 'Hockey is often identified as Canada’s national winter sport, and lacrosse as the national summer sport.',
    a: 'true',
    e: 'That pairing is the one the study guide expects. You do not need to be a fan.',
  },
  {
    id: 'sym-015',
    p: 'Victoria Day commemorates:',
    o: [
      'The official birthday of the Crown’s sovereign for ceremonial purposes',
      'Confederation in 1867 only',
      'D-Day',
      'Nunavut Day',
    ],
    a: 'a',
    e: 'It is a holiday tied to the monarchy (originally Queen Victoria).',
  },
  {
    id: 'sym-016',
    p: 'Canada’s coat of arms includes symbols of:',
    o: [
      'England, Scotland, Ireland, and France, among other elements',
      'Only the United States',
      'Only the Hudson’s Bay Company beaver with no shield',
      'The UN wreath alone',
    ],
    a: 'a',
    e: 'The arms record colonial heritage. They also include a maple leaf and other Canadian elements.',
  },
  {
    id: 'sym-017',
    p: 'The Library of Parliament is famous in part because:',
    o: [
      'It survived the 1916 fire that destroyed the original Centre Block',
      'It is in Vancouver',
      'It is Canada’s only hockey rink',
      'It stores all provincial flags only',
    ],
    a: 'a',
    e: 'The round library is an architectural and historic landmark on the Hill.',
  },
  {
    id: 'sym-018',
    p: 'Calixa Lavallée is associated with:',
    o: ['The music of O Canada', 'The Persons Case', 'Vimy Ridge command', 'The last spike'],
    a: 'a',
    e: 'Adolphe-Basile Routhier wrote the original French lyrics; Robert Stanley Weir wrote the English lyrics most people know.',
  },
  {
    id: 'sym-019',
    t: 'tf',
    p: 'The Union Jack has no remaining official place in Canadian symbolism.',
    a: 'false',
    e: 'The Royal Union Flag is still a symbol of membership in the Commonwealth and of allegiance to the Crown, even though it is not the national flag.',
  },
  {
    id: 'sym-020',
    p: 'Canada Day is celebrated on:',
    o: ['July 1', 'November 11', 'April 17', 'The first Monday in September only'],
    a: 'a',
    e: 'It marks Confederation (1867). It was long called Dominion Day.',
  },
  {
    id: 'sym-021',
    p: 'The maple leaf was used as a Canadian emblem:',
    o: [
      'Long before the 1965 flag, including by soldiers in the world wars',
      'Only after 1999',
      'Only in Quebec City in 1608',
      'Never, until social media',
    ],
    a: 'a',
    e: 'The flag standardized a symbol that was already in use.',
  },
  {
    id: 'sym-022',
    p: 'Rideau Hall in Ottawa is:',
    o: [
      'The Governor General’s official residence',
      'The Supreme Court’s only courtroom',
      'A provincial legislature',
      'The CN Tower’s lobby',
    ],
    a: 'a',
    e: 'It is a working residence and ceremonial site for the Crown in Canada.',
  },
  {
    id: 'sym-023',
    p: 'The loon on the one-dollar coin is an example of:',
    o: [
      'Wildlife used as a popular national emblem',
      'A British royal portrait requirement on all coins with no animals',
      'A municipal mascot from PEI only',
      'A Senate seating chart',
    ],
    a: 'a',
    e: 'The “loonie” became an unofficial popular symbol. The monarch still appears on coins too.',
  },
  {
    id: 'sym-024',
    t: 'tf',
    p: 'The poppy is worn as a symbol of remembrance, especially in November.',
    a: 'true',
    e: 'It comes from McCrae’s poem and from the poppies of the Western Front.',
  },
  {
    id: 'sym-025',
    p: 'Which building’s silhouette is most often used as a postcard of federal Canada?',
    o: ['The Parliament Buildings', 'Toronto City Hall only', 'A grain elevator in Regina only', 'A lighthouse in PEI only'],
    a: 'a',
    e: 'Centre Block and the Peace Tower are the visual shorthand for the capital.',
  },
  {
    id: 'sym-026',
    p: 'Tartans, clan symbols, and Highland games in Canada mainly reflect:',
    o: ['Scottish heritage', 'Inuit law', 'Acadian deportation policy', 'The Auto Pact'],
    a: 'a',
    e: 'They are cultural symbols of one founding immigrant stream, not official national symbols on the same level as the flag.',
  },
  {
    id: 'sym-027',
    p: 'The snowbirds of the Canadian Forces are:',
    o: [
      'A demonstration aerobatic team and a public symbol of the military',
      'A Senate committee',
      'A type of beaver',
      'A Quebec flag variant',
    ],
    a: 'a',
    e: 'Military symbols include the Forces themselves, not only historic red tunics.',
  },
  {
    id: 'sym-028',
    p: 'Which statement about the national flag is correct?',
    o: [
      'It should be treated with respect; there are customs for flying and disposing of it',
      'It may be thrown on the ground as a joke with no social meaning',
      'It is illegal to show it on a backpack',
      'It replaced O Canada as the anthem',
    ],
    a: 'a',
    e: 'Flag etiquette is taught as civic manners. The anthem is a song, not a piece of cloth.',
  },
  {
    id: 'sym-029',
    t: 'tf',
    p: 'The beaver was important to the fur-trade economy that shaped early Canada.',
    a: 'true',
    e: 'That is why it became an emblem, not because it is the largest animal.',
  },
  {
    id: 'sym-030',
    p: 'Provincial flags and floral emblems are:',
    o: [
      'Official symbols of each province and territory, used alongside national ones',
      'Illegal under the Charter',
      'Replacements for the maple leaf flag in Ottawa',
      'Only for sports teams',
    ],
    a: 'a',
    e: 'Know national symbols first, then a couple from your own province.',
  },
  {
    id: 'sym-031',
    p: 'The Memorial Chamber in the Peace Tower honours:',
    o: [
      'Canadians who died in military service',
      'Only Fathers of Confederation',
      'Only Olympic athletes',
      'Only senators',
    ],
    a: 'a',
    e: 'Books of Remembrance name the dead. It is a sacred civic space, not a tourist gimmick.',
  },
  {
    id: 'sym-032',
    t: 'tf',
    p: 'O Canada was composed in the 19th century and later became the official national anthem.',
    a: 'true',
    e: 'The song is older than its official legal status (1980). Both the history and the official date can appear on tests.',
  },
  {
    id: 'sym-033',
    p: 'Emily Carr is celebrated as:',
    o: [
      'A painter of West Coast landscapes and Indigenous village scenes',
      'Canada’s first Prime Minister',
      'The composer of God Save the King',
      'The designer of the Peace Tower clock only',
    ],
    a: 'a',
    e: 'She is a major Canadian artist often taught with the Group of Seven, even though she was not a member.',
  },
  {
    id: 'sym-034',
    p: 'The Bluenose is a Canadian symbol associated with:',
    o: [
      'A famous Nova Scotia schooner, also on the dime',
      'A Prairie grain elevator only',
      'The Senate mace in London',
      'Yukon’s territorial flower',
    ],
    a: 'a',
    e: 'It is both a maritime history story and everyday coinage.',
  },
  {
    id: 'sym-035',
    t: 'tf',
    p: 'An inuksuk (inukshuk) is a stone landmark associated especially with Inuit culture and now widely used as a northern Canadian symbol.',
    a: 'true',
    e: 'It is not a replacement for the maple leaf. It is a recognizable northern emblem, including at some public events.'
  },
  {
    id: 'sym-036',
    p: 'Canada’s Latin motto, A mari usque ad mare, means:',
    o: [
      'From sea to sea',
      'Peace, order, and good government',
      'Ready aye ready',
      'The true north strong and free only as a legal motto',
    ],
    a: 'a',
    e: 'It appears with the coat of arms. The anthem line is related in spirit but is not the heraldic motto.'
  },
  {
    id: 'sym-037',
    p: 'The National War Memorial in Ottawa (the Response) commemorates:',
    o: [
      'Canadians who served, especially those who died, beginning with the First World War',
      'Only Olympic gold medallists',
      'Only Fathers of Confederation',
      'Only the Group of Seven',
    ],
    a: 'a',
    e: 'The November 11 ceremony there is a civic ritual, not a sports rally.',
  },
  {
    id: 'sym-038',
    p: 'The mace in the House of Commons is a symbol that:',
    o: [
      'Parliament is in session and the Crown’s authority is present',
      'Hockey season has started',
      'The Senate has been abolished',
      'Municipal councils run Ottawa',
    ],
    a: 'a',
    e: 'When the mace is on the table, the House can work. It is ceremony with a constitutional meaning.'
  },
  {
    id: 'sym-039',
    t: 'tf',
    p: 'The RCMP Musical Ride is a ceremonial cavalry display that also functions as a national symbol.',
    a: 'true',
    e: 'The Force is a police service first. The Ride is how many people meet the Mountie image.',
  },
  {
    id: 'sym-040',
    p: 'Provincial floral emblems (for example the white trillium or fleur-de-lys as a cultural emblem) are:',
    o: [
      'Official or traditional symbols of provinces, used with the national maple leaf',
      'Replacements for the Canadian flag in Ottawa',
      'Illegal under official-languages law',
      'Only for hockey jerseys',
    ],
    a: 'a',
    e: 'Know the maple leaf first. A provincial flower is a bonus regional fact.',
  },
  {
    id: 'sym-041',
    p: 'The Centennial Flame on Parliament Hill marks:',
    o: [
      'Canada’s 100th anniversary in 1967',
      'Confederation debates in 1864 only',
      'The founding of NATO',
      'The Persons Case',
    ],
    a: 'a',
    e: 'It is a physical reminder of the centennial, in front of the buildings that symbolize federal Canada.',
  },
  {
    id: 'sym-042',
    p: 'The canoe is often treated as a Canadian symbol because it:',
    o: [
      'Was central to Indigenous travel and the fur-trade economy',
      'Is the official bird of Canada',
      'Replaced the maple leaf on the flag in 1965',
      'Is banned on Crown land',
    ],
    a: 'a',
    e: 'It is a historic working craft, not a coat-of-arms animal. The maple leaf remains the flag emblem.'
  },
  {
    id: 'sym-043',
    t: 'tf',
    p: 'Victoria Cross recipients in Canadian history are honoured for extreme valour in combat.',
    a: 'true',
    e: 'The VC is the highest military decoration in the Canadian honours story taught with other symbols of service.'
  },
  {
    id: 'sym-044',
    p: 'The carillon in the Peace Tower is:',
    o: [
      'A set of bells that plays for ceremonies and remembrance',
      'The Senate voting machine',
      'A Prairie grain dryer',
      'Ottawa’s subway signal',
    ],
    a: 'a',
    e: 'It is part of why the Tower is more than a clock on a postcard.'
  },
  {
    id: 'sym-045',
    p: 'The Stanley Cup is a Canadian cultural symbol because it:',
    o: [
      'Is the championship trophy of the National Hockey League, donated by Lord Stanley when he was Governor General',
      'Is the mace of the Senate',
      'Replaced O Canada in 1980',
      'Is awarded for wheat yields only',
    ],
    a: 'a',
    e: 'Hockey’s trophy has a Crown-era origin story. It is culture, not a constitutional office.'
  },
  {
    id: 'sym-046',
    p: 'The Governor General’s flag (the blue flag with the viceregal lion) is used to:',
    o: [
      'Mark the presence of the Governor General',
      'Replace the national flag forever',
      'Signal a municipal snow day in Ottawa',
      'Close the Supreme Court',
    ],
    a: 'a',
    e: 'Personal and official flags of the Crown’s representatives are a protocol symbol, not a rival national flag.'
  },
]);
