import { build } from './build.mjs';

export default build('canadian-symbols', 'Discover Canada — Canadian Symbols', [
  {
    id: 'sym-001',
    p: 'Which plant appears on the Canadian flag?',
    pf: 'Quelle plante figure sur le drapeau du Canada?',
    o: ['A fleur-de-lis', 'A maple leaf', 'A shamrock', 'A rose'],
    of: ['Une fleur de lys', 'Une feuille d’érable', 'Un trèfle', 'Une rose'],
    a: 'b',
    e: 'The National Flag of Canada, adopted in 1965, is red and white with a red maple leaf at the centre.',
    ef: 'Le drapeau national du Canada, adopté en 1965, est rouge et blanc et porte une feuille d’érable rouge en son centre.',
  },
  {
    id: 'sym-002',
    p: 'What is Canada’s national animal?',
    pf: 'Quel est l’animal national du Canada?',
    o: ['The moose', 'The beaver', 'The polar bear', 'The Canada goose'],
    of: ['L’orignal', 'Le castor', 'L’ours polaire', 'La bernache du Canada'],
    a: 'b',
    e: 'The beaver, long tied to the fur trade, is an official emblem of Canada.',
    ef: 'Le castor, longtemps lié à la traite des fourrures, est un emblème officiel du Canada.',
  },
  {
    id: 'sym-003',
    p: 'Where do the Parliament Buildings stand?',
    pf: 'Où se trouvent les édifices du Parlement?',
    o: ['Toronto', 'Montreal', 'Ottawa', 'Quebec City'],
    of: ['Toronto', 'Montréal', 'Ottawa', 'Québec'],
    a: 'c',
    e: 'Parliament Hill in Ottawa is the seat of the federal Parliament and a widely recognized national symbol.',
    ef: 'La colline du Parlement, à Ottawa, est le siège du Parlement fédéral et un symbole national largement reconnu.',
  },
  {
    id: 'sym-004',
    p: 'Canada’s official colours, from a 1921 royal proclamation, are:',
    pf: 'Les couleurs officielles du Canada, issues d’une proclamation royale de 1921, sont :',
    o: ['Red and white', 'Blue and gold only', 'Green and brown', 'Black and orange'],
    of: ['Le rouge et le blanc', 'Le bleu et l’or seulement', 'Le vert et le brun', 'Le noir et l’orange'],
    a: 'a',
    e: 'King George V assigned red and white. They appear on the flag and in many other emblems.',
    ef: 'Le roi George V a attribué le rouge et le blanc au Canada. On les retrouve sur le drapeau et dans bien d’autres emblèmes.',
  },
  {
    id: 'sym-005',
    p: 'The Peace Tower is part of:',
    pf: 'La Tour de la Paix fait partie :',
    o: ['The Parliament Buildings in Ottawa', 'Casa Loma', 'The Halifax Citadel only', 'Rideau Cottage’s garage'],
    of: ['Des édifices du Parlement, à Ottawa', 'De Casa Loma', 'De la seule Citadelle d’Halifax', 'Du garage du chalet Rideau'],
    a: 'a',
    e: 'It holds a memorial chamber for the dead of the world wars and later conflicts.',
    ef: 'Elle abrite une chapelle du Souvenir consacrée aux morts des guerres mondiales et des conflits ultérieurs.',
  },
  {
    id: 'sym-006',
    p: 'Canada’s national anthem is:',
    pf: 'L’hymne national du Canada est :',
    o: ['O Canada', 'The Star-Spangled Banner', 'God Save the King only', 'La Marseillaise'],
    of: ['Ô Canada', 'The Star-Spangled Banner', 'God Save the King seulement', 'La Marseillaise'],
    a: 'a',
    e: 'O Canada is the national anthem. God Save the King is the royal anthem.',
    ef: 'Ô Canada est l’hymne national. God Save the King est l’hymne royal.',
  },
  {
    id: 'sym-007',
    t: 'tf',
    p: 'God Save the King is Canada’s royal anthem.',
    pf: 'God Save the King est l’hymne royal du Canada.',
    a: 'true',
    e: 'It honours the Crown. It is not a replacement for O Canada at ordinary sports events.',
    ef: 'Il rend hommage à la Couronne. Il ne remplace pas l’Ô Canada lors des événements sportifs ordinaires.',
  },
  {
    id: 'sym-008',
    p: 'Remembrance Day is:',
    pf: 'Le jour du Souvenir a lieu :',
    o: ['November 11', 'July 1', 'April 17', 'December 25'],
    of: ['Le 11 novembre', 'Le 1er juillet', 'Le 17 avril', 'Le 25 décembre'],
    a: 'a',
    e: 'The eleventh hour of the eleventh day of the eleventh month marks the Armistice of 1918. Wear a poppy; keep a silence.',
    ef: 'La onzième heure du onzième jour du onzième mois rappelle l’armistice de 1918. Portez le coquelicot; observez la minute de silence.',
  },
  {
    id: 'sym-009',
    p: '“In Flanders Fields” was written by:',
    pf: 'Le poème « In Flanders Fields » (Au champ d’honneur) a été écrit par :',
    o: ['John McCrae', 'Sir John A. Macdonald', 'Calixa Lavallée', 'Emily Murphy'],
    of: ['John McCrae', 'Sir John A. Macdonald', 'Calixa Lavallée', 'Emily Murphy'],
    a: 'a',
    e: 'McCrae, a Canadian medical officer in the First World War, wrote the poem that made the poppy a remembrance symbol.',
    ef: 'McCrae, médecin militaire canadien pendant la Première Guerre mondiale, a écrit le poème qui a fait du coquelicot un symbole du souvenir.',
  },
  {
    id: 'sym-010',
    p: 'The Crown as a symbol stands for:',
    pf: 'Comme symbole, la Couronne représente :',
    o: [
      'The state and the constitutional monarchy',
      'A hockey trophy only',
      'The official opposition',
      'A grocery chain',
    ],
    of: [
      'L’État et la monarchie constitutionnelle',
      'Un trophée de hockey seulement',
      'L’opposition officielle',
      'Une chaîne d’alimentation',
    ],
    a: 'a',
    e: 'It appears on police and military badges, some coins, and in legal language such as Crown land.',
    ef: 'Elle figure sur les insignes des policiers et des militaires, sur certaines pièces de monnaie et dans le vocabulaire juridique, comme les terres de la Couronne.',
  },
  {
    id: 'sym-011',
    p: 'The fleur-de-lis is especially associated with:',
    pf: 'La fleur de lys est surtout associée :',
    o: ['French-Canadian heritage', 'Inuit drum dancing only', 'The Klondike stampede', 'NATO stars'],
    of: ['À l’héritage canadien-français', 'À la seule danse du tambour chez les Inuits', 'À la ruée vers le Klondike', 'Aux étoiles de l’OTAN'],
    a: 'a',
    e: 'It appears on Quebec’s flag and in many French-Canadian emblems.',
    ef: 'Elle figure sur le drapeau du Québec et dans de nombreux emblèmes canadiens-français.',
  },
  {
    id: 'sym-012',
    p: 'The RCMP (“Mounties”) are a national symbol as well as:',
    pf: 'La Gendarmerie royale du Canada est un symbole national, mais aussi :',
    o: ['A police service', 'A hockey team', 'A railway', 'A brand of maple syrup'],
    of: ['Un service de police', 'Une équipe de hockey', 'Un chemin de fer', 'Une marque de sirop d’érable'],
    a: 'a',
    e: 'The red serge and Musical Ride are ceremonial; the force’s daily work is policing.',
    ef: 'La tunique rouge et le Carrousel relèvent du cérémonial; le travail quotidien de la Gendarmerie, c’est le maintien de l’ordre.',
  },
  {
    id: 'sym-013',
    p: 'The Order of Canada motto is:',
    pf: 'La devise de l’Ordre du Canada est :',
    o: [
      'Desiderantes meliorem patriam (they desire a better country)',
      'From sea to sea, in Latin only on hockey jerseys',
      'Liberty, equality, fraternity',
      'E pluribus unum',
    ],
    of: [
      'Desiderantes meliorem patriam (ils désirent une patrie meilleure)',
      'D’un océan à l’autre, en latin uniquement sur les chandails de hockey',
      'Liberté, égalité, fraternité',
      'E pluribus unum',
    ],
    a: 'a',
    e: 'The Order honours outstanding contribution to Canada. The motto is taken from Hebrews 11:16.',
    ef: 'L’Ordre souligne une contribution exceptionnelle au Canada. La devise est tirée de l’Épître aux Hébreux, chapitre 11, verset 16.',
  },
  {
    id: 'sym-014',
    t: 'tf',
    p: 'Hockey is often identified as Canada’s national winter sport, and lacrosse as the national summer sport.',
    pf: 'Le hockey est souvent désigné comme le sport national d’hiver du Canada, et la crosse comme le sport national d’été.',
    a: 'true',
    e: 'That pairing is the one the study guide expects. You do not need to be a fan.',
    ef: 'C’est le couple que le guide d’étude attend. Nul besoin d’être un amateur de sport.',
  },
  {
    id: 'sym-015',
    p: 'Victoria Day commemorates:',
    pf: 'La fête de Victoria souligne :',
    o: [
      'The official birthday of the Crown’s sovereign for ceremonial purposes',
      'Confederation in 1867 only',
      'D-Day',
      'Nunavut Day',
    ],
    of: [
      'L’anniversaire officiel du souverain de la Couronne, à des fins cérémonielles',
      'La seule Confédération de 1867',
      'Le jour J',
      'La Journée du Nunavut',
    ],
    a: 'a',
    e: 'It is a holiday tied to the monarchy (originally Queen Victoria).',
    ef: 'C’est un congé lié à la monarchie, rattaché à l’origine à la reine Victoria.',
  },
  {
    id: 'sym-016',
    p: 'Canada’s coat of arms includes symbols of:',
    pf: 'Les armoiries du Canada comprennent des symboles :',
    o: [
      'England, Scotland, Ireland, and France, among other elements',
      'Only the United States',
      'Only the Hudson’s Bay Company beaver with no shield',
      'The UN wreath alone',
    ],
    of: [
      'De l’Angleterre, de l’Écosse, de l’Irlande et de la France, parmi d’autres éléments',
      'Des États-Unis seulement',
      'Du seul castor de la Compagnie de la Baie d’Hudson, sans écu',
      'De la seule couronne de feuillage de l’ONU',
    ],
    a: 'a',
    e: 'The arms record colonial heritage. They also include a maple leaf and other Canadian elements.',
    ef: 'Les armoiries rappellent l’héritage colonial. Elles comportent aussi une feuille d’érable et d’autres éléments canadiens.',
  },
  {
    id: 'sym-017',
    p: 'The Library of Parliament is famous in part because:',
    pf: 'La Bibliothèque du Parlement est célèbre en partie parce que :',
    o: [
      'It survived the 1916 fire that destroyed the original Centre Block',
      'It is in Vancouver',
      'It is Canada’s only hockey rink',
      'It stores all provincial flags only',
    ],
    of: [
      'Elle a survécu à l’incendie de 1916 qui a détruit l’édifice du Centre d’origine',
      'Elle se trouve à Vancouver',
      'C’est la seule patinoire de hockey du Canada',
      'Elle ne conserve que les drapeaux provinciaux',
    ],
    a: 'a',
    e: 'The round library is an architectural and historic landmark on the Hill.',
    ef: 'La bibliothèque circulaire est un monument architectural et historique de la colline du Parlement.',
  },
  {
    id: 'sym-018',
    p: 'Calixa Lavallée is associated with:',
    pf: 'Calixa Lavallée est associé :',
    o: ['The music of O Canada', 'The Persons Case', 'Vimy Ridge command', 'The last spike'],
    of: ['À la musique de l’Ô Canada', 'À l’affaire « personne »', 'Au commandement à la crête de Vimy', 'Au dernier crampon'],
    a: 'a',
    e: 'Adolphe-Basile Routhier wrote the original French lyrics; Robert Stanley Weir wrote the English lyrics most people know.',
    ef: 'Adolphe-Basile Routhier a signé les paroles françaises d’origine; Robert Stanley Weir a écrit les paroles anglaises que la plupart des gens connaissent.',
  },
  {
    id: 'sym-019',
    t: 'tf',
    p: 'The Union Jack has no remaining official place in Canadian symbolism.',
    pf: 'L’Union Jack n’a plus aucune place officielle dans la symbolique canadienne.',
    a: 'false',
    e: 'The Royal Union Flag is still a symbol of membership in the Commonwealth and of allegiance to the Crown, even though it is not the national flag.',
    ef: 'Le drapeau royal de l’Union demeure un symbole de l’appartenance au Commonwealth et de l’allégeance à la Couronne, même s’il n’est pas le drapeau national.',
  },
  {
    id: 'sym-020',
    p: 'Canada Day is celebrated on:',
    pf: 'La fête du Canada est célébrée :',
    o: ['July 1', 'November 11', 'April 17', 'The first Monday in September only'],
    of: ['Le 1er juillet', 'Le 11 novembre', 'Le 17 avril', 'Le premier lundi de septembre seulement'],
    a: 'a',
    e: 'It marks Confederation (1867). It was long called Dominion Day.',
    ef: 'Elle souligne la Confédération de 1867. On l’a longtemps appelée la fête du Dominion.',
  },
  {
    id: 'sym-021',
    p: 'The maple leaf was used as a Canadian emblem:',
    pf: 'La feuille d’érable a servi d’emblème canadien :',
    o: [
      'Long before the 1965 flag, including by soldiers in the world wars',
      'Only after 1999',
      'Only in Quebec City in 1608',
      'Never, until social media',
    ],
    of: [
      'Bien avant le drapeau de 1965, notamment chez les soldats des guerres mondiales',
      'Seulement après 1999',
      'Seulement à Québec, en 1608',
      'Jamais, avant les médias sociaux',
    ],
    a: 'a',
    e: 'The flag standardized a symbol that was already in use.',
    ef: 'Le drapeau a officialisé un symbole qui était déjà en usage.',
  },
  {
    id: 'sym-022',
    p: 'Rideau Hall in Ottawa is:',
    pf: 'Rideau Hall, à Ottawa, est :',
    o: [
      'The Governor General’s official residence',
      'The Supreme Court’s only courtroom',
      'A provincial legislature',
      'The CN Tower’s lobby',
    ],
    of: [
      'La résidence officielle du gouverneur général',
      'La seule salle d’audience de la Cour suprême',
      'Une législature provinciale',
      'Le hall d’entrée de la Tour CN',
    ],
    a: 'a',
    e: 'It is a working residence and ceremonial site for the Crown in Canada.',
    ef: 'C’est à la fois une résidence en activité et un lieu cérémoniel de la Couronne au Canada.',
  },
  {
    id: 'sym-023',
    p: 'The loon on the one-dollar coin is an example of:',
    pf: 'Le plongeon huard sur la pièce de un dollar est un exemple :',
    o: [
      'Wildlife used as a popular national emblem',
      'A British royal portrait requirement on all coins with no animals',
      'A municipal mascot from PEI only',
      'A Senate seating chart',
    ],
    of: [
      'D’un animal sauvage devenu un emblème national populaire',
      'D’une obligation de faire figurer un portrait royal britannique sur toutes les pièces, sans aucun animal',
      'D’une mascotte municipale de l’Île-du-Prince-Édouard seulement',
      'D’un plan de sièges du Sénat',
    ],
    a: 'a',
    e: 'The “loonie” became an unofficial popular symbol. The monarch still appears on coins too.',
    ef: 'Le « huard » est devenu un symbole populaire non officiel. Le monarque figure encore lui aussi sur les pièces.',
  },
  {
    id: 'sym-024',
    t: 'tf',
    p: 'The poppy is worn as a symbol of remembrance, especially in November.',
    pf: 'On porte le coquelicot comme symbole du souvenir, surtout en novembre.',
    a: 'true',
    e: 'It comes from McCrae’s poem and from the poppies of the Western Front.',
    ef: 'Il vient du poème de McCrae et des coquelicots du front de l’Ouest.',
  },
  {
    id: 'sym-025',
    p: 'Which building’s silhouette is most often used as a postcard of federal Canada?',
    pf: 'Quelle silhouette d’édifice sert le plus souvent de carte postale du Canada fédéral?',
    o: ['The Parliament Buildings', 'Toronto City Hall only', 'A grain elevator in Regina only', 'A lighthouse in PEI only'],
    of: ['Les édifices du Parlement', 'L’hôtel de ville de Toronto seulement', 'Un silo à grains de Regina seulement', 'Un phare de l’Île-du-Prince-Édouard seulement'],
    a: 'a',
    e: 'Centre Block and the Peace Tower are the visual shorthand for the capital.',
    ef: 'L’édifice du Centre et la Tour de la Paix sont le raccourci visuel de la capitale.',
  },
  {
    id: 'sym-026',
    p: 'Tartans, clan symbols, and Highland games in Canada mainly reflect:',
    pf: 'Au Canada, les tartans, les symboles de clans et les jeux des Highlands reflètent surtout :',
    o: ['Scottish heritage', 'Inuit law', 'Acadian deportation policy', 'The Auto Pact'],
    of: ['L’héritage écossais', 'Le droit inuit', 'La politique de déportation des Acadiens', 'Le Pacte de l’automobile'],
    a: 'a',
    e: 'They are cultural symbols of one founding immigrant stream, not official national symbols on the same level as the flag.',
    ef: 'Ce sont des symboles culturels de l’un des grands courants d’immigration fondateurs, et non des symboles nationaux officiels du même rang que le drapeau.',
  },
  {
    id: 'sym-027',
    p: 'The snowbirds of the Canadian Forces are:',
    pf: 'Les Snowbirds des Forces canadiennes sont :',
    o: [
      'A demonstration aerobatic team and a public symbol of the military',
      'A Senate committee',
      'A type of beaver',
      'A Quebec flag variant',
    ],
    of: [
      'Une équipe de démonstration de voltige aérienne et un symbole public des forces armées',
      'Un comité du Sénat',
      'Une espèce de castor',
      'Une variante du drapeau du Québec',
    ],
    a: 'a',
    e: 'Military symbols include the Forces themselves, not only historic red tunics.',
    ef: 'Les symboles militaires comprennent les forces armées elles-mêmes, et pas seulement les tuniques rouges d’autrefois.',
  },
  {
    id: 'sym-028',
    p: 'Which statement about the national flag is correct?',
    pf: 'Quel énoncé au sujet du drapeau national est exact?',
    o: [
      'It should be treated with respect; there are customs for flying and disposing of it',
      'It may be thrown on the ground as a joke with no social meaning',
      'It is illegal to show it on a backpack',
      'It replaced O Canada as the anthem',
    ],
    of: [
      'Il faut le traiter avec respect; des usages encadrent la façon de le hisser et de s’en départir',
      'On peut le jeter par terre pour blaguer, sans que cela ait la moindre portée sociale',
      'Il est illégal de l’afficher sur un sac à dos',
      'Il a remplacé l’Ô Canada comme hymne',
    ],
    a: 'a',
    e: 'Flag etiquette is taught as civic manners. The anthem is a song, not a piece of cloth.',
    ef: 'L’étiquette du drapeau s’enseigne comme une règle de savoir-vivre civique. L’hymne est un chant, non un morceau de tissu.',
  },
  {
    id: 'sym-029',
    t: 'tf',
    p: 'The beaver was important to the fur-trade economy that shaped early Canada.',
    pf: 'Le castor a joué un rôle important dans l’économie de la traite des fourrures qui a façonné les débuts du Canada.',
    a: 'true',
    e: 'That is why it became an emblem, not because it is the largest animal.',
    ef: 'C’est pour cette raison qu’il est devenu un emblème, et non parce qu’il serait le plus gros animal.',
  },
  {
    id: 'sym-030',
    p: 'Provincial flags and floral emblems are:',
    pf: 'Les drapeaux et les emblèmes floraux des provinces sont :',
    o: [
      'Official symbols of each province and territory, used alongside national ones',
      'Illegal under the Charter',
      'Replacements for the maple leaf flag in Ottawa',
      'Only for sports teams',
    ],
    of: [
      'Des symboles officiels de chaque province et territoire, utilisés en parallèle avec les symboles nationaux',
      'Illégaux en vertu de la Charte',
      'Des remplacements du drapeau à la feuille d’érable à Ottawa',
      'Réservés aux équipes sportives',
    ],
    a: 'a',
    e: 'Know national symbols first, then a couple from your own province.',
    ef: 'Apprenez d’abord les symboles nationaux, puis quelques-uns de votre province.',
  },
  {
    id: 'sym-031',
    p: 'The Memorial Chamber in the Peace Tower honours:',
    pf: 'La Chapelle du Souvenir, dans la Tour de la Paix, honore :',
    o: [
      'Canadians who died in military service',
      'Only Fathers of Confederation',
      'Only Olympic athletes',
      'Only senators',
    ],
    of: [
      'Les Canadiens morts au service militaire',
      'Seulement les Pères de la Confédération',
      'Seulement les athlètes olympiques',
      'Seulement les sénateurs',
    ],
    a: 'a',
    e: 'Books of Remembrance name the dead. It is a sacred civic space, not a tourist gimmick.',
    ef: 'Les Livres du Souvenir nomment les morts. C’est un lieu civique sacré, et non une attraction touristique.',
  },
  {
    id: 'sym-032',
    t: 'tf',
    p: 'O Canada was composed in the 19th century and later became the official national anthem.',
    pf: 'L’Ô Canada a été composé au XIXe siècle et est devenu plus tard l’hymne national officiel.',
    a: 'true',
    e: 'The song is older than its official legal status (1980). Both the history and the official date can appear on tests.',
    ef: 'Le chant est plus ancien que son statut juridique officiel (1980). L’histoire comme la date officielle peuvent faire l’objet d’une question à l’examen.',
  },
  {
    id: 'sym-033',
    p: 'Emily Carr is celebrated as:',
    pf: 'Emily Carr est célébrée comme :',
    o: [
      'A painter of West Coast landscapes and Indigenous village scenes',
      'Canada’s first Prime Minister',
      'The composer of God Save the King',
      'The designer of the Peace Tower clock only',
    ],
    of: [
      'Une peintre des paysages de la côte Ouest et de scènes de villages autochtones',
      'La première personne à diriger le Canada comme premier ministre',
      'La compositrice de God Save the King',
      'La conceptrice de la seule horloge de la Tour de la Paix',
    ],
    a: 'a',
    e: 'She is a major Canadian artist often taught with the Group of Seven, even though she was not a member.',
    ef: 'C’est une artiste canadienne majeure, souvent enseignée avec le Groupe des Sept, même si elle n’en faisait pas partie.',
  },
  {
    id: 'sym-034',
    p: 'The Bluenose is a Canadian symbol associated with:',
    pf: 'Le Bluenose est un symbole canadien associé :',
    o: [
      'A famous Nova Scotia schooner, also on the dime',
      'A Prairie grain elevator only',
      'The Senate mace in London',
      'Yukon’s territorial flower',
    ],
    of: [
      'À une célèbre goélette de la Nouvelle-Écosse, qui figure aussi sur la pièce de dix cents',
      'À un seul silo à grains des Prairies',
      'À la masse du Sénat, à Londres',
      'À la fleur emblème du Yukon',
    ],
    a: 'a',
    e: 'It is both a maritime history story and everyday coinage.',
    ef: 'C’est à la fois une histoire maritime et une image de la monnaie de tous les jours.',
  },
  {
    id: 'sym-035',
    t: 'tf',
    p: 'An inuksuk (inukshuk) is a stone landmark associated especially with Inuit culture and now widely used as a northern Canadian symbol.',
    pf: 'Un inuksuk (inukshuk) est un repère de pierre associé tout particulièrement à la culture inuite et largement utilisé aujourd’hui comme symbole du Nord canadien.',
    a: 'true',
    e: 'It is not a replacement for the maple leaf. It is a recognizable northern emblem, including at some public events.',
    ef: 'Il ne remplace pas la feuille d’érable. C’est un emblème nordique facile à reconnaître, présent notamment lors de certains événements publics.'
  },
  {
    id: 'sym-036',
    p: 'Canada’s Latin motto, A mari usque ad mare, means:',
    pf: 'La devise latine du Canada, A mari usque ad mare, signifie :',
    o: [
      'From sea to sea',
      'Peace, order, and good government',
      'Ready aye ready',
      'The true north strong and free only as a legal motto',
    ],
    of: [
      'D’un océan à l’autre',
      'Paix, ordre et bon gouvernement',
      'Toujours prêt',
      'Le vrai Nord fort et libre, uniquement à titre de devise juridique',
    ],
    a: 'a',
    e: 'It appears with the coat of arms. The anthem line is related in spirit but is not the heraldic motto.',
    ef: 'Elle accompagne les armoiries. Le vers de l’hymne s’en rapproche par l’esprit, mais ce n’est pas la devise héraldique.'
  },
  {
    id: 'sym-037',
    p: 'The National War Memorial in Ottawa (the Response) commemorates:',
    pf: 'Le Monument commémoratif de guerre du Canada, à Ottawa (La Réponse), commémore :',
    o: [
      'Canadians who served, especially those who died, beginning with the First World War',
      'Only Olympic gold medallists',
      'Only Fathers of Confederation',
      'Only the Group of Seven',
    ],
    of: [
      'Les Canadiens qui ont servi, surtout ceux qui sont morts, depuis la Première Guerre mondiale',
      'Seulement les médaillés d’or olympiques',
      'Seulement les Pères de la Confédération',
      'Seulement le Groupe des Sept',
    ],
    a: 'a',
    e: 'The November 11 ceremony there is a civic ritual, not a sports rally.',
    ef: 'La cérémonie du 11 novembre qui s’y déroule est un rituel civique, et non un rassemblement sportif.',
  },
  {
    id: 'sym-038',
    p: 'The mace in the House of Commons is a symbol that:',
    pf: 'À la Chambre des communes, la masse est un symbole qui indique :',
    o: [
      'Parliament is in session and the Crown’s authority is present',
      'Hockey season has started',
      'The Senate has been abolished',
      'Municipal councils run Ottawa',
    ],
    of: [
      'Que le Parlement siège et que l’autorité de la Couronne est présente',
      'Que la saison de hockey est commencée',
      'Que le Sénat a été aboli',
      'Que les conseils municipaux dirigent Ottawa',
    ],
    a: 'a',
    e: 'When the mace is on the table, the House can work. It is ceremony with a constitutional meaning.',
    ef: 'Quand la masse repose sur la table, la Chambre peut siéger. C’est un cérémonial à portée constitutionnelle.'
  },
  {
    id: 'sym-039',
    t: 'tf',
    p: 'The RCMP Musical Ride is a ceremonial cavalry display that also functions as a national symbol.',
    pf: 'Le Carrousel de la Gendarmerie royale du Canada est une démonstration équestre cérémonielle qui fait aussi office de symbole national.',
    a: 'true',
    e: 'The Force is a police service first. The Ride is how many people meet the Mountie image.',
    ef: 'La Gendarmerie est d’abord un service de police. Le Carrousel est la façon dont bien des gens découvrent l’image du policier à cheval.',
  },
  {
    id: 'sym-040',
    p: 'Provincial floral emblems (for example the white trillium or fleur-de-lys as a cultural emblem) are:',
    pf: 'Les emblèmes floraux des provinces (par exemple le trille blanc, ou la fleur de lys comme emblème culturel) sont :',
    o: [
      'Official or traditional symbols of provinces, used with the national maple leaf',
      'Replacements for the Canadian flag in Ottawa',
      'Illegal under official-languages law',
      'Only for hockey jerseys',
    ],
    of: [
      'Des symboles officiels ou traditionnels des provinces, utilisés avec la feuille d’érable nationale',
      'Des remplacements du drapeau canadien à Ottawa',
      'Illégaux en vertu de la loi sur les langues officielles',
      'Réservés aux chandails de hockey',
    ],
    a: 'a',
    e: 'Know the maple leaf first. A provincial flower is a bonus regional fact.',
    ef: 'Apprenez d’abord la feuille d’érable. La fleur d’une province est un fait régional en prime.',
  },
  {
    id: 'sym-041',
    p: 'The Centennial Flame on Parliament Hill marks:',
    pf: 'La Flamme du centenaire, sur la colline du Parlement, souligne :',
    o: [
      'Canada’s 100th anniversary in 1967',
      'Confederation debates in 1864 only',
      'The founding of NATO',
      'The Persons Case',
    ],
    of: [
      'Le 100e anniversaire du Canada, en 1967',
      'Seulement les débats sur la Confédération, en 1864',
      'La fondation de l’OTAN',
      'L’affaire « personne »',
    ],
    a: 'a',
    e: 'It is a physical reminder of the centennial, in front of the buildings that symbolize federal Canada.',
    ef: 'C’est un rappel concret du centenaire, devant les édifices qui symbolisent le Canada fédéral.',
  },
  {
    id: 'sym-042',
    p: 'The canoe is often treated as a Canadian symbol because it:',
    pf: 'Le canot est souvent considéré comme un symbole canadien parce qu’il :',
    o: [
      'Was central to Indigenous travel and the fur-trade economy',
      'Is the official bird of Canada',
      'Replaced the maple leaf on the flag in 1965',
      'Is banned on Crown land',
    ],
    of: [
      'A été au cœur des déplacements autochtones et de l’économie de la traite des fourrures',
      'Est l’oiseau officiel du Canada',
      'A remplacé la feuille d’érable sur le drapeau en 1965',
      'Est interdit sur les terres de la Couronne',
    ],
    a: 'a',
    e: 'It is a historic working craft, not a coat-of-arms animal. The maple leaf remains the flag emblem.',
    ef: 'C’est une embarcation de travail historique, et non un animal des armoiries. La feuille d’érable demeure l’emblème du drapeau.'
  },
  {
    id: 'sym-043',
    t: 'tf',
    p: 'Victoria Cross recipients in Canadian history are honoured for extreme valour in combat.',
    pf: 'Dans l’histoire canadienne, les récipiendaires de la Croix de Victoria sont honorés pour leur bravoure exceptionnelle au combat.',
    a: 'true',
    e: 'The VC is the highest military decoration in the Canadian honours story taught with other symbols of service.',
    ef: 'La Croix de Victoria est la plus haute distinction militaire du régime canadien des honneurs, enseignée avec les autres symboles du service.'
  },
  {
    id: 'sym-044',
    p: 'The carillon in the Peace Tower is:',
    pf: 'Le carillon de la Tour de la Paix est :',
    o: [
      'A set of bells that plays for ceremonies and remembrance',
      'The Senate voting machine',
      'A Prairie grain dryer',
      'Ottawa’s subway signal',
    ],
    of: [
      'Un ensemble de cloches qui sonne pour les cérémonies et le souvenir',
      'La machine à voter du Sénat',
      'Un séchoir à grain des Prairies',
      'Le signal du métro d’Ottawa',
    ],
    a: 'a',
    e: 'It is part of why the Tower is more than a clock on a postcard.',
    ef: 'C’est une des raisons pour lesquelles la Tour est plus qu’une horloge sur une carte postale.'
  },
  {
    id: 'sym-045',
    p: 'The Stanley Cup is a Canadian cultural symbol because it:',
    pf: 'La Coupe Stanley est un symbole culturel canadien parce qu’elle :',
    o: [
      'Is the championship trophy of the National Hockey League, donated by Lord Stanley when he was Governor General',
      'Is the mace of the Senate',
      'Replaced O Canada in 1980',
      'Is awarded for wheat yields only',
    ],
    of: [
      'Est le trophée des champions de la Ligue nationale de hockey, offert par lord Stanley alors qu’il était gouverneur général',
      'Est la masse du Sénat',
      'A remplacé l’Ô Canada en 1980',
      'Est décernée uniquement pour les rendements de blé',
    ],
    a: 'a',
    e: 'Hockey’s trophy has a Crown-era origin story. It is culture, not a constitutional office.',
    ef: 'Le trophée du hockey doit son origine à un représentant de la Couronne. C’est de la culture, et non une charge constitutionnelle.'
  },
  {
    id: 'sym-046',
    p: 'The Governor General’s flag (the blue flag with the viceregal lion) is used to:',
    pf: 'Le drapeau du gouverneur général (le drapeau bleu au lion vice-royal) sert :',
    o: [
      'Mark the presence of the Governor General',
      'Replace the national flag forever',
      'Signal a municipal snow day in Ottawa',
      'Close the Supreme Court',
    ],
    of: [
      'À marquer la présence du gouverneur général',
      'À remplacer le drapeau national pour toujours',
      'À annoncer une journée de neige municipale à Ottawa',
      'À fermer la Cour suprême',
    ],
    a: 'a',
    e: 'Personal and official flags of the Crown’s representatives are a protocol symbol, not a rival national flag.',
    ef: 'Les drapeaux personnels et officiels des représentants de la Couronne sont un symbole protocolaire, et non un drapeau national concurrent.'
  },
  {
    id: 'sym-047',
    p: 'What is the highest military honour a Canadian can receive?',
    pf: 'Quelle est la plus haute distinction militaire qu’un Canadien puisse recevoir?',
    o: ['The Victoria Cross', 'The Order of Canada only', 'A Senate appointment', 'The Speakers’ Chain of Office'],
    of: ['La Croix de Victoria', 'L’Ordre du Canada seulement', 'Une nomination au Sénat', 'Le collier du président de la Chambre'],
    a: 'a',
    e: 'The Victoria Cross is the highest award for valour in the face of the enemy. The Order of Canada is a civilian honour for outstanding contribution.',
    ef: 'La Croix de Victoria est la plus haute distinction pour bravoure face à l’ennemi. L’Ordre du Canada est une distinction civile pour une contribution exceptionnelle.',
  },
]);
