import { build } from './build.mjs';

export default build('who-we-are', 'Discover Canada — Who We Are', [
  {
    id: 'wwa-001',
    p: 'Which three groups are recognized as Indigenous peoples in Canada?',
    o: [
      'First Nations, Inuit, and Métis',
      'Inuit, Acadians, and Loyalists',
      'Métis, Voyageurs, and Acadians',
      'First Nations, Ukrainians, and Inuit',
    ],
    a: 'a',
    e: 'Canada recognizes First Nations, Inuit, and Métis as the Indigenous peoples of this land, each with distinct histories, languages, and cultures.',
  },
  {
    id: 'wwa-002',
    p: 'What are Canada’s two official languages?',
    o: ['English and Spanish', 'French and Cree', 'English and French', 'French and Inuktitut'],
    a: 'c',
    e: 'English and French have equal status in Parliament and the Government of Canada. Many other languages are spoken, including Indigenous languages.',
  },
  {
    id: 'wwa-003',
    t: 'tf',
    p: 'The Métis are a people of mixed First Nations and European ancestry who developed their own culture and identity.',
    a: 'true',
    e: 'Métis communities formed especially on the Prairies, with a distinct culture, including Michif in some communities, and a history tied to the fur trade.',
  },
  {
    id: 'wwa-004',
    p: 'Where do most Inuit communities lie?',
    o: [
      'In the Arctic (Inuit Nunangat)',
      'Only in southern Ontario',
      'Only on Vancouver Island',
      'Only in the Annapolis Valley',
    ],
    a: 'a',
    e: 'Inuit are the Indigenous people of the Arctic. Their homeland is often called Inuit Nunangat, spanning land, water, and ice in the north.',
  },
  {
    id: 'wwa-005',
    p: 'First Nations in Canada are best described as:',
    o: [
      'A single nation with one language',
      'Many distinct nations with their own languages and governments',
      'A European settler group',
      'Residents of Nunavut only',
    ],
    a: 'b',
    e: 'Hundreds of First Nations live in every region. They are not one people with one language or government.',
  },
  {
    id: 'wwa-006',
    t: 'tf',
    p: 'The Inuit are one of the First Nations.',
    a: 'false',
    e: 'Inuit are Indigenous but distinct from First Nations. The three recognized groups are First Nations, Inuit, and Métis.',
  },
  {
    id: 'wwa-007',
    p: 'Who are the Acadians?',
    o: [
      'Descendants of early French settlers in the Maritimes',
      'A First Nation of the Prairies',
      'Loyalists from New York only',
      'Inuit from Labrador only',
    ],
    a: 'a',
    e: 'Acadian communities descend from 17th- and 18th-century French settlement in what is now the Maritimes, especially New Brunswick, Nova Scotia, and PEI.',
  },
  {
    id: 'wwa-008',
    p: 'What happened to many Acadians in the 1750s?',
    o: [
      'They were elected to the first House of Commons',
      'They were deported from their lands by the British',
      'They founded Vancouver',
      'They wrote the Charter',
    ],
    a: 'b',
    e: 'During the Seven Years’ War, British authorities expelled thousands of Acadians. Many later returned; the deportation remains a central Acadian memory.',
  },
  {
    id: 'wwa-009',
    p: 'United Empire Loyalists were people who:',
    o: [
      'Left the United States for British North America after the American Revolution',
      'Founded New France in 1608',
      'Signed Treaty 7 in Alberta only',
      'Created Nunavut in 1999',
    ],
    a: 'a',
    e: 'Loyalists who would not join the American republic moved north, strengthening English-speaking settlement in the Maritimes and in what became Ontario.',
  },
  {
    id: 'wwa-010',
    p: 'Which province has a French-speaking majority?',
    o: ['Ontario', 'Quebec', 'Alberta', 'Newfoundland and Labrador'],
    a: 'b',
    e: 'Quebec is the only province with a French-speaking majority. French is also important in New Brunswick and in communities elsewhere.',
  },
  {
    id: 'wwa-011',
    p: 'Canada is often described, in area, as:',
    o: [
      'The smallest G7 country',
      'The world’s second-largest country',
      'Smaller than France',
      'An island in the Caribbean',
    ],
    a: 'b',
    e: 'Canada spans a huge landmass. Most people live in cities in a relatively narrow band near the U.S. border.',
  },
  {
    id: 'wwa-012',
    t: 'tf',
    p: 'Most Canadians live in rural areas far from cities.',
    a: 'false',
    e: 'Canada is highly urban. A large majority live in towns and cities, especially in the south.',
  },
  {
    id: 'wwa-013',
    p: 'Chinese workers in the 19th century are especially remembered for:',
    o: [
      'Building much of the Canadian Pacific Railway through the mountains',
      'Founding Halifax',
      'Writing the BNA Act',
      'Discovering the Klondike before anyone else',
    ],
    a: 'a',
    e: 'Chinese labour was essential to the western railway. Canada later imposed a head tax and exclusion laws, now recognized as racist injustice.',
  },
  {
    id: 'wwa-014',
    p: 'Ukrainian settlement is especially associated with:',
    o: ['The Prairies', 'Prince Edward Island only', 'Downtown Halifax in the 1600s', 'The Senate of 1867'],
    a: 'a',
    e: 'From the 1890s on, many Ukrainians farmed on the Prairies and became a major cultural community in Manitoba, Saskatchewan, and Alberta.',
  },
  {
    id: 'wwa-015',
    p: 'Black Loyalists and later Black refugees are an important part of the history of:',
    o: ['Nova Scotia', 'Nunavut', 'Yukon only', 'Prince Edward Island’s capital buildings'],
    a: 'a',
    e: 'People of African descent who backed Britain, and others who escaped slavery, settled in Nova Scotia (and elsewhere). Their history is part of who Canada is.',
  },
  {
    id: 'wwa-016',
    p: 'A large Sikh and broader South Asian community has long been part of:',
    o: ['British Columbia, especially the Lower Mainland', 'Only Newfoundland outports', 'Only Nunavut hamlets', 'The 1867 Senate'],
    a: 'a',
    e: 'Punjabi Sikh immigrants arrived in B.C. more than a century ago, faced exclusion, and are now a major community in Greater Vancouver and beyond.',
  },
  {
    id: 'wwa-017',
    p: 'Treaties between Indigenous nations and the Crown are:',
    o: [
      'Historic and living agreements that still have legal force',
      'Expired automatically in 1867',
      'Tourism slogans with no legal meaning',
      'Municipal bylaws',
    ],
    a: 'a',
    e: 'Historic and modern treaties set out rights and relationships. They are part of Canada’s constitutional order, not museum pieces.',
  },
  {
    id: 'wwa-018',
    t: 'tf',
    p: 'English and French are the only languages spoken in Canada.',
    a: 'false',
    e: 'They are the official languages of the federal state. Indigenous languages and many immigrant languages are widely spoken.',
  },
  {
    id: 'wwa-019',
    p: 'The fur trade linked Indigenous nations with:',
    o: [
      'French and later British commercial empires, including the Hudson’s Bay Company',
      'The World Bank in 1944',
      'NATO headquarters',
      'The Supreme Court registry',
    ],
    a: 'a',
    e: 'The fur trade shaped early contact, Métis communities, and the map of posts that later became towns.',
  },
  {
    id: 'wwa-020',
    p: 'Irish immigration in the 19th century grew sharply because of:',
    o: ['The Great Famine and other hardship', 'The Quiet Revolution', 'The Klondike gold rush only', 'Nunavut’s creation'],
    a: 'a',
    e: 'Famine and poverty drove large Irish migration to British North American cities and to work on canals and railways.',
  },
  {
    id: 'wwa-021',
    p: 'Scottish settlement left a strong mark on:',
    o: [
      'Nova Scotia (literally “New Scotland”) and other regions',
      'Only the Yukon gold fields',
      'Only Nunavut hamlets',
      'The 1982 Charter’s French text alone',
    ],
    a: 'a',
    e: 'Highland and Lowland Scots settled in the Maritimes, Ontario, and the West. Nova Scotia’s name records that history.',
  },
  {
    id: 'wwa-022',
    p: 'Canada’s population today is:',
    o: [
      'Drawn from Indigenous peoples and many waves of immigration',
      'Unchanged since 1608',
      'Made up only of English Loyalists',
      'Forbidden to include newcomers',
    ],
    a: 'a',
    e: 'Indigenous nations were here first. French and British colonial societies followed, then immigration from around the world.',
  },
  {
    id: 'wwa-023',
    t: 'tf',
    p: 'Quebec’s society is rooted in a French-speaking, historically Catholic culture that survived the British Conquest.',
    a: 'true',
    e: 'The Quebec Act and later constitutional arrangements allowed that society to keep its language, faith, and civil law.',
  },
  {
    id: 'wwa-024',
    p: 'Which phrase best matches federal multiculturalism as taught for the test?',
    o: [
      'People may keep cultural traditions while sharing Canada’s laws and civic values',
      'Every province must have the same official church',
      'Only two cultures are allowed',
      'Immigrants must abandon all food and music from home',
    ],
    a: 'a',
    e: 'Diversity is expected. It does not suspend the Criminal Code, equality of women and men, or democratic rules.',
  },
  {
    id: 'wwa-025',
    p: 'The largest city in Canada is:',
    o: ['Toronto', 'Ottawa', 'Quebec City', 'Charlottetown'],
    a: 'a',
    e: 'Toronto is the most populous city. Ottawa is the national capital. Do not mix the two on the test.',
  },
  {
    id: 'wwa-026',
    p: 'A “founding” colonial pair often named in the guide is:',
    o: ['French and British', 'Spanish and Portuguese', 'Dutch and Russian', 'American and Mexican'],
    a: 'a',
    e: 'French and British institutions, languages, and legal traditions shaped the colonial state—on Indigenous lands that were already occupied.',
  },
  {
    id: 'wwa-027',
    t: 'tf',
    p: 'Métis identity is simply “anyone with one Indigenous grandparent,” with no distinct culture.',
    a: 'false',
    e: 'Métis are a people with a historic culture and communities, not a casual mixed-ancestry label for the test’s purposes.',
  },
  {
    id: 'wwa-028',
    p: 'Which city is Canada’s largest French-speaking metropolis?',
    o: ['Montreal', 'Calgary', 'Victoria', 'St. John’s'],
    a: 'a',
    e: 'Montreal is the principal French-speaking city of Canada (and a bilingual metropolis in daily life). Quebec City is the provincial capital.',
  },
  {
    id: 'wwa-029',
    p: 'Indigenous peoples were in what is now Canada:',
    o: [
      'For thousands of years before European settlement',
      'Only after Confederation',
      'Only after the War of 1812',
      'Only in the 20th century',
    ],
    a: 'a',
    e: 'That is the starting point of the “who we are” story: this is not an empty land that began in 1867.',
  },
  {
    id: 'wwa-030',
    p: 'Many Canadians today were born outside Canada, especially in:',
    o: [
      'Large cities such as Toronto, Montreal, and Vancouver',
      'Only fly-in Arctic hamlets',
      'Only the Senate chamber',
      'Only Prince Edward Island farms in 1864',
    ],
    a: 'a',
    e: 'Immigration is concentrated in big metro areas, which is why those cities are so diverse.',
  },
  {
    id: 'wwa-031',
    t: 'tf',
    p: 'New Brunswick is the only officially bilingual province.',
    a: 'true',
    e: 'Federally, Canada is bilingual. Among provinces, only New Brunswick is officially bilingual in its own constitution.',
  },
  {
    id: 'wwa-032',
    p: 'The term “Québécois” most often refers to:',
    o: [
      'The people of Quebec, especially the French-speaking majority and their culture',
      'Only senators from Ottawa',
      'Inuit of the western Arctic',
      'Acadians of Louisiana only',
    ],
    a: 'a',
    e: 'It names a national and cultural identity centred on Quebec. It is not a synonym for all Canadians.',
  },
  {
    id: 'wwa-033',
    p: 'Residential schools were:',
    o: [
      'A system that took Indigenous children from their families and attacked their languages and cultures',
      'Ordinary public high schools in Toronto',
      'Military colleges for Loyalists',
      'French lycées in Paris',
    ],
    a: 'a',
    e: 'The schools were a grave injustice. The guide is brief; an informed citizen should still know what they were.',
  },
  {
    id: 'wwa-034',
    p: 'Anglophone and Francophone communities both exist:',
    o: [
      'Across Canada, not only in one province',
      'Only in Yukon',
      'Only inside the Parliament Buildings',
      'Only before 1763',
    ],
    a: 'a',
    e: 'English-speaking majorities live in most provinces; French-speaking communities exist from the Acadian regions through Quebec to the West.',
  },
  {
    id: 'wwa-035',
    t: 'tf',
    p: 'Indigenous peoples all share one culture and one language.',
    a: 'false',
    e: 'Diversity among First Nations, Inuit, and Métis—and among First Nations themselves—is a basic fact for the test.',
  },
]);
