import { build } from './build.mjs';

export default build('who-we-are', 'Discover Canada — Who We Are', [
  {
    id: 'wwa-001',
    p: 'Which three groups are recognized as Indigenous peoples in Canada?',
    pf: 'Quels sont les trois groupes reconnus comme peuples autochtones au Canada?',
    o: [
      'First Nations, Inuit, and Métis',
      'Inuit, Acadians, and Loyalists',
      'Métis, Voyageurs, and Acadians',
      'First Nations, Ukrainians, and Inuit',
    ],
    of: [
      'Les Premières Nations, les Inuit et les Métis',
      'Les Inuit, les Acadiens et les Loyalistes',
      'Les Métis, les voyageurs et les Acadiens',
      'Les Premières Nations, les Ukrainiens et les Inuit',
    ],
    a: 'a',
    e: 'Canada recognizes First Nations, Inuit, and Métis as the Indigenous peoples of this land, each with distinct histories, languages, and cultures.',
    ef: 'Le Canada reconnaît les Premières Nations, les Inuit et les Métis comme les peuples autochtones de ce territoire, chacun ayant ses propres histoires, langues et cultures.',
  },
  {
    id: 'wwa-002',
    p: 'What are Canada’s two official languages?',
    pf: 'Quelles sont les deux langues officielles du Canada?',
    o: ['English and Spanish', 'French and Cree', 'English and French', 'French and Inuktitut'],
    of: ['L’anglais et l’espagnol', 'Le français et le cri', 'L’anglais et le français', 'Le français et l’inuktitut'],
    a: 'c',
    e: 'English and French have equal status in Parliament and the Government of Canada. Many other languages are spoken, including Indigenous languages.',
    ef: 'L’anglais et le français ont un statut égal au Parlement et au gouvernement du Canada. De nombreuses autres langues sont parlées, dont des langues autochtones.',
  },
  {
    id: 'wwa-003',
    t: 'tf',
    p: 'The Métis are a people of mixed First Nations and European ancestry who developed their own culture and identity.',
    pf: 'Les Métis sont un peuple d’ascendance mixte, à la fois des Premières Nations et européenne, qui a développé sa propre culture et sa propre identité.',
    a: 'true',
    e: 'Métis communities formed especially on the Prairies, with a distinct culture, including Michif in some communities, and a history tied to the fur trade.',
    ef: 'Les communautés métisses se sont formées surtout dans les Prairies, avec une culture distincte, dont le michif dans certaines communautés, et une histoire liée à la traite des fourrures.',
  },
  {
    id: 'wwa-004',
    p: 'Where do most Inuit communities lie?',
    pf: 'Où se trouvent la plupart des communautés inuites?',
    o: [
      'In the Arctic (Inuit Nunangat)',
      'Only in southern Ontario',
      'Only on Vancouver Island',
      'Only in the Annapolis Valley',
    ],
    of: [
      'Dans l’Arctique (l’Inuit Nunangat)',
      'Dans le sud de l’Ontario seulement',
      'Sur l’île de Vancouver seulement',
      'Dans la vallée de l’Annapolis seulement',
    ],
    a: 'a',
    e: 'Inuit are the Indigenous people of the Arctic. Their homeland is often called Inuit Nunangat, spanning land, water, and ice in the north.',
    ef: 'Les Inuit sont le peuple autochtone de l’Arctique. Leur patrie est souvent appelée Inuit Nunangat et englobe la terre, l’eau et la glace du Nord.',
  },
  {
    id: 'wwa-005',
    p: 'First Nations in Canada are best described as:',
    pf: 'Les Premières Nations du Canada se décrivent le mieux comme :',
    o: [
      'A single nation with one language',
      'Many distinct nations with their own languages and governments',
      'A European settler group',
      'Residents of Nunavut only',
    ],
    of: [
      'Une seule nation parlant une seule langue',
      'De nombreuses nations distinctes ayant leurs propres langues et gouvernements',
      'Un groupe de colons européens',
      'Des résidents du Nunavut seulement',
    ],
    a: 'b',
    e: 'Hundreds of First Nations live in every region. They are not one people with one language or government.',
    ef: 'Des centaines de Premières Nations vivent dans toutes les régions. Elles ne forment pas un seul peuple avec une seule langue ou un seul gouvernement.',
  },
  {
    id: 'wwa-006',
    t: 'tf',
    p: 'The Inuit are one of the First Nations.',
    pf: 'Les Inuit sont l’une des Premières Nations.',
    a: 'false',
    e: 'Inuit are Indigenous but distinct from First Nations. The three recognized groups are First Nations, Inuit, and Métis.',
    ef: 'Les Inuit sont autochtones, mais distincts des Premières Nations. Les trois groupes reconnus sont les Premières Nations, les Inuit et les Métis.',
  },
  {
    id: 'wwa-007',
    p: 'Who are the Acadians?',
    pf: 'Qui sont les Acadiens?',
    o: [
      'Descendants of early French settlers in the Maritimes',
      'A First Nation of the Prairies',
      'Loyalists from New York only',
      'Inuit from Labrador only',
    ],
    of: [
      'Les descendants des premiers colons français des Maritimes',
      'Une Première Nation des Prairies',
      'Des Loyalistes venus de New York seulement',
      'Des Inuit du Labrador seulement',
    ],
    a: 'a',
    e: 'Acadian communities descend from 17th- and 18th-century French settlement in what is now the Maritimes, especially New Brunswick, Nova Scotia, and PEI.',
    ef: 'Les communautés acadiennes descendent de la colonisation française des 17e et 18e siècles dans ce qui est aujourd’hui les Maritimes, surtout au Nouveau-Brunswick, en Nouvelle-Écosse et à l’Île-du-Prince-Édouard.',
  },
  {
    id: 'wwa-008',
    p: 'What happened to many Acadians in the 1750s?',
    pf: 'Qu’est-il arrivé à de nombreux Acadiens dans les années 1750?',
    o: [
      'They were elected to the first House of Commons',
      'They were deported from their lands by the British',
      'They founded Vancouver',
      'They wrote the Charter',
    ],
    of: [
      'Ils ont été élus à la première Chambre des communes',
      'Ils ont été déportés de leurs terres par les Britanniques',
      'Ils ont fondé Vancouver',
      'Ils ont rédigé la Charte',
    ],
    a: 'b',
    e: 'During the Seven Years’ War, British authorities expelled thousands of Acadians. Many later returned; the deportation remains a central Acadian memory.',
    ef: 'Pendant la guerre de Sept Ans, les autorités britanniques ont expulsé des milliers d’Acadiens. Beaucoup sont revenus par la suite; la déportation demeure un souvenir central de l’Acadie.',
  },
  {
    id: 'wwa-009',
    p: 'United Empire Loyalists were people who:',
    pf: 'Les Loyalistes de l’Empire-Uni étaient des personnes qui :',
    o: [
      'Left the United States for British North America after the American Revolution',
      'Founded New France in 1608',
      'Signed Treaty 7 in Alberta only',
      'Created Nunavut in 1999',
    ],
    of: [
      'Ont quitté les États-Unis pour l’Amérique du Nord britannique après la Révolution américaine',
      'Ont fondé la Nouvelle-France en 1608',
      'Ont signé le Traité no 7 en Alberta seulement',
      'Ont créé le Nunavut en 1999',
    ],
    a: 'a',
    e: 'Loyalists who would not join the American republic moved north, strengthening English-speaking settlement in the Maritimes and in what became Ontario.',
    ef: 'Les Loyalistes qui refusaient de se joindre à la république américaine sont montés vers le nord, renforçant la colonisation anglophone dans les Maritimes et dans ce qui allait devenir l’Ontario.',
  },
  {
    id: 'wwa-010',
    p: 'Which province has a French-speaking majority?',
    pf: 'Quelle province compte une majorité francophone?',
    o: ['Ontario', 'Quebec', 'Alberta', 'Newfoundland and Labrador'],
    of: ['L’Ontario', 'Le Québec', 'L’Alberta', 'Terre-Neuve-et-Labrador'],
    a: 'b',
    e: 'Quebec is the only province with a French-speaking majority. French is also important in New Brunswick and in communities elsewhere.',
    ef: 'Le Québec est la seule province à majorité francophone. Le français est aussi important au Nouveau-Brunswick et dans des communautés ailleurs au pays.',
  },
  {
    id: 'wwa-011',
    p: 'Canada is often described, in area, as:',
    pf: 'Par sa superficie, le Canada est souvent décrit comme :',
    o: [
      'The smallest G7 country',
      'The world’s second-largest country',
      'Smaller than France',
      'An island in the Caribbean',
    ],
    of: [
      'Le plus petit pays du G7',
      'Le deuxième plus grand pays du monde',
      'Un pays plus petit que la France',
      'Une île des Caraïbes',
    ],
    a: 'b',
    e: 'Canada spans a huge landmass. Most people live in cities in a relatively narrow band near the U.S. border.',
    ef: 'Le Canada s’étend sur un immense territoire. La plupart des gens vivent dans des villes situées dans une bande relativement étroite près de la frontière américaine.',
  },
  {
    id: 'wwa-012',
    t: 'tf',
    p: 'Most Canadians live in rural areas far from cities.',
    pf: 'La plupart des Canadiens vivent en milieu rural, loin des villes.',
    a: 'false',
    e: 'Canada is highly urban. A large majority live in towns and cities, especially in the south.',
    ef: 'Le Canada est très urbanisé. Une forte majorité vit dans des villes et des villages, surtout dans le sud.',
  },
  {
    id: 'wwa-013',
    p: 'Chinese workers in the 19th century are especially remembered for:',
    pf: 'Au 19e siècle, les travailleurs chinois sont surtout reconnus pour :',
    o: [
      'Building much of the Canadian Pacific Railway through the mountains',
      'Founding Halifax',
      'Writing the BNA Act',
      'Discovering the Klondike before anyone else',
    ],
    of: [
      'Avoir construit une grande partie du chemin de fer Canadien Pacifique à travers les montagnes',
      'Avoir fondé Halifax',
      'Avoir rédigé l’Acte de l’Amérique du Nord britannique',
      'Avoir découvert le Klondike avant tout le monde',
    ],
    a: 'a',
    e: 'Chinese labour was essential to the western railway. Canada later imposed a head tax and exclusion laws, now recognized as racist injustice.',
    ef: 'La main-d’œuvre chinoise a été essentielle au chemin de fer de l’Ouest. Le Canada a ensuite imposé une taxe d’entrée et des lois d’exclusion, aujourd’hui reconnues comme une injustice raciste.',
  },
  {
    id: 'wwa-014',
    p: 'Ukrainian settlement is especially associated with:',
    pf: 'La colonisation ukrainienne est surtout associée :',
    o: ['The Prairies', 'Prince Edward Island only', 'Downtown Halifax in the 1600s', 'The Senate of 1867'],
    of: ['Aux Prairies', 'À l’Île-du-Prince-Édouard seulement', 'Au centre-ville de Halifax au 17e siècle', 'Au Sénat de 1867'],
    a: 'a',
    e: 'From the 1890s on, many Ukrainians farmed on the Prairies and became a major cultural community in Manitoba, Saskatchewan, and Alberta.',
    ef: 'À partir des années 1890, de nombreux Ukrainiens ont cultivé la terre dans les Prairies et sont devenus une communauté culturelle majeure au Manitoba, en Saskatchewan et en Alberta.',
  },
  {
    id: 'wwa-015',
    p: 'Black Loyalists and later Black refugees are an important part of the history of:',
    pf: 'Les Loyalistes noirs et, plus tard, les réfugiés noirs occupent une place importante dans l’histoire :',
    o: ['Nova Scotia', 'Nunavut', 'Yukon only', 'Prince Edward Island’s capital buildings'],
    of: ['De la Nouvelle-Écosse', 'Du Nunavut', 'Du Yukon seulement', 'Des édifices de la capitale de l’Île-du-Prince-Édouard'],
    a: 'a',
    e: 'People of African descent who backed Britain, and others who escaped slavery, settled in Nova Scotia (and elsewhere). Their history is part of who Canada is.',
    ef: 'Des personnes d’ascendance africaine qui ont appuyé la Grande-Bretagne, et d’autres qui ont fui l’esclavage, se sont établies en Nouvelle-Écosse (et ailleurs). Leur histoire fait partie de ce qu’est le Canada.',
  },
  {
    id: 'wwa-016',
    p: 'A large Sikh and broader South Asian community has long been part of:',
    pf: 'Une importante communauté sikhe, et plus largement sud-asiatique, fait partie depuis longtemps :',
    o: ['British Columbia, especially the Lower Mainland', 'Only Newfoundland outports', 'Only Nunavut hamlets', 'The 1867 Senate'],
    of: ['De la Colombie-Britannique, surtout du Lower Mainland', 'Des villages côtiers de Terre-Neuve seulement', 'Des hameaux du Nunavut seulement', 'Du Sénat de 1867'],
    a: 'a',
    e: 'Punjabi Sikh immigrants arrived in B.C. more than a century ago, faced exclusion, and are now a major community in Greater Vancouver and beyond.',
    ef: 'Des immigrants sikhs du Pendjab sont arrivés en Colombie-Britannique il y a plus d’un siècle, ont subi l’exclusion et forment aujourd’hui une communauté majeure dans le Grand Vancouver et ailleurs.',
  },
  {
    id: 'wwa-017',
    p: 'Treaties between Indigenous nations and the Crown are:',
    pf: 'Les traités conclus entre les nations autochtones et la Couronne sont :',
    o: [
      'Historic and living agreements that still have legal force',
      'Expired automatically in 1867',
      'Tourism slogans with no legal meaning',
      'Municipal bylaws',
    ],
    of: [
      'Des ententes historiques et vivantes qui ont toujours force de loi',
      'Des ententes expirées automatiquement en 1867',
      'Des slogans touristiques sans portée juridique',
      'Des règlements municipaux',
    ],
    a: 'a',
    e: 'Historic and modern treaties set out rights and relationships. They are part of Canada’s constitutional order, not museum pieces.',
    ef: 'Les traités historiques et modernes établissent des droits et des relations. Ils font partie de l’ordre constitutionnel du Canada et ne sont pas des pièces de musée.',
  },
  {
    id: 'wwa-018',
    t: 'tf',
    p: 'English and French are the only languages spoken in Canada.',
    pf: 'L’anglais et le français sont les seules langues parlées au Canada.',
    a: 'false',
    e: 'They are the official languages of the federal state. Indigenous languages and many immigrant languages are widely spoken.',
    ef: 'Ce sont les langues officielles de l’État fédéral. Les langues autochtones et de nombreuses langues d’immigration sont largement parlées.',
  },
  {
    id: 'wwa-019',
    p: 'The fur trade linked Indigenous nations with:',
    pf: 'La traite des fourrures a relié les nations autochtones :',
    o: [
      'French and later British commercial empires, including the Hudson’s Bay Company',
      'The World Bank in 1944',
      'NATO headquarters',
      'The Supreme Court registry',
    ],
    of: [
      'Aux empires commerciaux français, puis britanniques, dont la Compagnie de la Baie d’Hudson',
      'À la Banque mondiale en 1944',
      'Au quartier général de l’OTAN',
      'Au greffe de la Cour suprême',
    ],
    a: 'a',
    e: 'The fur trade shaped early contact, Métis communities, and the map of posts that later became towns.',
    ef: 'La traite des fourrures a façonné les premiers contacts, les communautés métisses et la carte des postes devenus plus tard des villes.',
  },
  {
    id: 'wwa-020',
    p: 'Irish immigration in the 19th century grew sharply because of:',
    pf: 'Au 19e siècle, l’immigration irlandaise a fortement augmenté en raison :',
    o: ['The Great Famine and other hardship', 'The Quiet Revolution', 'The Klondike gold rush only', 'Nunavut’s creation'],
    of: ['De la Grande Famine et d’autres épreuves', 'De la Révolution tranquille', 'De la ruée vers l’or du Klondike seulement', 'De la création du Nunavut'],
    a: 'a',
    e: 'Famine and poverty drove large Irish migration to British North American cities and to work on canals and railways.',
    ef: 'La famine et la pauvreté ont provoqué une forte migration irlandaise vers les villes de l’Amérique du Nord britannique et vers les chantiers de canaux et de chemins de fer.',
  },
  {
    id: 'wwa-021',
    p: 'Scottish settlement left a strong mark on:',
    pf: 'La colonisation écossaise a laissé une forte empreinte :',
    o: [
      'Nova Scotia (literally “New Scotland”) and other regions',
      'Only the Yukon gold fields',
      'Only Nunavut hamlets',
      'The 1982 Charter’s French text alone',
    ],
    of: [
      'Sur la Nouvelle-Écosse (littéralement « nouvelle Écosse ») et d’autres régions',
      'Sur les champs aurifères du Yukon seulement',
      'Sur les hameaux du Nunavut seulement',
      'Sur le texte français de la Charte de 1982 uniquement',
    ],
    a: 'a',
    e: 'Highland and Lowland Scots settled in the Maritimes, Ontario, and the West. Nova Scotia’s name records that history.',
    ef: 'Des Écossais des Highlands et des Lowlands se sont établis dans les Maritimes, en Ontario et dans l’Ouest. Le nom de la Nouvelle-Écosse rappelle cette histoire.',
  },
  {
    id: 'wwa-022',
    p: 'Canada’s population today is:',
    pf: 'La population du Canada aujourd’hui est :',
    o: [
      'Drawn from Indigenous peoples and many waves of immigration',
      'Unchanged since 1608',
      'Made up only of English Loyalists',
      'Forbidden to include newcomers',
    ],
    of: [
      'Issue des peuples autochtones et de nombreuses vagues d’immigration',
      'Inchangée depuis 1608',
      'Composée uniquement de Loyalistes anglais',
      'Interdite d’accueillir de nouveaux arrivants',
    ],
    a: 'a',
    e: 'Indigenous nations were here first. French and British colonial societies followed, then immigration from around the world.',
    ef: 'Les nations autochtones étaient ici les premières. Les sociétés coloniales française et britannique ont suivi, puis l’immigration venue du monde entier.',
  },
  {
    id: 'wwa-023',
    t: 'tf',
    p: 'Quebec’s society is rooted in a French-speaking, historically Catholic culture that survived the British Conquest.',
    pf: 'La société québécoise est enracinée dans une culture francophone, historiquement catholique, qui a survécu à la Conquête britannique.',
    a: 'true',
    e: 'The Quebec Act and later constitutional arrangements allowed that society to keep its language, faith, and civil law.',
    ef: 'L’Acte de Québec et les arrangements constitutionnels ultérieurs ont permis à cette société de conserver sa langue, sa foi et son droit civil.',
  },
  {
    id: 'wwa-024',
    p: 'Which phrase best matches federal multiculturalism as taught for the test?',
    pf: 'Quel énoncé correspond le mieux au multiculturalisme fédéral tel qu’il est enseigné pour l’examen?',
    o: [
      'People may keep cultural traditions while sharing Canada’s laws and civic values',
      'Every province must have the same official church',
      'Only two cultures are allowed',
      'Immigrants must abandon all food and music from home',
    ],
    of: [
      'Les gens peuvent conserver leurs traditions culturelles tout en partageant les lois et les valeurs civiques du Canada',
      'Chaque province doit avoir la même Église officielle',
      'Seules deux cultures sont permises',
      'Les immigrants doivent abandonner toute la cuisine et la musique de leur pays d’origine',
    ],
    a: 'a',
    e: 'Diversity is expected. It does not suspend the Criminal Code, equality of women and men, or democratic rules.',
    ef: 'La diversité est attendue. Elle ne suspend ni le Code criminel, ni l’égalité des femmes et des hommes, ni les règles démocratiques.',
  },
  {
    id: 'wwa-025',
    p: 'The largest city in Canada is:',
    pf: 'La plus grande ville du Canada est :',
    o: ['Toronto', 'Ottawa', 'Quebec City', 'Charlottetown'],
    of: ['Toronto', 'Ottawa', 'Québec', 'Charlottetown'],
    a: 'a',
    e: 'Toronto is the most populous city. Ottawa is the national capital. Do not mix the two on the test.',
    ef: 'Toronto est la ville la plus peuplée. Ottawa est la capitale nationale. Ne confondez pas les deux à l’examen.',
  },
  {
    id: 'wwa-026',
    p: 'A “founding” colonial pair often named in the guide is:',
    pf: 'Le duo colonial « fondateur » souvent nommé dans le guide est :',
    o: ['French and British', 'Spanish and Portuguese', 'Dutch and Russian', 'American and Mexican'],
    of: ['Les Français et les Britanniques', 'Les Espagnols et les Portugais', 'Les Néerlandais et les Russes', 'Les Américains et les Mexicains'],
    a: 'a',
    e: 'French and British institutions, languages, and legal traditions shaped the colonial state—on Indigenous lands that were already occupied.',
    ef: 'Les institutions, les langues et les traditions juridiques françaises et britanniques ont façonné l’État colonial — sur des terres autochtones déjà occupées.',
  },
  {
    id: 'wwa-027',
    t: 'tf',
    p: 'Métis identity is simply “anyone with one Indigenous grandparent,” with no distinct culture.',
    pf: 'L’identité métisse se résume à « toute personne ayant un grand-parent autochtone », sans culture distincte.',
    a: 'false',
    e: 'Métis are a people with a historic culture and communities, not a casual mixed-ancestry label for the test’s purposes.',
    ef: 'Les Métis sont un peuple doté d’une culture et de communautés historiques, et non une simple étiquette d’ascendance mixte aux fins de l’examen.',
  },
  {
    id: 'wwa-028',
    p: 'Which city is Canada’s largest French-speaking metropolis?',
    pf: 'Quelle ville est la plus grande métropole francophone du Canada?',
    o: ['Montreal', 'Calgary', 'Victoria', 'St. John’s'],
    of: ['Montréal', 'Calgary', 'Victoria', 'St. John’s'],
    a: 'a',
    e: 'Montreal is the principal French-speaking city of Canada (and a bilingual metropolis in daily life). Quebec City is the provincial capital.',
    ef: 'Montréal est la principale ville francophone du Canada (et une métropole bilingue au quotidien). Québec est la capitale provinciale.',
  },
  {
    id: 'wwa-029',
    p: 'Indigenous peoples were in what is now Canada:',
    pf: 'Les peuples autochtones se trouvaient sur le territoire actuel du Canada :',
    o: [
      'For thousands of years before European settlement',
      'Only after Confederation',
      'Only after the War of 1812',
      'Only in the 20th century',
    ],
    of: [
      'Depuis des milliers d’années avant la colonisation européenne',
      'Seulement après la Confédération',
      'Seulement après la guerre de 1812',
      'Seulement au 20e siècle',
    ],
    a: 'a',
    e: 'That is the starting point of the “who we are” story: this is not an empty land that began in 1867.',
    ef: 'C’est le point de départ du récit « qui nous sommes » : ce n’est pas une terre vide dont l’histoire commence en 1867.',
  },
  {
    id: 'wwa-030',
    p: 'Many Canadians today were born outside Canada, especially in:',
    pf: 'Beaucoup de Canadiens d’aujourd’hui sont nés à l’étranger et vivent surtout :',
    o: [
      'Large cities such as Toronto, Montreal, and Vancouver',
      'Only fly-in Arctic hamlets',
      'Only the Senate chamber',
      'Only Prince Edward Island farms in 1864',
    ],
    of: [
      'Dans de grandes villes comme Toronto, Montréal et Vancouver',
      'Dans des hameaux arctiques accessibles par avion seulement',
      'Dans la chambre du Sénat seulement',
      'Dans les fermes de l’Île-du-Prince-Édouard en 1864 seulement',
    ],
    a: 'a',
    e: 'Immigration is concentrated in big metro areas, which is why those cities are so diverse.',
    ef: 'L’immigration se concentre dans les grandes régions métropolitaines, ce qui explique la grande diversité de ces villes.',
  },
  {
    id: 'wwa-031',
    t: 'tf',
    p: 'New Brunswick is the only officially bilingual province.',
    pf: 'Le Nouveau-Brunswick est la seule province officiellement bilingue.',
    a: 'true',
    e: 'Federally, Canada is bilingual. Among provinces, only New Brunswick is officially bilingual in its own constitution.',
    ef: 'Au fédéral, le Canada est bilingue. Parmi les provinces, seul le Nouveau-Brunswick est officiellement bilingue dans sa propre constitution.',
  },
  {
    id: 'wwa-032',
    p: 'The term “Québécois” most often refers to:',
    pf: 'Le terme « Québécois » désigne le plus souvent :',
    o: [
      'The people of Quebec, especially the French-speaking majority and their culture',
      'Only senators from Ottawa',
      'Inuit of the western Arctic',
      'Acadians of Louisiana only',
    ],
    of: [
      'La population du Québec, surtout la majorité francophone et sa culture',
      'Les sénateurs d’Ottawa seulement',
      'Les Inuit de l’Arctique de l’Ouest',
      'Les Acadiens de la Louisiane seulement',
    ],
    a: 'a',
    e: 'It names a national and cultural identity centred on Quebec. It is not a synonym for all Canadians.',
    ef: 'Il nomme une identité nationale et culturelle centrée sur le Québec. Ce n’est pas un synonyme de l’ensemble des Canadiens.',
  },
  {
    id: 'wwa-033',
    p: 'Residential schools were:',
    pf: 'Les pensionnats étaient :',
    o: [
      'A system that took Indigenous children from their families and attacked their languages and cultures',
      'Ordinary public high schools in Toronto',
      'Military colleges for Loyalists',
      'French lycées in Paris',
    ],
    of: [
      'Un système qui arrachait les enfants autochtones à leur famille et s’attaquait à leurs langues et à leurs cultures',
      'Des écoles secondaires publiques ordinaires de Toronto',
      'Des collèges militaires pour les Loyalistes',
      'Des lycées français à Paris',
    ],
    a: 'a',
    e: 'The schools were a grave injustice. The guide is brief; an informed citizen should still know what they were.',
    ef: 'Les pensionnats ont constitué une grave injustice. Le guide est bref; un citoyen informé devrait tout de même savoir ce qu’ils étaient.',
  },
  {
    id: 'wwa-034',
    p: 'Anglophone and Francophone communities both exist:',
    pf: 'Les communautés anglophones et francophones existent toutes deux :',
    o: [
      'Across Canada, not only in one province',
      'Only in Yukon',
      'Only inside the Parliament Buildings',
      'Only before 1763',
    ],
    of: [
      'Partout au Canada, et pas seulement dans une seule province',
      'Au Yukon seulement',
      'À l’intérieur des édifices du Parlement seulement',
      'Avant 1763 seulement',
    ],
    a: 'a',
    e: 'English-speaking majorities live in most provinces; French-speaking communities exist from the Acadian regions through Quebec to the West.',
    ef: 'Des majorités anglophones vivent dans la plupart des provinces; des communautés francophones existent des régions acadiennes jusqu’au Québec et à l’Ouest.',
  },
  {
    id: 'wwa-035',
    t: 'tf',
    p: 'Indigenous peoples all share one culture and one language.',
    pf: 'Les peuples autochtones partagent tous une seule culture et une seule langue.',
    a: 'false',
    e: 'Diversity among First Nations, Inuit, and Métis—and among First Nations themselves—is a basic fact for the test.',
    ef: 'La diversité entre les Premières Nations, les Inuit et les Métis — et entre les Premières Nations elles-mêmes — est un fait de base pour l’examen.',
  },
  {
    id: 'wwa-036',
    p: 'Inuktitut is best described as:',
    pf: 'L’inuktitut se décrit le mieux comme :',
    o: [
      'A language of the Inuit, still spoken in many northern communities',
      'The official language of Alberta only',
      'A type of prairie wheat',
      'The original name of Ottawa',
    ],
    of: [
      'Une langue des Inuit, encore parlée dans de nombreuses communautés nordiques',
      'La langue officielle de l’Alberta seulement',
      'Une variété de blé des Prairies',
      'Le nom d’origine d’Ottawa',
    ],
    a: 'a',
    e: 'Indigenous languages are living languages. English and French are official federally; they are not the only tongues in Canada.',
    ef: 'Les langues autochtones sont des langues vivantes. L’anglais et le français sont officiels au fédéral; ce ne sont pas les seules langues parlées au Canada.',
  },
  {
    id: 'wwa-037',
    p: 'The Chinese head tax and later exclusion laws were:',
    pf: 'La taxe d’entrée imposée aux Chinois et les lois d’exclusion qui ont suivi étaient :',
    o: [
      'Racist immigration barriers later recognized as wrong',
      'A Confederation promise to B.C. in 1867',
      'A Charter right',
      'A municipal parking rule',
    ],
    of: [
      'Des obstacles racistes à l’immigration, reconnus plus tard comme injustes',
      'Une promesse de la Confédération faite à la Colombie-Britannique en 1867',
      'Un droit garanti par la Charte',
      'Un règlement municipal de stationnement',
    ],
    a: 'a',
    e: 'Chinese labour built the railway, then faced discriminatory fees and a 1923 exclusion act. Redress came much later.',
    ef: 'La main-d’œuvre chinoise a construit le chemin de fer, puis a subi des droits discriminatoires et une loi d’exclusion en 1923. La réparation est venue bien plus tard.',
  },
  {
    id: 'wwa-038',
    t: 'tf',
    p: 'The Komagata Maru incident involved South Asian passengers who were turned away from Vancouver in 1914.',
    pf: 'L’incident du Komagata Maru a touché des passagers sud-asiatiques refoulés de Vancouver en 1914.',
    a: 'true',
    e: 'It is a landmark of exclusion in immigration history. Canada later apologized for the treatment of the passengers.',
    ef: 'C’est un jalon de l’exclusion dans l’histoire de l’immigration. Le Canada s’est plus tard excusé du traitement réservé aux passagers.',
  },
  {
    id: 'wwa-039',
    p: 'Many Mennonite, Doukhobor, and other European farm settlers were drawn to the Prairies by:',
    pf: 'De nombreux colons agricoles mennonites, doukhobors et autres Européens ont été attirés vers les Prairies par :',
    o: [
      'Offers of land and a chance to farm in community',
      'A guarantee of Senate seats',
      'The Quiet Revolution',
      'NORAD membership',
    ],
    of: [
      'Des offres de terres et la possibilité de cultiver en communauté',
      'Une garantie de sièges au Sénat',
      'La Révolution tranquille',
      'L’adhésion au NORAD',
    ],
    a: 'a',
    e: 'The wheat boom mixed many European groups onto Prairie homesteads. Language and religion often stayed distinctive.',
    ef: 'L’essor du blé a réuni de nombreux groupes européens sur les fermes des Prairies. La langue et la religion sont souvent demeurées distinctes.',
  },
  {
    id: 'wwa-040',
    p: 'A large postwar Italian-Canadian community is especially associated with:',
    pf: 'L’importante communauté italo-canadienne d’après-guerre est surtout associée :',
    o: [
      'Cities such as Toronto and Montreal',
      'Only Yukon gold camps',
      'Only the Senate chamber',
      'Only 17th-century New France',
    ],
    of: [
      'À des villes comme Toronto et Montréal',
      'Aux camps aurifères du Yukon seulement',
      'À la chambre du Sénat seulement',
      'À la Nouvelle-France du 17e siècle seulement',
    ],
    a: 'a',
    e: 'Southern European immigration after 1945 reshaped Canada’s cities. That is part of “who we are” today.',
    ef: 'L’immigration sud-européenne après 1945 a transformé les villes du Canada. Cela fait partie de « qui nous sommes » aujourd’hui.',
  },
  {
    id: 'wwa-041',
    p: 'Caribbean and African immigration to Canada grew especially after:',
    pf: 'L’immigration caribéenne et africaine au Canada a surtout augmenté après :',
    o: [
      'Racial barriers in immigration policy were reduced in the 1960s',
      'Confederation in 1867',
      'The War of 1812',
      'The founding of the Hudson’s Bay Company',
    ],
    of: [
      'La réduction des barrières raciales dans la politique d’immigration au cours des années 1960',
      'La Confédération de 1867',
      'La guerre de 1812',
      'La fondation de la Compagnie de la Baie d’Hudson',
    ],
    a: 'a',
    e: 'The points system and later reforms opened doors that earlier “preferred country” rules had closed.',
    ef: 'Le système de points et les réformes ultérieures ont ouvert des portes que les anciennes règles de « pays de prédilection » avaient fermées.',
  },
  {
    id: 'wwa-042',
    t: 'tf',
    p: 'Many First Nations people today live in cities as well as in First Nation communities.',
    pf: 'Aujourd’hui, de nombreux membres des Premières Nations vivent en ville autant que dans les communautés des Premières Nations.',
    a: 'true',
    e: 'Urban Indigenous populations are large. “Who we are” is not only a reserve or northern-village story.',
    ef: 'Les populations autochtones urbaines sont nombreuses. « Qui nous sommes » n’est pas seulement une histoire de réserve ou de village nordique.',
  },
  {
    id: 'wwa-043',
    p: 'Treaties are described as living agreements because they:',
    pf: 'Les traités sont décrits comme des ententes vivantes parce qu’ils :',
    o: [
      'Continue to define relationships between Indigenous nations and the Crown',
      'Expired automatically in 1867',
      'Apply only to tourists',
      'Are municipal parking permits',
    ],
    of: [
      'Continuent de définir les relations entre les nations autochtones et la Couronne',
      'Ont expiré automatiquement en 1867',
      'Ne s’appliquent qu’aux touristes',
      'Sont des permis de stationnement municipaux',
    ],
    a: 'a',
    e: 'Historic and modern treaties are constitutional facts, not folklore. Implementation remains contested in politics and courts.',
    ef: 'Les traités historiques et modernes sont des réalités constitutionnelles, et non du folklore. Leur mise en œuvre demeure contestée en politique et devant les tribunaux.',
  },
  {
    id: 'wwa-044',
    p: 'Haitian and other Francophone newcomers have especially strengthened French-speaking life in:',
    pf: 'Les nouveaux arrivants haïtiens et d’autres francophones ont surtout renforcé la vie en français :',
    o: ['Montreal and other parts of Quebec', 'Only Whitehorse', 'Only rural Saskatchewan wheat towns', 'Only the Peace Tower'],
    of: ['À Montréal et ailleurs au Québec', 'À Whitehorse seulement', 'Dans les villages céréaliers ruraux de la Saskatchewan seulement', 'À la Tour de la Paix seulement'],
    a: 'a',
    e: 'French in Canada is not only “old stock” Quebec. Immigration also feeds Francophone communities.',
    ef: 'Le français au Canada n’est pas seulement celui du Québec « de souche ». L’immigration alimente aussi les communautés francophones.',
  },
  {
    id: 'wwa-045',
    p: 'A heritage language (for example, Punjabi, Italian, or Mandarin) in Canada is:',
    pf: 'Au Canada, une langue patrimoniale (par exemple le pendjabi, l’italien ou le mandarin) est :',
    o: [
      'A language other than English or French that a community continues to use',
      'Illegal under the Official Languages Act',
      'The only language allowed in federal court',
      'A type of maple product',
    ],
    of: [
      'Une langue autre que l’anglais ou le français qu’une communauté continue d’utiliser',
      'Une langue illégale selon la Loi sur les langues officielles',
      'La seule langue permise devant les tribunaux fédéraux',
      'Un type de produit de l’érable',
    ],
    a: 'a',
    e: 'Official bilingualism does not ban other languages in homes, temples, newspapers, or businesses.',
    ef: 'Le bilinguisme officiel n’interdit pas les autres langues à la maison, dans les lieux de culte, les journaux ou les commerces.',
  },
  {
    id: 'wwa-046',
    t: 'tf',
    p: 'Inuit Nunangat refers to the Inuit homeland across the Arctic, including parts of the territories and northern Quebec and Labrador.',
    pf: 'L’Inuit Nunangat désigne la patrie des Inuit dans l’Arctique, y compris des parties des territoires ainsi que le Nord du Québec et le Labrador.',
    a: 'true',
    e: 'It is a geographic and cultural idea, not a tenth province. Nunavut is one political expression of that homeland.',
    ef: 'C’est une notion géographique et culturelle, et non une dixième province. Le Nunavut est une expression politique de cette patrie.',
  },
  {
    id: 'wwa-047',
    p: 'Jewish Canadians have been part of Canada for generations and include:',
    pf: 'Les Canadiens juifs font partie du Canada depuis des générations et comprennent :',
    o: [
      'Communities in Montreal, Toronto, and other cities, including Holocaust survivors after 1945',
      'Only a 21st-century arrival with no earlier history',
      'A group banned from citizenship',
      'A Senate-only religious order',
    ],
    of: [
      'Des communautés à Montréal, à Toronto et dans d’autres villes, dont des survivants de la Shoah arrivés après 1945',
      'Uniquement une arrivée du 21e siècle, sans histoire antérieure',
      'Un groupe exclu de la citoyenneté',
      'Un ordre religieux réservé au Sénat',
    ],
    a: 'a',
    e: 'The community is both historic and renewed by refugees after the Second World War. Antisemitism is part of the harder history too.',
    ef: 'La communauté est à la fois historique et renouvelée par les réfugiés arrivés après la Seconde Guerre mondiale. L’antisémitisme fait aussi partie de cette histoire plus difficile.',
  },
  {
    id: 'wwa-048',
    p: 'Which statement about official languages is most accurate for everyday life?',
    pf: 'Quel énoncé sur les langues officielles est le plus exact dans la vie de tous les jours?',
    o: [
      'You may speak any language privately; federal institutions must serve the public in English and French',
      'Every shopkeeper must speak Inuktitut',
      'English is banned in Quebec homes',
      'French is banned west of Ontario',
    ],
    of: [
      'Vous pouvez parler la langue de votre choix en privé; les institutions fédérales doivent servir le public en anglais et en français',
      'Chaque commerçant doit parler l’inuktitut',
      'L’anglais est interdit dans les foyers québécois',
      'Le français est interdit à l’ouest de l’Ontario',
    ],
    a: 'a',
    e: 'The duty sits mainly on Parliament, federal institutions, and some courts—not on every private conversation.',
    ef: 'L’obligation repose surtout sur le Parlement, les institutions fédérales et certains tribunaux — et non sur chaque conversation privée.',
  },
  {
    id: 'wwa-049',
    p: 'Métis communities historically grew along:',
    pf: 'Historiquement, les communautés métisses se sont développées le long :',
    o: [
      'Fur-trade routes of the Prairies and the West, with distinct language and culture',
      'Only the Halifax waterfront in 1497',
      'Only Parliament Hill offices',
      'Only NATO bases in Europe',
    ],
    of: [
      'Des routes de la traite des fourrures des Prairies et de l’Ouest, avec une langue et une culture distinctes',
      'Du front de mer de Halifax en 1497 seulement',
      'Des bureaux de la Colline du Parlement seulement',
      'Des bases de l’OTAN en Europe seulement',
    ],
    a: 'a',
    e: 'Red River and later Prairie settlements are the classic Métis geography. Identity is not a blood-quantum worksheet on the test.',
    ef: 'La rivière Rouge et les établissements ultérieurs des Prairies forment la géographie métisse classique. L’identité n’est pas une question de quantum de sang aux fins de l’examen.',
  },
]);
